//! polyplug host library — Rust bindings for host-side (app developer) use.
//!
//! This crate provides idiomatic Rust wrappers over the polyplug C ABI,
//! for applications that want to host a polyplug runtime.
//!
//! # Status
//! Scaffold only. Full implementation is code-generated by `polyplugc`.

// Re-export the runtime ABI types for convenience.
pub use polyplug_abi as abi;
pub use polyplug::error;
pub use polyplug::registry;
pub use polyplug::runtime;

use polyplug_abi::HostVTable;
use polyplug_abi::PluginHandle;
use polyplug_abi::PluginVTable;

/// Look up the first provider of a contract at or above `min_version`.
/// Returns `PluginHandle::null()` if not found.
///
/// # Safety
/// `vtable` must point to a valid, live `HostVTable` backed by an active runtime.
pub unsafe fn find_by_contract(
    vtable: &HostVTable,
    contract_id: u64,
    min_version: u32,
) -> PluginHandle {
    // SAFETY: caller guarantees vtable is valid and runtime is alive.
    unsafe { (vtable.find_by_contract)(contract_id, min_version) }
}

/// Look up a specific bundle's implementation of a contract.
///
/// # Safety
/// `vtable` must point to a valid, live `HostVTable` backed by an active runtime.
pub unsafe fn find_by_bundle(
    vtable: &HostVTable,
    bundle_id: u64,
    contract_id: u64,
    min_version: u32,
) -> PluginHandle {
    // SAFETY: caller guarantees vtable is valid and runtime is alive.
    unsafe { (vtable.find_by_bundle)(bundle_id, contract_id, min_version) }
}

/// Enumerate all providers of a contract into a caller-provided buffer.
/// Returns the number of handles written.
///
/// # Safety
/// `vtable` must point to a valid, live `HostVTable` backed by an active runtime.
pub unsafe fn find_all_by_contract(
    vtable: &HostVTable,
    contract_id: u64,
    min_version: u32,
    out: &mut [PluginHandle],
) -> usize {
    // SAFETY: out slice is valid for the duration of this call.
    unsafe { (vtable.find_all_by_contract)(contract_id, min_version, out.as_mut_ptr(), out.len()) }
}

/// Resolve a handle to the raw vtable pointer for direct dispatch.
/// Returns null if the handle is stale.
///
/// # Safety
/// The returned pointer is valid only while the plugin library remains loaded.
pub unsafe fn resolve_plugin(vtable: &HostVTable, handle: PluginHandle) -> *const PluginVTable {
    // SAFETY: caller guarantees vtable is valid and runtime is alive.
    unsafe { (vtable.resolve_plugin)(handle) }
}

// ─── String Helpers ───────────────────────────────────────────────────────────

/// Convert a `StringView` to a `&str`.
///
/// # Safety
/// The `StringView` must point to valid UTF-8 data that remains valid for the
/// duration of the returned reference's use.
pub fn to_str(sv: &polyplug_abi::StringView) -> &str {
    if sv.ptr.is_null() || sv.len == 0 {
        return "";
    }
    unsafe { core::str::from_utf8(core::slice::from_raw_parts(sv.ptr, sv.len)).unwrap_or("") }
}

/// Convert a `&str` to a `StringView` (borrowed, for passing to guest).
///
/// The returned `StringView` borrows from the input string. The caller must
/// ensure the string outlives the `StringView`.
pub fn str_as_view(s: &str) -> polyplug_abi::StringView {
    polyplug_abi::StringView {
        ptr: s.as_ptr(),
        len: s.len(),
    }
}

/// Create an owned `String` from a `StringView`.
///
/// This copies the data, so the `StringView` can be freed after this call.
pub fn to_string(sv: &polyplug_abi::StringView) -> String {
    to_str(sv).to_string()
}
