[package]
name = "polyplug"
description = "Universal high-performance zero-overhead cross-language plugin runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "polyplug"
crate-type = ["cdylib", "rlib"]

[dependencies]
polyplug_utils = { workspace = true }
polyplug_abi = { workspace = true }

thiserror = { workspace = true }
petgraph = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

[features]
default = []

[lints]
workspace = true

[dev-dependencies]
criterion = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }
libloading = { workspace = true }

[[bench]]
name = "contract_dispatch"
harness = false

[[bench]]
name = "ffi_resolve"
harness = false

[[bench]]
name = "ffi_find_all"
harness = false

[[bench]]
name = "registry_resolve"
harness = false

[[bench]]
name = "registry_find"
harness = false

[[bench]]
name = "counter_inc"
harness = false

