[bundle]
name = "csharp_encoder"
version = "1.0.0"
api = "../../../api.toml"
loader = "dotnet"
file = "encoder.dll"

[[plugin]]
name = "encoder"
version = "1.0.0"
implements = ["pipeline.Encoder@1.0"]
