<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Polyplug.Loaders.Native</AssemblyName>
    <RootNamespace>Polyplug.Loaders</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>true</IsPackable>
    <Description>Polyplug native library loader for loading native (C ABI) plugins. Native libraries for Linux, macOS, and Windows are embedded.</Description>
    <PackageId>Polyplug.Loaders.Native</PackageId>
    <Version>0.1.0</Version>
    <Authors>polyplug</Authors>
    <PackageTags>polyplug;plugin;runtime;ffi;native;loader</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/polyplug/polyplug</PackageProjectUrl>
    <RepositoryUrl>https://github.com/polyplug/polyplug.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Polyplug/Polyplug.csproj" />
    <Content Include="runtimes\**\*.*">
      <Pack>true</Pack>
      <PackagePath>runtimes</PackagePath>
    </Content>
  </ItemGroup>
</Project>