[workspace]

[package]
name = "polyplug-full"
version = "0.1.0"
edition = "2024"

[lib]
name = "polyplug_full"
crate-type = ["cdylib"]

[dependencies]
polyplug = { path = "../../../crates/polyplug" }
polyplug_python = { path = "../../../crates/polyplug_python" }
polyplug_lua = { path = "../../../crates/polyplug_lua" }
polyplug_js = { path = "../../../crates/polyplug_js" }
polyplug_dotnet = { path = "../../../crates/polyplug_dotnet" }
