[package]
name = "polyplug_native"
description = "Native loader for polyplug - loads C ABI plugins (.so/.dll/.dylib)"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "polyplug_native"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]
polyplug = { workspace = true }
polyplug_abi = { workspace = true }
polyplug_utils = { workspace = true }

libloading = { workspace = true }

[lints]
workspace = true
