<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../sdks/csharp/host/Polyplug.Host.csproj" />
    <ProjectReference Include="../../../sdks/csharp/guest/Polyplug.Guest.csproj" />
    <ProjectReference Include="../../../sdks/csharp/loaders/Native/Polyplug.Loaders.Native.csproj" />
    <ProjectReference Include="../../../sdks/csharp/loaders/Python/Polyplug.Loaders.Python.csproj" />
    <ProjectReference Include="../../../sdks/csharp/loaders/Lua/Polyplug.Loaders.Lua.csproj" />
    <ProjectReference Include="../../../sdks/csharp/loaders/Js/Polyplug.Loaders.Js.csproj" />
    <ProjectReference Include="../../../sdks/csharp/loaders/Dotnet/Polyplug.Loaders.Dotnet.csproj" />
  </ItemGroup>
</Project>
