# THIS FILE IS AUTO-GENERATED BY polyplug_abi build script.
# DO NOT EDIT STRUCT/FIELD DEFINITIONS.
# Helper methods are embedded by the build script (see crates/polyplug_abi/build/generate.rs).
from __future__ import annotations

import ctypes
import enum
from typing import ClassVar



class NativeDispatch(ctypes.Structure):
    """ Native dispatch data — direct function pointer array.
    
     Used when `dispatch_type == DispatchType::Native`.
     The `functions` array contains `function_count` function pointers.
    """
    _fields_ = [
        ("function_count", ctypes.c_uint32),
        ("functions", ctypes.c_void_p),
    ]

# Expected size: 16 bytes
assert ctypes.sizeof(NativeDispatch) == 16, f"NativeDispatch expected 16 bytes, got {ctypes.sizeof(NativeDispatch)}"


class VmLoaderData(ctypes.Structure):
    """ Opaque handle to VM loader-specific data.
    
     Wraps VM-specific state managed by each loader (Python, Lua, JS).
     Opaque to core runtime — loaders know their own state layout.
    
     # OWNERSHIP
     Owned by the loader. Lives for the lifetime of the loaded plugin.
    """
    _fields_ = [
        ("data", ctypes.c_void_p),
    ]

# Expected size: 8 bytes
assert ctypes.sizeof(VmLoaderData) == 8, f"VmLoaderData expected 8 bytes, got {ctypes.sizeof(VmLoaderData)}"


class GuestContractInstance(ctypes.Structure):
    """ Opaque handle to a guest contract instance.
    
     Created by `GuestContractInterface::create_instance`, destroyed by `destroy_instance`.
    
     # Who provides
     Guest code creates instances via create_instance factory.
     The guest owns the underlying data.
    
     # Who calls
     Host code passes instances to dispatch functions and destroy_instance.
    
     # Ownership
     This is an owned handle - the instance must be destroyed via
     `GuestContractInterface::destroy_instance` before hot-reload.
     Failure to destroy causes memory leaks and prevents safe hot-reload.
    
     # Lifetime
     Lives until `destroy_instance` is called. Must be destroyed before
     the bundle is unloaded or hot-reloaded.
    
     # Layout
     - `data`: Opaque instance pointer (owned by guest)
     - `contract_id`: Contract ID stamped at instance creation
    """
    _fields_ = [
        ("data", ctypes.c_void_p),
        ("contract_id", ctypes.c_uint64),
    ]

# Expected size: 16 bytes
assert ctypes.sizeof(GuestContractInstance) == 16, f"GuestContractInstance expected 16 bytes, got {ctypes.sizeof(GuestContractInstance)}"


class HostContractInstance(ctypes.Structure):
    """ Opaque handle to a host contract instance.
    
     Created by `HostContractInterface::create_instance`, destroyed by `destroy_instance`.
     For singleton host contracts, the same instance is returned for all callers.
    """
    _fields_ = [
        ("data", ctypes.c_void_p),
    ]

# Expected size: 8 bytes
assert ctypes.sizeof(HostContractInstance) == 8, f"HostContractInstance expected 8 bytes, got {ctypes.sizeof(HostContractInstance)}"


class GuestContractHandle(ctypes.Structure):
    """ Opaque handle to a registered guest contract.
    
     The handle pairs the slot `index` with the `generation` the slot held when the
     handle was minted. `resolve_guest_contract` rejects a handle whose `generation`
     no longer matches the slot's current generation (the slot was vacated on unload
     and the index possibly reused), returning `StaleHandle`. Out-of-bounds or empty-slot
     indices return InvalidHandle.
    
     # Naming
     Named `GuestContractHandle` for consistency with `GuestContractInterface`
     and `GuestContractInstance`.
    
     # Layout
     - `index`: Slot index in the registry (u32, offset 0)
     - `generation`: Slot generation the handle was minted against (u32, offset 4)
    
     # Safety
     Handles become stale after unload. Call `resolve_guest_contract` to validate.
     Returns null pointer if the handle is invalid.
    """
    _fields_ = [
        ("index", ctypes.c_uint32),
        ("generation", ctypes.c_uint32),
    ]

# Expected size: 8 bytes
assert ctypes.sizeof(GuestContractHandle) == 8, f"GuestContractHandle expected 8 bytes, got {ctypes.sizeof(GuestContractHandle)}"


class Array(ctypes.Structure):
    """ FFI-safe array with caller-frees ownership model.
    
     # Memory Management
     - Allocated via `host->alloc(self, len * sizeof(T), align)`
     - Freed via `host->free(self, items, len * sizeof(T), align)`
    
     # Ownership
     Caller owns the memory and must free via host allocator.
     CodeGen generates RAII wrappers in each language SDK:
     - Rust: `Drop` impl calls `host->free`
     - Python: `__del__` calls free
     - C#: `IDisposable.Dispose` calls free
    
     # Safety
     The `align` field is required for proper freeing. Generic code must
     track alignment of `T` to free correctly.
    
     # Thread Safety
     Safe to read from multiple threads if underlying data is immutable.
     Send/Sync implemented for T: Send/Sync.
    """
    _fields_ = [
        ("items", ctypes.c_void_p),
        ("len", ctypes.c_size_t),
        ("align", ctypes.c_size_t),
    ]


class Buffer(ctypes.Structure):
    """ Owning byte buffer.
    
     OWNERSHIP: `ptr` is always allocated through the host allocator — the
     `alloc` field on `HostApi`. The owner releases it through the matching
     `free` field (`(host.free)(host, ptr, cap, align)`) when done. There are
     no separate allocator C exports; allocation always flows through `HostApi`.
    """
    _fields_ = [
        ("ptr", ctypes.c_void_p),
        ("len", ctypes.c_size_t),
        ("cap", ctypes.c_size_t),
    ]

# Expected size: 24 bytes
assert ctypes.sizeof(Buffer) == 24, f"Buffer expected 24 bytes, got {ctypes.sizeof(Buffer)}"


class ArenaOverflowBlock(ctypes.Structure):
    """ Header prepended to every host-allocated overflow block.
    
     Overflow blocks form a singly linked list rooted at `CallArena.first_overflow`.
     Each block stores the total `capacity` it was allocated with (including this
     header) so the arena can free it with the exact size/align the host expects.
     Blocks are **retained across resets** and reused by rewinding `used` back to the
     header size; they are freed only when the arena is dropped.
    """
    _fields_ = [
        ("next", ctypes.c_void_p),
        ("capacity", ctypes.c_size_t),
        ("used", ctypes.c_size_t),
    ]

# Expected size: 24 bytes
assert ctypes.sizeof(ArenaOverflowBlock) == 24, f"ArenaOverflowBlock expected 24 bytes, got {ctypes.sizeof(ArenaOverflowBlock)}"


class CallArena(ctypes.Structure):
    """ Per-call bump allocator handed to a VM dispatch call.
    
     # Layout
    
     `#[repr(C)]` with five pointer-sized fields (40 bytes, align 8). The first
     three fields define the primary bump region `[base, end)` with `cur` as the
     next free byte. When the primary region is exhausted, `alloc` walks the
     retained overflow chain for a block with spare room; if none fits, it requests
     a fresh block from `host->alloc`, chains it, and serves from it.
    
     A null `CallArena*` passed to a dispatch function means "no arena": the bridge
     falls back to per-value `host->alloc`.
    """
    _fields_ = [
        ("cur", ctypes.c_void_p),
        ("end", ctypes.c_void_p),
        ("base", ctypes.c_void_p),
        ("host", ctypes.c_void_p),
        ("first_overflow", ctypes.c_void_p),
    ]

# Expected size: 40 bytes
assert ctypes.sizeof(CallArena) == 40, f"CallArena expected 40 bytes, got {ctypes.sizeof(CallArena)}"


class DependencyInfo(ctypes.Structure):
    r""" Dependency information returned by get_dependencies introspection API.
    
     Mirrors `manifest.toml` `\[dependency\]` table structure for plugins to query
     their own declared dependencies at runtime.
    
     # Who provides
     Runtime returns this from `HostApi::get_dependencies`.
    
     # Who calls
     Guest (plugin) code calls `get_dependencies` during initialization
     to discover available dependencies.
    
     # Ownership
     Returned in an Array that caller owns and must free via `host->free`.
    
     # Fields
     - `contract_id`: The contract being depended upon
     - `min_version`: Minimum version required
     - `bundle_id`: Specific bundle if ByBundle, 0 if ByContract
    """
    _fields_ = [
        ("contract_id", ctypes.c_uint64),
        ("min_version", ctypes.c_uint32),
        ("bundle_id", ctypes.c_uint64),
    ]

# Expected size: 24 bytes
assert ctypes.sizeof(DependencyInfo) == 24, f"DependencyInfo expected 24 bytes, got {ctypes.sizeof(DependencyInfo)}"


class Ed25519PublicKey(ctypes.Structure):
    """ Raw Ed25519 public-key bytes (the 32-byte compressed Edwards point encoding).
    
     # Layout
     `#[repr(C)]`, 32 bytes, align 1 — a bare byte array with no padding.
    """
    _fields_ = [
        ("bytes", ctypes.c_uint8 * 32),
    ]

# Expected size: 32 bytes
assert ctypes.sizeof(Ed25519PublicKey) == 32, f"Ed25519PublicKey expected 32 bytes, got {ctypes.sizeof(Ed25519PublicKey)}"


class StringView(ctypes.Structure):
    """ Non-owning UTF-8 string view.
    
     OWNERSHIP: borrowed reference. `ptr` must remain valid for the duration
     of the call. Never freed by the receiver.
    """
    _fields_ = [
        ("ptr", ctypes.c_void_p),
        ("len", ctypes.c_size_t),
    ]

# Expected size: 16 bytes
assert ctypes.sizeof(StringView) == 16, f"StringView expected 16 bytes, got {ctypes.sizeof(StringView)}"


class Version(ctypes.Structure):
    """ A three-component semantic version (major.minor.patch)."""
    _fields_ = [
        ("major", ctypes.c_uint32),
        ("minor", ctypes.c_uint32),
        ("patch", ctypes.c_uint32),
    ]

# Expected size: 12 bytes
assert ctypes.sizeof(Version) == 12, f"Version expected 12 bytes, got {ctypes.sizeof(Version)}"


class ContractType(enum.IntEnum):
    """ABI enum."""
    Host = 0
    Plugin = 1


class DispatchType(enum.IntEnum):
    """ Dispatch mechanism type — determines how function calls are routed."""
    Native = 0
    VirtualMachine = 1


class Compatibility(enum.IntEnum):
    """ How strictly version compatibility is enforced when resolving plugins."""
    Strict = 0
    Relaxed = 1
    Yolo = 2


class ReloadPhaseType(enum.IntEnum):
    """ Type of reload phase for FFI callbacks."""
    Preparing = 0
    Reloaded = 1
    Failed = 2
    Unloading = 3


class SignaturePolicy(enum.IntEnum):
    """ How strictly bundle signature verification is enforced at load time."""
    Off = 0
    WarnOnly = 1
    Required = 2


class SupportedLanguage(enum.IntEnum):
    """ Supported plugin language identifier — identifies the language/runtime hosting plugins."""
    Rust = 0
    Cpp = 1
    Dotnet = 2
    Python = 3
    Lua = 4
    JavaScript = 5


class AbiErrorCode(enum.IntEnum):
    """ ABI error codes (reserved: 0-255 runtime, 256+ plugin-defined).
    
     These codes are returned by all ABI functions to indicate success or failure.
     The `code` field of `AbiError` uses these values.
    """
    Ok = 0
    Generic = 1
    BufferTooSmall = 2
    Panic = 3
    NotFound = 4
    StaleHandle = 5
    FunctionNotAvailable = 6
    DuplicateProvider = 7
    InvalidPointer = 8
    ReentrantCall = 9
    HostContractNotFound = 100
    HostContractVersionMismatch = 101
    HostContractCallFailed = 102


class LogLevel(enum.IntEnum):
    """ Log severity levels for the host-supplied logger callback (`RuntimeConfig::log`).
    
     Numeric ordering is significant: lower values are more severe. A message is
     delivered to the callback only when `level as u32 <= RuntimeConfig::log_max_level`.
    """
    Error = 1
    Warn = 2
    Info = 3
    Debug = 4
    Trace = 5


class ParseVersionError(enum.IntEnum):
    """ABI enum."""
    InvalidFormat = 0
    InvalidInt = 1
POLYPLUG_ABI_VERSION: int = 1


_vm_dispatch_call_t = ctypes.CFUNCTYPE(None, VmLoaderData, GuestContractInstance, ctypes.c_uint32, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p)
class VmDispatch(ctypes.Structure):
    """ VM dispatch data — call through a dispatch function.
    
     Used when `dispatch_type == DispatchType::VirtualMachine`.
     The `call` function receives `loader_data` which contains VM-specific state.
    """
    _fields_ = [
        ("call", _vm_dispatch_call_t),
        ("loader_data", VmLoaderData),
    ]

# Expected size: 16 bytes
assert ctypes.sizeof(VmDispatch) == 16, f"VmDispatch expected 16 bytes, got {ctypes.sizeof(VmDispatch)}"


_host_api_register_guest_contract_t = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p)
_host_api_alloc_t = ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_size_t)
_host_api_free_t = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_size_t)
_host_api_find_guest_contract_t = ctypes.CFUNCTYPE(GuestContractHandle, ctypes.c_void_p, ctypes.c_uint64, ctypes.c_uint32)
_host_api_find_all_guest_contracts_t = ctypes.CFUNCTYPE(Array, ctypes.c_void_p, ctypes.c_uint64, ctypes.c_uint32)
_host_api_resolve_guest_contract_t = ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.c_void_p, GuestContractHandle)
_host_api_get_host_contract_t = ctypes.CFUNCTYPE(HostContractInstance, ctypes.c_void_p, ctypes.c_uint64, ctypes.c_uint32)
_host_api_resolve_host_contract_interface_t = ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.c_void_p, ctypes.c_uint64, ctypes.c_uint32)
_host_api_list_bundles_t = ctypes.CFUNCTYPE(Array, ctypes.c_void_p)
_host_api_get_dependencies_t = ctypes.CFUNCTYPE(Array, ctypes.c_void_p)
_host_api_load_bundle_t = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p)
_host_api_reload_bundle_t = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p)
_host_api_register_host_contract_t = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p)
_host_api_register_loader_t = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p)
_host_api_get_last_error_t = ctypes.CFUNCTYPE(ctypes.c_size_t, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t)
_host_api_get_error_len_t = ctypes.CFUNCTYPE(ctypes.c_size_t, ctypes.c_void_p)
_host_api_unload_bundle_t = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_uint64, ctypes.c_void_p)
_host_api_log_t = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_uint32, StringView, StringView)
_host_api_create_guest_instance_t = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p)
_host_api_destroy_guest_instance_t = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_void_p, GuestContractInstance)
_host_api_revision_counter_t = ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.c_void_p)
class HostApi(ctypes.Structure):
    """ Host Interface — function table passed to guests during initialization.
    
     Contains an opaque runtime pointer and function pointers for guest calls.
     All functions use self-passing pattern (receive HostApi pointer as first parameter).
     `HostApi` is `184 bytes` (1 opaque runtime pointer + 21 function pointer fields + 1 reserved data pointer).
     Tail offsets: `create_guest_instance` @152, `destroy_guest_instance` @160, `revision_counter` @168, `reserved` @176.
    
     # Who provides
     The runtime creates this struct and passes it to `polyplug_init()`.
     The struct is allocated using `Box::leak()` for `'static` lifetime.
    
     # Nullability
     Every function-pointer field is REQUIRED and ALWAYS non-null: the runtime
     is the sole producer of this struct and populates all 21 callbacks at
     creation. Consumers never construct or mutate a `HostApi`. Only the
     `runtime` pointer can become null (it is swapped to null by
     `polyplug_runtime_destroy`), and only the trailing `reserved` data pointer
     is a null placeholder by contract.
    
     # Who calls
     Guest (plugin) code calls these functions to interact with the runtime.
     SDK-generated wrappers handle the self-passing pattern automatically.
    
     # Ownership
     The struct is statically allocated by the runtime. The pointer is valid
     until the runtime is destroyed. Guest must NOT free this pointer.
    
     # Lifetime
     Lives as long as the runtime that created it.
    
     # Thread Safety
     All functions are safe to call from any thread. The runtime uses
     internal synchronization (RwLock/Mutex) for shared state.
    
     # Self-passing pattern
     Each function receives the interface pointer as its first parameter,
     allowing guests to call: `host->find_guest_contract(host, id, ver)`
     SDKs hide this pattern: `host.find_guest_contract(id, ver)`
    """
    _fields_ = [
        ("runtime", ctypes.c_void_p),
        ("register_guest_contract", _host_api_register_guest_contract_t),
        ("alloc", _host_api_alloc_t),
        ("free", _host_api_free_t),
        ("find_guest_contract", _host_api_find_guest_contract_t),
        ("find_all_guest_contracts", _host_api_find_all_guest_contracts_t),
        ("resolve_guest_contract", _host_api_resolve_guest_contract_t),
        ("get_host_contract", _host_api_get_host_contract_t),
        ("resolve_host_contract_interface", _host_api_resolve_host_contract_interface_t),
        ("list_bundles", _host_api_list_bundles_t),
        ("get_dependencies", _host_api_get_dependencies_t),
        ("load_bundle", _host_api_load_bundle_t),
        ("reload_bundle", _host_api_reload_bundle_t),
        ("register_host_contract", _host_api_register_host_contract_t),
        ("register_loader", _host_api_register_loader_t),
        ("get_last_error", _host_api_get_last_error_t),
        ("get_error_len", _host_api_get_error_len_t),
        ("unload_bundle", _host_api_unload_bundle_t),
        ("log", _host_api_log_t),
        ("create_guest_instance", _host_api_create_guest_instance_t),
        ("destroy_guest_instance", _host_api_destroy_guest_instance_t),
        ("revision_counter", _host_api_revision_counter_t),
        ("reserved", ctypes.c_void_p),
    ]

# Expected size: 184 bytes
assert ctypes.sizeof(HostApi) == 184, f"HostApi expected 184 bytes, got {ctypes.sizeof(HostApi)}"


class BundleInitContext(ctypes.Structure):
    """ Context passed to every guest `polyplug_init()` function.
    
     # OWNERSHIP
     The `bundle_path` pointer is runtime-owned and valid for the lifetime of the `PluginRuntime`.
     **Plugin must not store the raw pointer** — copy the string value if persistence is needed.
    """
    _fields_ = [
        ("bundle_id", ctypes.c_uint64),
        ("bundle_path", StringView),
    ]

# Expected size: 24 bytes
assert ctypes.sizeof(BundleInitContext) == 24, f"BundleInitContext expected 24 bytes, got {ctypes.sizeof(BundleInitContext)}"


class PluginDescriptor(ctypes.Structure):
    """ Metadata about a plugin within a bundle.
    
     # OWNERSHIP
     value type passed by pointer during init. The `name` and
     `contract_name` StringViews are borrowed from the plugin's static memory.
     The receiver must not free or outlive the plugin's library.
    """
    _fields_ = [
        ("name", StringView),
        ("contract_name", StringView),
        ("version", Version),
    ]

# Expected size: 48 bytes
assert ctypes.sizeof(PluginDescriptor) == 48, f"PluginDescriptor expected 48 bytes, got {ctypes.sizeof(PluginDescriptor)}"


class ReloadPhase(ctypes.Structure):
    """ FFI-safe reload phase for hot-reload callbacks.
    
     Tagged union style struct — `phase_type` indicates which variant is active.
     Uses `StringView` for FFI compatibility (non-owning borrows).
    
     # Lifetime
     `StringView` fields are borrowed from the caller's strings.
     The callback must not store these views beyond the callback scope.
    """
    _fields_ = [
        ("phase_type", ctypes.c_uint32),
        ("bundle_id", ctypes.c_uint64),
        ("bundle_name", StringView),
        ("reason", StringView),
    ]

# Expected size: 48 bytes
assert ctypes.sizeof(ReloadPhase) == 48, f"ReloadPhase expected 48 bytes, got {ctypes.sizeof(ReloadPhase)}"


_runtime_config_on_reload_t = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_void_p)
# Nullable function pointer (Option<fn>). Can be set to None.
_runtime_config_log_t = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_uint32, StringView, StringView)
# Nullable function pointer (Option<fn>). Can be set to None.
class RuntimeConfig(ctypes.Structure):
    """ Configuration for the polyplug runtime passed to `polyplug_runtime_create`.
    
     # OWNERSHIP
     Borrowed for the duration of the runtime build only.
     The runtime copies any data it needs to retain.
    """
    _fields_ = [
        ("compatibility", ctypes.c_uint32),
        ("hot_reload_enabled", ctypes.c_bool),
        ("on_reload", _runtime_config_on_reload_t),
        ("on_reload_user_data", ctypes.c_void_p),
        ("log", _runtime_config_log_t),
        ("log_user_data", ctypes.c_void_p),
        ("log_max_level", ctypes.c_uint32),
        ("signature_policy", ctypes.c_uint32),
        ("trusted_keys", ctypes.c_void_p),
        ("trusted_keys_len", ctypes.c_size_t),
        ("trusted_keys__align", ctypes.c_size_t),
    ]

# Expected size: 72 bytes
assert ctypes.sizeof(RuntimeConfig) == 72, f"RuntimeConfig expected 72 bytes, got {ctypes.sizeof(RuntimeConfig)}"


class AbiError(ctypes.Structure):
    """ ABI error — returned by value from all ABI calls.
    
     CODE: a raw `u32`, NOT the [`AbiErrorCode`] enum. Plugins are untrusted and
     return `AbiError` by value across the C ABI, so any 32-bit pattern can land
     here — including values that are not declared discriminants of the frozen
     [`AbiErrorCode`] enum. Materializing such a value as the enum would be
     instant undefined behaviour, so the field stays a raw `u32`. Construct it
     with `AbiErrorCode::X as u32` and interpret it with
     [`AbiErrorCode::from_u32`], which is total and safe. The layout is identical
     to the `#[repr(u32)]` enum (4 bytes at offset 0), so the C ABI is unchanged.
    
     OWNERSHIP: `message` is always a static or runtime-owned string. The receiver
     must NEVER free it. Rich, allocated error detail is retrieved separately via
     `get_last_error`.
    """
    _fields_ = [
        ("code", ctypes.c_uint32),
        ("message", StringView),
    ]

# Expected size: 24 bytes
assert ctypes.sizeof(AbiError) == 24, f"AbiError expected 24 bytes, got {ctypes.sizeof(AbiError)}"


class DispatchMechanisms(ctypes.Union):
    """ Union of dispatch mechanisms — use based on `dispatch_type`.
    
     # Safety
     Access the correct variant based on `GuestContractInterface::dispatch_type`:
     - `dispatch_type == Native` → access `.native`
     - `dispatch_type == VirtualMachine` → access `.vm`
    """
    _fields_ = [
        ("native", NativeDispatch),
        ("vm", VmDispatch),
    ]


_guest_contract_interface_create_instance_t = ctypes.CFUNCTYPE(None, VmLoaderData, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p)
_guest_contract_interface_destroy_instance_t = ctypes.CFUNCTYPE(None, VmLoaderData, ctypes.c_void_p, GuestContractInstance)
class GuestContractInterface(ctypes.Structure):
    """ Guest Contract Interface — one per contract implemented by a guest (plugin).
    
     # Who provides
     Guest (plugin) code creates this struct and registers it via `register_guest_contract`.
     Must be `'static` or intentionally leaked.
    
     # Who calls
     Host code calls `create_instance`, `destroy_instance`, and dispatch functions.
    
     # Ownership
     Must be `'static`. Never stack-allocated. Never freed while runtime lives.
     Typically created as `static` or via `Box::leak()`.
    
     # Lifetime
     Lives for the entire runtime lifetime. Must survive hot-reload.
    
     # Instance Lifecycle
     - `create_instance`: Factory function to create new instances
     - `destroy_instance`: Destructor to clean up instances before hot-reload
    
     # Dispatch
     - `dispatch_type == Native`: Call via `dispatch.native.functions[fn_id](instance, args, out, out_err)`
     - `dispatch_type == VirtualMachine`: Call via `dispatch.vm.call(loader_data, instance, fn_id, args, out, arena, out_err)`
    """
    _fields_ = [
        ("contract_id", ctypes.c_uint64),
        ("contract_version", Version),
        ("dispatch_type", ctypes.c_uint32),
        ("create_instance", _guest_contract_interface_create_instance_t),
        ("destroy_instance", _guest_contract_interface_destroy_instance_t),
        ("dispatch", DispatchMechanisms),
    ]

# Expected size: 56 bytes
assert ctypes.sizeof(GuestContractInterface) == 56, f"GuestContractInterface expected 56 bytes, got {ctypes.sizeof(GuestContractInterface)}"


_host_contract_interface_create_instance_t = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p)
_host_contract_interface_destroy_instance_t = ctypes.CFUNCTYPE(None, ctypes.c_void_p, HostContractInstance)
class HostContractInterface(ctypes.Structure):
    """ Host Contract Interface — for host-provided services.
    
     Host contracts are services provided by the host application to plugins.
    
     # Who provides
     Host application code creates this struct and registers it with the runtime.
     Must be `'static` or intentionally leaked.
    
     # Who calls
     Guest (plugin) code calls the dispatch functions after obtaining an instance
     via `HostApi::get_host_contract()`.
    
     # Ownership
     Must be `'static`. The runtime holds a reference for the plugin lifetime.
     Never freed while runtime lives.
    
     # Lifetime
     Lives for the entire runtime lifetime. Must survive hot-reload.
    
     # Singleton Mode
     - `singleton == true`: Same instance returned for all callers
     - `singleton == false`: New instance per caller (caller must destroy)
    
     # Self-Passing Pattern
     `create_instance` and `destroy_instance` take `self: *const HostContractInterface`.
     The runtime field provides access to runtime services.
    """
    _fields_ = [
        ("contract_id", ctypes.c_uint64),
        ("contract_version", Version),
        ("singleton", ctypes.c_bool),
        ("dispatch_type", ctypes.c_uint32),
        ("runtime", ctypes.c_void_p),
        ("user_data", ctypes.c_void_p),
        ("create_instance", _host_contract_interface_create_instance_t),
        ("destroy_instance", _host_contract_interface_destroy_instance_t),
        ("dispatch", DispatchMechanisms),
    ]

# Expected size: 80 bytes
assert ctypes.sizeof(HostContractInterface) == 80, f"HostContractInterface expected 80 bytes, got {ctypes.sizeof(HostContractInterface)}"


# ─── Helper Methods (embedded by the build script) ───

# ─── FNV-1a 64-bit Hash / Contract-ID Helpers ─────────────────────────────────

FNV_OFFSET: int = 0xCBF29CE484222325
FNV_PRIME: int = 0x00000100000001B3


def fnv1a_64(data: bytes) -> int:
    """Compute FNV-1a 64-bit hash of a byte sequence."""
    hash_val: int = FNV_OFFSET
    for byte in data:
        hash_val ^= byte
        hash_val = (hash_val * FNV_PRIME) & 0xFFFFFFFFFFFFFFFF
    return hash_val


def guest_contract_id(name: str, major_version: int) -> int:
    """Calculate guest contract ID from name and major version."""
    return fnv1a_64(f"guest_contract:{name}@{major_version}".encode("utf-8"))


def host_contract_id(name: str, major_version: int) -> int:
    """Calculate host contract ID from name and major version."""
    return fnv1a_64(f"host_contract:{name}@{major_version}".encode("utf-8"))


def bundle_id(name: str) -> int:
    """Compute a bundle ID from its name using FNV-1a 64-bit hash."""
    return fnv1a_64(name.encode("utf-8"))
