[bundle]
name = "csharp_decoder"
version = "1.0.0"
api = "../../../api.toml"
runtime = "csharp"
file = "decoder.cs"

[[plugin]]
name = "decoder"
version = "1.0.0"
implements = ["pipeline.Decoder@1.0"]
