<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>decoder</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../sdks/csharp/guest/Polyplug.Guest.csproj" />
    <ProjectReference Include="../../../../sdks/csharp/host/Polyplug.Host.csproj" />
  </ItemGroup>
</Project>