//! C++ code generator for polyplugc.
//!
//! Generates:
//! - Host-side: header-only C++ callers (RAII wrapper + vtable dispatch)
//! - Guest-side: extern "C" ABI wrappers + abstract base classes + vtable statics

use crate::error::PolyplugcError;
use crate::generators::CodeGenerator;
use crate::generators::GeneratedFile;
use crate::generators::GeneratedFiles;
use crate::ir::AbiBuiltin;
use crate::ir::EnumDef;
use crate::ir::EnumVariant;
use crate::ir::PrimitiveType;
use crate::ir::ResolvedBundle;
use crate::ir::ResolvedContract;
use crate::ir::ResolvedDependency;
use crate::ir::ResolvedFunction;
use crate::ir::ResolvedPlugin;
use crate::ir::ResolvedType;
use crate::ir::ResolvedTypeRef;
use crate::ir::ValidatedIr;

/// The C++ code generator.
pub(crate) struct CppGenerator;

impl CodeGenerator for CppGenerator {
    fn language_name(&self) -> &'static str {
        "cpp"
    }

    fn generate_host(
        &self,
        ir: &ValidatedIr,
        files: &mut GeneratedFiles,
    ) -> Result<(), PolyplugcError> {
        // ── File 1: types.hpp ────────────────────────────────────────────────
        let types_hpp: String = generate_types_hpp(ir);
        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("host/types.hpp"),
            content: types_hpp,
            force_regenerate: false,
        });

        // ── File 2: host_callers.hpp ─────────────────────────────────────────
        let host_callers_hpp: String = generate_host_callers_hpp(ir)?;
        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("host/host_callers.hpp"),
            content: host_callers_hpp,
            force_regenerate: false,
        });

        // ── File 3: manifest.toml ────────────────────────────────────────────
        let manifest_toml: String = generate_manifest_toml();
        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("manifest.toml"),
            content: manifest_toml,
            force_regenerate: true,
        });

        Ok(())
    }

    fn generate_guest(
        &self,
        ir: &ValidatedIr,
        files: &mut GeneratedFiles,
    ) -> Result<(), PolyplugcError> {
        // ── File 1: types.hpp ────────────────────────────────────────────────
        let types_hpp: String = generate_types_hpp(ir);
        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("guest/types.hpp"),
            content: types_hpp,
            force_regenerate: false,
        });

        // ── File 2: contracts.hpp ────────────────────────────────────────────
        let contracts_hpp: String = generate_contracts_hpp(ir);
        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("guest/contracts.hpp"),
            content: contracts_hpp,
            force_regenerate: false,
        });

        // ── File 3: vtables.hpp ──────────────────────────────────────────────
        let vtables_hpp: String = generate_vtables_hpp(ir)?;
        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("guest/vtables.hpp"),
            content: vtables_hpp,
            force_regenerate: false,
        });

        // ── File 4: init.hpp ─────────────────────────────────────────────────
        let init_hpp: String = generate_init_hpp(ir)?;
        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("guest/init.hpp"),
            content: init_hpp,
            force_regenerate: false,
        });

        // --api: manifest emitted by generate_host(); --bundle: emit full discovery manifest
        if ir.bundle.is_some() {
            let manifest_toml: String = generate_bundle_manifest_cpp(ir);
            files.files.push(GeneratedFile {
                path: std::path::PathBuf::from("manifest.toml"),
                content: manifest_toml,
                force_regenerate: true,
            });
        }
        // When ir.bundle.is_none() (--api mode): NO manifest emitted here.
        // The root manifest.toml was already emitted by generate_host().
        Ok(())
    }
}

// ─── types.hpp generator ─────────────────────────────────────────────────────

fn generate_types_hpp(ir: &ValidatedIr) -> String {
    let mut out: String = String::new();
    out.push_str("// THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n");
    out.push_str("// Re-generate with: polyplugc generate --api api.toml --lang cpp --out <dir>\n");
    out.push_str("#pragma once\n");
    out.push_str("#include <cstdint>\n");
    out.push_str("#include \"polyplug/abi.hpp\"\n\n");
    out.push_str("namespace polyplug_generated {\n\n");

    // Emit contract ID constants
    for contract in &ir.contracts {
        let contract_upper: String = contract.name.to_uppercase().replace(['.', '-'], "_");
        out.push_str(&format!(
            "constexpr uint64_t {}_CONTRACT_ID = 0x{:016X};\n",
            contract_upper, contract.contract_id
        ));
    }
    out.push('\n');

    // Emit enums before struct types
    for e in &ir.enums {
        generate_cpp_enum(&mut out, e);
    }

    for ty in &ir.types {
        generate_cpp_type(&mut out, ty);
    }

    out.push_str("}  // namespace polyplug_generated\n");
    out
}

// ─── contracts.hpp generator ─────────────────────────────────────────────────

fn generate_contracts_hpp(ir: &ValidatedIr) -> String {
    let mut out: String = String::new();
    out.push_str("// THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n");
    out.push_str("// Re-generate with: polyplugc generate --api api.toml --lang cpp --out <dir>\n");
    out.push_str("#pragma once\n");
    out.push_str("#include \"types.hpp\"\n");
    out.push_str("#include <cstdint>\n\n");
    out.push_str("namespace polyplug_plugin {\n\nusing namespace polyplug_generated;\n\n");
    out.push_str("struct PolyplugError { uint32_t code; };\n\n");

    for contract in &ir.contracts {
        generate_cpp_guest_contract_class(&mut out, contract);
    }

    out.push_str("}  // namespace polyplug_plugin\n");
    out
}

fn generate_cpp_guest_contract_class(out: &mut String, contract: &ResolvedContract) {
    let class_name: String = contract_name_to_plugin_class(&contract.name);
    out.push_str(&format!(
        "/// Abstract plugin base for contract `{}` (id=0x{:016X})\n",
        contract.name, contract.contract_id
    ));
    out.push_str(&format!("class {} {{\npublic:\n", class_name));
    out.push_str(&format!("    virtual ~{}() = default;\n", class_name));

    for func in &contract.functions {
        generate_cpp_guest_abstract_method(out, func);
    }

    out.push_str("};\n\n");
}

fn generate_cpp_guest_abstract_method(out: &mut String, func: &ResolvedFunction) {
    let return_type: String = func
        .returns
        .as_ref()
        .map(cpp_type_name)
        .unwrap_or_else(|| "void".to_owned());

    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| {
            let cpp_ty: String = cpp_type_name(&p.ty);
            match &p.ty {
                ResolvedTypeRef::UserDefined(_) => format!("const {}& {}", cpp_ty, p.name),
                ResolvedTypeRef::Primitive(_) | ResolvedTypeRef::AbiType(_) => {
                    format!("{} {}", cpp_ty, p.name)
                }
            }
        })
        .collect();
    let params_str: String = params.join(", ");

    out.push_str(&format!(
        "    virtual {} {}({}) = 0;\n",
        return_type, func.name, params_str
    ));
}

// ─── vtables.hpp generator ───────────────────────────────────────────────────

fn generate_vtables_hpp(ir: &ValidatedIr) -> Result<String, PolyplugcError> {
    let mut out: String = String::new();
    out.push_str("// THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n");
    out.push_str("// Re-generate with: polyplugc generate --api api.toml --lang cpp --out <dir>\n");
    out.push_str("#pragma once\n");
    out.push_str("#include \"contracts.hpp\"\n");
    out.push_str("#include \"polyplug/abi.hpp\"\n");
    out.push_str("#include <cstdint>\n");
    out.push_str("#include <exception>\n\n");
    out.push_str("namespace polyplug_plugin {\n\nusing namespace polyplug_generated;\n\n");

    if let Some(bundle) = &ir.bundle {
        for plugin in &bundle.plugins {
            for contract_impl in &plugin.implements {
                if let Some(contract) = ir.contracts.iter().find(|c| {
                    let contract_full =
                        format!("{}@{}.{}", c.name, c.version.major, c.version.minor);
                    &contract_full == contract_impl
                }) {
                    generate_cpp_guest_plugin_vtable(&mut out, &plugin.name, contract)?;
                }
            }
        }
    } else {
        for contract in &ir.contracts {
            generate_cpp_guest_contract_vtable(&mut out, contract)?;
        }
    }

    out.push_str("}  // namespace polyplug_plugin\n");
    Ok(out)
}

fn generate_cpp_guest_plugin_vtable(
    out: &mut String,
    plugin_name: &str,
    contract: &ResolvedContract,
) -> Result<(), PolyplugcError> {
    let plugin_upper: String = plugin_name.to_uppercase().replace('.', "_");
    let plugin_lower: String = plugin_name.to_lowercase().replace('.', "_");
    let class_name: String = contract_name_to_plugin_class(&contract.name);
    let fn_count: usize = contract.functions.len();
    let contract_version: u32 = (contract.version.minor << 16) | contract.version.patch;

    out.push_str(&format!("// Plugin: {}\n", plugin_name));
    out.push_str(&format!(
        "extern {}* g_{}_impl;\n\n",
        class_name, plugin_lower
    ));

    out.push_str(&format!(
        "constexpr uint64_t {}_CONTRACT_ID = 0x{:016X}ULL;\n\n",
        plugin_upper, contract.contract_id
    ));

    out.push_str(&format!(
        "inline void set_{}_impl({}* impl) {{ g_{}_impl = impl; }}\n\n",
        plugin_lower, class_name, plugin_lower
    ));

    for func in &contract.functions {
        generate_cpp_guest_abi_wrapper(out, &plugin_lower, func)?;
    }

    out.push_str(&format!("static void* const {}_FNS[] = {{\n", plugin_upper));
    for func in &contract.functions {
        out.push_str(&format!(
            "    reinterpret_cast<void*>({0}_{1}_abi),\n",
            plugin_lower, func.name
        ));
    }
    out.push_str("};\n\n");

    out.push_str(&format!(
        "static PluginVTable {}_VTABLE = {{\n",
        plugin_upper
    ));
    out.push_str(&format!("    {}_CONTRACT_ID,\n", plugin_upper));
    out.push_str(&format!("    {}U,\n", contract_version));
    out.push_str(&format!("    {}U,\n", fn_count));
    out.push_str(&format!("    {}_FNS\n", plugin_upper));
    out.push_str("};\n\n");

    Ok(())
}

fn generate_cpp_guest_contract_vtable(
    out: &mut String,
    contract: &ResolvedContract,
) -> Result<(), PolyplugcError> {
    let lower: String = contract_name_to_lower_snake(&contract.name);
    let upper: String = contract_name_to_upper_snake(&contract.name);
    let class_name: String = contract_name_to_plugin_class(&contract.name);
    let fn_count: usize = contract.functions.len();
    let contract_version: u32 = (contract.version.minor << 16) | contract.version.patch;

    // Forward declaration of impl pointer
    out.push_str("// Forward declaration -- set by polyplug_init\n");
    out.push_str(&format!("extern {}* g_{}_impl;\n\n", class_name, lower));

    // Contract ID constant
    out.push_str(&format!(
        "constexpr uint64_t {}_CONTRACT_ID = 0x{:016X}ULL;\n\n",
        upper, contract.contract_id
    ));

    // ABI wrapper functions — one per function
    for func in &contract.functions {
        generate_cpp_guest_abi_wrapper(out, &lower, func)?;
    }

    // Function pointer array
    out.push_str(&format!("static void* const {}_FNS[] = {{\n", upper));
    for func in &contract.functions {
        out.push_str(&format!(
            "    reinterpret_cast<void*>({0}_{1}_abi),\n",
            lower, func.name
        ));
    }
    out.push_str("};\n\n");

    // VTable static
    out.push_str(&format!("static PluginVTable {}_VTABLE = {{\n", upper));
    out.push_str(&format!("    {}_CONTRACT_ID,\n", upper));
    out.push_str(&format!(
        "    {}U,  // contract_version: (minor << 16) | patch\n",
        contract_version
    ));
    out.push_str(&format!("    {}U,  // function_count\n", fn_count));
    out.push_str(&format!("    {}_FNS\n", upper));
    out.push_str("};\n\n");

    Ok(())
}

fn generate_cpp_guest_abi_wrapper(
    out: &mut String,
    contract_lower: &str,
    func: &ResolvedFunction,
) -> Result<(), PolyplugcError> {
    let fn_id: u32 = func.function_id;
    let is_void_return: bool = matches!(
        func.returns.as_ref(),
        None | Some(ResolvedTypeRef::AbiType(AbiBuiltin::Void))
    );

    out.push_str(&format!(
        "// ABI wrapper for {} (function_id = {})\n",
        func.name, fn_id
    ));
    out.push_str(&format!(
        "inline AbiError {0}_{1}_abi(const void* args, void* out) noexcept {{\n",
        contract_lower, func.name
    ));
    out.push_str("    try {\n");

    // Build the call expression
    let call_expr: String = build_guest_call_expr(contract_lower, func);
    out.push_str(&call_expr);

    if is_void_return {
        // For void, emit success return (call_expr already emits the call + newline)
        out.push_str("        (void)out;\n");
        out.push_str("        return AbiError{ABI_OK, StringView{nullptr, 0}};\n");
    } else {
        let ret_type: String = func
            .returns
            .as_ref()
            .map(cpp_type_name)
            .unwrap_or_else(|| "void".to_owned());
        out.push_str(&format!(
            "        *static_cast<{}*>(out) = result;\n",
            ret_type
        ));
        out.push_str("        return AbiError{ABI_OK, StringView{nullptr, 0}};\n");
    }

    out.push_str("    } catch (const std::exception&) {\n");
    out.push_str("        return AbiError{1U, StringView{nullptr, 0}};  // ABI_ERROR_GENERIC\n");
    out.push_str("    } catch (...) {\n");
    out.push_str("        return AbiError{3U, StringView{nullptr, 0}};  // ABI_ERROR_PANIC\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    Ok(())
}

/// Build the call-to-impl lines inside the try block.
/// For non-void, assigns `auto result = ...`. For void, just calls.
fn build_guest_call_expr(contract_lower: &str, func: &ResolvedFunction) -> String {
    let is_void_return: bool = matches!(
        func.returns.as_ref(),
        None | Some(ResolvedTypeRef::AbiType(AbiBuiltin::Void))
    );

    let result_prefix: &str = if is_void_return { "" } else { "auto result = " };

    if func.params.is_empty() {
        // No params — ignore args entirely
        return format!(
            "        (void)args;\n        {}g_{}_impl->{}();\n",
            result_prefix, contract_lower, func.name
        );
    }

    if func.params.len() == 1 {
        let param: &crate::ir::ResolvedParam = &func.params[0];
        match &param.ty {
            ResolvedTypeRef::UserDefined(type_name) => {
                // Single user-defined struct param — dereference args directly
                return format!(
                    "        {}g_{}_impl->{}(*static_cast<const {}*>(args));\n",
                    result_prefix, contract_lower, func.name, type_name
                );
            }
            ResolvedTypeRef::Primitive(_) | ResolvedTypeRef::AbiType(_) => {
                // Single primitive param — dereference args as the primitive type
                let cpp_ty: String = cpp_type_name(&param.ty);
                return format!(
                    "        {}g_{}_impl->{}(*static_cast<const {}*>(args));\n",
                    result_prefix, contract_lower, func.name, cpp_ty
                );
            }
        }
    }

    // Multiple params — use a packed struct
    let func_name_cap: String = capitalise_first(&func.name);
    let struct_name: String = format!("{}Args", func_name_cap);

    let mut code: String = String::new();
    // Inline struct definition
    code.push_str(&format!("        struct {} {{", struct_name));
    for param in &func.params {
        let cpp_ty: String = cpp_type_name(&param.ty);
        code.push_str(&format!(" {} {};", cpp_ty, param.name));
    }
    code.push_str(" };\n");

    // Cast args to packed struct pointer
    code.push_str(&format!(
        "        const {name}* packed = static_cast<const {name}*>(args);\n",
        name = struct_name
    ));

    // Build call argument list
    let call_args: Vec<String> = func
        .params
        .iter()
        .map(|p| format!("packed->{}", p.name))
        .collect();
    let call_args_str: String = call_args.join(", ");

    code.push_str(&format!(
        "        {}g_{}_impl->{}({});\n",
        result_prefix, contract_lower, func.name, call_args_str
    ));

    code
}

// ─── init.hpp generator ──────────────────────────────────────────────────────

fn generate_init_hpp(ir: &ValidatedIr) -> Result<String, PolyplugcError> {
    let mut out: String = String::new();
    let has_trace: bool = ir
        .bundle
        .as_ref()
        .is_some_and(|b: &crate::ir::ResolvedBundle| {
            b.plugins
                .iter()
                .any(|p: &crate::ir::ResolvedPlugin| p.optional.contains(&"trace".to_owned()))
        });
    out.push_str("// THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n");
    out.push_str("// Re-generate with: polyplugc generate --api api.toml --lang cpp --out <dir>\n");
    out.push_str("#pragma once\n");
    out.push_str("#include \"vtables.hpp\"\n");
    out.push_str("#include \"polyplug/abi.hpp\"\n\n");

    out.push_str("namespace polyplug_plugin {\n\nusing namespace polyplug_generated;\n\n");
    if let Some(bundle) = &ir.bundle {
        for plugin in &bundle.plugins {
            let plugin_lower: String = plugin.name.to_lowercase().replace('.', "_");
            let class_name = if let Some(contract_impl) = plugin.implements.first() {
                if let Some(contract) = ir.contracts.iter().find(|c| {
                    let contract_full =
                        format!("{}@{}.{}", c.name, c.version.major, c.version.minor);
                    &contract_full == contract_impl
                }) {
                    contract_name_to_plugin_class(&contract.name)
                } else {
                    "IPlugin".to_string()
                }
            } else {
                "IPlugin".to_string()
            };
            out.push_str(&format!(
                "{}* g_{}_impl = nullptr;\n",
                class_name, plugin_lower
            ));
        }
    } else {
        for contract in &ir.contracts {
            let lower: String = contract_name_to_lower_snake(&contract.name);
            let class_name: String = contract_name_to_plugin_class(&contract.name);
            out.push_str(&format!("{}* g_{}_impl = nullptr;\n", class_name, lower));
        }
    }
    out.push_str("\n}  // namespace polyplug_plugin\n\n");

    // polyplug_abi_version
    out.push_str("extern \"C\" uint32_t polyplug_abi_version() { return 1U; }\n\n");

    // polyplug_init
    out.push_str("extern \"C\" AbiError polyplug_init(PluginRegistrar* registrar, const PluginContext* ctx) {\n");
    out.push_str("    if (!registrar || !ctx) return AbiError{1U, StringView{nullptr, 0}};\n\n");
    if has_trace {
        out.push_str("    static constexpr uint32_t EXT_TRACE_ID = 0xC4EB9AEEu;\n");
        out.push_str("    // Optional: trace extension — query via host vtable at init time\n");
        out.push_str(
            "    const void* trace_vtable_ptr = registrar->host->get_extension(EXT_TRACE_ID);\n",
        );
        out.push_str(
            "    // trace_vtable_ptr is null if the host does not provide the trace extension.\n",
        );
        out.push_str(
            "    (void)trace_vtable_ptr;  // suppress unused warning if not used further\n\n",
        );
    }

    if let Some(bundle) = &ir.bundle {
        for plugin in &bundle.plugins {
            let plugin_upper: String = plugin.name.to_uppercase().replace('.', "_");
            let plugin_lower: String = plugin.name.to_lowercase().replace('.', "_");
            let contract_impl = plugin.implements.first().map(|s| s.as_str()).unwrap_or("");
            let (contract_name, version_str) = contract_impl
                .split_once('@')
                .unwrap_or((contract_impl, "1.0.0"));
            let (version_major, version_minor_patch) =
                version_str.split_once('.').unwrap_or((version_str, "0"));
            let version_minor = version_minor_patch.split('.').next().unwrap_or("0");
            let contract_name_full = format!("{}@{}", contract_name, version_major);

            out.push_str(&format!("    // Register plugin: {}\n", plugin.name));
            out.push_str(&format!(
                "    polyplug_plugin::set_{}_impl(polyplug_plugin::create_{}_impl());\n",
                plugin_lower, plugin_lower
            ));

            out.push_str(&format!(
                "    PluginDescriptor desc_{} = {{\n",
                plugin_upper
            ));
            out.push_str(&format!(
                "        {{ (const uint8_t*)\"{name}\", {len}U }},\n",
                name = plugin.name,
                len = plugin.name.len()
            ));
            out.push_str(&format!(
                "        {{ (const uint8_t*)\"{name}\", {len}U }},\n",
                name = contract_name_full,
                len = contract_name_full.len()
            ));
            out.push_str(&format!(
                "        {}U, {}U, 0U\n",
                version_major, version_minor
            ));
            out.push_str("    };\n");

            out.push_str(&format!(
                "    AbiError err_{upper} = registrar->register_plugin(registrar, &desc_{upper}, &polyplug_plugin::{upper}_VTABLE);\n",
                upper = plugin_upper
            ));
            out.push_str(&format!(
                "    if (err_{}.code != 0U) return err_{};\n\n",
                plugin_upper, plugin_upper
            ));
        }
    } else {
        for contract in &ir.contracts {
            generate_init_hpp_register_contract(&mut out, contract)?;
        }
    }

    out.push_str("    return AbiError{0U, StringView{nullptr, 0}};\n");
    out.push_str("}\n");

    Ok(out)
}

fn generate_init_hpp_register_contract(
    out: &mut String,
    contract: &ResolvedContract,
) -> Result<(), PolyplugcError> {
    let lower: String = contract_name_to_lower_snake(&contract.name);
    let upper: String = contract_name_to_upper_snake(&contract.name);
    let name_bytes: usize = contract.name.len();

    out.push_str(&format!("    // Register contract: {}\n", contract.name));
    out.push_str(&format!(
        "    polyplug_plugin::g_{0}_impl = polyplug_plugin::create_{0}_impl();\n",
        lower
    ));

    out.push_str("    PluginDescriptor desc_");
    out.push_str(&upper);
    out.push_str(" = {\n");
    let contract_name_full: String = format!(
        "{}@{}.{}",
        contract.name, contract.version.major, contract.version.minor
    );
    let name_bytes_full: usize = contract_name_full.len();
    out.push_str(&format!(
        "        {{ (const uint8_t*)\"{name}\", {len}U }},  // name\n",
        name = contract.name,
        len = name_bytes
    ));
    out.push_str(&format!(
        "        {{ (const uint8_t*)\"{name}\", {len}U }},  // contract_name\n",
        name = contract_name_full,
        len = name_bytes_full
    ));
    out.push_str(&format!(
        "        {}U, {}U, {}U\n",
        contract.version.major, contract.version.minor, contract.version.patch
    ));
    out.push_str("    };\n");

    out.push_str(&format!(
        "    AbiError err_{upper} = registrar->register_plugin(registrar, &desc_{upper}, &polyplug_plugin::{upper}_VTABLE);\n",
        upper = upper
    ));
    out.push_str(&format!(
        "    if (err_{}.code != 0U) return err_{};\n\n",
        upper, upper
    ));

    Ok(())
}

// ─── host_callers.hpp generator ──────────────────────────────────────────────

fn generate_host_callers_hpp(ir: &ValidatedIr) -> Result<String, PolyplugcError> {
    let mut out: String = String::new();
    out.push_str("// THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n");
    out.push_str("// Re-generate with: polyplugc generate --api api.toml --lang cpp --out <dir>\n");
    out.push_str("#pragma once\n");
    out.push_str("#include \"types.hpp\"\n");
    out.push_str("#include \"polyplug/error.hpp\"\n");
    out.push_str("#include \"polyplug/abi.hpp\"\n");
    out.push_str("#include \"polyplug/runtime.hpp\"\n");
    out.push_str("#include <optional>\n\n");
    out.push_str("namespace polyplug_generated {\n\n");
    if let Some(ref bundle) = ir.bundle {
        out.push_str(&format!(
            "static constexpr uint64_t MY_BUNDLE_ID = {}ULL;\n\n",
            bundle.bundle_id
        ));
    }

    for contract in &ir.contracts {
        generate_cpp_host_contract(&mut out, contract)?;
    }

    out.push_str("}  // namespace polyplug_generated\n");
    Ok(out)
}

// ─── manifest.toml generator ─────────────────────────────────────────────────

fn generate_manifest_toml() -> String {
    let mut out: String = String::new();
    out.push_str("# THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n");
    out.push_str("[manifest]\n");
    out.push_str("schema_version = 1\n");
    out.push_str("lang = \"cpp\"\n");
    out.push_str("generated_by = \"polyplugc\"\n");
    out
}

/// Generate a full discovery `manifest.toml` for `--bundle` invocations.
/// Called only when `ir.bundle.is_some()`.
fn generate_bundle_manifest_cpp(ir: &ValidatedIr) -> String {
    let bundle: &ResolvedBundle = match ir.bundle.as_ref() {
        Some(b) => b,
        None => return String::from("# ERROR: bundle manifest called without bundle IR\n"),
    };

    let name: &str = &bundle.name;
    let version: String = format!(
        "{}.{}.{}",
        bundle.version.major, bundle.version.minor, bundle.version.patch
    );
    // C++ native runtime uses platform-specific shared libraries from bundle.toml
    let file_field: String = super::format_manifest_file_field(&bundle.file);

    // Collect provides: all implements from all plugins, deduplicated
    let mut provides: Vec<String> = bundle
        .plugins
        .iter()
        .flat_map(|p: &ResolvedPlugin| p.implements.iter().cloned())
        .map(|impl_str: String| {
            if let Some(at_pos) = impl_str.find('@') {
                let contract_name: &str = &impl_str[..at_pos];
                let version_part: &str = &impl_str[at_pos + 1..];
                if let Some(dot_pos) = version_part.find('.') {
                    let major: &str = &version_part[..dot_pos];
                    format!("{}@{}", contract_name, major)
                } else {
                    impl_str
                }
            } else {
                impl_str
            }
        })
        .collect();
    provides.sort();
    provides.dedup();

    // Build TOML string array for provides
    let provides_toml: String = if provides.is_empty() {
        String::from("[]")
    } else {
        format!(
            "[{}]",
            provides
                .iter()
                .map(|s: &String| format!("\"{}\"", s))
                .collect::<Vec<_>>()
                .join(", ")
        )
    };

    // Build function_count inline table: only for contracts this bundle PROVIDES
    let provides_set: std::collections::HashSet<String> = provides.iter().cloned().collect();
    let fn_count_entries: Vec<String> = ir
        .contracts
        .iter()
        .filter(|c: &&ResolvedContract| {
            provides_set.contains(&format!("{}@{}", c.name, c.version.major))
        })
        .map(|c: &ResolvedContract| {
            let fn_count: u32 = c.functions.len() as u32;
            format!("\"{}@{}\" = {}", c.name, c.version.major, fn_count)
        })
        .collect();
    let function_count_toml: String = format!("{{ {} }}", fn_count_entries.join(", "));

    // Build [[dependency]] tables
    let mut dep_tables: String = String::new();
    for dep in &bundle.dependencies {
        match dep {
            ResolvedDependency::ByContract {
                contract,
                contract_id,
                min_version,
            } => {
                dep_tables.push_str(&format!(
                    "[[dependency]]\ncontract = \"{}\"\ncontract_id = 0x{:016X}\nmin_version = {}\n\n",
                    contract, contract_id, min_version
                ));
            }
            ResolvedDependency::ByBundle {
                bundle: dep_bundle,
                bundle_id,
                contract,
                contract_id,
                min_version,
            } => {
                dep_tables.push_str(&format!(
                    "[[dependency]]\nbundle = \"{}\"\nbundle_id = 0x{:016X}\ncontract = \"{}\"\ncontract_id = 0x{:016X}\nmin_version = {}\n\n",
                    dep_bundle, bundle_id, contract, contract_id, min_version
                ));
            }
        }
    }

    let reinit: bool = bundle.needs_reinit_on_dep_reload;
    let runtime: &str = "native";

    format!(
        "# THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n\
name = \"{name}\"\n\
id = {bundle_id}\n\
version = \"{version}\"\n\
runtime = \"{runtime}\"\n\
provides = {provides_toml}\n\
function_count = {function_count_toml}\n\
needs_reinit_on_dep_reload = {reinit}\n\
{file_field}\n\
{dep_tables}",
        bundle_id = bundle.bundle_id
    )
}

// ─── Per-enum emitter ────────────────────────────────────────────────────────

fn substitute_variant_refs_cpp(
    declared_variants: &[EnumVariant],
    expr: &str,
    enum_name: &str,
    repr_cpp: &str,
) -> String {
    let declared_names: Vec<&str> = declared_variants.iter().map(|v| v.name.as_str()).collect();
    let chars: Vec<char> = expr.chars().collect();
    let len: usize = chars.len();
    let mut result: String = String::new();
    let mut i: usize = 0;
    while i < len {
        let c: char = chars[i];
        if c.is_alphabetic() || c == '_' {
            let start: usize = i;
            while i < len && (chars[i].is_alphanumeric() || chars[i] == '_') {
                i += 1;
            }
            let ident: String = chars[start..i].iter().collect();
            if declared_names.contains(&ident.as_str()) {
                result.push_str(&format!(
                    "static_cast<{}>({}::{})",
                    repr_cpp, enum_name, ident
                ));
            } else {
                result.push_str(&ident);
            }
        } else {
            result.push(c);
            i += 1;
        }
    }
    result
}

fn generate_cpp_enum(out: &mut String, e: &EnumDef) {
    let repr_cpp: &str = e.repr.cpp_name();
    out.push_str(&format!("/// Enum `{}` (repr: {})\n", e.name, repr_cpp));
    out.push_str(&format!("enum class {} : {} {{\n", e.name, repr_cpp));
    for variant in &e.variants {
        let subst_value: String =
            substitute_variant_refs_cpp(&e.variants, &variant.value, &e.name, repr_cpp);
        out.push_str(&format!("    {} = {},\n", variant.name, subst_value));
    }
    out.push_str("};\n");
    if e.bitflag {
        out.push_str(&format!(
            "inline {} operator|({}  a, {} b) {{ return static_cast<{}>(static_cast<{}>(a) | static_cast<{}>(b)); }}\n",
            e.name, e.name, e.name, e.name, repr_cpp, repr_cpp
        ));
        out.push_str(&format!(
            "inline {} operator&({} a, {} b) {{ return static_cast<{}>(static_cast<{}>(a) & static_cast<{}>(b)); }}\n",
            e.name, e.name, e.name, e.name, repr_cpp, repr_cpp
        ));
        out.push_str(&format!(
            "inline {} operator~({} a) {{ return static_cast<{}>(~static_cast<{}>(a)); }}\n",
            e.name, e.name, e.name, repr_cpp
        ));
    }
    out.push('\n');
}

// ─── Per-type struct emitter ──────────────────────────────────────────────────

fn generate_cpp_type(out: &mut String, ty: &ResolvedType) {
    out.push_str(&format!("/// User-defined type `{}`\n", ty.name));
    out.push_str("struct ");
    out.push_str(&ty.name);
    out.push_str(" {\n");
    for field in &ty.fields {
        out.push_str(&format!(
            "    {} {};\n",
            cpp_type_name(&field.ty),
            field.name
        ));
    }
    out.push_str("};\n\n");
}

// ─── Per-contract class emitter ───────────────────────────────────────────────

fn generate_cpp_host_contract(
    out: &mut String,
    contract: &ResolvedContract,
) -> Result<(), PolyplugcError> {
    let class_name: String = contract_name_to_class(&contract.name);
    let contract_upper: String = contract.name.to_uppercase().replace(['.', '-'], "_");

    out.push_str(&format!(
        "/// Host caller for contract `{}` (id=0x{:016X})\n",
        contract.name, contract.contract_id
    ));
    out.push_str(&format!("class {} {{\npublic:\n", class_name));

    out.push_str("    /// Factory method - creates instance or nullopt if not found.\n");
    out.push_str(&format!(
        "    static std::optional<{}> create(polyplug::Runtime& rt, uint32_t min_version = 0) noexcept {{\n",
        class_name
    ));
    out.push_str(&format!(
        "        uint64_t handle = rt.find({}_CONTRACT_ID, min_version);\n",
        contract_upper
    ));
    out.push_str("        if (handle == UINT64_MAX) {\n");
    out.push_str("            return std::nullopt;\n");
    out.push_str("        }\n");
    out.push_str("        polyplug::PluginGuard guard = rt.resolve_plugin(handle);\n");
    out.push_str("        if (!guard) {\n");
    out.push_str("            return std::nullopt;\n");
    out.push_str("        }\n");
    out.push_str(&format!(
        "        return {}(std::move(guard));\n",
        class_name
    ));
    out.push_str("    }\n\n");

    out.push_str("    // Move-only (guard is not copyable)\n");
    out.push_str(&format!(
        "    {}({}&&) noexcept = default;\n",
        class_name, class_name
    ));
    out.push_str(&format!(
        "    {}& operator=({}&&) noexcept = default;\n",
        class_name, class_name
    ));
    out.push_str(&format!(
        "    {}(const {}&) = delete;\n",
        class_name, class_name
    ));
    out.push_str(&format!(
        "    {}& operator=(const {}&) = delete;\n\n",
        class_name, class_name
    ));

    out.push_str("    /// Check if instance is valid.\n");
    out.push_str(
        "    explicit operator bool() const noexcept { return static_cast<bool>(guard_); }\n\n",
    );
    out.push_str("    /// Check if instance is valid.\n");
    out.push_str("    bool is_valid() const noexcept { return static_cast<bool>(guard_); }\n\n");
    out.push_str("    /// Explicitly destroy instance (optional - destructor does this too).\n");
    out.push_str("    void reset() noexcept { guard_ = polyplug::PluginGuard{}; }\n\n");

    for func in &contract.functions {
        generate_cpp_host_function(out, &class_name, func)?;
    }

    out.push_str("private:\n");
    out.push_str(&format!(
        "    explicit {}(polyplug::PluginGuard guard) noexcept\n",
        class_name
    ));
    out.push_str("        : guard_(std::move(guard)) {}\n\n");
    out.push_str("    polyplug::PluginGuard guard_;\n");
    out.push_str("};\n\n");
    Ok(())
}

// ─── Per-function method emitter ──────────────────────────────────────────────

fn generate_cpp_host_function(
    out: &mut String,
    class_name: &str,
    func: &ResolvedFunction,
) -> Result<(), PolyplugcError> {
    let return_type: String = func
        .returns
        .as_ref()
        .map(cpp_type_name)
        .unwrap_or_else(|| "void".to_owned());

    // Build parameter list string.
    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| format!("{} {}", cpp_type_name(&p.ty), p.name))
        .collect();
    let params_str: String = params.join(", ");

    out.push_str(&format!(
        "    {} {}({}) {{\n",
        return_type, func.name, params_str
    ));

    // Determine args_ptr expression.
    let args_ptr_code: String = build_args_ptr_code(class_name, func);
    out.push_str(&args_ptr_code);

    let fn_id: u32 = func.function_id;

    let is_void_return: bool = matches!(
        func.returns.as_ref(),
        None | Some(ResolvedTypeRef::AbiType(AbiBuiltin::Void))
    );

    out.push_str("        const PluginVTable* vtable = guard_.vtable();\n");
    out.push_str("        if (!vtable) {\n");
    out.push_str("            polyplug::check_abi_error(AbiError{4, {nullptr, 0}});\n");
    out.push_str("        }\n");

    if is_void_return {
        out.push_str(&format!(
            "        auto fn_ = reinterpret_cast<AbiError(*)(const void*, void*)>(vtable->functions[{}U]);\n",
            fn_id
        ));
        out.push_str("        AbiError err = fn_(args_ptr, nullptr);\n");
        out.push_str("        polyplug::check_abi_error(err);\n");
    } else {
        out.push_str(&format!("        {} out{{}};\n", return_type));
        out.push_str("        void* out_ptr = &out;\n");
        out.push_str(&format!(
            "        if ({}_u32 >= vtable->function_count) {{ polyplug::check_abi_error(AbiError{{4, {{nullptr, 0}}}}); }}\n",
            fn_id
        ));
        out.push_str(&format!(
            "        auto fn_ = reinterpret_cast<AbiError(*)(const void*, void*)>(vtable->functions[{}U]);\n",
            fn_id
        ));
        out.push_str("        AbiError err = fn_(args_ptr, out_ptr);\n");
        out.push_str("        polyplug::check_abi_error(err);\n");
        out.push_str("        return out;\n");
    }

    out.push_str("    }\n\n");
    Ok(())
}

/// Build the `args_ptr` preamble lines for a function body.
///
/// Returns the lines (indented 8 spaces) that set up `args_ptr`.
fn build_args_ptr_code(class_name: &str, func: &ResolvedFunction) -> String {
    if func.params.is_empty() {
        // No args — pass nullptr.
        return "        const void* args_ptr = nullptr;\n".to_owned();
    }

    if func.params.len() == 1 {
        let param = &func.params[0];
        match &param.ty {
            ResolvedTypeRef::UserDefined(_) => {
                // User-defined struct: pass pointer directly.
                return format!("        const void* args_ptr = &{};\n", param.name);
            }
            ResolvedTypeRef::Primitive(_) | ResolvedTypeRef::AbiType(_) => {
                // Single primitive: store in local and pass pointer.
                let cpp_ty: String = cpp_type_name(&param.ty);
                return format!(
                    "        const {cpp_ty} local_{name} = {name};\n        const void* args_ptr = &local_{name};\n",
                    cpp_ty = cpp_ty,
                    name = param.name
                );
            }
        }
    }

    // Multiple params: pack into a generated args struct.
    // Capitalise the function name for the struct name.
    let func_name_cap: String = capitalise_first(&func.name);
    let struct_name: String = format!("{}{}{}", class_name, func_name_cap, "Args");

    let mut code: String = String::new();
    // Inline struct definition.
    code.push_str(&format!("        struct {} {{", struct_name));
    for param in &func.params {
        let cpp_ty: String = cpp_type_name(&param.ty);
        code.push_str(&format!(" {} {};", cpp_ty, param.name));
    }
    code.push_str(" };\n");

    // Initialise the struct.
    let field_inits: Vec<String> = func.params.iter().map(|p| p.name.clone()).collect();
    code.push_str(&format!(
        "        {} args_val{{ {} }};\n",
        struct_name,
        field_inits.join(", ")
    ));
    code.push_str("        const void* args_ptr = &args_val;\n");
    code
}

// ─── Utility helpers ──────────────────────────────────────────────────────────

fn cpp_type_name(ty: &ResolvedTypeRef) -> String {
    match ty {
        ResolvedTypeRef::Primitive(p) => p.cpp_name().to_owned(),
        ResolvedTypeRef::AbiType(AbiBuiltin::StringView) => "StringView".to_owned(),
        ResolvedTypeRef::AbiType(AbiBuiltin::Buffer) => "Buffer".to_owned(),
        ResolvedTypeRef::AbiType(AbiBuiltin::Ptr) => "void*".to_owned(),
        ResolvedTypeRef::AbiType(AbiBuiltin::Void) => "void".to_owned(),
        ResolvedTypeRef::UserDefined(name) => name.clone(),
    }
}

fn contract_name_to_class(name: &str) -> String {
    // Convert "image.decode" -> "ImageDecodeContract"
    name.split('.')
        .map(|p| {
            let mut chars: core::str::Chars<'_> = p.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join("")
        + "Contract"
}

/// Convert "test.add" → "TestAddPlugin"
fn contract_name_to_plugin_class(name: &str) -> String {
    name.split('.')
        .map(|p| {
            let mut chars: core::str::Chars<'_> = p.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join("")
        + "Plugin"
}

/// Convert "test.add" → "test_add"
fn contract_name_to_lower_snake(name: &str) -> String {
    name.replace('.', "_")
}

/// Convert "test.add" → "TEST_ADD"
fn contract_name_to_upper_snake(name: &str) -> String {
    name.replace('.', "_").to_uppercase()
}

fn capitalise_first(s: &str) -> String {
    let mut chars: core::str::Chars<'_> = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

// Suppress unused import warning
const _: fn() = || {
    let _ = cpp_type_name(&ResolvedTypeRef::Primitive(PrimitiveType::U8));
};

#[cfg(test)]
mod tests {
    #![allow(clippy::expect_used)]
    #![allow(clippy::unwrap_used)]

    use super::*;
    use crate::ir::ReprType;

    #[test]
    fn class_name_conversion() {
        assert_eq!(
            contract_name_to_class("image.decode"),
            "ImageDecodeContract"
        );
    }

    #[test]
    fn plugin_class_name_conversion() {
        assert_eq!(contract_name_to_plugin_class("test.add"), "TestAddPlugin");
    }

    #[test]
    fn lower_snake_conversion() {
        assert_eq!(contract_name_to_lower_snake("test.add"), "test_add");
    }

    #[test]
    fn upper_snake_conversion() {
        assert_eq!(contract_name_to_upper_snake("test.add"), "TEST_ADD");
    }

    #[test]
    fn generate_host_empty_ir() {
        let generator: CppGenerator = CppGenerator;
        let ir: ValidatedIr = ValidatedIr {
            types: vec![],
            enums: vec![],
            contracts: vec![],
            bundle: None,
        };
        let mut files: GeneratedFiles = GeneratedFiles::default();
        generator
            .generate_host(&ir, &mut files)
            .expect("generate_host");
        // Now produces 3 files: types.hpp, host_callers.hpp, manifest.toml
        assert!(!files.files.is_empty());
        // At least one file contains the AUTO-GENERATED header
        assert!(
            files
                .files
                .iter()
                .any(|f| f.content.contains("AUTO-GENERATED"))
        );
    }

    #[test]
    fn generate_guest_empty_ir() {
        let generator: CppGenerator = CppGenerator;
        let ir: ValidatedIr = ValidatedIr {
            types: vec![],
            enums: vec![],
            contracts: vec![],
            bundle: None,
        };
        let mut files: GeneratedFiles = GeneratedFiles::default();
        generator
            .generate_guest(&ir, &mut files)
            .expect("generate_guest");
        // Produces 4 files (bundle=None, so no manifest): types.hpp, contracts.hpp, vtables.hpp, init.hpp
        assert_eq!(files.files.len(), 4);
        let names: Vec<String> = files
            .files
            .iter()
            .map(|f| f.path.to_string_lossy().to_string())
            .collect();
        assert!(names.contains(&"guest/types.hpp".to_owned()));
        assert!(names.contains(&"guest/contracts.hpp".to_owned()));
        assert!(names.contains(&"guest/vtables.hpp".to_owned()));
        assert!(names.contains(&"guest/init.hpp".to_owned()));
    }

    #[test]
    fn generate_cpp_enum_non_bitflag() {
        let e: EnumDef = EnumDef {
            name: "PixelFormat".to_owned(),
            repr: ReprType::U32,
            bitflag: false,
            variants: vec![
                EnumVariant {
                    name: "Unknown".to_owned(),
                    value: "0".to_owned(),
                },
                EnumVariant {
                    name: "Rgba8".to_owned(),
                    value: "1".to_owned(),
                },
            ],
        };
        let mut out: String = String::new();
        generate_cpp_enum(&mut out, &e);
        assert!(
            out.contains("enum class PixelFormat : uint32_t"),
            "missing enum class: {out}"
        );
        assert!(
            out.contains("Unknown = 0"),
            "missing Unknown variant: {out}"
        );
        assert!(
            !out.contains("operator|"),
            "non-bitflag should not have operator|: {out}"
        );
    }

    #[test]
    fn generate_cpp_enum_bitflag() {
        let e: EnumDef = EnumDef {
            name: "ImageFlags".to_owned(),
            repr: ReprType::U32,
            bitflag: true,
            variants: vec![
                EnumVariant {
                    name: "None".to_owned(),
                    value: "0".to_owned(),
                },
                EnumVariant {
                    name: "Compressed".to_owned(),
                    value: "1".to_owned(),
                },
            ],
        };
        let mut out: String = String::new();
        generate_cpp_enum(&mut out, &e);
        assert!(
            out.contains("enum class ImageFlags : uint32_t"),
            "missing enum class: {out}"
        );
        assert!(out.contains("operator|"), "missing operator|: {out}");
        assert!(out.contains("operator&"), "missing operator&: {out}");
        assert!(out.contains("operator~"), "missing operator~: {out}");
        assert!(
            out.contains("static_cast<uint32_t>"),
            "missing static_cast: {out}"
        );
    }

    #[test]
    fn generate_cpp_host_contract_has_factory_method() {
        use crate::ir::PrimitiveType;
        use crate::ir::ResolvedContract;
        use crate::ir::ResolvedFunction;
        use crate::ir::ResolvedParam;
        use crate::ir::ResolvedTypeRef;
        use crate::ir::Version;

        let contract = ResolvedContract {
            name: "test.add".to_owned(),
            contract_id: 0x123456789ABCDEF0,
            version: Version {
                major: 1,
                minor: 0,
                patch: 0,
            },
            functions: vec![ResolvedFunction {
                name: "add".to_owned(),
                function_id: 0,
                params: vec![
                    ResolvedParam {
                        name: "a".to_owned(),
                        ty: ResolvedTypeRef::Primitive(PrimitiveType::I32),
                    },
                    ResolvedParam {
                        name: "b".to_owned(),
                        ty: ResolvedTypeRef::Primitive(PrimitiveType::I32),
                    },
                ],
                returns: Some(ResolvedTypeRef::Primitive(PrimitiveType::I32)),
            }],
        };

        let mut out: String = String::new();
        generate_cpp_host_contract(&mut out, &contract).unwrap();

        assert!(
            out.contains("static std::optional<TestAddContract> create(polyplug::Runtime& rt, uint32_t min_version = 0)"),
            "missing factory method: {out}"
        );

        assert!(
            out.contains("polyplug::PluginGuard guard_"),
            "missing guard member: {out}"
        );

        assert!(
            out.contains("bool is_valid() const noexcept"),
            "missing is_valid method: {out}"
        );
        assert!(
            out.contains("explicit operator bool() const noexcept"),
            "missing operator bool: {out}"
        );
        assert!(
            out.contains("void reset() noexcept"),
            "missing reset method: {out}"
        );

        assert!(
            out.contains("TestAddContract(TestAddContract&&) noexcept = default"),
            "missing move constructor: {out}"
        );
        assert!(
            out.contains("TestAddContract(const TestAddContract&) = delete"),
            "missing deleted copy constructor: {out}"
        );

        assert!(
            out.contains("explicit TestAddContract(polyplug::PluginGuard guard) noexcept"),
            "missing private constructor: {out}"
        );

        assert!(
            out.contains("guard_.vtable()"),
            "missing guard_.vtable() call: {out}"
        );
    }
}
