//! js_deno generator — produces V8/deno_core-compatible TypeScript guest code.
//!
//! THIS FILE IS PART OF polyplugc.
//! Generates code using BigInt for all u64/pointer values (V8 has native BigInt).

use std::path::PathBuf;

use crate::error::PolyplugcError;
use crate::generators::CodeGenerator;
use crate::generators::GeneratedFile;
use crate::generators::GeneratedFiles;
use crate::ir::AbiBuiltin;
use crate::ir::EnumDef;
use crate::ir::EnumVariant;
use crate::ir::PrimitiveType;
use crate::ir::ReprType;
use crate::ir::ResolvedBundle;
use crate::ir::ResolvedContract;
use crate::ir::ResolvedDependency;
use crate::ir::ResolvedField;
use crate::ir::ResolvedParam;
use crate::ir::ResolvedPlugin;
use crate::ir::ResolvedType;
use crate::ir::ResolvedTypeRef;
use crate::ir::ValidatedIr;

/// Generator for js-deno plugin bundles.
///
/// Produces TypeScript files using BigInt for 64-bit values
/// (V8/deno_core has native BigInt support).
pub(crate) struct JsDenoGenerator;

impl CodeGenerator for JsDenoGenerator {
    fn language_name(&self) -> &'static str {
        "js-deno"
    }

    fn generate_host(
        &self,
        ir: &ValidatedIr,
        files: &mut GeneratedFiles,
    ) -> Result<(), PolyplugcError> {
        files.files.push(GeneratedFile {
            path: PathBuf::from("host/types.ts"),
            content: generate_types_ts(ir),
            force_regenerate: false,
        });
        files.files.push(GeneratedFile {
            path: PathBuf::from("host/callers.ts"),
            content: generate_callers_ts(ir),
            force_regenerate: false,
        });
        Ok(())
    }

    fn generate_guest(
        &self,
        _ir: &ValidatedIr,
        _files: &mut GeneratedFiles,
    ) -> Result<(), PolyplugcError> {
        Err(PolyplugcError::GuestGenerationNotSupported {
            language: "js-deno".to_owned(),
            reason: "V8 cannot be loaded as a shared library (.so) on Linux due to thread-local storage (TLS) requirements. Use js-quickjs for JavaScript guest plugins instead.".to_owned(),
        })
    }
}

/// Map a resolved type reference to its TypeScript representation (Deno/V8 BigInt style).
fn ts_type_ref(ty: &ResolvedTypeRef) -> String {
    match ty {
        ResolvedTypeRef::Primitive(p) => ts_primitive(p).to_owned(),
        ResolvedTypeRef::AbiType(b) => ts_abi_builtin(b).to_owned(),
        ResolvedTypeRef::UserDefined(name) => name.clone(),
    }
}

fn ts_primitive(p: &PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::U8
        | PrimitiveType::U16
        | PrimitiveType::U32
        | PrimitiveType::I8
        | PrimitiveType::I16
        | PrimitiveType::I32
        | PrimitiveType::F32
        | PrimitiveType::F64 => "number",
        PrimitiveType::Bool => "boolean",
        PrimitiveType::U64 | PrimitiveType::I64 => "bigint",
    }
}

fn ts_abi_builtin(b: &AbiBuiltin) -> &'static str {
    match b {
        AbiBuiltin::StringView => "{ ptr: bigint; len: number }",
        AbiBuiltin::Buffer => "{ ptr: bigint; len: number; cap: number }",
        AbiBuiltin::Ptr => "bigint",
        AbiBuiltin::Void => "void",
    }
}

fn generate_types_ts(ir: &ValidatedIr) -> String {
    let mut out: String = String::new();
    out.push_str(
        "// THIS FILE IS AUTO-GENERATED BY polyplugc\n\
         // DO NOT EDIT BY HAND\n\
         // Runtime: js-deno\n\n",
    );
    for e in &ir.enums {
        generate_js_deno_enum(&mut out, e);
    }
    for type_def in &ir.types {
        render_resolved_type(&mut out, type_def);
    }
    out
}

fn substitute_variant_refs_jsdeno(declared_variants: &[EnumVariant], expr: &str) -> String {
    let chars: Vec<char> = expr.chars().collect();
    let len: usize = chars.len();
    let mut result: String = String::new();
    let mut i: usize = 0;
    while i < len {
        let c: char = chars[i];
        if c.is_alphabetic() || c == '_' {
            let start: usize = i;
            while i < len && (chars[i].is_alphanumeric() || chars[i] == '_') {
                i += 1;
            }
            let ident: String = chars[start..i].iter().collect();
            let found: Option<&EnumVariant> = declared_variants.iter().find(|v| v.name == ident);
            if let Some(ref_variant) = found {
                result.push('(');
                result.push_str(&ref_variant.value);
                result.push(')');
            } else {
                result.push_str(&ident);
            }
        } else {
            result.push(c);
            i += 1;
        }
    }
    result
}

/// Returns true if the expression is a pure integer literal (decimal, hex, binary).
fn is_pure_integer_literal(s: &str) -> bool {
    let s: &str = s.trim();
    if s.is_empty() {
        return false;
    }
    // Hex: 0x...
    if s.starts_with("0x") || s.starts_with("0X") {
        return s[2..].chars().all(|c| c.is_ascii_hexdigit());
    }
    // Binary: 0b...
    if s.starts_with("0b") || s.starts_with("0B") {
        return s[2..].chars().all(|c| c == '0' || c == '1');
    }
    // Decimal
    s.chars().all(|c| c.is_ascii_digit())
}

fn generate_js_deno_enum(out: &mut String, e: &EnumDef) {
    let is_u64: bool = matches!(e.repr, ReprType::U64);
    if is_u64 {
        out.push_str(&format!("/** @u64enum Enum {} */\n", e.name));
    } else if e.bitflag {
        out.push_str(&format!("/** @bitflag Enum {} */\n", e.name));
    } else {
        out.push_str(&format!("/** Enum {} */\n", e.name));
    }
    out.push_str(&format!("const {} = Object.freeze({{\n", e.name));
    for variant in &e.variants {
        let subst_value: String = substitute_variant_refs_jsdeno(&e.variants, &variant.value);
        let final_value: String = if is_u64 && is_pure_integer_literal(&subst_value) {
            format!("{}n", subst_value.trim())
        } else {
            subst_value
        };
        out.push_str(&format!("    {}: {},\n", variant.name, final_value));
    }
    out.push_str("} as const);\n");
    out.push_str(&format!(
        "type {} = typeof {}[keyof typeof {}];\n\n",
        e.name, e.name, e.name
    ));
}

fn render_resolved_type(out: &mut String, type_def: &ResolvedType) {
    out.push_str(&format!("export interface {} {{\n", type_def.name));
    for field in &type_def.fields {
        render_resolved_field(out, field);
    }
    out.push_str("}\n\n");
}

fn render_resolved_field(out: &mut String, field: &ResolvedField) {
    let ts_t: String = ts_type_ref(&field.ty);
    out.push_str(&format!("    readonly {}: {};\n", field.name, ts_t));
}

#[allow(dead_code)]
fn generate_contracts_ts(ir: &ValidatedIr) -> Result<String, PolyplugcError> {
    let mut out: String = String::new();
    out.push_str(
        "// THIS FILE IS AUTO-GENERATED BY polyplugc\n\
         // DO NOT EDIT BY HAND\n\
         // Runtime: js-deno\n\n",
    );
    out.push_str("import type { } from './types';\n\n");

    if let Some(bundle) = &ir.bundle {
        for plugin in &bundle.plugins {
            for contract_impl in &plugin.implements {
                if let Some(contract) = ir.contracts.iter().find(|c| {
                    let contract_full =
                        format!("{}@{}.{}", c.name, c.version.major, c.version.minor);
                    &contract_full == contract_impl
                }) {
                    render_plugin_vtable_deno(&mut out, &plugin.name, contract)?;
                }
            }
        }
    }

    Ok(out)
}

#[allow(dead_code)]
fn render_plugin_vtable_deno(
    out: &mut String,
    plugin_name: &str,
    contract: &ResolvedContract,
) -> Result<(), PolyplugcError> {
    let plugin_var: String = plugin_name.to_uppercase().replace(['.', '-'], "_");
    let contract_name_full: String = format!("{}@{}", contract.name, contract.version.major);
    let contract_id: u64 = polyplug_abi::contract_id(&contract.name, contract.version.major);
    let function_count: usize = contract.functions.len();

    out.push_str(&format!(
        "// Plugin: {plugin_name} ({contract_name_full})\n"
    ));
    for func in &contract.functions {
        let params: String = func
            .params
            .iter()
            .map(|p: &ResolvedParam| format!("{}: {}", p.name, ts_type_ref(&p.ty)))
            .collect::<Vec<String>>()
            .join(", ");
        let ret_type: String = match &func.returns {
            None => "void".to_owned(),
            Some(ty) => ts_type_ref(ty),
        };
        out.push_str(&format!(
            "//   {fn_name}({params}): {ret_type}\n",
            fn_name = func.name
        ));
    }

    out.push_str(&format!("\nconst {plugin_var}_VTABLE = {{\n"));
    out.push_str(&format!("    contractId: 0x{:016X}n,\n", contract_id));
    out.push_str(&format!("    fnCount: {function_count},\n"));
    out.push_str("    functions: null as unknown as ((...args: any[]) => any)[],\n");
    out.push_str(&format!("    contractName: \"{contract_name_full}\"\n"));
    out.push_str("};\n");

    let set_impl_name: String = format!(
        "set{}Impl",
        plugin_name
            .replace(['.', '-'], "_")
            .split('_')
            .map(|s| {
                let mut chars = s.chars();
                match chars.next() {
                    None => String::new(),
                    Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                }
            })
            .collect::<String>()
    );

    out.push_str(&format!("\nexport function {set_impl_name}("));
    let impl_params: Vec<String> = contract
        .functions
        .iter()
        .enumerate()
        .map(|(idx, f)| {
            let params: String = f
                .params
                .iter()
                .map(|p| format!("{}: {}", p.name, ts_type_ref(&p.ty)))
                .collect::<Vec<String>>()
                .join(", ");
            let ret: String = match &f.returns {
                None => "void".to_owned(),
                Some(ty) => ts_type_ref(ty),
            };
            format!("fn{idx}: ({}) => {}", params, ret)
        })
        .collect();
    out.push_str(&impl_params.join(", "));
    out.push_str("): void {\n");

    // Build functions array
    out.push_str(&format!("    {plugin_var}_VTABLE.functions = ["));
    let fn_refs: Vec<String> = contract
        .functions
        .iter()
        .enumerate()
        .map(|(idx, _)| format!("fn{idx}"))
        .collect();
    out.push_str(&fn_refs.join(", "));
    out.push_str("];\n");

    out.push_str("    // Register vtable with host\n");
    out.push_str("    // Host provides Deno.core.ops.op_register_vtable\n");
    out.push_str("    (globalThis as any).Deno?.core?.ops?.op_register_vtable?.(\n");
    out.push_str(&format!("        {plugin_var}_VTABLE.contractId,\n"));
    out.push_str(&format!("        {plugin_var}_VTABLE.fnCount,\n"));
    out.push_str(&format!("        {plugin_var}_VTABLE.contractName,\n"));
    out.push_str(&format!("        {plugin_var}_VTABLE.functions\n"));
    out.push_str("    );\n");
    out.push_str("}\n");

    Ok(())
}

#[allow(dead_code)]
fn generate_init_ts(ir: &ValidatedIr) -> String {
    let bundle: &ResolvedBundle = match ir.bundle.as_ref() {
        Some(b) => b,
        None => return String::from("// ERROR: init.ts called without bundle IR\n"),
    };

    let mut out: String = String::new();
    out.push_str(
        "// THIS FILE IS AUTO-GENERATED BY polyplugc\n\
         // DO NOT EDIT BY HAND\n\
         // Runtime: js-deno\n\n",
    );

    out.push_str("import {\n");
    for (idx, plugin) in bundle.plugins.iter().enumerate() {
        let set_impl_name: String = format!(
            "set{}Impl",
            plugin
                .name
                .replace(['.', '-'], "_")
                .split('_')
                .map(|s| {
                    let mut chars = s.chars();
                    match chars.next() {
                        None => String::new(),
                        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                    }
                })
                .collect::<String>()
        );
        if idx > 0 {
            out.push_str(",\n");
        }
        out.push_str(&format!("    {set_impl_name}"));
    }
    out.push_str("\n} from './contracts';\n\n");

    out.push_str("// Plugin implementation registration\n");
    out.push_str("// Call each set*Impl function with your plugin's function implementations\n");
    out.push_str("// Example:\n");
    for plugin in &bundle.plugins {
        let set_impl_name: String = format!(
            "set{}Impl",
            plugin
                .name
                .replace(['.', '-'], "_")
                .split('_')
                .map(|s| {
                    let mut chars = s.chars();
                    match chars.next() {
                        None => String::new(),
                        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                    }
                })
                .collect::<String>()
        );
        out.push_str(&format!(
            "//   {set_impl_name}(/* your function implementations */);\n"
        ));
    }

    out.push_str("\n// Implement your plugin functions and call set*Impl above to register them\n");
    out
}

#[allow(dead_code)]
fn generate_manifest_toml(ir: &ValidatedIr) -> String {
    let bundle: &ResolvedBundle = match ir.bundle.as_ref() {
        Some(b) => b,
        None => return String::from("# ERROR: bundle manifest called without bundle IR\n"),
    };

    let name: &str = &bundle.name;
    let version: String = format!(
        "{}.{}.{}",
        bundle.version.major, bundle.version.minor, bundle.version.patch
    );

    // Collect provides: all implements from all plugins, deduplicated
    let mut provides: Vec<String> = bundle
        .plugins
        .iter()
        .flat_map(|p: &ResolvedPlugin| p.implements.iter().cloned())
        .map(|impl_str: String| {
            if let Some(at_pos) = impl_str.find('@') {
                let contract_name: &str = &impl_str[..at_pos];
                let version_part: &str = &impl_str[at_pos + 1..];
                if let Some(dot_pos) = version_part.find('.') {
                    let major: &str = &version_part[..dot_pos];
                    format!("{}@{}", contract_name, major)
                } else {
                    impl_str
                }
            } else {
                impl_str
            }
        })
        .collect();
    provides.sort();
    provides.dedup();

    let provides_toml: String = if provides.is_empty() {
        String::from("[]")
    } else {
        format!(
            "[{}]",
            provides
                .iter()
                .map(|s: &String| format!("\"{}\"", s))
                .collect::<Vec<_>>()
                .join(", ")
        )
    };

    let provides_set: std::collections::HashSet<String> = provides.iter().cloned().collect();
    let fn_count_entries: Vec<String> = ir
        .contracts
        .iter()
        .filter(|c: &&ResolvedContract| {
            provides_set.contains(&format!("{}@{}", c.name, c.version.major))
        })
        .map(|c: &ResolvedContract| {
            let fn_count: u32 = c.functions.len() as u32;
            format!("\"{}@{}\" = {}", c.name, c.version.major, fn_count)
        })
        .collect();
    let function_count_toml: String = format!("{{ {} }}", fn_count_entries.join(", "));

    let mut dep_toml: String = String::new();
    for dep in &bundle.dependencies {
        dep_toml.push_str("\n[[dependency]]\n");
        match dep {
            ResolvedDependency::ByContract {
                contract,
                min_version,
                ..
            } => {
                dep_toml.push_str("kind = \"contract\"\n");
                dep_toml.push_str(&format!("contract = \"{}\"\n", contract));
                dep_toml.push_str(&format!("min_version = \"{}.0\"\n", min_version));
            }
            ResolvedDependency::ByBundle {
                bundle,
                contract,
                min_version,
                ..
            } => {
                dep_toml.push_str("kind = \"bundle\"\n");
                dep_toml.push_str(&format!("bundle = \"{}\"\n", bundle));
                dep_toml.push_str(&format!("contract = \"{}\"\n", contract));
                dep_toml.push_str(&format!("min_version = \"{}.0\"\n", min_version));
            }
        }
    }

    let reinit: bool = bundle.needs_reinit_on_dep_reload;
    let file_field: String = super::format_manifest_file_field(&bundle.file);
    let runtime: &str = &bundle.runtime;

    format!(
        "# THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n\
         name = \"{name}\"\n\
         bundle_id = {bundle_id}\n\
         version = \"{version}\"\n\
         runtime = \"{runtime}\"\n\
         provides = {provides_toml}\n\
         function_count = {function_count_toml}\n\
         needs_reinit_on_dep_reload = {reinit}\n\
         {file_field}\n\
         {dep_toml}",
        bundle_id = bundle.bundle_id
    )
}

#[allow(dead_code)]
fn generate_readme_deno(ir: &ValidatedIr) -> String {
    let bundle_name: &str = ir
        .contracts
        .first()
        .map(|c: &ResolvedContract| c.name.as_str())
        .unwrap_or("my-bundle");
    format!(
        "# js-deno Plugin Bundle: {bundle_name}\n\n\
         ## Requirements\n\
         - Deno (https://deno.land)\n\n\
         ## Build\n\
         ```bash\n\
         # TypeScript is loaded natively by deno_core\n\
         # For npm deps, optionally use rolldown\n\
         rolldown index.ts --format esm --file bundle.js\n\
         ```\n"
    )
}

fn generate_callers_ts(ir: &ValidatedIr) -> String {
    let mut out: String = String::new();
    out.push_str(
        "// THIS FILE IS AUTO-GENERATED BY polyplugc\n\
         // DO NOT EDIT BY HAND\n\
         // Runtime: js-deno (host-side callers)\n\n",
    );

    // ABI constants
    out.push_str("// ABI constants\n");
    out.push_str("export const ABI_OK = 0;\n");
    out.push_str("export const ABI_ERROR_GENERIC = 1;\n\n");

    // Contract ID constants
    out.push_str("// Contract ID constants\n");
    out.push_str("export const ContractIds = {\n");
    for contract in &ir.contracts {
        let upper_name: String = contract.name.to_uppercase().replace(['.', '-'], "_");
        out.push_str(&format!(
            "  {}_CONTRACT_ID: 0x{:016X}n,\n",
            upper_name, contract.contract_id
        ));
    }
    out.push_str("} as const;\n\n");

    for contract in &ir.contracts {
        generate_host_caller_class_deno(&mut out, contract);
    }

    out
}

fn generate_host_caller_class_deno(out: &mut String, contract: &ResolvedContract) {
    let class_name: String = contract_to_class_name(&contract.name);
    let contract_upper: String = contract.name.to_uppercase().replace(['.', '-'], "_");
    let contract_id_const: String = format!("ContractIds.{}_CONTRACT_ID", contract_upper);

    out.push_str(&format!(
        "/** Host caller for contract `{}` with hot-reload support. */\n",
        contract.name
    ));
    out.push_str(&format!("export class {}Contract {{\n", class_name));
    out.push_str("    #guard: any;\n\n");
    out.push_str("    private constructor(guard: any) {\n");
    out.push_str("        this.#guard = guard;\n");
    out.push_str("    }\n\n");
    out.push_str("    /** Factory method - creates instance or null if not found. */\n");
    out.push_str(&format!(
        "    static create(rt: any, minVersion: number = 0): {}Contract | null {{\n",
        class_name
    ));
    out.push_str(&format!(
        "        const handle = rt.findByContract({}, minVersion);\n",
        contract_id_const
    ));
    out.push_str("        if (handle === null || handle === undefined) {\n");
    out.push_str("            return null;\n");
    out.push_str("        }\n");
    out.push_str("        const guard = rt.getGuard(handle);\n");
    out.push_str("        if (!guard) {\n");
    out.push_str("            return null;\n");
    out.push_str("        }\n");
    out.push_str(&format!(
        "        return new {}Contract(guard);\n",
        class_name
    ));
    out.push_str("    }\n\n");
    out.push_str("    /** Check if this caller instance is still valid. */\n");
    out.push_str("    isValid(): boolean {\n");
    out.push_str("        return this.#guard !== null && this.#guard !== undefined;\n");
    out.push_str("    }\n\n");
    out.push_str("    /** Explicitly release the guard reference. */\n");
    out.push_str("    reset(): void {\n");
    out.push_str("        this.#guard = null;\n");
    out.push_str("    }\n\n");
    for func in &contract.functions {
        let params: String = func
            .params
            .iter()
            .map(|p: &ResolvedParam| format!("{}: {}", p.name, ts_type_ref(&p.ty)))
            .collect::<Vec<String>>()
            .join(", ");
        let ret_type: String = match &func.returns {
            None => "void".to_owned(),
            Some(ty) => ts_type_ref(ty),
        };

        out.push_str(&format!("    /** Call `{}` */\n", func.name));
        out.push_str(&format!("    {}({}): {} {{\n", func.name, params, ret_type));
        out.push_str("        const vtable = this.#guard?.vtable?.();\n");
        out.push_str("        if (!vtable) throw new Error('caller is not valid');\n");

        if func.params.is_empty() {
            out.push_str("        const argsPtr = 0n;\n");
        } else if func.params.len() == 1 {
            let param = &func.params[0];
            out.push_str(&format!("        const argsPtr = {};\n", param.name));
        } else {
            out.push_str("        const args = {");
            for param in &func.params {
                out.push_str(&format!(" {}: {},", param.name, param.name));
            }
            out.push_str(" };\n");
            out.push_str("        const argsPtr = args;\n");
        }

        out.push_str(&format!(
            "        const fnPtr = vtable.functions[{}];\n",
            func.function_id
        ));
        out.push_str("        if (!fnPtr) throw new Error('function not available');\n");
        out.push_str("        const fn = fnPtr as unknown as (args: any, out: any) => bigint;\n");
        out.push_str("        const outVal = { value: 0n };\n");
        out.push_str("        const err = fn(argsPtr, outVal);\n");
        out.push_str("        if (err !== 0n) throw new Error('call failed');\n");

        if func.returns.is_some() {
            out.push_str("        return outVal.value;\n");
        } else {
            out.push_str("        return;\n");
        }

        out.push_str("    }\n\n");
    }

    out.push_str("}\n\n");
}

fn contract_to_class_name(contract_name: &str) -> String {
    contract_name
        .split('.')
        .map(|part: &str| {
            let mut chars: core::str::Chars<'_> = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect::<Vec<String>>()
        .join("")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::EnumDef;
    use crate::ir::EnumVariant;
    use crate::ir::ReprType;

    #[test]
    fn generate_js_deno_enum_non_bitflag() {
        let e: EnumDef = EnumDef {
            name: "PixelFormat".to_owned(),
            repr: ReprType::U32,
            bitflag: false,
            variants: vec![
                EnumVariant {
                    name: "Unknown".to_owned(),
                    value: "0".to_owned(),
                },
                EnumVariant {
                    name: "Rgba8".to_owned(),
                    value: "1".to_owned(),
                },
            ],
        };
        let mut out: String = String::new();
        generate_js_deno_enum(&mut out, &e);
        assert!(
            out.contains("Object.freeze({"),
            "missing Object.freeze: {out}"
        );
        assert!(out.contains("Unknown: 0"), "missing Unknown: {out}");
        assert!(
            !out.contains("@bitflag"),
            "non-bitflag should not have @bitflag: {out}"
        );
    }

    #[test]
    fn generate_js_deno_enum_bitflag() {
        let e: EnumDef = EnumDef {
            name: "ImageFlags".to_owned(),
            repr: ReprType::U32,
            bitflag: true,
            variants: vec![
                EnumVariant {
                    name: "None".to_owned(),
                    value: "0".to_owned(),
                },
                EnumVariant {
                    name: "Compressed".to_owned(),
                    value: "1".to_owned(),
                },
            ],
        };
        let mut out: String = String::new();
        generate_js_deno_enum(&mut out, &e);
        assert!(out.contains("@bitflag"), "missing @bitflag: {out}");
        assert!(
            out.contains("Object.freeze({"),
            "missing Object.freeze: {out}"
        );
    }
}
