//! polyplug host library — Rust bindings for host-side (app developer) use.
//!
//! This crate provides idiomatic Rust wrappers over the polyplug C ABI,
//! for applications that want to host a polyplug runtime.
//!
//! # Status
//! Scaffold only. Full implementation is code-generated by `polyplugc`.

// Re-export the runtime ABI types for convenience.
pub use polyplug::abi;
pub use polyplug::error;
pub use polyplug::registry;
pub use polyplug::runtime;
