[bundle]
name = "lua_validator"
version = "1.0.0"
api = "../../../api.toml"
runtime = "lua"
file = "validator.lua"

[[plugin]]
name = "validator"
version = "1.0.0"
implements = ["pipeline.Validator@1.0"]
