//! Memory plugin for polyplug Buffer/StringView stress tests.
//!
//! This is a hand-written test plugin (not generated by polyplugc).
//! It implements the "memory.test" contract with 4 functions exercising
//! Buffer allocation, StringView echo, pre-allocated buffer fill, and
//! zero-length roundtrip.

// ─── ABI Types (mirrored from polyplug) ──────────────────────────────
// We cannot depend on polyplug here (cdylib circular dependency).
// Mirror the ABI types inline. These are frozen per §7 ABI Stability.

/// Non-owning UTF-8 string view — mirrors polyplug::abi::StringView.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct StringView {
    pub ptr: *const u8,
    pub len: usize,
}

impl StringView {
    /// Construct the null/empty StringView.
    pub const fn null() -> StringView {
        StringView {
            ptr: core::ptr::null(),
            len: 0,
        }
    }
}

// SAFETY: StringView is a read-only view into externally-owned 'static data.
// Concurrent reads from multiple threads are safe.
unsafe impl Send for StringView {}
// SAFETY: Same reasoning as Send.
unsafe impl Sync for StringView {}

/// ABI error — mirrors polyplug::abi::AbiError.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct AbiError {
    pub code: u32,
    pub message: StringView,
}

impl AbiError {
    /// Construct a success AbiError.
    pub const fn ok() -> AbiError {
        AbiError {
            code: 0,
            message: StringView::null(),
        }
    }
}

// SAFETY: AbiError is a plain-old-data struct with no interior mutability.
unsafe impl Send for AbiError {}
// SAFETY: AbiError is a plain-old-data struct with no interior mutability.
unsafe impl Sync for AbiError {}

/// Byte buffer — mirrors polyplug::abi::Buffer.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct Buffer {
    pub ptr: *mut u8,
    pub len: usize,
    pub cap: usize,
}

// SAFETY: Buffer points to host-allocated memory managed by the host allocator.
// Ownership and aliasing are enforced by the ABI contract.
unsafe impl Send for Buffer {}
// SAFETY: Same reasoning as Send — host manages lifetime.
unsafe impl Sync for Buffer {}

/// Plugin context passed by the loader — mirrors polyplug::abi::PluginContext.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct PluginContext {
    pub bundle_path: StringView,
}

/// Plugin VTable — mirrors polyplug::abi::PluginVTable.
#[repr(C)]
pub struct PluginVTable {
    pub contract_id: u64,
    pub contract_version: u32,
    pub function_count: u32,
    pub functions: *const FnPtr,
}

// SAFETY: PluginVTable points to 'static function arrays. All fields are static pointers.
unsafe impl Send for PluginVTable {}
// SAFETY: PluginVTable points to 'static function arrays. All fields are static pointers.
unsafe impl Sync for PluginVTable {}

/// Plugin descriptor — mirrors polyplug::abi::PluginDescriptor.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct PluginDescriptor {
    pub name: StringView,
    pub contract_name: StringView,
    pub version_major: u32,
    pub version_minor: u32,
    pub version_patch: u32,
}

// SAFETY: PluginDescriptor contains only StringViews and u32 values.
unsafe impl Send for PluginDescriptor {}
// SAFETY: PluginDescriptor contains only StringViews and u32 values.
unsafe impl Sync for PluginDescriptor {}

/// Opaque handle to a loaded plugin — mirrors polyplug::abi::PluginHandle.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PluginHandle {
    pub index: u32,
    pub generation: u32,
}

/// Host VTable — mirrors polyplug::abi::HostVTable.
#[repr(C)]
pub struct HostVTable {
    pub alloc: unsafe extern "C" fn(size: usize, align: usize) -> *mut u8,
    pub free: unsafe extern "C" fn(ptr: *mut u8, size: usize, align: usize),
    pub find_by_contract: unsafe extern "C" fn(contract_id: u64, min_version: u32) -> PluginHandle,
    pub find_by_bundle:
        unsafe extern "C" fn(bundle_id: u64, contract_id: u64, min_version: u32) -> PluginHandle,
    pub find_all_by_contract: unsafe extern "C" fn(
        contract_id: u64,
        min_version: u32,
        out: *mut PluginHandle,
        out_cap: usize,
    ) -> usize,
    pub resolve_plugin: unsafe extern "C" fn(handle: PluginHandle) -> *const PluginVTable,
    pub get_extension: unsafe extern "C" fn(extension_id: u32) -> *const (),
}

/// Plugin registrar — mirrors polyplug::abi::PluginRegistrar.
#[repr(C)]
pub struct PluginRegistrar {
    pub register_plugin: unsafe extern "C" fn(
        registrar: *mut PluginRegistrar,
        descriptor: *const PluginDescriptor,
        vtable: *const PluginVTable,
    ) -> AbiError,
    pub host: *const HostVTable,
}

// ─── Function pointer newtype wrapper ────────────────────────────────────────
// Raw `*const ()` is not `Sync`, but function pointers in a static array are
// effectively 'static and immutable. We wrap them to implement Sync.

/// Wrapper for a function pointer stored in a static vtable array.
/// The pointer is 'static (lifetime of the plugin binary) and read-only.
#[repr(transparent)]
pub struct FnPtr(pub *const ());

// SAFETY: FnPtr wraps a 'static function pointer. Function pointers are safe
// to share across threads — the function itself handles its own synchronization.
unsafe impl Send for FnPtr {}
// SAFETY: Function pointers are inherently Sync — multiple threads may call the
// same function concurrently. The underlying data is read-only 'static memory.
unsafe impl Sync for FnPtr {}

// ─── FNV-1a hash (compile-time constant for "memory.test@1") ─────────────────

const fn fnv1a_64_const(bytes: &[u8]) -> u64 {
    let mut hash: u64 = 0xcbf29ce484222325_u64;
    let mut i: usize = 0;
    while i < bytes.len() {
        hash ^= bytes[i] as u64;
        hash = hash.wrapping_mul(0x00000100000001b3_u64);
        i += 1;
    }
    hash
}

const MEMORY_TEST_CONTRACT_ID: u64 = fnv1a_64_const(b"memory.test@1");

// ─── memory.test contract argument/result types ───────────────────────────────

/// Arguments to `memory_fill_preallocated_buffer` (fn 0).
#[repr(C)]
pub struct FillArgs {
    pub buf: Buffer,
    pub fill_byte: u8,
}

/// Arguments to `memory_alloc_buffer_via_host` (fn 1).
#[repr(C)]
pub struct AllocArgs {
    pub host: *const HostVTable,
    pub size: u64,
    pub fill_byte: u8,
}

/// Arguments to `memory_zero_length_roundtrip` (fn 3).
#[repr(C)]
pub struct ZeroArgs {
    pub buf: Buffer,
    pub sv: StringView,
}

/// Result of `memory_zero_length_roundtrip` (fn 3).
#[repr(C)]
pub struct ZeroResult {
    pub buf_len: u64,
    pub sv_len: u64,
}

// ─── Implementation ───────────────────────────────────────────────────────────

/// fn 0 — fill a pre-allocated buffer with a single byte value.
///
/// Args: `*const FillArgs` (host pre-allocated buffer + fill byte).
/// Out:  `*mut u32` (number of bytes written = buf.cap).
/// Does NOT allocate — host owns the buffer.
///
/// # Safety
/// `args` must point to a valid `FillArgs`. `out` must point to a valid `u32`.
/// The `buf.ptr` in `FillArgs` must be valid for writes of at least `buf.cap` bytes.
extern "C" fn memory_fill_preallocated_buffer(args: *const (), out: *mut ()) -> AbiError {
    // SAFETY: args points to a valid FillArgs per the ABI contract.
    // out points to a valid u32 per the ABI contract.
    let fill_args: &FillArgs = unsafe { &*(args as *const FillArgs) };
    let ptr: *mut u8 = fill_args.buf.ptr;
    let cap: usize = fill_args.buf.cap;
    // SAFETY: ptr is a valid buffer of at least cap bytes owned and allocated by the host.
    // The host guarantees the buffer is writable for the full capacity.
    unsafe {
        let mut i: usize = 0;
        while i < cap {
            ptr.add(i).write(fill_args.fill_byte);
            i += 1;
        }
        let out_u32: *mut u32 = out as *mut u32;
        out_u32.write(cap as u32);
    }
    AbiError::ok()
}

/// fn 1 — allocate a buffer via the host vtable, fill it, and return it.
///
/// Args: `*const AllocArgs` (host vtable ptr, size, fill byte).
/// Out:  `*mut Buffer` (allocated buffer filled with fill_byte).
///
/// # Safety
/// `args` must point to a valid `AllocArgs`. `out` must point to a valid `Buffer`.
/// `alloc_args.host` must be a valid `HostVTable` pointer.
extern "C" fn memory_alloc_buffer_via_host(args: *const (), out: *mut ()) -> AbiError {
    // SAFETY: args points to a valid AllocArgs per the ABI contract.
    let alloc_args: &AllocArgs = unsafe { &*(args as *const AllocArgs) };
    // SAFETY: host is a valid non-null HostVTable pointer provided by the caller per ABI contract.
    let host: &HostVTable = unsafe { &*alloc_args.host };
    let size: usize = alloc_args.size as usize;
    // SAFETY: host.alloc is a valid function pointer set by the host runtime.
    // size and align=1 are valid arguments for the host allocator.
    let ptr: *mut u8 = unsafe { (host.alloc)(size, 1) };
    if ptr.is_null() {
        return AbiError {
            code: 1_u32, // ABI_ERROR_GENERIC
            message: StringView::null(),
        };
    }
    // SAFETY: ptr is a valid allocation of at least `size` bytes returned by the host allocator.
    unsafe {
        let mut i: usize = 0;
        while i < size {
            ptr.add(i).write(alloc_args.fill_byte);
            i += 1;
        }
        let out_buf: *mut Buffer = out as *mut Buffer;
        out_buf.write(Buffer {
            ptr,
            len: size,
            cap: size,
        });
    }
    AbiError::ok()
}

/// fn 2 — echo a StringView back without copying.
///
/// Args: `*const StringView` (input UTF-8 string view).
/// Out:  `*mut StringView` (same ptr/len echoed back).
/// Validates UTF-8 before echoing.
///
/// # Safety
/// `args` must point to a valid `StringView`. `out` must point to a valid `StringView`.
/// `sv.ptr` must be valid for reads of `sv.len` bytes.
extern "C" fn memory_echo_string_view(args: *const (), out: *mut ()) -> AbiError {
    // SAFETY: args points to a valid StringView per the ABI contract.
    let sv: StringView = unsafe { *(args as *const StringView) };
    // SAFETY: sv.ptr is valid for sv.len bytes per the ABI contract.
    // The caller guarantees the StringView points to live, readable memory.
    let bytes: &[u8] = unsafe { core::slice::from_raw_parts(sv.ptr, sv.len) };
    if core::str::from_utf8(bytes).is_err() {
        return AbiError {
            code: 1_u32, // ABI_ERROR_GENERIC — invalid UTF-8
            message: StringView::null(),
        };
    }
    // SAFETY: out points to a valid StringView per the ABI contract.
    unsafe { (out as *mut StringView).write(sv) };
    AbiError::ok()
}

/// fn 3 — zero-length roundtrip: report buf.len and sv.len (both expected to be 0).
///
/// Args: `*const ZeroArgs` (zero-length Buffer + zero-length StringView).
/// Out:  `*mut ZeroResult` (buf_len and sv_len as u64).
///
/// # Safety
/// `args` must point to a valid `ZeroArgs`. `out` must point to a valid `ZeroResult`.
extern "C" fn memory_zero_length_roundtrip(args: *const (), out: *mut ()) -> AbiError {
    // SAFETY: args points to a valid ZeroArgs per the ABI contract.
    // out points to a valid ZeroResult per the ABI contract.
    let zero_args: &ZeroArgs = unsafe { &*(args as *const ZeroArgs) };
    let result: ZeroResult = ZeroResult {
        buf_len: zero_args.buf.len as u64,
        sv_len: zero_args.sv.len as u64,
    };
    // SAFETY: out points to a valid ZeroResult per the ABI contract.
    unsafe { (out as *mut ZeroResult).write(result) };
    AbiError::ok()
}

// ─── Static VTable ────────────────────────────────────────────────────────────

// The function pointer array for the memory.test vtable.
// function_id 0 = memory_fill_preallocated_buffer(args: FillArgs) -> u32
// function_id 1 = memory_alloc_buffer_via_host(args: AllocArgs) -> Buffer
// function_id 2 = memory_echo_string_view(args: StringView) -> StringView
// function_id 3 = memory_zero_length_roundtrip(args: ZeroArgs) -> ZeroResult
static MEMORY_TEST_FNS: [FnPtr; 4] = [
    FnPtr(memory_fill_preallocated_buffer as *const ()),
    FnPtr(memory_alloc_buffer_via_host as *const ()),
    FnPtr(memory_echo_string_view as *const ()),
    FnPtr(memory_zero_length_roundtrip as *const ()),
];

static MEMORY_TEST_VTABLE: PluginVTable = PluginVTable {
    contract_id: MEMORY_TEST_CONTRACT_ID,
    contract_version: 1_u32 << 16, // minor=1, patch=0
    function_count: 4,
    functions: MEMORY_TEST_FNS.as_ptr(),
};

static MEMORY_TEST_DESCRIPTOR: PluginDescriptor = PluginDescriptor {
    name: StringView {
        ptr: b"memory_plugin".as_ptr(),
        len: 13,
    },
    contract_name: StringView {
        ptr: b"memory.test".as_ptr(),
        len: 11,
    },
    version_major: 1,
    version_minor: 0,
    version_patch: 0,
};

// ─── ABI Exports ─────────────────────────────────────────────────────────────

/// ABI version sentinel — loader checks this before calling polyplug_init.
#[unsafe(no_mangle)]
pub extern "C" fn polyplug_abi_version() -> u32 {
    1
}

/// Plugin init — called by the loader to register vtables.
///
/// # Safety
/// `registrar` must be a valid non-null pointer to a PluginRegistrar from the host.
/// `ctx` must be a valid non-null pointer to a PluginContext from the host.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn polyplug_init(
    registrar: *mut PluginRegistrar,
    ctx: *const PluginContext,
) -> AbiError {
    if registrar.is_null() {
        return AbiError {
            code: 1, // ABI_ERROR_GENERIC
            message: StringView::null(),
        };
    }
    if ctx.is_null() {
        return AbiError {
            code: 1,
            message: StringView::null(),
        };
    }

    // SAFETY: registrar is non-null and provided by the host runtime per ABI contract.
    let reg: &mut PluginRegistrar = unsafe { &mut *registrar };

    // SAFETY: register_plugin is a valid function pointer set by the host.
    // MEMORY_TEST_DESCRIPTOR and MEMORY_TEST_VTABLE are 'static.
    unsafe {
        (reg.register_plugin)(
            registrar,
            &MEMORY_TEST_DESCRIPTOR as *const PluginDescriptor,
            &MEMORY_TEST_VTABLE as *const PluginVTable,
        )
    }
}
