//! Memory plugin for polyplug Buffer/StringView stress tests.
//!
//! This is a hand-written test plugin (not generated by polyplugc).
//! It implements the "memory.test" contract with 6 functions exercising
//! Buffer allocation, StringView echo, pre-allocated buffer fill,
//! zero-length roundtrip, and a borrowed-vs-owned return pair used by the
//! marshalling benchmark.

use core::mem::align_of;
use polyplug_abi::AbiErrorCode;
use polyplug_abi::*;
use polyplug_utils::GuestContractId;

// ─── memory.test contract argument/result types ───────────────────────────────

/// Arguments to `memory_fill_preallocated_buffer` (fn 0).
#[repr(C)]
pub struct FillArgs {
    pub buf: Buffer,
    pub fill_byte: u8,
}

/// Arguments to `memory_alloc_buffer_via_host` (fn 1).
#[repr(C)]
pub struct AllocArgs {
    pub host: *const HostApi,
    pub size: u64,
    pub fill_byte: u8,
}

/// Arguments to `memory_zero_length_roundtrip` (fn 3).
#[repr(C)]
pub struct ZeroArgs {
    pub buf: Buffer,
    pub sv: StringView,
}

/// Arguments to `memory_return_owned` (fn 5).
#[repr(C)]
pub struct CopyArgs {
    pub host: *const HostApi,
    pub sv: StringView,
}

/// Result of `memory_zero_length_roundtrip` (fn 3).
#[repr(C)]
pub struct ZeroResult {
    pub buf_len: u64,
    pub sv_len: u64,
}

// ─── Implementation ───────────────────────────────────────────────────────────

/// fn 0 — fill a pre-allocated buffer with a single byte value.
///
/// Args: `*const FillArgs` (host pre-allocated buffer + fill byte).
/// Out:  `*mut u32` (number of bytes written = buf.cap).
/// Does NOT allocate — host owns the buffer.
///
/// # Safety
/// `args` must point to a valid `FillArgs`. `out` must point to a valid `u32`.
/// The `buf.ptr` in `FillArgs` must be valid for writes of at least `buf.cap` bytes.
extern "C" fn memory_fill_preallocated_buffer(
    _instance: GuestContractInstance,
    args: *const (),
    out: *mut (),
    out_err: *mut AbiError,
) {
    let __result_err: AbiError = (|| {
        // SAFETY: args points to a valid FillArgs per the ABI contract.
        // out points to a valid u32 per the ABI contract.
        let fill_args: &FillArgs = unsafe { &*(args as *const FillArgs) };
        let ptr: *mut u8 = fill_args.buf.ptr;
        let len: usize = fill_args.buf.len;
        let cap: usize = fill_args.buf.cap;
        let required_align: usize = align_of::<u64>();
        if cap < len {
            return AbiError {
                code: AbiErrorCode::Generic as u32,
                message: string_view_null(),
            };
        }
        if cap > 0 && ptr.is_null() {
            return AbiError {
                code: AbiErrorCode::Generic as u32,
                message: string_view_null(),
            };
        }
        if cap > 0 && (ptr as usize) % required_align != 0 {
            return AbiError {
                code: AbiErrorCode::Generic as u32,
                message: string_view_null(),
            };
        }
        // SAFETY: ptr is a valid buffer of at least cap bytes owned and allocated by the host.
        // The host guarantees the buffer is writable for the full capacity.
        unsafe {
            let mut i: usize = 0;
            while i < cap {
                ptr.add(i).write(fill_args.fill_byte);
                i += 1;
            }
            let out_u32: *mut u32 = out as *mut u32;
            out_u32.write(cap as u32);
        }
        abi_error_ok()
    })();
    if !out_err.is_null() {
        // SAFETY: out_err is non-null (just checked) and writable per the ABI contract.
        unsafe { out_err.write(__result_err) };
    }
}

/// fn 1 — allocate a buffer via the host abi, fill it, and return it.
///
/// Args: `*const AllocArgs` (host abi ptr, size, fill byte).
/// Out:  `*mut Buffer` (allocated buffer filled with fill_byte).
///
/// # Safety
/// `args` must point to a valid `AllocArgs`. `out` must point to a valid `Buffer`.
/// `alloc_args.host` must be a valid `HostApi` pointer.
extern "C" fn memory_alloc_buffer_via_host(
    _instance: GuestContractInstance,
    args: *const (),
    out: *mut (),
    out_err: *mut AbiError,
) {
    let __result_err: AbiError = (|| {
        // SAFETY: args points to a valid AllocArgs per the ABI contract.
        let alloc_args: &AllocArgs = unsafe { &*(args as *const AllocArgs) };
        // SAFETY: host is a valid non-null HostApi pointer provided by the caller per ABI contract.
        let host: &HostApi = unsafe { &*alloc_args.host };
        let size: usize = alloc_args.size as usize;
        // SAFETY: host.alloc is a valid function pointer set by the host runtime.
        // size and align=1 are valid arguments for the host allocator.
        let ptr: *mut u8 = unsafe { (host.alloc)(alloc_args.host, size, 1) };
        if ptr.is_null() {
            return AbiError {
                code: AbiErrorCode::Generic as u32,
                message: string_view_null(),
            };
        }
        // SAFETY: ptr is a valid allocation of at least `size` bytes returned by the host allocator.
        unsafe {
            let mut i: usize = 0;
            while i < size {
                ptr.add(i).write(alloc_args.fill_byte);
                i += 1;
            }
            let out_buf: *mut Buffer = out as *mut Buffer;
            out_buf.write(Buffer {
                ptr,
                len: size,
                cap: size,
            });
        }
        abi_error_ok()
    })();
    if !out_err.is_null() {
        // SAFETY: out_err is non-null (just checked) and writable per the ABI contract.
        unsafe { out_err.write(__result_err) };
    }
}

/// fn 2 — echo a StringView back without copying.
///
/// Args: `*const StringView` (input UTF-8 string view).
/// Out:  `*mut StringView` (same ptr/len echoed back).
/// Validates UTF-8 before echoing.
///
/// # Safety
/// `args` must point to a valid `StringView`. `out` must point to a valid `StringView`.
/// `sv.ptr` must be valid for reads of `sv.len` bytes.
extern "C" fn memory_echo_string_view(
    _instance: GuestContractInstance,
    args: *const (),
    out: *mut (),
    out_err: *mut AbiError,
) {
    let __result_err: AbiError = (|| {
        // SAFETY: args points to a valid StringView per the ABI contract.
        let sv: StringView = unsafe { *(args as *const StringView) };
        // SAFETY: sv.ptr is valid for sv.len bytes per the ABI contract.
        // The caller guarantees the StringView points to live, readable memory.
        let bytes: &[u8] = unsafe { core::slice::from_raw_parts(sv.ptr, sv.len) };
        if core::str::from_utf8(bytes).is_err() {
            return AbiError {
                code: AbiErrorCode::Generic as u32, // invalid UTF-8
                message: string_view_null(),
            };
        }
        // SAFETY: out points to a valid StringView per the ABI contract.
        unsafe { (out as *mut StringView).write(sv) };
        abi_error_ok()
    })();
    if !out_err.is_null() {
        // SAFETY: out_err is non-null (just checked) and writable per the ABI contract.
        unsafe { out_err.write(__result_err) };
    }
}

/// fn 3 — zero-length roundtrip: report buf.len and sv.len (both expected to be 0).
///
/// Args: `*const ZeroArgs` (zero-length Buffer + zero-length StringView).
/// Out:  `*mut ZeroResult` (buf_len and sv_len as u64).
///
/// # Safety
/// `args` must point to a valid `ZeroArgs`. `out` must point to a valid `ZeroResult`.
extern "C" fn memory_zero_length_roundtrip(
    _instance: GuestContractInstance,
    args: *const (),
    out: *mut (),
    out_err: *mut AbiError,
) {
    let __result_err: AbiError = {
        // SAFETY: args points to a valid ZeroArgs per the ABI contract.
        // out points to a valid ZeroResult per the ABI contract.
        let zero_args: &ZeroArgs = unsafe { &*(args as *const ZeroArgs) };
        let result: ZeroResult = ZeroResult {
            buf_len: zero_args.buf.len as u64,
            sv_len: zero_args.sv.len as u64,
        };
        // SAFETY: out points to a valid ZeroResult per the ABI contract.
        unsafe { (out as *mut ZeroResult).write(result) };
        abi_error_ok()
    };
    if !out_err.is_null() {
        // SAFETY: out_err is non-null (just checked) and writable per the ABI contract.
        unsafe { out_err.write(__result_err) };
    }
}

/// fn 4 — return a **borrowed** StringView of the input (zero-copy).
///
/// Args: `*const StringView` (input view). Out: `*mut StringView` (same ptr/len).
/// Allocates nothing and copies nothing — the returned view borrows the caller's
/// memory. This is the cheap, size-independent return path; pair it with fn 5
/// (`memory_return_owned`) to measure the cost of an owned copy.
///
/// # Safety
/// `args` must point to a valid `StringView`. `out` must point to a valid `StringView`.
extern "C" fn memory_return_borrowed(
    _instance: GuestContractInstance,
    args: *const (),
    out: *mut (),
    out_err: *mut AbiError,
) {
    let __result_err: AbiError = {
        // SAFETY: args points to a valid StringView per the ABI contract.
        let sv: StringView = unsafe { *(args as *const StringView) };
        // SAFETY: out points to a valid StringView per the ABI contract.
        unsafe { (out as *mut StringView).write(sv) };
        abi_error_ok()
    };
    if !out_err.is_null() {
        // SAFETY: out_err is non-null (just checked) and writable per the ABI contract.
        unsafe { out_err.write(__result_err) };
    }
}

/// fn 5 — return an **owned** Buffer copy of the input via the host allocator.
///
/// Args: `*const CopyArgs` (host abi ptr + input view). Out: `*mut Buffer`.
/// Allocates `sv.len` bytes from the host allocator and copies the input into
/// them — the cost scales with payload size, unlike fn 4. The caller owns the
/// returned buffer and must free it through the host allocator.
///
/// # Safety
/// `args` must point to a valid `CopyArgs`. `out` must point to a valid `Buffer`.
/// `copy_args.host` must be a valid `HostApi` pointer and `copy_args.sv` must be
/// valid for reads of `sv.len` bytes.
extern "C" fn memory_return_owned(
    _instance: GuestContractInstance,
    args: *const (),
    out: *mut (),
    out_err: *mut AbiError,
) {
    let __result_err: AbiError = (|| {
        // SAFETY: args points to a valid CopyArgs per the ABI contract.
        let copy_args: &CopyArgs = unsafe { &*(args as *const CopyArgs) };
        // SAFETY: host is a valid non-null HostApi pointer provided by the caller per ABI contract.
        let host: &HostApi = unsafe { &*copy_args.host };
        let len: usize = copy_args.sv.len;
        // SAFETY: host.alloc is a valid function pointer set by the host runtime;
        // len and align=1 are valid arguments for the host allocator.
        let ptr: *mut u8 = unsafe { (host.alloc)(copy_args.host, len, 1) };
        if len > 0 && ptr.is_null() {
            return AbiError {
                code: AbiErrorCode::Generic as u32,
                message: string_view_null(),
            };
        }
        if len > 0 {
            // SAFETY: copy_args.sv.ptr is valid for `len` reads per the ABI contract,
            // and `ptr` is a fresh allocation of at least `len` bytes; the two regions
            // do not overlap (distinct allocations).
            unsafe { core::ptr::copy_nonoverlapping(copy_args.sv.ptr, ptr, len) };
        }
        // SAFETY: out points to a valid Buffer per the ABI contract.
        unsafe {
            (out as *mut Buffer).write(Buffer { ptr, len, cap: len });
        }
        abi_error_ok()
    })();
    if !out_err.is_null() {
        // SAFETY: out_err is non-null (just checked) and writable per the ABI contract.
        unsafe { out_err.write(__result_err) };
    }
}

// ─── Instance lifecycle (stub for test plugin) ────────────────────────────────

/// Stub create_instance for test plugin - returns null instance.
///
/// # Safety
/// Test plugins don't need real instances; dispatch uses global state.
unsafe extern "C" fn create_instance_stub(
    _host: *const HostApi,
    _args: *const (),
    out_instance: *mut GuestContractInstance,
) {
    if !out_instance.is_null() {
        // SAFETY: out_instance is non-null (just checked) and writable per the ABI contract.
        unsafe { out_instance.write(GuestContractInstance::null()) };
    }
}

/// Stub destroy_instance for test plugin - no cleanup needed.
///
/// # Safety
/// Test plugins don't own instance data.
unsafe extern "C" fn destroy_instance_stub(
    _host: *const HostApi,
    _instance: GuestContractInstance,
) {
}

// ─── Static Interface ────────────────────────────────────────────────────────────

/// Wrapper for a function pointer stored in a static interface array.
/// The pointer is 'static (lifetime of the plugin binary) and read-only.
#[repr(transparent)]
pub struct FnPtr(pub *const ());

// SAFETY: FnPtr wraps a 'static function pointer. Function pointers are safe
// to share across threads — the function itself handles its own synchronization.
unsafe impl Send for FnPtr {}
// SAFETY: Function pointers are inherently Sync — multiple threads may call the
// same function concurrently. The underlying data is read-only 'static memory.
unsafe impl Sync for FnPtr {}

// The function pointer array for the memory.test interface.
// function_id 0 = memory_fill_preallocated_buffer(args: FillArgs) -> u32
// function_id 1 = memory_alloc_buffer_via_host(args: AllocArgs) -> Buffer
// function_id 2 = memory_echo_string_view(args: StringView) -> StringView
// function_id 3 = memory_zero_length_roundtrip(args: ZeroArgs) -> ZeroResult
// function_id 4 = memory_return_borrowed(args: StringView) -> StringView (zero-copy)
// function_id 5 = memory_return_owned(args: CopyArgs) -> Buffer (host-alloc copy)
static MEMORY_TEST_FNS: [FnPtr; 6] = [
    FnPtr(memory_fill_preallocated_buffer as *const ()),
    FnPtr(memory_alloc_buffer_via_host as *const ()),
    FnPtr(memory_echo_string_view as *const ()),
    FnPtr(memory_zero_length_roundtrip as *const ()),
    FnPtr(memory_return_borrowed as *const ()),
    FnPtr(memory_return_owned as *const ()),
];

/// Build the memory.test interface with the canonical contract ID computed at
/// runtime via `GuestContractId::new`, keeping it scheme-proof (no baked hash).
fn memory_test_interface() -> GuestContractInterface {
    GuestContractInterface {
        contract_id: GuestContractId::new("memory.test", 1),
        contract_version: Version {
            major: 1,
            minor: 0,
            patch: 0,
        },
        dispatch_type: DispatchType::Native,
        create_instance: create_instance_stub,
        destroy_instance: destroy_instance_stub,
        dispatch: DispatchMechanisms {
            native: NativeDispatch {
                function_count: 6,
                functions: MEMORY_TEST_FNS.as_ptr() as *const *const (),
            },
        },
    }
}

static MEMORY_TEST_DESCRIPTOR: PluginDescriptor = PluginDescriptor {
    name: StringView {
        ptr: b"memory_plugin".as_ptr(),
        len: 13,
    },
    contract_name: StringView {
        ptr: b"memory.test".as_ptr(),
        len: 11,
    },
    version: Version {
        major: 1,
        minor: 0,
        patch: 0,
    },
};

// ─── ABI Exports ─────────────────────────────────────────────────────────────

/// ABI version sentinel — loader checks this before calling polyplug_init.
#[unsafe(no_mangle)]
pub extern "C" fn polyplug_abi_version() -> u32 {
    1
}

/// Plugin init — called by the loader to register interfaces.
///
/// # Safety
/// `host_abi` must be a valid non-null pointer to a HostApi from the host.
/// `ctx` must be a valid non-null pointer to a BundleInitContext from the host.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn polyplug_init(
    host_abi: *const HostApi,
    ctx: *const BundleInitContext,
) -> AbiError {
    if host_abi.is_null() {
        return AbiError {
            code: AbiErrorCode::Generic as u32,
            message: string_view_null(),
        };
    }
    if ctx.is_null() {
        return AbiError {
            code: AbiErrorCode::Generic as u32,
            message: string_view_null(),
        };
    }

    // SAFETY: host_abi is non-null and provided by the host runtime per ABI contract.
    let host: &HostApi = unsafe { &*host_abi };

    // The host copies the interface during this synchronous call, so a local
    // value (carrying the runtime-computed contract ID) is sufficient.
    let interface: GuestContractInterface = memory_test_interface();

    // Out-param ABI: register_guest_contract writes its AbiError through a
    // trailing pointer and returns void; init still surfaces it by value.
    let mut err: AbiError = AbiError {
        code: AbiErrorCode::Ok as u32,
        message: string_view_null(),
    };
    // SAFETY: register_guest_contract is a valid function pointer set by the host.
    // MEMORY_TEST_DESCRIPTOR is 'static; `interface` outlives the synchronous call; &mut err is valid.
    unsafe {
        (host.register_guest_contract)(
            host_abi,
            &MEMORY_TEST_DESCRIPTOR as *const PluginDescriptor,
            &interface as *const GuestContractInterface,
            &mut err as *mut AbiError,
        );
    }
    err
}
