[bundle]
name = "cpp_transformer"
version = "1.0.0"
api = "../../../api.toml"
loader = "native"

[bundle.file]
linux.x86_64 = "libtransformer.so"

[[plugin]]
name = "transformer"
implements = ["data.Transformer@1.0"]

[[dependency]]
kind = "contract"
contract = "pipeline.Validator"
min_version = "1.0"
