[bundle]
name = "python_encoder"
version = "1.0.0"
api = "../../../api.toml"
loader = "python"
file = "encoder.py"

[[plugin]]
name = "encoder"
version = "1.0.0"
implements = ["pipeline.Encoder@1.0"]
