//! csv_decoder — Rust native plugin implementing pipeline.decoder v1.0.
//!
//! This is a hand-written cdylib plugin (not generated by polyplugc).
//! It implements the "pipeline.decoder" contract: decode(input: Buffer) -> DataRecord.

// ─── ABI Types (mirrored from polyplug) ──────────────────────────────────────
// We cannot depend on polyplug here (cdylib circular dependency).
// Mirror the ABI types inline. These are frozen per §7 ABI Stability.

use std::sync::OnceLock;


/// Non-owning UTF-8 string view — mirrors polyplug::abi::StringView.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct StringView {
    pub ptr: *const u8,
    pub len: usize,
}

impl StringView {
    /// Construct the null/empty StringView.
    pub const fn null() -> StringView {
        StringView {
            ptr: core::ptr::null(),
            len: 0,
        }
    }
}

// SAFETY: StringView is a read-only view into externally-owned 'static data.
// Concurrent reads from multiple threads are safe.
unsafe impl Send for StringView {}
// SAFETY: Same reasoning as Send.
unsafe impl Sync for StringView {}

/// ABI error — mirrors polyplug::abi::AbiError.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct AbiError {
    pub code: u32,
    pub message: StringView,
}

impl AbiError {
    /// Construct a success AbiError.
    pub const fn ok() -> AbiError {
        AbiError {
            code: 0,
            message: StringView::null(),
        }
    }
}

// SAFETY: AbiError is a plain-old-data struct with no interior mutability.
unsafe impl Send for AbiError {}
// SAFETY: AbiError is a plain-old-data struct with no interior mutability.
unsafe impl Sync for AbiError {}

/// Plugin VTable — mirrors polyplug::abi::PluginVTable.
#[repr(C)]
pub struct PluginVTable {
    pub contract_id: u64,
    pub contract_version: u32,
    pub function_count: u32,
    pub functions: *const FnPtr,
}

// SAFETY: PluginVTable points to 'static function arrays. All fields are static pointers.
unsafe impl Send for PluginVTable {}
// SAFETY: PluginVTable points to 'static function arrays. All fields are static pointers.
unsafe impl Sync for PluginVTable {}

/// Plugin descriptor — mirrors polyplug::abi::PluginDescriptor.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct PluginDescriptor {
    pub name: StringView,
    pub contract_name: StringView,
    pub version_major: u32,
    pub version_minor: u32,
    pub version_patch: u32,
}

// SAFETY: PluginDescriptor contains only StringViews and u32 values.
unsafe impl Send for PluginDescriptor {}
// SAFETY: PluginDescriptor contains only StringViews and u32 values.
unsafe impl Sync for PluginDescriptor {}

/// Opaque handle to a loaded plugin — mirrors polyplug::abi::PluginHandle.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PluginHandle {
    pub index: u32,
    pub generation: u32,
}

/// Host VTable — mirrors polyplug::abi::HostVTable.
#[repr(C)]
pub struct HostVTable {
    pub alloc: unsafe extern "C" fn(size: usize, align: usize) -> *mut u8,
    pub free: unsafe extern "C" fn(ptr: *mut u8, size: usize, align: usize),
    pub find_by_contract: unsafe extern "C" fn(contract_id: u64, min_version: u32) -> PluginHandle,
    pub find_by_bundle:
        unsafe extern "C" fn(bundle_id: u64, contract_id: u64, min_version: u32) -> PluginHandle,
    pub find_all_by_contract: unsafe extern "C" fn(
        contract_id: u64,
        min_version: u32,
        out: *mut PluginHandle,
        out_cap: usize,
    ) -> usize,
    pub resolve_plugin: unsafe extern "C" fn(handle: PluginHandle) -> *const PluginVTable,
    pub get_extension: unsafe extern "C" fn(extension_id: u32) -> *const (),
}

/// Plugin registrar — mirrors polyplug::abi::PluginRegistrar.
#[repr(C)]
pub struct PluginRegistrar {
    pub register_plugin: unsafe extern "C" fn(
        registrar: *mut PluginRegistrar,
        descriptor: *const PluginDescriptor,
        vtable: *const PluginVTable,
    ) -> AbiError,
    pub host: *const HostVTable,
}

// ─── Function pointer newtype wrapper ────────────────────────────────────────
// Raw `*const ()` is not `Sync`, but function pointers in a static array are
// effectively 'static and immutable. We wrap them to implement Sync.

/// Wrapper for a function pointer stored in a static vtable array.
/// The pointer is 'static (lifetime of the plugin binary) and read-only.
#[repr(transparent)]
pub struct FnPtr(pub *const ());

// SAFETY: FnPtr wraps a 'static function pointer. Function pointers are safe
// to share across threads — the function itself handles its own synchronization.
unsafe impl Send for FnPtr {}
// SAFETY: Function pointers are inherently Sync — multiple threads may call the
// same function concurrently. The underlying data is read-only 'static memory.
unsafe impl Sync for FnPtr {}

// ─── Trace Extension (mirrored layout) ───────────────────────────────────────
// EXT_TRACE_ID = FNV-1a 32-bit hash of b"trace" = 0xC4EB9AEE
// TraceVTable layout from crates/polyplug/src/extensions/trace/mod.rs

/// FNV-1a 32-bit hash of b"trace" — matches EXT_TRACE_ID in host trace extension.
const EXT_TRACE_ID: u32 = 0xC4EB9AEE_u32;

/// C-ABI vtable for the trace extension — mirrors polyplug::extensions::trace::TraceVTable.
#[repr(C)]
pub struct TraceVTable {
    /// Emit a trace message. msg is valid UTF-8 for call duration.
    pub emit: unsafe extern "C" fn(msg: StringView, state: *const ()),
    /// Opaque pointer to the heap-allocated TraceState (same as this vtable's state field).
    pub state: *const (),
}

// SAFETY: TraceVTable fields are a function pointer and a *const () to a leaked allocation.
// Function pointers are thread-safe. The state pointer is immutable after construction.
unsafe impl Send for TraceVTable {}
// SAFETY: Same reasoning — no mutable state, concurrent reads are safe.
unsafe impl Sync for TraceVTable {}

// ─── Contract ID ──────────────────────────────────────────────────────────────
// FNV1a-64 of "pipeline.decoder" at major version 1.
// Computed by: contract_id("pipeline.decoder", 1) = 0x133E62ABD6E7D5BE

const DECODER_CONTRACT_ID: u64 = 0x133E62ABD6E7D5BE;

// ─── pipeline.decoder contract types ─────────────────────────────────────────

/// Raw byte buffer passed in from the host.
#[repr(C)]
pub struct Buffer {
    pub ptr: *const u8,
    pub len: usize,
    pub cap: usize,
}

/// Output record produced by decoding one CSV line.
#[repr(C)]
pub struct DataRecord {
    pub name: StringView,
    pub value: StringView,
    pub count: u32,
}

// ─── Trace callback storage ─────────────────────────────────────────────────

/// Newtype wrapping `*const TraceVTable` so we can store it in a `static OnceLock`.
/// The pointer is a stable leaked allocation from the host runtime.
#[derive(Clone, Copy)]
struct TracePtr(*const TraceVTable);

// SAFETY: TracePtr wraps a pointer to a leaked host allocation that is
// immutable after construction. Reading it from multiple threads is safe.
unsafe impl Send for TracePtr {}
// SAFETY: Same reasoning — no mutable state, concurrent reads are safe.
unsafe impl Sync for TracePtr {}

/// Stores the TraceVTable pointer acquired at init time. None = no trace extension present.
static TRACE_CB: OnceLock<Option<TracePtr>> = OnceLock::new();



/// Emit a trace message if the trace extension is available.
///
/// # Safety
/// This function reads the TRACE_CB OnceLock which stores a potentially-null pointer.
/// The pointer is valid for the lifetime of the runtime (host guarantees this).
unsafe fn emit_trace(msg: &str) {
    if let Some(Some(TracePtr(vtable_ptr))) = TRACE_CB.get() {
        // SAFETY: vtable_ptr was obtained from get_extension(EXT_TRACE_ID) and is
        // guaranteed non-null here. It points to a valid TraceVTable for the lifetime
        // of the host runtime. msg is a valid UTF-8 &str for this call's duration.
        let sv = StringView { ptr: msg.as_ptr(), len: msg.len() };
        unsafe { ((**vtable_ptr).emit)(sv, (**vtable_ptr).state) };
    }
}

// ─── Implementation ───────────────────────────────────────────────────────────

/// The `decode` function: parses a CSV line into a DataRecord.
///
/// Signature matches the generic dispatch: `extern "C" fn(*const (), *mut ()) -> AbiError`.
///
/// # Safety
/// `args` must point to a valid `Buffer`. `out` must point to a valid `DataRecord`.
extern "C" fn plugin_decode(args: *const (), out: *mut ()) -> AbiError {
    // SAFETY: The host runtime guarantees args points to a valid Buffer
    // and out points to a valid DataRecord. Enforced by the ABI contract.
    unsafe { decode_impl(args as *const Buffer, out as *mut DataRecord) }
}

/// Core decode implementation operating on typed pointers.
///
/// # Safety
/// `input` must be a non-null pointer to a valid `Buffer`.
/// `out` must be a non-null pointer to a valid `DataRecord` writable by caller.
unsafe fn decode_impl(input: *const Buffer, out: *mut DataRecord) -> AbiError {
    // SAFETY: input is non-null and valid per ABI contract from plugin_decode.
    let buf: &Buffer = unsafe { &*input };

    // SAFETY: buf.ptr points to valid UTF-8 bytes for buf.len bytes — guaranteed by host.
    let bytes: &[u8] = unsafe { core::slice::from_raw_parts(buf.ptr, buf.len) };

    let csv_str: &str = match core::str::from_utf8(bytes) {
        Ok(s) => s,
        Err(_) => {
            return AbiError {
                code: 1,
                message: StringView {
                    ptr: b"invalid UTF-8".as_ptr(),
                    len: 13,
                },
            };
        }
    };

    // Split on first line to handle trailing newline gracefully.
    let line: &str = csv_str.trim_end_matches('\n').trim_end_matches('\r');

    // Split on comma — expect exactly [name, value, count].
    let mut fields: core::str::SplitN<char> = line.splitn(3, ',');

    let name_str: &str = match fields.next() {
        Some(f) => f,
        None => {
            return AbiError {
                code: 1,
                message: StringView {
                    ptr: b"malformed CSV".as_ptr(),
                    len: 13,
                },
            };
        }
    };

    let value_str: &str = match fields.next() {
        Some(f) => f,
        None => {
            return AbiError {
                code: 1,
                message: StringView {
                    ptr: b"malformed CSV".as_ptr(),
                    len: 13,
                },
            };
        }
    };

    let count_str: &str = match fields.next() {
        Some(f) => f,
        None => {
            return AbiError {
                code: 1,
                message: StringView {
                    ptr: b"malformed CSV".as_ptr(),
                    len: 13,
                },
            };
        }
    };

    let count: u32 = match count_str.trim().parse::<u32>() {
        Ok(n) => n,
        Err(_) => {
            return AbiError {
                code: 1,
                message: StringView {
                    ptr: b"invalid count".as_ptr(),
                    len: 13,
                },
            };
        }
    };

    // Leak the CSV field strings into 'static memory.
    // This is acceptable in the examples context — the host is expected to
    // manage the lifetime of output DataRecord fields externally.
    let name_bytes: Vec<u8> = name_str.as_bytes().to_vec();
    let name_leaked: &'static [u8] = Box::leak(name_bytes.into_boxed_slice());

    let value_bytes: Vec<u8> = value_str.as_bytes().to_vec();
    let value_leaked: &'static [u8] = Box::leak(value_bytes.into_boxed_slice());

    let record = DataRecord {
        name: StringView {
            ptr: name_leaked.as_ptr(),
            len: name_leaked.len(),
        },
        value: StringView {
            ptr: value_leaked.as_ptr(),
            len: value_leaked.len(),
        },
        count,
    };

    // SAFETY: out is non-null and points to a valid DataRecord per ABI contract.
    unsafe {
        core::ptr::write(out, record);
    }

    // Emit trace if the extension is available.
    // SAFETY: emit_trace reads a stable OnceLock — no unsoundness.
    unsafe { emit_trace("[csv_decoder] decode called") };

    AbiError::ok()
}

// ─── Static VTable ────────────────────────────────────────────────────────────

// The function pointer array for the pipeline.decoder vtable.
// function_id 0 = decode(args: Buffer) -> DataRecord
static CSV_DECODER_FNS: [FnPtr; 1] = [FnPtr(plugin_decode as *const ())];

static CSV_DECODER_VTABLE: PluginVTable = PluginVTable {
    contract_id: DECODER_CONTRACT_ID,
    contract_version: 0u32, // v1.0: minor=0, patch=0
    function_count: 1,
    functions: CSV_DECODER_FNS.as_ptr(),
};

static CSV_DECODER_DESCRIPTOR: PluginDescriptor = PluginDescriptor {
    name: StringView {
        ptr: b"csv_decoder".as_ptr(),
        len: 11,
    },
    contract_name: StringView {
        ptr: b"pipeline.decoder".as_ptr(),
        len: 16,
    },
    version_major: 1,
    version_minor: 0,
    version_patch: 0,
};

// ─── ABI Exports ─────────────────────────────────────────────────────────────

/// ABI version sentinel — loader checks this before calling polyplug_init.
#[no_mangle]
pub extern "C" fn polyplug_abi_version() -> u32 {
    1
}

/// Plugin init — called by the loader to register vtables.
///
/// # Safety
/// `registrar` must be a valid non-null pointer to a PluginRegistrar from the host.
#[no_mangle]
pub unsafe extern "C" fn polyplug_init(registrar: *mut PluginRegistrar) -> AbiError {
    if registrar.is_null() {
        return AbiError {
            code: 1, // ABI_ERROR_GENERIC
            message: StringView::null(),
        };
    }

    // Acquire trace extension from host (nullable — missing trace ext is not an error).
    // SAFETY: registrar is non-null, so host field is valid per ABI contract.
    let host: *const HostVTable = unsafe { (*registrar).host };
    if !host.is_null() {
        // SAFETY: host is non-null and valid per ABI contract.
        let ext_ptr: *const () = unsafe { ((*host).get_extension)(EXT_TRACE_ID) };
        let trace_vtable: Option<TracePtr> = if ext_ptr.is_null() {
            None
        } else {
            Some(TracePtr(ext_ptr as *const TraceVTable))
        };
        // OnceLock::set fails silently if already initialised — acceptable at plugin load.
        let _: Result<(), _> = TRACE_CB.set(trace_vtable);
    } else {
        let _: Result<(), _> = TRACE_CB.set(None);
    }

    // Emit trace after storing the vtable pointer.
    // SAFETY: emit_trace reads a stable OnceLock — no unsoundness.
    unsafe { emit_trace("[csv_decoder] init") };

    // SAFETY: registrar is non-null and provided by the host runtime per ABI contract.
    let reg: &mut PluginRegistrar = unsafe { &mut *registrar };

    // SAFETY: register_plugin is a valid function pointer set by the host.
    // CSV_DECODER_DESCRIPTOR and CSV_DECODER_VTABLE are 'static.
    unsafe {
        (reg.register_plugin)(
            registrar,
            &CSV_DECODER_DESCRIPTOR as *const PluginDescriptor,
            &CSV_DECODER_VTABLE as *const PluginVTable,
        )
    }
}
