[workspace]

[package]
name = "showcase-host"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "showcase-host"
path = "src/main.rs"

[dependencies]
polyplug = { workspace = true }
polyplug_python = { workspace = true }
polyplug_lua = { workspace = true }
polyplug_js = { workspace = true }
polyplug_dotnet = { workspace = true }
