[workspace]

[package]
name    = "showcase-host"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "showcase-host"
path = "src/main.rs"

[dependencies]
polyplug        = { path = "../../crates/polyplug" }
polyplug_python = { path = "../../crates/polyplug-python" }
polyplug_lua    = { path = "../../crates/polyplug-lua" }
polyplug_js     = { path = "../../crates/polyplug-js" }
polyplug_dotnet = { path = "../../crates/polyplug-dotnet" }
