//! pack — generates scaffold metadata for packaging plugins.
//!
//! Produces language-specific project scaffolding for plugin authors.
//! Calls the appropriate code generator and writes both the generated ABI
//! code and the language-specific build system scaffolding.

use std::fs;
use std::path::Path;
use std::path::PathBuf;

use crate::generators::CodeGenerator;
use crate::generators::GeneratedFiles;
use crate::generators::cpp::CppGenerator;
use crate::generators::csharp::CSharpGenerator;
use crate::generators::js_quickjs::JsQuickjsGenerator;
use crate::generators::lua::LuaGenerator;
use crate::generators::python::PythonGenerator;
use crate::generators::rust::RustGenerator;
use crate::ir::ValidatedIr;
use polyplug_codegen::PolyplugcError;

pub(crate) fn run(ir: &ValidatedIr, out: &Path, lang: &str) -> Result<(), PolyplugcError> {
    let bundle_name: &str = ir
        .bundle
        .as_ref()
        .map(|b| b.name.as_str())
        .unwrap_or("plugin");
    let version: String = ir
        .bundle
        .as_ref()
        .map(|b| {
            format!(
                "{}.{}.{}",
                b.version.major, b.version.minor, b.version.patch
            )
        })
        .unwrap_or_else(|| "0.1.0".to_owned());

    match lang {
        "rust" => pack_rust(ir, out, bundle_name, &version),
        "cpp" => pack_cpp(ir, out, bundle_name, &version),
        "csharp" => pack_csharp(ir, out, bundle_name, &version),
        "python" => pack_python(ir, out, bundle_name, &version),
        "lua" => pack_lua(ir, out, bundle_name, &version),
        "js-quickjs" => pack_js_quickjs(ir, out, bundle_name, &version),
        _ => Err(PolyplugcError::UnsupportedLanguage {
            lang: lang.to_owned(),
        }),
    }
}

fn write_file(dir: &Path, relative_path: &str, content: &str) -> Result<(), PolyplugcError> {
    let full_path: PathBuf = dir.join(relative_path);
    if let Some(parent) = full_path.parent() {
        fs::create_dir_all(parent).map_err(|e: std::io::Error| PolyplugcError::WriteFailed {
            path: full_path.display().to_string(),
            source: e,
        })?;
    }
    fs::write(&full_path, content).map_err(|e: std::io::Error| PolyplugcError::WriteFailed {
        path: full_path.display().to_string(),
        source: e,
    })?;
    Ok(())
}

fn write_generated(out: &Path, generated: &GeneratedFiles) -> Result<(), PolyplugcError> {
    for file in &generated.files {
        let path_str: &str = file
            .path
            .to_str()
            .ok_or_else(|| PolyplugcError::WriteFailed {
                path: file.path.display().to_string(),
                source: std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    "non-UTF-8 path in generated output",
                ),
            })?;
        write_file(out, path_str, &file.content)?;
    }
    Ok(())
}

fn pack_rust(
    ir: &ValidatedIr,
    out: &Path,
    bundle_name: &str,
    version: &str,
) -> Result<(), PolyplugcError> {
    let mut generated: GeneratedFiles = GeneratedFiles::default();
    RustGenerator.generate_guest(ir, &mut generated)?;
    write_generated(out, &generated)?;

    let cargo_toml: String = format!(
        "# Generated by polyplugc pack. DO NOT EDIT BY HAND.\n\
[package]\n\
name = \"{bundle_name}\"\n\
version = \"{version}\"\n\
edition = \"2021\"\n\n\
[lib]\n\
crate-type = [\"cdylib\"]\n\n\
[dependencies]\n\
polyplug_guest = {{ path = \"../../sdks/rust/guest\" }}\n"
    );

    let lib_rs: String = format!(
        "// THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
// Plugin: {bundle_name}\n\
// Add your contract implementations below.\n\
\n\
#[path = \"../guest/mod.rs\"]\n\
mod guest;\n\
\n\
/// Called by polyplug_init to register plugin implementations.\n\
/// Add registration calls here: guest::interfaces::set_XYZ_impl(Box::new(MyImpl))\n\
#[unsafe(no_mangle)]\n\
pub extern \"C\" fn polyplug_user_init() {{}}\n\
\n\
/// ABI version — must match the host runtime.\n\
#[unsafe(no_mangle)]\n\
pub extern \"C\" fn polyplug_abi_version() -> u32 {{\n\
    1\n\
}}\n"
    );

    write_file(out, "Cargo.toml", &cargo_toml)?;
    write_file(out, "src/lib.rs", &lib_rs)?;
    Ok(())
}

fn pack_cpp(
    ir: &ValidatedIr,
    out: &Path,
    bundle_name: &str,
    version: &str,
) -> Result<(), PolyplugcError> {
    let mut generated: GeneratedFiles = GeneratedFiles::default();
    CppGenerator.generate_guest(ir, &mut generated)?;
    write_generated(out, &generated)?;

    let cmake: String = format!(
        "cmake_minimum_required(VERSION 3.20)\n\
project({bundle_name} VERSION {version})\n\n\
add_library({bundle_name} SHARED src/{bundle_name}.cpp)\n\
target_include_directories({bundle_name} PRIVATE\n\
    include\n\
    ../../sdks/cpp/abi\n\
)\n\
set_target_properties({bundle_name} PROPERTIES PREFIX \"lib\")\n"
    );

    let plugin_hpp: String = format!(
        "// THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
// Plugin: {bundle_name}\n\
#pragma once\n\
#include \"../../sdks/cpp/abi/polyplug_abi.h\"\n"
    );

    let plugin_cpp: String = format!(
        "// THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
// Plugin: {bundle_name}\n\
// Add your contract implementations below.\n\
#include \"../include/{bundle_name}.hpp\"\n\
#include \"../guest/init.hpp\"\n"
    );

    write_file(out, "CMakeLists.txt", &cmake)?;
    write_file(out, &format!("include/{bundle_name}.hpp"), &plugin_hpp)?;
    write_file(out, &format!("src/{bundle_name}.cpp"), &plugin_cpp)?;
    Ok(())
}

fn to_pascal_case(name: &str) -> String {
    name.split('-')
        .map(|part: &str| {
            let mut chars: core::str::Chars<'_> = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => {
                    let upper: String = first.to_uppercase().collect();
                    upper + chars.as_str()
                }
            }
        })
        .collect::<Vec<String>>()
        .join("")
}

fn pack_csharp(
    ir: &ValidatedIr,
    out: &Path,
    bundle_name: &str,
    version: &str,
) -> Result<(), PolyplugcError> {
    let mut generated: GeneratedFiles = GeneratedFiles::default();
    CSharpGenerator.generate_guest(ir, &mut generated)?;
    write_generated(out, &generated)?;

    let pascal_name: String = to_pascal_case(bundle_name);
    let csproj_path: String = format!("{pascal_name}.csproj");
    let csproj: String = format!(
        "<!-- Generated by polyplugc pack. DO NOT EDIT BY HAND. -->\n\
<Project Sdk=\"Microsoft.NET.Sdk\">\n\
  <PropertyGroup>\n\
    <TargetFramework>net10.0</TargetFramework>\n\
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>\n\
    <AssemblyName>{pascal_name}</AssemblyName>\n\
    <Version>{version}</Version>\n\
  </PropertyGroup>\n\
  <ItemGroup>\n\
    <Compile Include=\"guest/**/*.cs\" />\n\
  </ItemGroup>\n\
</Project>\n"
    );

    let nuspec_path: String = format!("{pascal_name}.nuspec");
    let nuspec: String = format!(
        "<!-- Generated by polyplugc pack. DO NOT EDIT BY HAND. -->\n\
<?xml version=\"1.0\"?>\n\
<package>\n\
  <metadata>\n\
    <id>{pascal_name}</id>\n\
    <version>{version}</version>\n\
    <description>Plugin: {bundle_name}</description>\n\
  </metadata>\n\
</package>\n"
    );

    let plugin_cs: String = format!(
        "// Generated by polyplugc pack. DO NOT EDIT BY HAND.\n\
// Plugin: {bundle_name}\n\
// Add your contract implementations below.\n\
namespace {pascal_name};\n\
\n\
public class Plugin\n\
{{\n\
}}\n"
    );

    write_file(out, &csproj_path, &csproj)?;
    write_file(out, &nuspec_path, &nuspec)?;
    write_file(out, "Plugin.cs", &plugin_cs)?;
    Ok(())
}

fn pack_python(
    ir: &ValidatedIr,
    out: &Path,
    bundle_name: &str,
    version: &str,
) -> Result<(), PolyplugcError> {
    let mut generated: GeneratedFiles = GeneratedFiles::default();
    PythonGenerator.generate_guest(ir, &mut generated)?;
    write_generated(out, &generated)?;

    let pkg_name: String = bundle_name.replace('-', "_");

    let pyproject: String = format!(
        "# Generated by polyplugc pack. DO NOT EDIT BY HAND.\n\
[build-system]\n\
requires = [\"hatchling\"]\n\
build-backend = \"hatchling.build\"\n\n\
[project]\n\
name = \"{bundle_name}\"\n\
version = \"{version}\"\n\
dependencies = [\"polyplug_guest\"]\n"
    );

    let init_py: String = format!(
        "# Generated by polyplugc pack. DO NOT EDIT BY HAND.\n\
# Plugin: {bundle_name}\n\
from .plugin import Plugin\n\
\n\
__all__ = [\"Plugin\"]\n"
    );

    let plugin_py: String = format!(
        "# Generated by polyplugc pack. DO NOT EDIT BY HAND.\n\
# Plugin: {bundle_name}\n\
# Add your contract implementations below.\n\
\n\
class Plugin:\n\
    pass\n"
    );

    write_file(out, "pyproject.toml", &pyproject)?;
    write_file(out, &format!("{pkg_name}/__init__.py"), &init_py)?;
    write_file(out, &format!("{pkg_name}/plugin.py"), &plugin_py)?;
    Ok(())
}

fn pack_lua(
    ir: &ValidatedIr,
    out: &Path,
    bundle_name: &str,
    version: &str,
) -> Result<(), PolyplugcError> {
    let mut generated: GeneratedFiles = GeneratedFiles::default();
    LuaGenerator.generate_guest(ir, &mut generated)?;
    write_generated(out, &generated)?;

    let init_lua: String = format!(
        "-- THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
-- Plugin: {bundle_name}\n\
-- This is the plugin entry point. Add contract implementations below.\n\
local M = {{}}\n\
local guest = require(\"guest.contracts\")\n\
M.guest = guest\n\
return M\n"
    );

    let rockspec_path: String = format!("{bundle_name}-{version}.rockspec");
    let rockspec: String = format!(
        "package = \"{bundle_name}\"\n\
version = \"{version}\"\n\
source = {{\n\
  url = \"*** fill in source url ***\"\n\
}}\n\
description = {{\n\
  summary = \"Plugin: {bundle_name}\"\n\
}}\n\
dependencies = {{\n\
  \"lua >= 5.1\",\n\
  \"polyplug_guest\"\n\
}}\n\
build = {{\n\
  type = \"builtin\",\n\
  modules = {{\n\
    [\"{bundle_name}\"] = \"init.lua\"\n\
  }}\n\
}}\n"
    );

    write_file(out, "init.lua", &init_lua)?;
    write_file(out, &rockspec_path, &rockspec)?;
    Ok(())
}

fn pack_js_quickjs(
    ir: &ValidatedIr,
    out: &Path,
    bundle_name: &str,
    version: &str,
) -> Result<(), PolyplugcError> {
    let mut generated: GeneratedFiles = GeneratedFiles::default();
    JsQuickjsGenerator.generate_guest(ir, &mut generated)?;
    write_generated(out, &generated)?;

    let package_json: String = format!(
        "{{\n\
  \"name\": \"{bundle_name}\",\n\
  \"version\": \"{version}\",\n\
  \"main\": \"bundle.js\",\n\
  \"dependencies\": {{\n\
    \"polyplug_guest\": \"*\"\n\
  }},\n\
  \"scripts\": {{\n\
    \"build\": \"rolldown index.ts --format esm --file bundle.js\"\n\
  }}\n\
}}\n"
    );

    let index_ts: String = format!(
        "// THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
// Plugin: {bundle_name}\n\
// Add your contract implementations below.\n\
import {{ init }} from \"./guest/index\";\n\
\n\
export {{ init }};\n"
    );

    let gitignore: &str = "node_modules/\nbundle.js\n*.d.ts\n";

    write_file(out, "package.json", &package_json)?;
    write_file(out, "index.ts", &index_ts)?;
    write_file(out, ".gitignore", gitignore)?;
    Ok(())
}
