[package]
name = "integration"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dev-dependencies]
polyplug = { workspace = true }
polyplug_native = { workspace = true }
polyplug_dotnet = { workspace = true }
polyplug_python = { workspace = true }
polyplug_lua = { workspace = true }
polyplug_js = { workspace = true }
polyplug_js_deno = { workspace = true }
tempfile = { workspace = true }
libloading = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true

