//! Reload test plugin V1 — returns 100 from version_check().
//!
//! This is a hand-written test plugin (not generated by polyplugc).
//! It implements the "reload.test@1" contract: version_check() -> u32.

use polyplug_abi::*;

// ─── Plugin-specific constants ────────────────────────────────────────────────

// RELOAD_TEST_CONTRACT_ID = fnv1a_64(b"reload.test@1") = 0xE55B8A5A3DC7C061
const RELOAD_TEST_CONTRACT_ID: u64 = 0xE55B8A5A3DC7C061_u64;

const POLYPLUG_ABI_VERSION: u32 = 1_u32;

// SAFETY: version_check is a C-compatible static function returning a constant.
unsafe extern "C" fn version_check() -> u32 {
    100_u32
}

/// Wrapper for a function pointer stored in a static vtable array.
/// The pointer is 'static (lifetime of the plugin binary) and read-only.
#[repr(transparent)]
pub struct FnPtr(pub *const ());

// SAFETY: FnPtr wraps a 'static function pointer. Function pointers are safe
// to share across threads — the function itself handles its own synchronization.
unsafe impl Send for FnPtr {}
// SAFETY: Function pointers are inherently Sync — multiple threads may call the
// same function concurrently. The underlying data is read-only 'static memory.
unsafe impl Sync for FnPtr {}

static VTABLE_FNS: [FnPtr; 1] = [FnPtr(version_check as *const ())];

static VTABLE: PluginInterface = PluginInterface {
    rt_ctx: core::ptr::null(),
    contract_id: RELOAD_TEST_CONTRACT_ID,
    contract_version: 1_u32 << 16,
    function_count: 1_u32,
    dispatch_type: DispatchType::Native,
    dispatch: PluginDispatch {
        native: NativeDispatch {
            functions: VTABLE_FNS.as_ptr() as *const *const (),
        },
    },
};

static DESCRIPTOR: PluginDescriptor = PluginDescriptor {
    name: StringView {
        ptr: b"reload_plugin_v1".as_ptr(),
        len: 16,
    },
    contract_name: StringView {
        ptr: b"reload.test".as_ptr(),
        len: 11,
    },
    version_major: 1_u32,
    version_minor: 0_u32,
    version_patch: 0_u32,
};

#[unsafe(no_mangle)]
pub extern "C" fn polyplug_abi_version() -> u32 {
    POLYPLUG_ABI_VERSION
}

/// Plugin init — called by the loader to register vtables.
///
/// # Safety
/// `rt_ctx` must be a valid opaque pointer to the host runtime context.
/// `host_vtable` must be a valid non-null pointer to a HostVTable from the host.
/// `ctx` must be a valid non-null pointer to a PluginContext from the host.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn polyplug_init(
    rt_ctx: *mut core::ffi::c_void,
    host_vtable: *const HostVTable,
    ctx: *const PluginContext,
) -> AbiError {
    if host_vtable.is_null() {
        return AbiError {
            code: ABI_ERROR_GENERIC,
            message: StringView::null(),
        };
    }
    if ctx.is_null() {
        return AbiError {
            code: ABI_ERROR_GENERIC,
            message: StringView::null(),
        };
    }
    // SAFETY: host_vtable is a valid non-null pointer from the host runtime, outlives this call.
    let host: &HostVTable = unsafe { &*host_vtable };
    // SAFETY: register_plugin is a valid function pointer set by the host.
    // DESCRIPTOR and VTABLE are 'static.
    unsafe {
        (host.register_plugin)(
            rt_ctx,
            &DESCRIPTOR as *const PluginDescriptor,
            &VTABLE as *const PluginInterface,
        )
    }
}
