[bundle]
name = "csharp_validator"
version = "1.0.0"
api = "../../../api.toml"
runtime = "csharp"
file = "decoder.dll"

[[plugin]]
name = "validator"
version = "1.0.0"
implements = ["pipeline.Validator@1.0"]
