[bundle]
name = "csharp_validator"
version = "1.0.0"
api = "../../../api.toml"
runtime = "csharp"
file = "validator.cs"

[[plugin]]
name = "validator"
version = "1.0.0"
contracts = ["pipeline.Validator@1.0"]
