//! Rust code generator for polyplugc.
//!
//! Generates:
//! - Host-side: type-safe Rust wrappers to call plugins (for app developers)
//! - Guest-side: ABI entry point, allocator hookup, vtable stubs (for plugin developers)

use crate::error::CodegenError;
use crate::generators::CodeGenerator;
use crate::generators::GeneratedFile;
use crate::generators::GeneratedFiles;
use crate::ir::AbiBuiltin;
use crate::ir::PrimitiveType;
use crate::ir::ResolvedBundle;
use crate::ir::ResolvedContract;
use crate::ir::ResolvedDependency;
use crate::ir::ResolvedFunction;
use crate::ir::ResolvedParam;
use crate::ir::ResolvedPlugin;
use crate::ir::ResolvedType;
use crate::ir::ResolvedTypeRef;
use crate::ir::ValidatedIr;

/// The Rust code generator.
pub(crate) struct RustGenerator;

impl CodeGenerator for RustGenerator {
    fn language_name(&self) -> &'static str {
        "rust"
    }

    fn generate_host(
        &self,
        ir: &ValidatedIr,
        files: &mut GeneratedFiles,
    ) -> Result<(), CodegenError> {
        let header: &str = "// THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n\
            // Re-generate with: polyplugc generate --api api.toml --lang rust --out <dir>\n\
            #![allow(unused_imports)]\n\n";

        // ── types.rs ──────────────────────────────────────────────────────────
        let mut types_out: String = String::new();
        types_out.push_str(header);

        // Emit user-defined types from IR
        for ty in &ir.types {
            generate_rust_type(&mut types_out, ty);
        }

        // Emit generated arg-pack structs for multi-primitive-param functions
        for contract in &ir.contracts {
            let struct_name: String = contract_name_to_struct(&contract.name);
            for func in &contract.functions {
                if needs_arg_pack(&func.params) {
                    emit_arg_pack_struct(&mut types_out, &struct_name, func);
                }
            }
        }

        if let Some(ref bundle) = ir.bundle {
            types_out.push_str(&format!(
                "pub const MY_BUNDLE_ID: u64 = {};\n\n",
                bundle.bundle_id
            ));
            for dep in &bundle.dependencies {
                let contract_upper: String = dep_contract_name(dep)
                    .to_uppercase()
                    .replace(['.', '-'], "_");
                types_out.push_str(&format!(
                    "pub const DEP_{contract_upper}: u64 = {};\n",
                    dep_contract_id(dep)
                ));
                types_out.push_str(&format!(
                    "pub const DEP_{contract_upper}_MIN_VERSION: u32 = {};\n",
                    dep_min_version(dep)
                ));
            }
            types_out.push('\n');
        }

        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("host/types.rs"),
            content: types_out,
        });

        // ── host_callers.rs ───────────────────────────────────────────────────
        let mut callers_out: String = String::new();
        callers_out.push_str(header);

        callers_out.push_str("use polyplug_guest::PluginError;\n");
        callers_out.push_str("use polyplug::abi::ABI_OK;\n");
        callers_out.push_str("use polyplug::abi::AbiError;\n");
        callers_out.push_str("use polyplug::abi::PluginVTable;\n");
        callers_out.push_str("use polyplug::abi::ABI_ERROR_GENERIC;\n");
        callers_out.push_str("use polyplug::abi::ABI_ERROR_NOT_FOUND;\n");
        callers_out.push_str("use polyplug::abi::ABI_ERROR_STALE_HANDLE;\n");
        callers_out.push_str("use polyplug::abi::ABI_FUNCTION_NOT_AVAIL;\n");
        callers_out.push_str("use polyplug::abi::PluginHandle;\n");
        callers_out.push_str("use polyplug::runtime::Runtime;\n");
        callers_out.push_str("use super::types::*;\n\n");

        for contract in &ir.contracts {
            generate_host_contract_caller(&mut callers_out, contract)?;
        }

        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("host/host_callers.rs"),
            content: callers_out,
        });

        // ── manifest.toml ─────────────────────────────────────────────────────
        let manifest_content: String = [
            "# THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n",
            "[manifest]\n",
            "schema_version = 1\n",
            "lang = \"rust\"\n",
            "generated_by = \"polyplugc\"\n",
        ]
        .concat();

        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("manifest.toml"),
            content: manifest_content,
        });

        Ok(())
    }

    fn generate_guest(
        &self,
        ir: &ValidatedIr,
        files: &mut GeneratedFiles,
    ) -> Result<(), CodegenError> {
        let header: &str = "// THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n\
            // Re-generate with: polyplugc generate --api api.toml --lang rust --out <dir>\n\
            #![allow(unused_imports)]\n\n";

        // ── types.rs ──────────────────────────────────────────────────────────
        let mut types_out: String = String::new();
        types_out.push_str(header);

        for ty in &ir.types {
            generate_rust_type(&mut types_out, ty);
        }

        for contract in &ir.contracts {
            let struct_name: String = contract_name_to_struct(&contract.name);
            for func in &contract.functions {
                if needs_arg_pack(&func.params) {
                    emit_arg_pack_struct(&mut types_out, &struct_name, func);
                }
            }
        }

        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("guest/types.rs"),
            content: types_out,
        });

        // ── contracts.rs ──────────────────────────────────────────────────────
        let mut contracts_out: String = String::new();
        contracts_out.push_str(header);
        contracts_out.push_str("use polyplug_guest::PluginError;\n");
        contracts_out.push_str("use polyplug_guest::StringView;\n");
        contracts_out.push_str("use super::types::*;\n\n");

        for contract in &ir.contracts {
            generate_guest_contract_trait(&mut contracts_out, contract);
        }

        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("guest/contracts.rs"),
            content: contracts_out,
        });

        // ── vtables.rs ────────────────────────────────────────────────────────
        let mut vtables_out: String = String::new();
        vtables_out.push_str(header);
        generate_guest_vtables_file(&mut vtables_out, ir)?;

        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("guest/vtables.rs"),
            content: vtables_out,
        });

        // ── init.rs ───────────────────────────────────────────────────────────
        let mut init_out: String = String::new();
        init_out.push_str(header);
        generate_guest_init_file(&mut init_out, ir);

        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("guest/init.rs"),
            content: init_out,
        });

        // --api: manifest already emitted by generate_host(); --bundle: emit full discovery manifest
        if ir.bundle.is_some() {
            let manifest_content: String = generate_bundle_manifest(ir);
            files.files.push(GeneratedFile {
                path: std::path::PathBuf::from("manifest.toml"),
                content: manifest_content,
            });
        }
        // When ir.bundle.is_none() (--api mode): NO manifest emitted here.
        // The root manifest.toml was already emitted by generate_host().
        Ok(())
    }
}

/// Generate a full discovery `manifest.toml` for `--bundle` invocations.
/// Called only when `ir.bundle.is_some()`.
fn generate_bundle_manifest(ir: &ValidatedIr) -> String {
    let bundle: &ResolvedBundle = match ir.bundle.as_ref() {
        Some(b) => b,
        None => return String::from("# ERROR: bundle manifest called without bundle IR\n"),
    };

    let name: &str = &bundle.name;
    let version: String = format!(
        "{}.{}.{}",
        bundle.version.major, bundle.version.minor, bundle.version.patch
    );
    let file: String = format!("lib{}.so", bundle.name);

    // Collect provides: all implements from all plugins, deduplicated
    let mut provides: Vec<String> = bundle
        .plugins
        .iter()
        .flat_map(|p: &ResolvedPlugin| p.implements.iter().cloned())
        .collect();
    provides.sort();
    provides.dedup();

    // Build TOML string arrays (keys with @ must be quoted)
    let provides_toml: String = if provides.is_empty() {
        String::from("[]")
    } else {
        format!(
            "[{}]",
            provides
                .iter()
                .map(|s: &String| format!("\"{}\"", s))
                .collect::<Vec<_>>()
                .join(", ")
        )
    };

    // Build function_count inline table: { "name@major" = count }
    let fn_count_entries: Vec<String> = ir
        .contracts
        .iter()
        .map(|c: &ResolvedContract| {
            let fn_count: u32 = c.functions.len() as u32;
            format!("\"{}@{}\" = {}", c.name, c.version.major, fn_count)
        })
        .collect();
    let function_count_toml: String = format!("{{ {} }}", fn_count_entries.join(", "));

    let mut dep_toml: String = String::new();
    for dep in &bundle.dependencies {
        dep_toml.push_str("\n[[dependency]]\n");
        match dep {
            ResolvedDependency::ByContract {
                contract,
                min_version,
                ..
            } => {
                dep_toml.push_str("kind = \"contract\"\n");
                dep_toml.push_str(&format!("contract = \"{contract}\"\n"));
                dep_toml.push_str(&format!("min_version = \"{min_version}.0\"\n"));
            }
            ResolvedDependency::ByBundle {
                bundle,
                contract,
                min_version,
                ..
            } => {
                dep_toml.push_str("kind = \"bundle\"\n");
                dep_toml.push_str(&format!("bundle = \"{bundle}\"\n"));
                dep_toml.push_str(&format!("contract = \"{contract}\"\n"));
                dep_toml.push_str(&format!("min_version = \"{min_version}.0\"\n"));
            }
        }
    }

    format!(
        "# THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n\
         name = \"{name}\"\n\
         version = \"{version}\"\n\
         runtime = \"native\"\n\
         file = \"{file}\"\n\
         provides = {provides_toml}\n\
         function_count = {function_count_toml}\n\
         {dep_toml}"
    )
}

#[allow(dead_code)]
const GUEST_ALLOCATOR_TEMPLATE: &str = r#"
use std::alloc::{GlobalAlloc, Layout};

struct HostAllocator;

// SAFETY: host_alloc and host_free use the system allocator, which is thread-safe.
unsafe impl GlobalAlloc for HostAllocator {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        polyplug_host_alloc(layout.size(), layout.align())
    }
    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        polyplug_host_free(ptr, layout.size(), layout.align())
    }
}

#[global_allocator]
static ALLOCATOR: HostAllocator = HostAllocator;
"#;

// ─── Guest code generation helpers ────────────────────────────────────────────────

/// Generate the guest trait for one contract.
fn generate_guest_contract_trait(out: &mut String, contract: &ResolvedContract) {
    let trait_name: String = contract_name_to_guest_trait(&contract.name);
    out.push_str(&format!(
        "/// Guest trait for contract `{}` (id=0x{:016X})\n",
        contract.name, contract.contract_id
    ));
    out.push_str(&format!("pub trait {trait_name}: Send + Sync {{\n"));
    for func in &contract.functions {
        generate_guest_trait_method(out, func, &contract_name_to_struct(&contract.name));
    }
    out.push_str("}\n\n");
}

/// Emit one trait method line into the contracts.rs trait.
fn generate_guest_trait_method(out: &mut String, func: &ResolvedFunction, contract_struct: &str) {
    let ret_type: String = match &func.returns {
        Some(ty) => rust_type_name(ty),
        None => "()".to_owned(),
    };
    let sig_params: String = build_guest_trait_params(func, contract_struct);
    out.push_str(&format!(
        "    fn {}(&self{}) -> Result<{ret_type}, PluginError>;\n",
        func.name, sig_params
    ));
}

/// Build the trait method parameter list (after `&self`).
fn build_guest_trait_params(func: &ResolvedFunction, contract_struct: &str) -> String {
    if func.params.is_empty() {
        return String::new();
    }
    if func.params.len() == 1 {
        let param: &ResolvedParam = &func.params[0];
        return match &param.ty {
            ResolvedTypeRef::UserDefined(_) => {
                format!(", {}: &{}", param.name, rust_type_name(&param.ty))
            }
            _ => format!(", {}: {}", param.name, rust_type_name(&param.ty)),
        };
    }
    // Multiple primitive params — individual args
    let _ = contract_struct;
    func.params
        .iter()
        .map(|p: &ResolvedParam| format!(", {}: {}", p.name, rust_type_name(&p.ty)))
        .collect::<Vec<_>>()
        .join("")
}

/// Convert contract name to guest trait name, e.g. "test.add" -> "TestAddPlugin".
fn contract_name_to_guest_trait(name: &str) -> String {
    name.split('.')
        .map(|p: &str| {
            let mut chars: core::str::Chars<'_> = p.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join("")
        + "Plugin"
}

/// Convert contract name to UPPER_SNAKE prefix, e.g. "test.add" -> "TEST_ADD".
fn contract_name_to_upper_snake(name: &str) -> String {
    name.replace('.', "_").to_uppercase()
}

/// Generate the full vtables.rs content.
fn generate_guest_vtables_file(out: &mut String, ir: &ValidatedIr) -> Result<(), CodegenError> {
    // Shared imports
    out.push_str("use std::sync::OnceLock;\n");
    out.push_str("use polyplug_guest::AbiError;\n");
    out.push_str("use polyplug_guest::PluginVTable;\n");
    out.push_str("use polyplug_guest::StringView;\n");
    out.push_str("#[allow(unused_imports)]\n");
    out.push_str("use polyplug_guest::{ABI_OK, ABI_ERROR_GENERIC, ABI_ERROR_PANIC};\n");
    out.push_str("use super::types::*;\n");
    for contract in &ir.contracts {
        let trait_name: String = contract_name_to_guest_trait(&contract.name);
        out.push_str(&format!("use super::contracts::{trait_name};\n"));
    }

    // FnPtr newtype — emitted once
    out.push_str("/// Wrapper for a function pointer stored in a static vtable array.\n");
    out.push_str("#[repr(transparent)]\n");
    out.push_str("pub struct FnPtr(pub *const ());\n");
    out.push_str("// SAFETY: FnPtr wraps a 'static function pointer. Function pointers are safe\n");
    out.push_str(
        "// to share across threads — the function itself handles its own synchronization.\n",
    );
    out.push_str("unsafe impl Send for FnPtr {}\n");
    out.push_str(
        "// SAFETY: Function pointers are inherently Sync — multiple threads may call the\n",
    );
    out.push_str(
        "// same function concurrently. The underlying data is read-only 'static memory.\n",
    );
    out.push_str("unsafe impl Sync for FnPtr {}\n\n");

    for contract in &ir.contracts {
        generate_guest_contract_vtable(out, contract)?;
    }

    Ok(())
}

/// Generate all vtable code for one contract.
fn generate_guest_contract_vtable(
    out: &mut String,
    contract: &ResolvedContract,
) -> Result<(), CodegenError> {
    let upper: String = contract_name_to_upper_snake(&contract.name);
    let struct_name: String = contract_name_to_struct(&contract.name);
    let trait_name: String = contract_name_to_guest_trait(&contract.name);
    let lower: String = contract.name.replace('.', "_");
    let fn_count: usize = contract.functions.len();

    // Contract ID constant
    out.push_str(&format!(
        "/// Contract ID constant -- pre-computed FNV-1a of \"{}@{}\".\n",
        contract.name, contract.version.major
    ));
    out.push_str(&format!(
        "pub(crate) const {upper}_CONTRACT_ID: u64 = 0x{:016X};\n\n",
        contract.contract_id
    ));

    // OnceLock for the trait object
    out.push_str(&format!(
        "pub(crate) static {upper}_IMPL: OnceLock<Box<dyn {trait_name}>> = OnceLock::new();\n\n"
    ));

    // ABI wrapper functions
    for func in &contract.functions {
        generate_guest_abi_wrapper(
            out,
            func,
            &lower,
            &upper,
            &struct_name,
            &trait_name,
            contract,
        )?;
    }

    // FnPtr array
    out.push_str(&format!(
        "static {upper}_FNS: [FnPtr; {fn_count}_usize] = [\n"
    ));
    for func in &contract.functions {
        out.push_str(&format!(
            "    FnPtr({lower}_{}_abi as *const ()),\n",
            func.name
        ));
    }
    out.push_str("];\n\n");

    // Static PluginVTable
    let minor: u32 = contract.version.minor;
    let patch: u32 = contract.version.patch;
    out.push_str(&format!(
        "pub(crate) static {upper}_VTABLE: PluginVTable = PluginVTable {{\n"
    ));
    out.push_str(&format!("    contract_id: {upper}_CONTRACT_ID,\n"));
    out.push_str(&format!(
        "    contract_version: {minor}_u32 << 16 | {patch}_u32,\n"
    ));
    out.push_str(&format!("    function_count: {fn_count}_u32,\n"));
    out.push_str(&format!(
        "    functions: {upper}_FNS.as_ptr() as *const *const (),\n"
    ));
    out.push_str("};\n\n");

    Ok(())
}

/// Generate one ABI wrapper function for a contract function.
fn generate_guest_abi_wrapper(
    out: &mut String,
    func: &ResolvedFunction,
    contract_lower: &str,
    contract_upper: &str,
    contract_struct: &str,
    trait_name: &str,
    _contract: &ResolvedContract,
) -> Result<(), CodegenError> {
    let wrapper_name: String = format!("{contract_lower}_{}_abi", func.name);
    let has_return: bool = func.returns.is_some();
    let out_param: &str = if has_return {
        "out: *mut ()"
    } else {
        "_out: *mut ()"
    };

    out.push_str(&format!(
        "/// ABI wrapper for {} (function_id = {}).\n",
        func.name, func.function_id
    ));
    out.push_str(
        "// SAFETY: args and out pointers are validated by the host runtime ABI contract.\n",
    );
    out.push_str(&format!(
        "extern \"C\" fn {wrapper_name}(args: *const (), {out_param}) -> AbiError {{\n"
    ));
    out.push_str("    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {\n");
    out.push_str(&format!(
        "        let impl_ref: &Box<dyn {trait_name}> = match {contract_upper}_IMPL.get() {{\n"
    ));
    out.push_str("            Some(i) => i,\n");
    out.push_str("            None => return AbiError { code: ABI_ERROR_GENERIC, message: StringView::null() },\n");
    out.push_str("        };\n");

    // Build the call expression
    emit_guest_wrapper_call(out, func, contract_struct);

    // Match on result
    if has_return {
        let ret_ty: String = match &func.returns {
            Some(ty) => rust_type_name(ty),
            None => String::new(),
        };
        out.push_str("        match result {\n");
        out.push_str("            Ok(val) => {\n");
        out.push_str(&format!(
            "                // SAFETY: out is a valid *mut {ret_ty} per ABI contract.\n"
        ));
        out.push_str(&format!(
            "                unsafe {{ std::ptr::write(out as *mut {ret_ty}, val); }}\n"
        ));
        out.push_str("                AbiError::ok()\n");
        out.push_str("            }\n");
        out.push_str(
            "            Err(e) => AbiError { code: e.code, message: StringView::null() },\n",
        );
        out.push_str("        }\n");
    } else {
        out.push_str("        match result {\n");
        out.push_str("            Ok(()) => AbiError::ok(),\n");
        out.push_str(
            "            Err(e) => AbiError { code: e.code, message: StringView::null() },\n",
        );
        out.push_str("        }\n");
    }

    out.push_str("    })) {\n");
    out.push_str("        Ok(err) => err,\n");
    out.push_str("        Err(_) => AbiError::panic_caught(),\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    Ok(())
}

/// Emit the trait call inside the ABI wrapper.
fn emit_guest_wrapper_call(out: &mut String, func: &ResolvedFunction, contract_struct: &str) {
    if func.params.is_empty() {
        out.push_str("        // SAFETY: no args for this function.\n");
        out.push_str("        let _ = args;\n");
        out.push_str(&format!("        let result = impl_ref.{}();\n", func.name));
        return;
    }
    if func.params.len() == 1 {
        let param: &ResolvedParam = &func.params[0];
        match &param.ty {
            ResolvedTypeRef::UserDefined(_) => {
                let ty_name: String = rust_type_name(&param.ty);
                out.push_str(&format!(
                    "        // SAFETY: args is a valid *const {ty_name} per ABI contract.\n"
                ));
                out.push_str(&format!(
                    "        let result = impl_ref.{}(unsafe {{ &*(args as *const {ty_name}) }});\n",
                    func.name
                ));
            }
            _ => {
                let ty_name: String = rust_type_name(&param.ty);
                out.push_str(&format!(
                    "        // SAFETY: args is a valid *const {ty_name} per ABI contract.\n"
                ));
                out.push_str(&format!(
                    "        let result = impl_ref.{}(unsafe {{ *(args as *const {ty_name}) }});\n",
                    func.name
                ));
            }
        }
        return;
    }
    // Multiple params — unpack arg-pack struct
    let pack_struct: String = arg_pack_struct_name(contract_struct, &func.name);
    out.push_str(&format!(
        "        // SAFETY: args is a valid *const {pack_struct} per ABI contract.\n"
    ));
    out.push_str(&format!(
        "        let packed: &{pack_struct} = unsafe {{ &*(args as *const {pack_struct}) }};\n"
    ));
    let call_args: String = func
        .params
        .iter()
        .map(|p: &ResolvedParam| format!("packed.{}", p.name))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!(
        "        let result = impl_ref.{}({call_args});\n",
        func.name
    ));
}

/// Generate the init.rs file content.
fn generate_guest_init_file(out: &mut String, ir: &ValidatedIr) {
    let has_trace: bool = ir
        .bundle
        .as_ref()
        .is_some_and(|b: &crate::ir::ResolvedBundle| {
            b.plugins
                .iter()
                .any(|p: &crate::ir::ResolvedPlugin| p.optional.contains(&"trace".to_owned()))
        });
    out.push_str("use polyplug_guest::AbiError;\n");
    out.push_str("use polyplug_guest::ABI_OK;\n");
    out.push_str("use polyplug_guest::ABI_ERROR_GENERIC;\n");
    out.push_str("use polyplug_guest::PluginDescriptor;\n");
    out.push_str("use polyplug_guest::PluginRegistrar;\n");
    out.push_str("use polyplug_guest::PluginVTable;\n");
    out.push_str("use polyplug_guest::StringView;\n");
    for contract in &ir.contracts {
        let upper: String = contract_name_to_upper_snake(&contract.name);
        out.push_str(&format!("use super::vtables::{upper}_CONTRACT_ID;\n"));
        out.push_str(&format!("use super::vtables::{upper}_VTABLE;\n"));
    }
    out.push('\n');

    out.push_str("#[unsafe(no_mangle)]\n");
    out.push_str("pub extern \"C\" fn polyplug_abi_version() -> u32 { 1 }\n\n");

    out.push_str("/// Register all plugin vtables with the host.\n");
    out.push_str("///\n");
    out.push_str("/// # Safety\n");
    out.push_str("/// `registrar` must be a valid non-null pointer to a PluginRegistrar.\n");
    out.push_str("#[unsafe(no_mangle)]\n");
    out.push_str(
        "pub unsafe extern \"C\" fn polyplug_init(registrar: *mut PluginRegistrar) -> AbiError {\n",
    );
    out.push_str("    if registrar.is_null() {\n");
    out.push_str(
        "        return AbiError { code: ABI_ERROR_GENERIC, message: StringView::null() };\n",
    );
    out.push_str("    }\n");
    out.push_str("    // SAFETY: registrar is non-null and valid per ABI contract.\n");
    out.push_str("    let reg: &mut PluginRegistrar = unsafe { &mut *registrar };\n\n");
    if has_trace {
        out.push_str("    // Optional: trace extension\n");
        out.push_str("    const EXT_TRACE_ID: u32 = 0xC4EB9AEE_u32;\n");
        out.push_str("    // SAFETY: reg.host is a valid HostVTable pointer set by the host.\n");
        out.push_str("    let trace_vtable_ptr: *const () = unsafe { ((*reg.host).get_extension)(EXT_TRACE_ID) };\n");
        out.push_str("    if trace_vtable_ptr.is_null() {\n");
        out.push_str("        // Trace extension not available — continue without tracing.\n");
        out.push_str("    }\n\n");
    }

    for contract in &ir.contracts {
        let upper: String = contract_name_to_upper_snake(&contract.name);
        let plugin_name: String = contract.name.replace('.', "_") + "_plugin";
        let plugin_name_len: usize = plugin_name.len();
        let contract_name: &str = &contract.name;
        let contract_name_len: usize = contract_name.len();
        let major: u32 = contract.version.major;
        let minor: u32 = contract.version.minor;
        let patch: u32 = contract.version.patch;

        out.push_str(&format!(
            "    let desc_{upper}: PluginDescriptor = PluginDescriptor {{\n"
        ));
        out.push_str(&format!(
            "        name: StringView {{ ptr: b\"{plugin_name}\".as_ptr(), len: {plugin_name_len}_usize }},\n"
        ));
        out.push_str(&format!(
            "        contract_name: StringView {{ ptr: b\"{contract_name}\".as_ptr(), len: {contract_name_len}_usize }},\n"
        ));
        out.push_str(&format!("        version_major: {major}_u32,\n"));
        out.push_str(&format!("        version_minor: {minor}_u32,\n"));
        out.push_str(&format!("        version_patch: {patch}_u32,\n"));
        out.push_str("    };\n");
        out.push_str("    // SAFETY: desc and vtable are 'static.\n");
        out.push_str(&format!("    let err_{upper}: AbiError = unsafe {{\n"));
        out.push_str(&format!(
            "        (reg.register_plugin)(registrar, &desc_{upper} as *const PluginDescriptor, &{upper}_VTABLE as *const PluginVTable)\n"
        ));
        out.push_str("    };\n");
        out.push_str(&format!("    if err_{upper}.code != ABI_OK {{\n"));
        out.push_str(&format!("        return err_{upper};\n"));
        out.push_str("    }\n\n");
    }

    out.push_str("    AbiError::ok()\n");
    out.push_str("}\n");
}

// ─── Host code generation helpers ────────────────────────────────────────────

/// Returns true when a function's params require an arg-pack struct
/// (i.e. 2+ primitive params, or any mix that isn't a single UserDefined param).
fn needs_arg_pack(params: &[ResolvedParam]) -> bool {
    if params.len() <= 1 {
        return false;
    }
    // Multiple params always need packing.
    true
}

/// Emit a `#[repr(C)]` arg-pack struct for a multi-param function into `types.rs`.
fn emit_arg_pack_struct(out: &mut String, contract_struct: &str, func: &ResolvedFunction) {
    let struct_name: String = arg_pack_struct_name(contract_struct, &func.name);
    out.push_str(&format!(
        "/// Auto-generated arg-pack for `{contract_struct}::{}`\n",
        func.name
    ));
    out.push_str("#[repr(C)]\n");
    out.push_str("#[derive(Debug, Clone, Copy)]\n");
    out.push_str(&format!("pub struct {struct_name} {{\n"));
    for param in &func.params {
        out.push_str(&format!(
            "    pub {}: {},\n",
            param.name,
            rust_type_name(&param.ty)
        ));
    }
    out.push_str("}\n\n");
}

/// Generate the PascalCase arg-pack struct name for a function.
/// e.g. "TestAddContract" + "add_primitive" → "TestAddContractAddPrimitiveArgs"
fn arg_pack_struct_name(contract_struct: &str, fn_name: &str) -> String {
    let fn_pascal: String = fn_name
        .split('_')
        .map(|seg: &str| {
            let mut chars: core::str::Chars<'_> = seg.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join("");
    format!("{contract_struct}{fn_pascal}Args")
}

fn dep_contract_name(dep: &ResolvedDependency) -> &str {
    match dep {
        ResolvedDependency::ByContract { contract, .. } => contract,
        ResolvedDependency::ByBundle { contract, .. } => contract,
    }
}

fn dep_contract_id(dep: &ResolvedDependency) -> u64 {
    match dep {
        ResolvedDependency::ByContract { contract_id, .. } => *contract_id,
        ResolvedDependency::ByBundle { contract_id, .. } => *contract_id,
    }
}

fn dep_min_version(dep: &ResolvedDependency) -> u32 {
    match dep {
        ResolvedDependency::ByContract { min_version, .. } => *min_version,
        ResolvedDependency::ByBundle { min_version, .. } => *min_version,
    }
}

/// Generate the full caller struct + impl for one contract.
fn generate_host_contract_caller(
    out: &mut String,
    contract: &ResolvedContract,
) -> Result<(), CodegenError> {
    let struct_name: String = contract_name_to_struct(&contract.name);

    out.push_str(&format!(
        "/// Host caller for contract `{}` (id=0x{:016X})\n",
        contract.name, contract.contract_id
    ));
    out.push_str(&format!("pub struct {struct_name} {{\n"));
    out.push_str("    handle: PluginHandle,\n");
    out.push_str("    runtime: &'static Runtime,\n");
    out.push_str("}\n\n");

    out.push_str(&format!("impl {struct_name} {{\n"));
    out.push_str(&format!(
        "    pub fn new(handle: PluginHandle, runtime: &'static Runtime) -> {struct_name} {{\n"
    ));
    out.push_str(&format!("        {struct_name} {{ handle, runtime }}\n"));
    out.push_str("    }\n\n");

    for func in &contract.functions {
        generate_host_fn_caller(out, func, contract, &struct_name)?;
    }

    out.push_str("}\n\n");
    Ok(())
}

/// Generate a single caller method for one contract function.
fn generate_host_fn_caller(
    out: &mut String,
    func: &ResolvedFunction,
    _contract: &ResolvedContract,
    contract_struct: &str,
) -> Result<(), CodegenError> {
    let fn_id: u32 = func.function_id;

    // Build parameter list for the Rust signature
    let sig_params: String = build_sig_params(func, contract_struct);

    // Build return type
    let ret_type: String = match &func.returns {
        Some(ty) => rust_type_name(ty),
        None => "()".to_owned(),
    };

    out.push_str(&format!(
        "    /// Call `{}` (function_id={})\n",
        func.name, fn_id
    ));
    out.push_str(&format!(
        "    pub fn {}(&self{}) -> Result<{ret_type}, PluginError> {{\n",
        func.name, sig_params
    ));

    // args setup
    emit_args_setup(out, func, contract_struct);

    // out setup
    emit_out_setup(out, &func.returns);

    // The unsafe call
    let out_arg: &str = if func.returns.is_some() {
        "&mut out_val as *mut {ret_ty} as *mut ()"
    } else {
        "core::ptr::null_mut()"
    };

    let param_ty_comment: String = args_type_comment(func, contract_struct);
    let ret_ty_comment: String = ret_type.clone();

    out.push_str(&format!(
        "        // SAFETY: args_ptr points to a valid {param_ty_comment} and out_ptr to a valid {ret_ty_comment}.\n"
    ));
    out.push_str("        // Enforced by the generated caller contract.\n");
    out.push_str("        let out_ptr: *mut () = ");
    if func.returns.is_some() {
        out.push_str(&format!("&mut out_val as *mut {ret_type} as *mut ();\n"));
    } else {
        out.push_str("core::ptr::null_mut();\n");
    }
    out.push_str("        let vtable_ptr: *const PluginVTable = match self.runtime.resolve_plugin(self.handle) {\n");
    out.push_str("            Ok(ptr) => ptr,\n");
    out.push_str("            Err(err) => {\n");
    out.push_str("                let code: u32 = match err {\n");
    out.push_str("                    polyplug::error::RegistryError::StaleHandle { .. } => ABI_ERROR_STALE_HANDLE,\n");
    out.push_str("                    polyplug::error::RegistryError::PluginNotFound { .. } => ABI_ERROR_NOT_FOUND,\n");
    out.push_str("                    polyplug::error::RegistryError::ContractIdCollision { .. } | polyplug::error::RegistryError::DuplicateProvider { .. } => ABI_ERROR_GENERIC,\n");
    out.push_str("                };\n");
    out.push_str("                return Err(PluginError { code, message: String::new() });\n");
    out.push_str("            }\n");
    out.push_str("        };\n");
    out.push_str("        if vtable_ptr.is_null() {\n");
    out.push_str("            return Err(PluginError { code: ABI_ERROR_NOT_FOUND, message: String::new() });\n");
    out.push_str("        }\n");
    out.push_str("        // SAFETY: vtable_ptr is valid for the duration of the call; args_ptr/out_ptr match the ABI contract.\n");
    out.push_str("        let err: AbiError = unsafe {\n");
    out.push_str("            let vtable: &PluginVTable = &*vtable_ptr;\n");
    out.push_str(&format!(
        "            if {fn_id}_u32 >= vtable.function_count {{\n"
    ));
    out.push_str("                AbiError { code: ABI_FUNCTION_NOT_AVAIL, message: polyplug::abi::StringView::null() }\n");
    out.push_str("            } else {\n");
    out.push_str(&format!(
        "                let fn_ptr: *const () = *vtable.functions.add({fn_id}_usize);\n"
    ));
    out.push_str("                let dispatch_fn: unsafe extern \"C\" fn(*const (), *mut ()) -> AbiError = core::mem::transmute(fn_ptr);\n");
    out.push_str("                dispatch_fn(args_ptr, out_ptr)\n");
    out.push_str("            }\n");
    out.push_str("        };\n");
    out.push_str("        if err.code != ABI_OK {\n");
    out.push_str(
        "            return Err(PluginError { code: err.code, message: String::new() });\n",
    );
    out.push_str("        }\n");

    // Return
    if func.returns.is_some() {
        out.push_str("        Ok(out_val)\n");
    } else {
        out.push_str("        Ok(())\n");
    }

    let _ = out_arg; // suppress unused warning
    out.push_str("    }\n\n");
    Ok(())
}

/// Build the parameter portion of the Rust function signature (after `&self`).
/// Returns a string starting with `, ` if there are params, else empty.
fn build_sig_params(func: &ResolvedFunction, contract_struct: &str) -> String {
    if func.params.is_empty() {
        return String::new();
    }
    if func.params.len() == 1 {
        let param: &ResolvedParam = &func.params[0];
        let ty: &ResolvedTypeRef = &param.ty;
        return match ty {
            ResolvedTypeRef::UserDefined(_) => {
                format!(", {}: &{}", param.name, rust_type_name(ty))
            }
            _ => format!(", {}: {}", param.name, rust_type_name(ty)),
        };
    }
    // Multiple params: individual args (will be packed in body)
    let params_str: String = func
        .params
        .iter()
        .map(|p: &ResolvedParam| format!(", {}: {}", p.name, rust_type_name(&p.ty)))
        .collect::<Vec<_>>()
        .join("");
    let _ = contract_struct; // used elsewhere
    params_str
}

/// Emit the `args_ptr` setup lines into the function body.
fn emit_args_setup(out: &mut String, func: &ResolvedFunction, contract_struct: &str) {
    if func.params.is_empty() {
        out.push_str("        let args_ptr: *const () = core::ptr::null();\n");
        return;
    }
    if func.params.len() == 1 {
        let param: &ResolvedParam = &func.params[0];
        let ty_name: String = rust_type_name(&param.ty);
        match &param.ty {
            ResolvedTypeRef::UserDefined(_) => {
                out.push_str(&format!(
                    "        let args_ptr: *const () = {name} as *const {ty} as *const ();\n",
                    name = param.name,
                    ty = ty_name,
                ));
            }
            _ => {
                out.push_str(&format!(
                    "        let {name}_val: {ty} = {name};\n",
                    name = param.name,
                    ty = ty_name,
                ));
                out.push_str(&format!(
                    "        let args_ptr: *const () = &{name}_val as *const {ty} as *const ();\n",
                    name = param.name,
                    ty = ty_name,
                ));
            }
        }
        return;
    }
    // Multiple params: pack into arg-pack struct
    let pack_struct: String = arg_pack_struct_name(contract_struct, &func.name);
    out.push_str(&format!(
        "        let args_val: {pack_struct} = {pack_struct} {{\n"
    ));
    for param in &func.params {
        out.push_str(&format!("            {}: {},\n", param.name, param.name));
    }
    out.push_str("        };\n");
    out.push_str(&format!(
        "        let args_ptr: *const () = &args_val as *const {pack_struct} as *const ();\n"
    ));
}

/// Emit the `out_val` / `out_ptr` setup (only when there is a return type).
fn emit_out_setup(out: &mut String, returns: &Option<ResolvedTypeRef>) {
    if let Some(ret_ty) = returns {
        let ty_name: String = rust_type_name(ret_ty);
        out.push_str(&format!(
            "        let mut out_val: {ty_name} = unsafe {{ core::mem::zeroed() }};\n"
        ));
    }
}

/// Return a human-readable string describing the args type for SAFETY comments.
fn args_type_comment(func: &ResolvedFunction, contract_struct: &str) -> String {
    if func.params.is_empty() {
        return "()".to_owned();
    }
    if func.params.len() == 1 {
        return rust_type_name(&func.params[0].ty);
    }
    arg_pack_struct_name(contract_struct, &func.name)
}

// ─── Shared helpers ───────────────────────────────────────────────────────────

fn generate_rust_type(out: &mut String, ty: &ResolvedType) {
    out.push_str(&format!("/// User-defined type `{}`\n", ty.name));
    out.push_str("#[repr(C)]\n");
    out.push_str("#[derive(Debug, Clone, Copy)]\n");
    out.push_str(&format!("pub struct {} {{\n", ty.name));
    for field in &ty.fields {
        out.push_str(&format!(
            "    pub {}: {},\n",
            field.name,
            rust_type_name(&field.ty)
        ));
    }
    out.push_str("}\n\n");
}

fn rust_type_name(ty: &ResolvedTypeRef) -> String {
    match ty {
        ResolvedTypeRef::Primitive(p) => p.rust_name().to_owned(),
        ResolvedTypeRef::AbiType(AbiBuiltin::StringView) => "StringView".to_owned(),
        ResolvedTypeRef::AbiType(AbiBuiltin::Buffer) => "Buffer".to_owned(),
        ResolvedTypeRef::AbiType(AbiBuiltin::Ptr) => "*mut ()".to_owned(),
        ResolvedTypeRef::AbiType(AbiBuiltin::Void) => "()".to_owned(),
        ResolvedTypeRef::UserDefined(name) => name.clone(),
    }
}

fn contract_name_to_struct(name: &str) -> String {
    // Convert "image.decode" -> "ImageDecodeContract"
    name.split('.')
        .map(|p: &str| {
            let mut chars: core::str::Chars<'_> = p.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join("")
        + "Contract"
}

// Suppress unused import warning
const _: fn() = || {
    let _: String = rust_type_name(&ResolvedTypeRef::Primitive(PrimitiveType::U8));
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn contract_name_to_struct_conversion() {
        assert_eq!(
            contract_name_to_struct("image.decode"),
            "ImageDecodeContract"
        );
        assert_eq!(contract_name_to_struct("audio"), "AudioContract");
    }

    #[test]
    fn generate_host_empty_ir() {
        let generator: RustGenerator = RustGenerator;
        let ir: ValidatedIr = ValidatedIr {
            types: vec![],
            contracts: vec![],
            bundle: None,
        };
        let mut files: GeneratedFiles = GeneratedFiles::default();
        generator
            .generate_host(&ir, &mut files)
            .expect("generate_host");
        assert_eq!(files.files.len(), 3);
        assert!(files.files[0].content.contains("AUTO-GENERATED"));
        assert!(files.files[1].content.contains("AUTO-GENERATED"));
        assert!(files.files[2].content.contains("AUTO-GENERATED"));
    }

    #[test]
    fn generate_host_produces_three_files() {
        let generator: RustGenerator = RustGenerator;
        let ir: ValidatedIr = ValidatedIr {
            types: vec![],
            contracts: vec![],
            bundle: None,
        };
        let mut files: GeneratedFiles = GeneratedFiles::default();
        generator
            .generate_host(&ir, &mut files)
            .expect("generate_host");
        let names: Vec<String> = files
            .files
            .iter()
            .map(|f: &GeneratedFile| f.path.to_string_lossy().to_string())
            .collect();
        assert!(names.contains(&"host/types.rs".to_owned()));
        assert!(names.contains(&"host/host_callers.rs".to_owned()));
        assert!(names.contains(&"manifest.toml".to_owned()));
    }

    #[test]
    fn arg_pack_struct_name_conversion() {
        assert_eq!(
            arg_pack_struct_name("TestAddContract", "add_primitive"),
            "TestAddContractAddPrimitiveArgs"
        );
        assert_eq!(
            arg_pack_struct_name("TestAddContract", "reset"),
            "TestAddContractResetArgs"
        );
    }
}
