<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Polyplug.Loaders.Dotnet</AssemblyName>
    <RootNamespace>Polyplug.Loaders</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>true</IsPackable>
    <Description>Polyplug .NET loader for loading .NET-based plugins</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Polyplug/Polyplug.csproj" />
  </ItemGroup>
</Project>