//! js_deno generator — produces V8/deno_core-compatible TypeScript guest code.
//!
//! THIS FILE IS PART OF polyplugc.
//! Generates code using BigInt for all u64/pointer values (V8 has native BigInt).

use std::path::PathBuf;

use crate::error::CodegenError;
use crate::generators::CodeGenerator;
use crate::generators::GeneratedFile;
use crate::generators::GeneratedFiles;
use crate::ir::AbiBuiltin;
use crate::ir::PrimitiveType;
use crate::ir::ResolvedBundle;
use crate::ir::ResolvedContract;
use crate::ir::ResolvedDependency;
use crate::ir::ResolvedField;
use crate::ir::ResolvedFunction;
use crate::ir::ResolvedParam;
use crate::ir::ResolvedPlugin;
use crate::ir::ResolvedType;
use crate::ir::ResolvedTypeRef;
use crate::ir::ValidatedIr;

/// Generator for js-deno plugin bundles.
///
/// Produces TypeScript files using BigInt for 64-bit values
/// (V8/deno_core has native BigInt support).
pub(crate) struct JsDenoGenerator;

impl CodeGenerator for JsDenoGenerator {
    fn language_name(&self) -> &'static str {
        "js-deno"
    }

    fn generate_host(
        &self,
        ir: &ValidatedIr,
        files: &mut GeneratedFiles,
    ) -> Result<(), CodegenError> {
        files.files.push(GeneratedFile {
            path: PathBuf::from("host/types.ts"),
            content: generate_types_ts(ir),
            force_regenerate: false,
        });
        files.files.push(GeneratedFile {
            path: PathBuf::from("host/callers.ts"),
            content: generate_callers_ts(ir),
            force_regenerate: false,
        });
        Ok(())
    }

    fn generate_guest(
        &self,
        ir: &ValidatedIr,
        files: &mut GeneratedFiles,
    ) -> Result<(), CodegenError> {
        files.files.push(GeneratedFile {
            path: PathBuf::from("guest/types.ts"),
            content: generate_types_ts(ir),
            force_regenerate: false,
        });
        files.files.push(GeneratedFile {
            path: PathBuf::from("guest/contracts.ts"),
            content: generate_contracts_ts(ir),
            force_regenerate: false,
        });
        files.files.push(GeneratedFile {
            path: PathBuf::from("guest/init.ts"),
            content: generate_init_ts(ir),
            force_regenerate: false,
        });
        if ir.bundle.is_some() {
            files.files.push(GeneratedFile {
                path: PathBuf::from("manifest.toml"),
                content: generate_manifest_toml(ir),
                force_regenerate: true,
            });
        }
        files.files.push(GeneratedFile {
            path: PathBuf::from("README.md"),
            content: generate_readme_deno(ir),
            force_regenerate: false,
        });
        Ok(())
    }
}

/// Map a resolved type reference to its TypeScript representation (Deno/V8 BigInt style).
fn ts_type_ref(ty: &ResolvedTypeRef) -> String {
    match ty {
        ResolvedTypeRef::Primitive(p) => ts_primitive(p).to_owned(),
        ResolvedTypeRef::AbiType(b) => ts_abi_builtin(b).to_owned(),
        ResolvedTypeRef::UserDefined(name) => name.clone(),
    }
}

fn ts_primitive(p: &PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::U8
        | PrimitiveType::U16
        | PrimitiveType::U32
        | PrimitiveType::I8
        | PrimitiveType::I16
        | PrimitiveType::I32
        | PrimitiveType::F32
        | PrimitiveType::F64 => "number",
        PrimitiveType::Bool => "boolean",
        PrimitiveType::U64 | PrimitiveType::I64 => "bigint",
    }
}

fn ts_abi_builtin(b: &AbiBuiltin) -> &'static str {
    match b {
        AbiBuiltin::StringView => "{ ptr: bigint; len: number }",
        AbiBuiltin::Buffer => "{ ptr: bigint; len: number; cap: number }",
        AbiBuiltin::Ptr => "bigint",
        AbiBuiltin::Void => "void",
    }
}

fn generate_types_ts(ir: &ValidatedIr) -> String {
    let mut out: String = String::new();
    out.push_str(
        "// THIS FILE IS AUTO-GENERATED BY polyplugc\n\
         // DO NOT EDIT BY HAND\n\
         // Runtime: js-deno\n\n",
    );
    for type_def in &ir.types {
        render_resolved_type(&mut out, type_def);
    }
    out
}

fn render_resolved_type(out: &mut String, type_def: &ResolvedType) {
    out.push_str(&format!("export interface {} {{\n", type_def.name));
    for field in &type_def.fields {
        render_resolved_field(out, field);
    }
    out.push_str("}\n\n");
}

fn render_resolved_field(out: &mut String, field: &ResolvedField) {
    let ts_t: String = ts_type_ref(&field.ty);
    out.push_str(&format!("    readonly {}: {};\n", field.name, ts_t));
}

fn generate_contracts_ts(ir: &ValidatedIr) -> String {
    let mut out: String = String::new();
    out.push_str(
        "// THIS FILE IS AUTO-GENERATED BY polyplugc\n\
         // DO NOT EDIT BY HAND\n\
         // Runtime: js-deno\n\n",
    );
    out.push_str("import type { } from './types';\n\n");
    for contract in &ir.contracts {
        render_contract_deno(&mut out, contract);
    }
    out
}

fn render_contract_deno(out: &mut String, contract: &ResolvedContract) {
    let class_name: String = contract_to_class_name(&contract.name);
    out.push_str(&format!("export abstract class {} {{\n", class_name));
    for func in &contract.functions {
        render_function_signature_deno(out, func);
    }
    out.push_str("}\n\n");
}

fn render_function_signature_deno(out: &mut String, func: &ResolvedFunction) {
    let params: String = func
        .params
        .iter()
        .map(|p: &ResolvedParam| format!("{}: {}", p.name, ts_type_ref(&p.ty)))
        .collect::<Vec<String>>()
        .join(", ");
    let ret_type: String = match &func.returns {
        None => "void".to_owned(),
        Some(ty) => ts_type_ref(ty),
    };
    out.push_str(&format!(
        "    abstract {}({}): {};\n",
        func.name, params, ret_type
    ));
}

fn generate_init_ts(ir: &ValidatedIr) -> String {
    let has_trace: bool = ir
        .bundle
        .as_ref()
        .is_some_and(|b: &crate::ir::ResolvedBundle| {
            b.plugins
                .iter()
                .any(|p: &crate::ir::ResolvedPlugin| p.optional.contains(&"trace".to_owned()))
        });
    let mut out: String = String::new();
    out.push_str(
        "// THIS FILE IS AUTO-GENERATED BY polyplugc\n\
         // DO NOT EDIT BY HAND\n\
         // Runtime: js-deno\n\n",
    );
    out.push_str("function init(): void {\n");
    out.push_str("    // Dependency resolution via Deno.core.ops.op_find_by_contract(...)\n");
    out.push_str("    // and vtable registration via Deno.core.ops.op_register_vtable(...)\n");
    out.push_str("    // would go here. Replace with generated values from bundle.toml.\n");
    if has_trace {
        out.push_str("    const EXT_TRACE_ID: number = 0xC4EB9AEE;\n");
        out.push_str("    // Optional: trace extension\n");
        out.push_str("    // Deno returns BigInt for pointer-sized values\n");
        out.push_str(
            "    const traceVtablePtr: bigint = Deno.core.ops.op_get_extension(EXT_TRACE_ID);\n",
        );
        out.push_str("    // traceVtablePtr is 0n if extension not available\n");
        out.push_str("    void traceVtablePtr;\n");
    }
    out.push_str("}\n\ninit();\n");
    out
}

fn generate_manifest_toml(ir: &ValidatedIr) -> String {
    let bundle: &ResolvedBundle = match ir.bundle.as_ref() {
        Some(b) => b,
        None => return String::from("# ERROR: bundle manifest called without bundle IR\n"),
    };

    let name: &str = &bundle.name;
    let version: String = format!(
        "{}.{}.{}",
        bundle.version.major, bundle.version.minor, bundle.version.patch
    );

    // Collect provides: all implements from all plugins, deduplicated
    let mut provides: Vec<String> = bundle
        .plugins
        .iter()
        .flat_map(|p: &ResolvedPlugin| p.implements.iter().cloned())
        .collect();
    provides.sort();
    provides.dedup();

    // Build TOML string arrays (keys with @ must be quoted)
    let provides_toml: String = if provides.is_empty() {
        String::from("[]")
    } else {
        format!(
            "[{}]",
            provides
                .iter()
                .map(|s: &String| format!("\"{}\"", s))
                .collect::<Vec<_>>()
                .join(", ")
        )
    };

    // Build function_count inline table: { "name@major" = count }
    let fn_count_entries: Vec<String> = ir
        .contracts
        .iter()
        .map(|c: &ResolvedContract| {
            let fn_count: u32 = c.functions.len() as u32;
            format!("\"{}@{}\" = {}", c.name, c.version.major, fn_count)
        })
        .collect();
    let function_count_toml: String = format!("{{ {} }}", fn_count_entries.join(", "));

    let mut dep_toml: String = String::new();
    for dep in &bundle.dependencies {
        dep_toml.push_str("\n[[dependency]]\n");
        match dep {
            ResolvedDependency::ByContract {
                contract,
                min_version,
                ..
            } => {
                dep_toml.push_str("kind = \"contract\"\n");
                dep_toml.push_str(&format!("contract = \"{}\"\n", contract));
                dep_toml.push_str(&format!("min_version = \"{}.0\"\n", min_version));
            }
            ResolvedDependency::ByBundle {
                bundle,
                contract,
                min_version,
                ..
            } => {
                dep_toml.push_str("kind = \"bundle\"\n");
                dep_toml.push_str(&format!("bundle = \"{}\"\n", bundle));
                dep_toml.push_str(&format!("contract = \"{}\"\n", contract));
                dep_toml.push_str(&format!("min_version = \"{}.0\"\n", min_version));
            }
        }
    }

    let reinit: bool = bundle.needs_reinit_on_dep_reload;

    format!(
        "# THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n\
         name = \"{name}\"\n\
         bundle_name = \"{name}\"\n\
         version = \"{version}\"\n\
         runtime = \"js-deno\"\n\
         file = \"index.ts\"\n\
         provides = {provides_toml}\n\
         function_count = {function_count_toml}\n\
         needs_reinit_on_dep_reload = {reinit}\n\
         {dep_toml}"
    )
}

fn generate_readme_deno(ir: &ValidatedIr) -> String {
    let bundle_name: &str = ir
        .contracts
        .first()
        .map(|c: &ResolvedContract| c.name.as_str())
        .unwrap_or("my-bundle");
    format!(
        "# js-deno Plugin Bundle: {bundle_name}\n\n\
         ## Requirements\n\
         - Deno (https://deno.land)\n\n\
         ## Build\n\
         ```bash\n\
         # TypeScript is loaded natively by deno_core\n\
         # For npm deps, optionally use rolldown\n\
         rolldown index.ts --format esm --file bundle.js\n\
         ```\n"
    )
}

fn generate_callers_ts(ir: &ValidatedIr) -> String {
    let mut out: String = String::new();
    out.push_str(
        "// THIS FILE IS AUTO-GENERATED BY polyplugc\n\
         // DO NOT EDIT BY HAND\n\
         // Runtime: js-deno (host-side callers)\n\n",
    );
    out.push_str("// TODO: implement host caller classes\n");
    // ir reserved for future caller generation
    let _: &ValidatedIr = ir;
    out
}

fn contract_to_class_name(contract_name: &str) -> String {
    contract_name
        .split('.')
        .map(|part: &str| {
            let mut chars: core::str::Chars<'_> = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect::<Vec<String>>()
        .join("")
}
