//! Register-then-fail plugin for polyplug native loader tests.
//!
//! This is a hand-written test plugin (not generated by polyplugc). Its
//! `polyplug_init` registers ONE contract (`regfail.add`) via
//! `register_guest_contract` and THEN returns a non-Ok `AbiError`. It exercises
//! the native loader's failure path where the library has already published a
//! live, resolvable interface before init reports failure — the loader must NOT
//! `dlclose` such a library (its registered statics may be referenced by the
//! retired interface) and must invalidate whatever the failed init registered.

use polyplug_abi::*;
use polyplug_utils::GuestContractId;

// ─── regfail.add contract types ──────────────────────────────────────────────

/// Arguments to the `add` function.
#[repr(C)]
pub struct AddArgs {
    pub a: u32,
    pub b: u32,
}

// ─── Implementation ──────────────────────────────────────────────────────────

/// The `add` function: returns a.wrapping_add(b).
///
/// Uses the frozen native cross-dispatch ABI signature
/// `extern "C" fn(GuestContractInstance, *const (), *mut (), *mut AbiError)` — the
/// exact shape the runtime's native dispatch transmutes each function-table slot
/// to. This fixture's `regfail.add` is never dispatched (init reports failure
/// after registration, so the loader invalidates it), but the signature is kept
/// canonical for ABI consistency with every other native fixture.
///
/// # Safety
/// `args` must point to a valid `AddArgs`; `out` must point to a valid `u32`.
unsafe extern "C" fn plugin_add(
    _instance: GuestContractInstance,
    args: *const (),
    out: *mut (),
    out_err: *mut AbiError,
) {
    let __result_err: AbiError = (|| {
        if args.is_null() || out.is_null() {
            return AbiError {
                code: AbiErrorCode::InvalidPointer as u32,
                message: string_view_null(),
            };
        }
        // SAFETY: the caller guarantees `args` points to a valid `AddArgs` per the
        // contract; non-null checked above.
        let add_args: &AddArgs = unsafe { &*(args as *const AddArgs) };
        let result: u32 = add_args.a.wrapping_add(add_args.b);
        // SAFETY: the caller guarantees `out` points to a valid `u32`; non-null
        // checked above.
        unsafe {
            core::ptr::write(out as *mut u32, result);
        }
        abi_error_ok()
    })();
    if !out_err.is_null() {
        // SAFETY: out_err is non-null (just checked) and writable per the ABI contract.
        unsafe { out_err.write(__result_err) };
    }
}

// ─── Instance lifecycle (stubs) ──────────────────────────────────────────────

/// Stub create_instance — returns a null instance (stateless contract).
///
/// # Safety
/// Stateless contract: dispatch never reads instance data.
unsafe extern "C" fn create_instance_stub(
    _host: *const HostApi,
    _args: *const (),
    out_instance: *mut GuestContractInstance,
) {
    if !out_instance.is_null() {
        // SAFETY: out_instance is non-null (just checked) and writable per the ABI contract.
        unsafe { out_instance.write(GuestContractInstance::null()) };
    }
}

/// Stub destroy_instance — no cleanup needed.
///
/// # Safety
/// Stateless contract: there is no instance data to release.
unsafe extern "C" fn destroy_instance_stub(
    _host: *const HostApi,
    _instance: GuestContractInstance,
) {
}

// ─── Static Interface ────────────────────────────────────────────────────────

/// Wrapper for a function pointer stored in a static interface array.
/// The pointer is 'static (lifetime of the plugin binary) and read-only.
#[repr(transparent)]
pub struct FnPtr(pub *const ());

// SAFETY: FnPtr wraps a 'static function pointer. Function pointers are safe to
// share across threads — the function itself handles its own synchronization.
unsafe impl Send for FnPtr {}
// SAFETY: Function pointers are inherently Sync — multiple threads may call the
// same function concurrently. The underlying data is read-only 'static memory.
unsafe impl Sync for FnPtr {}

// The function pointer array for the regfail.add interface.
// function_id 0 = add(args: AddArgs) -> u32
static REGFAIL_ADD_FNS: [FnPtr; 1] = [FnPtr(plugin_add as *const ())];

/// Build the regfail.add interface with the canonical contract ID computed at
/// runtime via `GuestContractId::new`, keeping it scheme-proof (no baked hash).
fn regfail_add_interface() -> GuestContractInterface {
    GuestContractInterface {
        contract_id: GuestContractId::new("regfail.add", 1),
        contract_version: Version {
            major: 1,
            minor: 0,
            patch: 0,
        },
        dispatch_type: DispatchType::Native,
        create_instance: create_instance_stub,
        destroy_instance: destroy_instance_stub,
        dispatch: DispatchMechanisms {
            native: NativeDispatch {
                function_count: 1,
                functions: REGFAIL_ADD_FNS.as_ptr() as *const *const (),
            },
        },
    }
}

static REGFAIL_ADD_DESCRIPTOR: PluginDescriptor = PluginDescriptor {
    name: StringView {
        ptr: b"regfail_adder".as_ptr(),
        len: 13,
    },
    contract_name: StringView {
        ptr: b"regfail.add".as_ptr(),
        len: 11,
    },
    version: Version {
        major: 1,
        minor: 0,
        patch: 0,
    },
};

// ─── ABI Exports ─────────────────────────────────────────────────────────────

/// ABI version sentinel — loader checks this before calling polyplug_init.
#[unsafe(no_mangle)]
pub extern "C" fn polyplug_abi_version() -> u32 {
    1
}

/// Plugin init — registers the regfail.add contract and THEN returns an error.
///
/// This is the whole point of the fixture: a live interface is published into
/// the host registry before init reports failure.
///
/// # Safety
/// `host_abi` must be a valid non-null pointer to a HostApi from the host.
/// `ctx` must be a valid non-null pointer to a BundleInitContext from the host.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn polyplug_init(
    host_abi: *const HostApi,
    ctx: *const BundleInitContext,
) -> AbiError {
    if host_abi.is_null() {
        return AbiError {
            code: AbiErrorCode::Generic as u32,
            message: string_view_null(),
        };
    }
    if ctx.is_null() {
        return AbiError {
            code: AbiErrorCode::Generic as u32,
            message: string_view_null(),
        };
    }

    // SAFETY: host_abi is non-null and provided by the host runtime per ABI contract.
    let host: &HostApi = unsafe { &*host_abi };

    // The host copies the interface during this synchronous call, so a local
    // value (carrying the runtime-computed contract ID) is sufficient.
    let interface: GuestContractInterface = regfail_add_interface();

    // Out-param ABI: register_guest_contract writes its AbiError through a
    // trailing pointer and returns void; the fixture still inspects it by value.
    let mut register_result: AbiError = AbiError {
        code: AbiErrorCode::Ok as u32,
        message: string_view_null(),
    };
    // SAFETY: register_guest_contract is a valid function pointer set by the host.
    // REGFAIL_ADD_DESCRIPTOR is 'static; `interface` outlives the synchronous call; &mut is valid.
    unsafe {
        (host.register_guest_contract)(
            host_abi,
            &REGFAIL_ADD_DESCRIPTOR as *const PluginDescriptor,
            &interface as *const GuestContractInterface,
            &mut register_result as *mut AbiError,
        );
    }
    if register_result.code != AbiErrorCode::Ok as u32 {
        return register_result;
    }

    // Registration succeeded and the interface is now live in the host registry.
    // Deliberately report failure AFTER publishing — this is the path the native
    // loader must handle without dlclosing the still-referenced library.
    AbiError {
        code: AbiErrorCode::Generic as u32,
        message: string_view_null(),
    }
}
