[bundle]
name = "cpp_reporter"
version = "1.0.0"
api = "../../../api.toml"
runtime = "native"

[bundle.file]
linux.x86_64 = "libreporter.so"

[[plugin]]
name = "reporter"
version = "1.0.0"
contracts = ["data.Reporter@1.0"]
