// Throwing C++ test fixture plugin for polyplug exception-isolation tests.
//
// Hand-written (not generated by polyplugc) to mirror the Rust `test_plugin`
// fixture but with a dispatch function that throws a C++ exception. The
// dispatch wrapper is `noexcept` and catches the exception, returning the
// `Generic` error code — exercising the host's exception-isolation contract
// (the process must survive, see test_exception_isolation_cpp).
//
// The dispatch entry stored in `functions[0]` uses the polyplug native calling
// convention `AbiError(GuestContractInstance, const void* args, void* out)`.
//
// ABI types come from the real C++ ABI SDK header (sdks/cpp/abi/polyplug/abi.hpp)
// so the fixture can never drift from the frozen layouts; build_all.sh passes
// the include path.

#include <cstddef>
#include <cstdint>
#include <stdexcept>

#include <polyplug/abi.hpp>

namespace {

// ─── test.add contract (throwing implementation) ─────────────────────────────

// FNV-1a 64-bit hash, evaluated at compile time, matching polyplug_utils.
constexpr uint64_t fnv1a_64(const char* data) {
    uint64_t hash = 0xcbf29ce484222325ULL;
    while (*data != '\0') {
        hash ^= static_cast<uint64_t>(static_cast<unsigned char>(*data));
        hash *= 0x00000100000001b3ULL;
        ++data;
    }
    return hash;
}

// Canonical guest contract ID for "test.add@1" — must match the Rust
// test_plugin fixture (fnv1a_64("guest_contract:test.add@1") = 0x40244DF59FCBECB6).
constexpr uint64_t kTestAddContractId = fnv1a_64("guest_contract:test.add@1");

// Throws on every call; the C++ runtime stack-unwinds into the noexcept wrapper.
void throwing_impl() {
    throw std::runtime_error("intentional test exception");
}

AbiError cpp_throw_abi(GuestContractInstance, const void* args, void* out) noexcept {
    (void)args;
    (void)out;
    try {
        throwing_impl();
        return AbiError{static_cast<uint32_t>(AbiErrorCode::Ok), StringView{nullptr, 0}};
    } catch (...) {
        return AbiError{static_cast<uint32_t>(AbiErrorCode::Generic), StringView{nullptr, 0}};
    }
}

GuestContractInstance create_instance_stub(const HostApi*, const void*) noexcept {
    return GuestContractInstance{nullptr, 0};
}

void destroy_instance_stub(const HostApi*, GuestContractInstance) noexcept {}

void* const kTestAddFns[] = {
    reinterpret_cast<void*>(&cpp_throw_abi),
};

GuestContractInterface kTestAddInterface = {
    kTestAddContractId,
    Version{1, 0, 0},
    DispatchType::Native,
    create_instance_stub,
    destroy_instance_stub,
    DispatchMechanisms{.native = NativeDispatch{1, kTestAddFns}},
};

const PluginDescriptor kTestAddDescriptor = {
    StringView{reinterpret_cast<const uint8_t*>("test_adder_cpp_throw"), 20},
    StringView{reinterpret_cast<const uint8_t*>("test.add"), 8},
    Version{1, 0, 0},
};

}  // namespace

// ─── ABI exports ──────────────────────────────────────────────────────────────

extern "C" uint32_t polyplug_abi_version() {
    return 1U;
}

extern "C" AbiError polyplug_init(const HostApi* host, const BundleInitContext* ctx) {
    if (host == nullptr || ctx == nullptr) {
        return AbiError{static_cast<uint32_t>(AbiErrorCode::Generic), StringView{nullptr, 0}};
    }
    return host->register_guest_contract(host, &kTestAddDescriptor, &kTestAddInterface);
}
