// Managed assembly-loading bridge for the polyplug .NET loader.
//
// This file is hand-written and editable (it is NOT generated by polyplugc). The native
// loader (crates/polyplug_dotnet) calls these [UnmanagedCallersOnly] entry points via
// hostfxr to load a guest assembly and obtain its PolyplugInit pointer.
//
// Each bundle is loaded into its own *collectible* AssemblyLoadContext, keyed by
// (runtime id, bundle id) — the runtime id is the owning Runtime's HostApi pointer value —
// so two Runtimes loading the same bundle id get fully isolated ALCs (no last-writer-wins
// race), and the host can later request true managed unload (Unload) per runtime. The CLR
// itself still initializes once per process (see the .NET isolation limitation in
// CLAUDE.md); collectible ALCs unload a *bundle's assemblies*, not the CLR.
//
// Collectible-ALC discipline (load-bearing): the bridge must NOT retain a strong managed
// reference (Assembly/Type/MethodInfo/delegate) into a bundle's ALC after returning the
// init function pointer — that would pin the ALC and prevent collection. Only the
// `s_contexts` dictionary roots an ALC; removing the entry (in Unload) drops that root.
// The returned native function pointer is an integer and does not root the ALC.

using System;
using System.Collections.Concurrent;
using System.IO;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Loader;
using System.Text;

namespace Polyplug.Loaders.DotnetByteBridge;

/// <summary>
/// Per-bundle collectible assembly loader invoked by the native .NET loader through hostfxr.
/// </summary>
public static class ByteBridge
{
    /// <summary>
    /// Per-(runtime, bundle) collectible load contexts. The composite key structurally
    /// isolates two Runtimes loading the same bundle id. This dictionary is the ONLY
    /// strong reference that roots a bundle's ALC; <see cref="Unload"/> removes the entry so
    /// the GC can reclaim the ALC once all native frames into it have unwound.
    /// (Loader bookkeeping under the CLR's once-per-process constraint — collectible ALCs
    /// must be rooted somewhere process-reachable; entries are runtime-scoped via the key.)
    /// </summary>
    private static readonly ConcurrentDictionary<(ulong RuntimeId, ulong BundleId), BundleLoadContext> s_contexts = new();

    /// <summary>
    /// Weak references stashed at unload time, keyed by (runtime id, bundle id), so a test
    /// probe (<see cref="IsAlcAlive"/>) can observe whether the ALC was actually collected.
    /// </summary>
    private static readonly ConcurrentDictionary<(ulong RuntimeId, ulong BundleId), WeakReference> s_unloaded = new();

    /// <summary>A collectible ALC for one bundle, with sibling-dependency probing.</summary>
    private sealed class BundleLoadContext : AssemblyLoadContext
    {
        private readonly AssemblyDependencyResolver? _resolver;

        public BundleLoadContext(string? mainAssemblyPath)
            : base(isCollectible: true)
        {
            // A resolver is only available for path-loaded bundles; byte-loaded bundles are
            // documented single-file, so they have no sibling dependencies to probe.
            _resolver = mainAssemblyPath is null
                ? null
                : new AssemblyDependencyResolver(mainAssemblyPath);
        }

        protected override Assembly? Load(AssemblyName assemblyName)
        {
            // Resolve the bundle's OWN private dependencies (sibling DLLs) into this ALC.
            // Return null for everything else (framework assemblies, Polyplug.Abi, etc.) so
            // they bind to the Default ALC — preserving shared/framework type identity.
            if (_resolver is not null)
            {
                string? path = _resolver.ResolveAssemblyToPath(assemblyName);
                if (path is not null)
                {
                    return LoadFromAssemblyPath(path);
                }
            }
            return null;
        }
    }

    private static BundleLoadContext GetOrCreate(ulong runtimeId, ulong bundleId, string? mainAssemblyPath)
        => s_contexts.GetOrAdd((runtimeId, bundleId), static (_, path) => new BundleLoadContext(path), mainAssemblyPath);

    /// <summary>
    /// Pre-load a dependency assembly from raw bytes into the given (runtime, bundle)
    /// collectible ALC so that a subsequently byte-loaded plugin in the same bundle can
    /// resolve its references.
    /// </summary>
    /// <returns>0 on success, non-zero on failure.</returns>
    [UnmanagedCallersOnly(EntryPoint = "PolyplugByteBridgePreloadDependency")]
    public static uint PreloadDependency(ulong runtimeId, ulong bundleId, IntPtr asmPtr, int asmLen)
    {
        try
        {
            if (asmPtr == IntPtr.Zero || asmLen <= 0)
            {
                return 1u;
            }
            byte[] asmBytes = CopyToManaged(asmPtr, asmLen);
            BundleLoadContext alc = GetOrCreate(runtimeId, bundleId, null);
            // LoadFromStream copies the buffer into managed storage; the native side may free
            // its buffer immediately after this call returns.
            alc.LoadFromStream(new MemoryStream(asmBytes, writable: false));
            return 0u;
        }
        catch
        {
            return 2u;
        }
    }

    /// <summary>
    /// Load a plugin assembly from raw bytes into the bundle's collectible ALC and return the
    /// native function pointer of its <c>[UnmanagedCallersOnly]</c> <c>PolyplugInit</c> entry.
    /// </summary>
    /// <returns>The native PolyplugInit function pointer, or <see cref="IntPtr.Zero"/> on failure.</returns>
    [UnmanagedCallersOnly(EntryPoint = "PolyplugByteBridgeLoadAndGetInit")]
    public static IntPtr LoadAndGetInit(ulong runtimeId, ulong bundleId, IntPtr asmPtr, int asmLen, IntPtr typeNamePtr, int typeNameLen)
    {
        try
        {
            if (asmPtr == IntPtr.Zero || asmLen <= 0 || typeNamePtr == IntPtr.Zero || typeNameLen <= 0)
            {
                return IntPtr.Zero;
            }
            byte[] asmBytes = CopyToManaged(asmPtr, asmLen);
            string typeName = ReadUtf8(typeNamePtr, typeNameLen);
            BundleLoadContext alc = GetOrCreate(runtimeId, bundleId, null);
            // LoadFromStream copies the buffer into managed storage; the native side may free
            // its buffer immediately after this call returns.
            Assembly asm = alc.LoadFromStream(new MemoryStream(asmBytes, writable: false));
            return ResolveInit(asm, typeName);
        }
        catch
        {
            return IntPtr.Zero;
        }
    }

    /// <summary>
    /// Load a plugin assembly from an on-disk path into the bundle's collectible ALC (with
    /// sibling-dependency probing) and return its <c>PolyplugInit</c> function pointer.
    /// </summary>
    [UnmanagedCallersOnly(EntryPoint = "PolyplugByteBridgeLoadFromPathAndGetInit")]
    public static IntPtr LoadFromPathAndGetInit(ulong runtimeId, ulong bundleId, IntPtr pathPtr, int pathLen, IntPtr typeNamePtr, int typeNameLen)
    {
        try
        {
            if (pathPtr == IntPtr.Zero || pathLen <= 0 || typeNamePtr == IntPtr.Zero || typeNameLen <= 0)
            {
                return IntPtr.Zero;
            }
            string path = ReadUtf8(pathPtr, pathLen);
            string typeName = ReadUtf8(typeNamePtr, typeNameLen);
            BundleLoadContext alc = GetOrCreate(runtimeId, bundleId, path);
            Assembly asm = alc.LoadFromAssemblyPath(path);
            return ResolveInit(asm, typeName);
        }
        catch
        {
            return IntPtr.Zero;
        }
    }

    /// <summary>
    /// Request true managed unload of a bundle's collectible ALC. Cooperative and async:
    /// removes the rooting entry, stashes a weak reference for reclaim observation, then calls
    /// <see cref="AssemblyLoadContext.Unload"/>. Actual reclamation completes after the next GC
    /// once all references and native frames into the ALC have cleared.
    /// </summary>
    /// <returns>0 on success (idempotent for an unknown id), non-zero on failure.</returns>
    [UnmanagedCallersOnly(EntryPoint = "PolyplugByteBridgeUnload")]
    public static uint Unload(ulong runtimeId, ulong bundleId)
    {
        try
        {
            if (s_contexts.TryRemove((runtimeId, bundleId), out BundleLoadContext? alc) && alc is not null)
            {
                s_unloaded[(runtimeId, bundleId)] = new WeakReference(alc);
                alc.Unload();
            }
            return 0u;
        }
        catch
        {
            return 1u;
        }
    }

    /// <summary>
    /// Test-only probe: forces a GC and reports whether the bundle's ALC is still alive.
    /// Returns 1 while the ALC is rooted (loaded, not yet unloaded), or after unload if it has
    /// not been collected yet; returns 0 once the ALC has been reclaimed (or was never loaded).
    /// </summary>
    [UnmanagedCallersOnly(EntryPoint = "PolyplugByteBridgeIsAlcAlive")]
    public static uint IsAlcAlive(ulong runtimeId, ulong bundleId)
    {
        if (s_contexts.ContainsKey((runtimeId, bundleId)))
        {
            return 1u;
        }
        if (!s_unloaded.TryGetValue((runtimeId, bundleId), out WeakReference? weak) || weak is null)
        {
            return 0u;
        }
        for (int i = 0; i < 10 && weak.IsAlive; i++)
        {
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();
        }
        return weak.IsAlive ? 1u : 0u;
    }

    /// <summary>
    /// Resolve <paramref name="typeName"/>.<c>PolyplugInit</c> from <paramref name="asm"/> and
    /// return its native entry pointer. Retains NO strong reference to the assembly/type/method
    /// after returning, so only <see cref="s_contexts"/> roots the ALC.
    /// </summary>
    private static IntPtr ResolveInit(Assembly asm, string typeName)
    {
        Type? type = asm.GetType(typeName, throwOnError: false, ignoreCase: false);
        if (type is null)
        {
            return IntPtr.Zero;
        }
        MethodInfo? method = type.GetMethod("PolyplugInit", BindingFlags.Public | BindingFlags.Static);
        if (method is null)
        {
            return IntPtr.Zero;
        }
        // The method must be JIT-compiled before its native entry is stable.
        RuntimeHelpers.PrepareMethod(method.MethodHandle);
        return method.MethodHandle.GetFunctionPointer();
    }

    private static byte[] CopyToManaged(IntPtr ptr, int len)
    {
        byte[] buffer = new byte[len];
        Marshal.Copy(ptr, buffer, 0, len);
        return buffer;
    }

    private static unsafe string ReadUtf8(IntPtr ptr, int len)
    {
        return Encoding.UTF8.GetString((byte*)ptr, len);
    }
}
