// Managed byte-array assembly-loading bridge for the polyplug .NET loader.
//
// This file is hand-written and editable (it is NOT generated by polyplugc). The native
// loader (crates/polyplug_dotnet) calls these [UnmanagedCallersOnly] entry points via
// hostfxr to load a guest assembly from raw bytes and obtain its PolyplugInit pointer.
//
// See the .csproj for why a managed bridge is required (stream-loaded assemblies cannot be
// resolved by hostfxr's path-less hdt_get_function_pointer).

using System;
using System.IO;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Loader;
using System.Text;

namespace Polyplug.Loaders.DotnetByteBridge;

/// <summary>
/// Static byte-array assembly loader invoked by the native .NET loader through hostfxr.
/// </summary>
public static class ByteBridge
{
    /// <summary>
    /// Pre-load a dependency assembly from raw bytes into the default
    /// <see cref="AssemblyLoadContext"/> so that a subsequently byte-loaded plugin can
    /// resolve its references.
    ///
    /// BundleSource::Bytes is documented as single-file only, so the production path uses
    /// only <see cref="LoadAndGetInit"/>; this entry exists for hosts (and tests) that
    /// must satisfy a non-self-contained plugin's dependencies in memory.
    /// </summary>
    /// <param name="asmPtr">Pointer to the dependency assembly bytes.</param>
    /// <param name="asmLen">Length of the dependency assembly bytes.</param>
    /// <returns>0 on success, non-zero on failure.</returns>
    [UnmanagedCallersOnly(EntryPoint = "PolyplugByteBridgePreloadDependency")]
    public static uint PreloadDependency(IntPtr asmPtr, int asmLen)
    {
        try
        {
            if (asmPtr == IntPtr.Zero || asmLen <= 0)
            {
                return 1u;
            }
            byte[] asmBytes = CopyToManaged(asmPtr, asmLen);
            // LoadFromStream copies the buffer into managed storage; the native side may
            // free its buffer immediately after this call returns.
            AssemblyLoadContext.Default.LoadFromStream(new MemoryStream(asmBytes, writable: false));
            return 0u;
        }
        catch
        {
            return 2u;
        }
    }

    /// <summary>
    /// Load a plugin assembly from raw bytes into the default
    /// <see cref="AssemblyLoadContext"/> and return the native function pointer of its
    /// <c>[UnmanagedCallersOnly]</c> <c>PolyplugInit</c> entry point.
    ///
    /// The plugin entry type is resolved directly from the returned <see cref="Assembly"/>
    /// object — no assembly-name re-binding — which is the whole reason this bridge exists.
    /// </summary>
    /// <param name="asmPtr">Pointer to the plugin assembly bytes.</param>
    /// <param name="asmLen">Length of the plugin assembly bytes.</param>
    /// <param name="typeNamePtr">Pointer to the UTF-8 plugin type name (e.g. <c>CsharpPlugin.Plugin</c>).</param>
    /// <param name="typeNameLen">Length in bytes of the UTF-8 type name.</param>
    /// <returns>The native PolyplugInit function pointer, or <see cref="IntPtr.Zero"/> on failure.</returns>
    [UnmanagedCallersOnly(EntryPoint = "PolyplugByteBridgeLoadAndGetInit")]
    public static IntPtr LoadAndGetInit(IntPtr asmPtr, int asmLen, IntPtr typeNamePtr, int typeNameLen)
    {
        try
        {
            if (asmPtr == IntPtr.Zero || asmLen <= 0 || typeNamePtr == IntPtr.Zero || typeNameLen <= 0)
            {
                return IntPtr.Zero;
            }

            byte[] asmBytes = CopyToManaged(asmPtr, asmLen);
            string typeName = ReadUtf8(typeNamePtr, typeNameLen);

            // LoadFromStream copies the buffer into managed storage; the native side may
            // free its buffer immediately after this call returns.
            Assembly asm = AssemblyLoadContext.Default.LoadFromStream(
                new MemoryStream(asmBytes, writable: false)
            );

            Type? type = asm.GetType(typeName, throwOnError: false, ignoreCase: false);
            if (type is null)
            {
                return IntPtr.Zero;
            }

            MethodInfo? method = type.GetMethod(
                "PolyplugInit",
                BindingFlags.Public | BindingFlags.Static
            );
            if (method is null)
            {
                return IntPtr.Zero;
            }

            // The method must be JIT-compiled before its native entry is stable.
            RuntimeHelpers.PrepareMethod(method.MethodHandle);
            return method.MethodHandle.GetFunctionPointer();
        }
        catch
        {
            return IntPtr.Zero;
        }
    }

    private static byte[] CopyToManaged(IntPtr ptr, int len)
    {
        byte[] buffer = new byte[len];
        Marshal.Copy(ptr, buffer, 0, len);
        return buffer;
    }

    private static unsafe string ReadUtf8(IntPtr ptr, int len)
    {
        return Encoding.UTF8.GetString((byte*)ptr, len);
    }
}
