//! pack — generates scaffold metadata for packaging plugins.
//!
//! Produces language-specific project scaffolding for plugin authors.
//! This command generates scaffold files only — no build execution.

use std::fs;
use std::path::Path;
use std::path::PathBuf;

use crate::error::CodegenError;
use crate::ir::ValidatedIr;

/// Generate scaffold packaging files for a plugin in the given language.
/// Writes scaffold files under `out/`.
///
/// Note: This command generates scaffold metadata only.
/// No build tools are invoked (no cargo, npm, dotnet, pip, luarocks, deno).
pub(crate) fn run(ir: &ValidatedIr, out: &Path, lang: &str) -> Result<(), CodegenError> {
    let bundle_name: &str = ir
        .bundle
        .as_ref()
        .map(|b| b.name.as_str())
        .unwrap_or("plugin");
    let version: String = ir
        .bundle
        .as_ref()
        .map(|b| {
            format!(
                "{}.{}.{}",
                b.version.major, b.version.minor, b.version.patch
            )
        })
        .unwrap_or_else(|| "0.1.0".to_owned());

    match lang {
        "rust" => pack_rust(ir, out, bundle_name, &version),
        "cpp" => pack_cpp(ir, out, bundle_name, &version),
        "csharp" => pack_csharp(ir, out, bundle_name, &version),
        "python" => pack_python(ir, out, bundle_name, &version),
        "lua" => pack_lua(ir, out, bundle_name, &version),
        "js-quickjs" => pack_js_quickjs(ir, out, bundle_name, &version),
        "js-deno" => pack_js_deno(ir, out, bundle_name, &version),
        _ => Err(CodegenError::UnsupportedLanguage {
            lang: lang.to_owned(),
        }),
    }
}

fn write_file(dir: &Path, relative_path: &str, content: &str) -> Result<(), CodegenError> {
    let full_path: PathBuf = dir.join(relative_path);
    if let Some(parent) = full_path.parent() {
        fs::create_dir_all(parent).map_err(|e: std::io::Error| CodegenError::WriteFailed {
            path: full_path.display().to_string(),
            source: e,
        })?;
    }
    fs::write(&full_path, content).map_err(|e: std::io::Error| CodegenError::WriteFailed {
        path: full_path.display().to_string(),
        source: e,
    })?;
    Ok(())
}

fn pack_rust(
    _ir: &ValidatedIr,
    out: &Path,
    bundle_name: &str,
    version: &str,
) -> Result<(), CodegenError> {
    let cargo_toml: String = format!(
        "# THIS FILE IS GENERATED BY polyplugc pack. DO NOT COMMIT THIS COMMENT — fill in actual paths.\n\
[package]\nname = \"{bundle_name}\"\nversion = \"{version}\"\nedition = \"2021\"\n\n\
[lib]\ncrate-type = [\"cdylib\"]\n\n\
[dependencies]\npolyplug-guest = \"*\"  # replace with actual path or registry version\n"
    );
    let lib_rs: String = format!(
        "// THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
// Plugin: {bundle_name}\n\
// TODO: implement the contract functions for this plugin\n"
    );
    write_file(out, "Cargo.toml", &cargo_toml)?;
    write_file(out, "src/lib.rs", &lib_rs)?;
    Ok(())
}

fn pack_cpp(
    _ir: &ValidatedIr,
    out: &Path,
    bundle_name: &str,
    version: &str,
) -> Result<(), CodegenError> {
    let header_path: String = format!("include/{bundle_name}.hpp");
    let header: String = format!(
        "// THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
// Plugin: {bundle_name}\n\
#pragma once\n\n\
// TODO: declare the contract functions for this plugin\n"
    );

    let cmake: String = format!(
        "# THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
cmake_minimum_required(VERSION 3.20)\n\
project({bundle_name} VERSION {version})\n\n\
add_library({bundle_name} SHARED src/{bundle_name}.cpp)\n\
target_include_directories({bundle_name} PUBLIC include)\n"
    );

    let src_path: String = format!("src/{bundle_name}.cpp");
    let src: String = format!(
        "// THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
// Plugin: {bundle_name}\n\
#include \"{bundle_name}.hpp\"\n\n\
// TODO: implement the contract functions for this plugin\n"
    );

    write_file(out, &header_path, &header)?;
    write_file(out, "CMakeLists.txt", &cmake)?;
    write_file(out, &src_path, &src)?;
    Ok(())
}

fn to_pascal_case(name: &str) -> String {
    name.split('-')
        .map(|part: &str| {
            let mut chars: core::str::Chars<'_> = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => {
                    let upper: String = first.to_uppercase().collect();
                    upper + chars.as_str()
                }
            }
        })
        .collect::<Vec<String>>()
        .join("")
}

fn pack_csharp(
    _ir: &ValidatedIr,
    out: &Path,
    bundle_name: &str,
    version: &str,
) -> Result<(), CodegenError> {
    let pascal_name: String = to_pascal_case(bundle_name);

    let csproj_path: String = format!("{pascal_name}.csproj");
    let csproj: String = format!(
        "<!-- THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND. -->\n\
<Project Sdk=\"Microsoft.NET.Sdk\">\n\
  <PropertyGroup>\n\
    <TargetFramework>net8.0</TargetFramework>\n\
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>\n\
    <AssemblyName>{pascal_name}</AssemblyName>\n\
    <Version>{version}</Version>\n\
  </PropertyGroup>\n\
</Project>\n"
    );

    let nuspec_path: String = format!("{pascal_name}.nuspec");
    let nuspec: String = format!(
        "<!-- THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND. -->\n\
<?xml version=\"1.0\"?>\n\
<package>\n\
  <metadata>\n\
    <id>{pascal_name}</id>\n\
    <version>{version}</version>\n\
    <description>Plugin: {bundle_name}</description>\n\
  </metadata>\n\
</package>\n"
    );

    let plugin_cs: String = format!(
        "// THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
// Plugin: {bundle_name}\n\
namespace {pascal_name};\n\n\
// TODO: implement the contract functions for this plugin\n\
public static class Plugin\n\
{{\n\
}}\n"
    );

    write_file(out, &csproj_path, &csproj)?;
    write_file(out, &nuspec_path, &nuspec)?;
    write_file(out, "Plugin.cs", &plugin_cs)?;
    Ok(())
}

fn pack_python(
    _ir: &ValidatedIr,
    out: &Path,
    bundle_name: &str,
    version: &str,
) -> Result<(), CodegenError> {
    let underscored: String = bundle_name.replace('-', "_");

    let pyproject: String = format!(
        "# THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
[build-system]\nrequires = [\"hatchling\"]\nbuild-backend = \"hatchling.build\"\n\n\
[project]\nname = \"{bundle_name}\"\nversion = \"{version}\"\n\
dependencies = [\"polyplug-guest\"]\n"
    );

    let init_path: String = format!("{underscored}/__init__.py");
    let init_py: String = format!(
        "# THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
# Plugin: {bundle_name}\n"
    );

    let plugin_path: String = format!("{underscored}/plugin.py");
    let plugin_py: String = format!(
        "# THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
# Plugin: {bundle_name}\n\n\
# TODO: implement the contract functions for this plugin\n"
    );

    write_file(out, "pyproject.toml", &pyproject)?;
    write_file(out, &init_path, &init_py)?;
    write_file(out, &plugin_path, &plugin_py)?;
    Ok(())
}

fn pack_lua(
    _ir: &ValidatedIr,
    out: &Path,
    bundle_name: &str,
    version: &str,
) -> Result<(), CodegenError> {
    let init_lua: String = format!(
        "-- THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
-- Plugin: {bundle_name}\n\n\
-- TODO: implement the contract functions for this plugin\n\
local M = {{}}\n\nreturn M\n"
    );

    let rockspec_path: String = format!("{bundle_name}-{version}.rockspec");
    let rockspec: String = format!(
        "-- THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
package = \"{bundle_name}\"\nversion = \"{version}-1\"\n\n\
source = {{\n  url = \"*** fill in source url ***\"\n}}\n\n\
description = {{\n  summary = \"Plugin: {bundle_name}\"\n}}\n\n\
dependencies = {{\n  \"lua >= 5.1\",\n  \"polyplug-guest\"\n}}\n\n\
build = {{\n  type = \"builtin\",\n  modules = {{\n    [\"{bundle_name}\"] = \"init.lua\"\n  }}\n}}\n"
    );

    write_file(out, "init.lua", &init_lua)?;
    write_file(out, &rockspec_path, &rockspec)?;
    Ok(())
}

fn pack_js_quickjs(
    _ir: &ValidatedIr,
    out: &Path,
    bundle_name: &str,
    version: &str,
) -> Result<(), CodegenError> {
    let package_json: String = format!(
        "{{\n\
  \"name\": \"{bundle_name}\",\n\
  \"version\": \"{version}\",\n\
  \"main\": \"bundle.js\",\n\
  \"scripts\": {{\n\
    \"build\": \"rolldown index.ts --format esm --file bundle.js\"\n\
  }},\n\
  \"dependencies\": {{\n\
    \"polyplug-guest\": \"*\"\n\
  }}\n\
}}\n"
    );

    let index_ts: String = format!(
        "// THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
// Plugin: {bundle_name} (QuickJS target)\n\n\
// TODO: implement the contract functions for this plugin\n"
    );

    let gitignore: &str = "bundle.js\nnode_modules/\n";

    write_file(out, "package.json", &package_json)?;
    write_file(out, "index.ts", &index_ts)?;
    write_file(out, ".gitignore", gitignore)?;
    Ok(())
}

fn pack_js_deno(
    _ir: &ValidatedIr,
    out: &Path,
    bundle_name: &str,
    version: &str,
) -> Result<(), CodegenError> {
    let index_ts: String = format!(
        "// THIS FILE IS GENERATED BY polyplugc pack. DO NOT EDIT BY HAND.\n\
// Plugin: {bundle_name} (Deno target)\n\
// Deno.core is available via QuickJS/Deno runtime — use the polyplug guest bindings.\n\n\
// TODO: implement the contract functions for this plugin\n"
    );

    let deno_json: String = format!(
        "{{\n\
  \"name\": \"{bundle_name}\",\n\
  \"version\": \"{version}\",\n\
  \"exports\": \"./index.ts\",\n\
  \"tasks\": {{\n\
    \"build\": \"deno bundle index.ts bundle.js\"\n\
  }}\n\
}}\n"
    );

    let readme: String = format!(
        "# {bundle_name}\n\n\
Generated by polyplugc pack. Version: {version}.\n\n\
## Usage\n\n\
Implement the contract functions in `index.ts`, then run:\n\n\
```sh\ndeno task build\n```\n"
    );

    write_file(out, "index.ts", &index_ts)?;
    write_file(out, "deno.json", &deno_json)?;
    write_file(out, "README.md", &readme)?;
    Ok(())
}
