//! Integration test: a Lua guest calls a REAL host contract through the runtime.
//!
//! This proves the lua host-contract caller fix (commit 4f36d77) end to end at
//! runtime — not just at the string level. The flow is:
//!
//!   1. The test registers a *real* `host.logger` `HostContractInterface` (native
//!      dispatch) on a live `Runtime`. Its `log` thunk records the message it
//!      receives into a process-global slot — this is NOT the null-returning stub
//!      used by the existing string-level tests.
//!   2. A Lua bundle (generated by `polyplugc` into a temp dir, with a hand-written
//!      `transformer.lua` that calls `HostLoggerContract.from_host(host):log(...)`)
//!      is loaded into the runtime.
//!   3. The guest's `transform` function is dispatched. It resolves the host
//!      contract via the runtime's real `HostApi` and calls `log`.
//!   4. The test asserts the host thunk actually received the guest's message.
//!
//! LuaJIT is vendored, so this always runs (no skip path).

#![allow(clippy::expect_used)]
#![allow(clippy::undocumented_unsafe_blocks)]

use core::ffi::c_void;
use polyplug::runtime::Runtime;
use polyplug_abi::AbiError;
use polyplug_abi::DispatchMechanisms;
use polyplug_abi::DispatchType;
use polyplug_abi::GuestContractHandle;
use polyplug_abi::GuestContractInterface;
use polyplug_abi::HostContractInstance;
use polyplug_abi::HostContractInterface;
use polyplug_abi::NativeDispatch;
use polyplug_abi::StringView;
use polyplug_abi::Version;
use polyplug_codegen::GenerateConfig;
use polyplug_codegen::GenerateOutput;
use polyplug_codegen::Lang;
use polyplug_codegen::Side;
use polyplug_utils::HostContractId;
use polyplug_utils::guest_contract_id;
use polyplug_utils::host_contract_id;
use std::path::Path;
use std::path::PathBuf;
use std::sync::Arc;
use std::sync::Mutex;

mod cli_support;
use cli_support::cli_generate;

/// Records the message the host `log` thunk received from the guest.
static LOGGED_MESSAGE: Mutex<Option<String>> = Mutex::new(None);

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p: &Path| p.parent())
        .expect("workspace root from tests/integration")
        .to_path_buf()
}

// ─── Real host.logger interface (native dispatch) ──────────────────────────────

/// The `log` thunk: reads the `StringView` argument and records it. Mirrors the
/// canonical `create_host_logger_interface` thunk shape (interface_factories.rs).
unsafe extern "C" fn host_logger_log_thunk(
    _impl_ptr: *const c_void,
    args: *const (),
    _out: *mut (),
    out_err: *mut AbiError,
) {
    // SAFETY: per the host.logger ABI, args is a valid *const StringView.
    let message_sv: StringView = unsafe { *(args as *const StringView) };
    let message: String = if message_sv.ptr.is_null() || message_sv.len == 0 {
        String::new()
    } else {
        // SAFETY: ptr is valid for len UTF-8 bytes for the duration of the call.
        let slice: &[u8] = unsafe { core::slice::from_raw_parts(message_sv.ptr, message_sv.len) };
        String::from_utf8_lossy(slice).into_owned()
    };
    *LOGGED_MESSAGE.lock().expect("LOGGED_MESSAGE poisoned") = Some(message);
    if !out_err.is_null() {
        // SAFETY: out_err is non-null (just checked) and writable per the ABI contract.
        unsafe { out_err.write(AbiError::ok()) };
    }
}

/// `create_instance`: hands back the registrant `user_data` as the instance data
/// (the self-passing pattern the generated lua caller forwards as the this-arg).
unsafe extern "C" fn host_logger_create_instance(
    this: *const HostContractInterface,
    _args: *const (),
    out_instance: *mut HostContractInstance,
) {
    if !out_instance.is_null() {
        // SAFETY: `this` is the valid interface pointer per the ABI contract;
        // out_instance is non-null (just checked) and writable.
        unsafe {
            out_instance.write(HostContractInstance {
                data: (*this).user_data,
            })
        };
    }
}

unsafe extern "C" fn host_logger_destroy_instance(
    _this: *const HostContractInterface,
    _instance: HostContractInstance,
) {
    // Stateless: nothing to clean up.
}

/// Build and leak a real `host.logger` native interface with a single `log`
/// function. Leaked so it satisfies the `&'static` bound of
/// `Runtime::register_host_contract`.
fn make_host_logger_interface() -> &'static HostContractInterface {
    // The function-pointer table must outlive the interface; leak a Box to give it
    // a stable 'static address (raw fn pointers are not `Sync`, so a `static` array
    // is rejected — leaking mirrors the generated interface_factories.rs pattern).
    let functions: &'static [*const (); 1] =
        Box::leak(Box::new([host_logger_log_thunk as *const ()]));

    let interface: HostContractInterface = HostContractInterface {
        contract_id: HostContractId::from(host_contract_id("host.logger", 1)),
        contract_version: Version {
            major: 1,
            minor: 0,
            patch: 0,
        },
        singleton: false,
        dispatch_type: DispatchType::Native,
        runtime: core::ptr::null_mut(),
        user_data: core::ptr::null_mut(),
        create_instance: host_logger_create_instance,
        destroy_instance: host_logger_destroy_instance,
        dispatch: DispatchMechanisms {
            native: NativeDispatch {
                function_count: 1_u32,
                functions: functions.as_ptr(),
            },
        },
    };
    Box::leak(Box::new(interface))
}

// ─── Lua bundle fixture (generated glue + hand-written guest) ───────────────────

/// Generate the Lua guest glue for the shared `examples/api.toml` (which declares
/// the `host.logger` host contract and the `data.Transformer` guest contract),
/// then write a `transformer.lua` whose `transform` calls the host logger. Returns
/// the bundle directory.
fn build_lua_bundle(tmp: &Path) -> PathBuf {
    let bundle_dir: PathBuf = tmp.join("lua_host_contract_bundle");
    std::fs::create_dir_all(&bundle_dir).expect("create bundle dir");

    // A bundle.toml pointing at the shared example API.
    let api_path: PathBuf = workspace_root().join("examples").join("api.toml");
    let bundle_toml: String = format!(
        "[bundle]\n\
         name = \"lua_host_contract\"\n\
         version = \"1.0.0\"\n\
         api = \"{api}\"\n\
         loader = \"lua\"\n\
         file = \"transformer.lua\"\n\n\
         [[plugin]]\n\
         name = \"transformer\"\n\
         implements = [\"data.Transformer@1.0\"]\n",
        // Backslashes are invalid TOML escape sequences; forward slashes are valid
        // path separators on every platform (including Windows).
        api = api_path.to_string_lossy().replace('\\', "/"),
    );
    let bundle_toml_path: PathBuf = bundle_dir.join("bundle.toml");
    std::fs::write(&bundle_toml_path, bundle_toml).expect("write bundle.toml");

    // Generate the lua guest glue (contracts.lua, host_contracts.lua, …) plus the
    // discovery manifest.toml via the polyplugc library, writing each emitted file
    // to disk (mirrors crates/polyplugc/tests usage of the same API).
    let gen_dir: PathBuf = bundle_dir.join("generated");
    let config: GenerateConfig = GenerateConfig {
        api_toml: bundle_toml_path,
        lang: Lang::Lua,
        side: Side::Guest,
        out_dir: gen_dir.clone(),
    };
    let output: GenerateOutput = cli_generate(&config).expect("polyplugc generate (lua)");
    for file in &output.files {
        let file_path: PathBuf = gen_dir.join(&file.path);
        if let Some(parent) = file_path.parent() {
            std::fs::create_dir_all(parent).expect("create generated parent dir");
        }
        std::fs::write(&file_path, &file.content).expect("write generated file");
    }

    // The --bundle manifest lands at <bundle>/generated/manifest.toml; the loader
    // discovers it at <bundle>/manifest.toml. Move it up.
    std::fs::rename(
        gen_dir.join("manifest.toml"),
        bundle_dir.join("manifest.toml"),
    )
    .expect("move manifest.toml to bundle root");

    // Guest impl: transform() resolves the host logger via the runtime's real
    // HostApi (stored during polyplug_init) and calls log(message), then returns
    // a confirmation string. This is the path the lua host-contract caller fix
    // (commit 4f36d77) repaired.
    let guest_lua: &str = "\
local polyplug = require('polyplug_guest')\n\
local contracts = require('generated.guest.contracts')\n\
local host_contracts = require('generated.guest.host_contracts')\n\
\n\
local function new_transformer(host)\n\
    local self = {}\n\
    function self:transform(input)\n\
        local msg = 'lua-guest called host.logger'\n\
        local logger = host_contracts.HostLoggerContract.from_host(host, 0)\n\
        if logger ~= nil then\n\
            logger:log(msg)\n\
        end\n\
        return 'OK:' .. msg\n\
    end\n\
    return self\n\
end\n\
\n\
contracts.set_transformer_factory(new_transformer)\n\
return contracts\n";
    std::fs::write(bundle_dir.join("transformer.lua"), guest_lua).expect("write transformer.lua");

    bundle_dir
}

// ─── Test ───────────────────────────────────────────────────────────────────────

#[test]
fn lua_guest_calls_real_host_contract() {
    *LOGGED_MESSAGE.lock().expect("poisoned") = None;

    let tmp: tempfile::TempDir = tempfile::tempdir().expect("tempdir");
    let bundle_dir: PathBuf = build_lua_bundle(tmp.path());

    let rt: Arc<Runtime> = Runtime::builder()
        .loader(polyplug_lua::LuaLoader::new(
            polyplug_lua::LuaConfig::default(),
        ))
        .build()
        .expect("build runtime");

    // Register the REAL host.logger interface BEFORE the guest runs.
    let logger_iface: &'static HostContractInterface = make_host_logger_interface();
    rt.register_host_contract(host_contract_id("host.logger", 1), logger_iface)
        .expect("register host.logger");

    rt.load_bundle(&bundle_dir).expect("lua bundle must load");

    // Resolve and dispatch data.Transformer::transform.
    let contract_id: u64 = guest_contract_id("data.Transformer", 1);
    let handle: GuestContractHandle = rt
        .find_guest_contract(contract_id, 0)
        .expect("data.Transformer must be registered after load");
    let vtable_ptr: *const GuestContractInterface = rt
        .resolve_guest_contract(handle)
        .expect("handle must resolve");
    // SAFETY: vtable_ptr is a live interface for the runtime lifetime.
    let vtable: &GuestContractInterface = unsafe { &*vtable_ptr };
    assert_eq!(
        vtable.dispatch_type,
        DispatchType::VirtualMachine,
        "lua guests use VM dispatch"
    );

    let input: &[u8] = b"DECODED:x|y|1";
    let input_view: StringView = StringView {
        ptr: input.as_ptr(),
        len: input.len(),
    };
    let mut out_view: StringView = StringView::null();
    const TRANSFORM_FN_ID: u32 = 0;

    // SAFETY: dispatch_type is VirtualMachine, so the vm union variant is active;
    // args/out match transform's ABI; a null arena selects the host->alloc fallback.
    let mut err: AbiError = AbiError::ok();
    unsafe {
        (vtable.dispatch.vm.call)(
            vtable.dispatch.vm.loader_data,
            polyplug_abi::GuestContractInstance::null(),
            TRANSFORM_FN_ID,
            &input_view as *const StringView as *const (),
            &mut out_view as *mut StringView as *mut (),
            core::ptr::null_mut(),
            &mut err as *mut AbiError,
        )
    };
    assert_eq!(
        err.code,
        polyplug_abi::AbiErrorCode::Ok as u32,
        "transform must return Ok"
    );

    // The host must have actually received the guest's log message — proving the
    // full guest→host-contract round-trip through the runtime's real HostApi.
    let logged: Option<String> = LOGGED_MESSAGE.lock().expect("poisoned").clone();
    assert_eq!(
        logged.as_deref(),
        Some("lua-guest called host.logger"),
        "host.logger::log must have received the guest's message"
    );
}
