// Layout tests for polyplug ABI structs.
// AUTO-GENERATED by polyplug_abi build script — do not edit.

#include "polyplug/abi.hpp"
#include <type_traits>

static_assert(sizeof(NativeDispatch) == 16, "NativeDispatch size mismatch");
static_assert(sizeof(VmDispatch) == 16, "VmDispatch size mismatch");
static_assert(sizeof(VmLoaderData) == 8, "VmLoaderData size mismatch");
static_assert(sizeof(GuestContractInstance) == 16, "GuestContractInstance size mismatch");
static_assert(sizeof(GuestContractInterface) == 64, "GuestContractInterface size mismatch");
static_assert(sizeof(HostApi) == 184, "HostApi size mismatch");
static_assert(sizeof(HostContractInstance) == 8, "HostContractInstance size mismatch");
static_assert(sizeof(HostContractInterface) == 80, "HostContractInterface size mismatch");
static_assert(sizeof(GuestContractHandle) == 8, "GuestContractHandle size mismatch");
static_assert(sizeof(BundleInitContext) == 24, "BundleInitContext size mismatch");
static_assert(sizeof(PluginDescriptor) == 48, "PluginDescriptor size mismatch");
static_assert(sizeof(ReloadPhase) == 48, "ReloadPhase size mismatch");
static_assert(sizeof(RuntimeConfig) == 72, "RuntimeConfig size mismatch");
static_assert(sizeof(AbiError) == 24, "AbiError size mismatch");
static_assert(sizeof(Buffer) == 24, "Buffer size mismatch");
static_assert(sizeof(ArenaOverflowBlock) == 24, "ArenaOverflowBlock size mismatch");
static_assert(sizeof(CallArena) == 40, "CallArena size mismatch");
static_assert(sizeof(DependencyInfo) == 24, "DependencyInfo size mismatch");
static_assert(sizeof(Ed25519PublicKey) == 32, "Ed25519PublicKey size mismatch");
static_assert(sizeof(StringView) == 16, "StringView size mismatch");
static_assert(sizeof(Version) == 12, "Version size mismatch");
static_assert(std::is_same_v<decltype(polyplug::abi::as_bytes(Buffer{})), polyplug::abi::ByteView>, "Buffer as_bytes must use the read-only byte view");
