// Layout tests for polyplug ABI structs.
// AUTO-GENERATED by polyplug_abi build script — do not edit.

using System.Runtime.InteropServices;
using Xunit;

namespace Polyplug.Abi.Tests
{
    public class LayoutTests
    {
        [Fact]
        public void NativeDispatchIs16Bytes() => Assert.Equal(16, Marshal.SizeOf<NativeDispatch>());

        [Fact]
        public void VmDispatchIs16Bytes() => Assert.Equal(16, Marshal.SizeOf<VmDispatch>());

        [Fact]
        public void VmLoaderDataIs8Bytes() => Assert.Equal(8, Marshal.SizeOf<VmLoaderData>());

        [Fact]
        public void GuestContractInstanceIs16Bytes() => Assert.Equal(16, Marshal.SizeOf<GuestContractInstance>());

        [Fact]
        public void GuestContractInterfaceIs56Bytes() => Assert.Equal(56, Marshal.SizeOf<GuestContractInterface>());

        [Fact]
        public void HostApiIs160Bytes() => Assert.Equal(160, Marshal.SizeOf<HostApi>());

        [Fact]
        public void HostContractInstanceIs8Bytes() => Assert.Equal(8, Marshal.SizeOf<HostContractInstance>());

        [Fact]
        public void HostContractInterfaceIs80Bytes() => Assert.Equal(80, Marshal.SizeOf<HostContractInterface>());

        [Fact]
        public void GuestContractHandleIs8Bytes() => Assert.Equal(8, Marshal.SizeOf<GuestContractHandle>());

        [Fact]
        public void BundleInitContextIs24Bytes() => Assert.Equal(24, Marshal.SizeOf<BundleInitContext>());

        [Fact]
        public void PluginDescriptorIs48Bytes() => Assert.Equal(48, Marshal.SizeOf<PluginDescriptor>());

        [Fact]
        public void ReloadPhaseIs48Bytes() => Assert.Equal(48, Marshal.SizeOf<ReloadPhase>());

        [Fact]
        public void RuntimeConfigIs24Bytes() => Assert.Equal(24, Marshal.SizeOf<RuntimeConfig>());

        [Fact]
        public void AbiErrorIs24Bytes() => Assert.Equal(24, Marshal.SizeOf<AbiError>());

        [Fact]
        public void BufferIs24Bytes() => Assert.Equal(24, Marshal.SizeOf<Buffer>());

        [Fact]
        public void ArenaOverflowBlockIs16Bytes() => Assert.Equal(16, Marshal.SizeOf<ArenaOverflowBlock>());

        [Fact]
        public void CallArenaIs40Bytes() => Assert.Equal(40, Marshal.SizeOf<CallArena>());

        [Fact]
        public void DependencyInfoIs24Bytes() => Assert.Equal(24, Marshal.SizeOf<DependencyInfo>());

        [Fact]
        public void StringViewIs16Bytes() => Assert.Equal(16, Marshal.SizeOf<StringView>());

        [Fact]
        public void VersionIs12Bytes() => Assert.Equal(12, Marshal.SizeOf<Version>());

    }
}
