[bundle]
name = "js_reporter"
version = "1.0.0"
api = "../../../api.toml"
runtime = "js-quickjs"
file = "reporter.js"

[[plugin]]
name = "reporter"
version = "1.0.0"
implements = ["data.Reporter@1.0"]
