-- THIS FILE IS AUTO-GENERATED BY polyplug_abi
-- DO NOT EDIT BY HAND
-- Re-generate with: polyplug_abi generate --lang lua

--- ABI constants and types for the polyplug plugin runtime.
-- This module contains the frozen ABI types that match the Rust ABI exactly.
-- DO NOT modify field order or sizes — these must match the host runtime.

local ffi = require("ffi")
local M = {}

-- ─── ABI Constants ────────────────────────────────────────────────────────────

M.POLYPLUG_ABI_VERSION = ffi.cast("uint32_t", 1)
M.ABI_OK = ffi.cast("uint32_t", 0)
M.ABI_ERROR_GENERIC = ffi.cast("uint32_t", 1)
M.ABI_BUFFER_TOO_SMALL = ffi.cast("uint32_t", 2)
M.ABI_ERROR_PANIC = ffi.cast("uint32_t", 3)
M.ABI_ERROR_NOT_FOUND = ffi.cast("uint32_t", 4)
M.ABI_ERROR_STALE_HANDLE = ffi.cast("uint32_t", 5)
M.ABI_FUNCTION_NOT_AVAIL = ffi.cast("uint32_t", 6)

-- ─── ABI Enums ────────────────────────────────────────────────────────────────

ffi.cdef[[
    //  Dispatch mechanism type — determines how function calls are routed.
    typedef enum DispatchType {
        //  Native dispatch: direct function pointer calls (zero overhead).
        DispatchType_Native = 0,
        //  VM dispatch: call through a dispatch function with loader_data.
        DispatchType_VirtualMachine = 1,
    } DispatchType;

]]

-- ─── ABI Structs ──────────────────────────────────────────────────────────────

ffi.cdef[[
    //  Non-owning UTF-8 string view.
    // 
    //  OWNERSHIP: borrowed reference. `ptr` must remain valid for the duration
    //  of the call. Never freed by the receiver.
    typedef struct StringView {
        //  UTF-8 bytes, NOT null-terminated.
        const uint8_t* ptr;
        //  Byte count.
        size_t len;
    } StringView;

    //  Owning byte buffer.
    // 
    //  OWNERSHIP: `ptr` is always allocated via `polyplug_host_alloc`.
    //  Owner calls `polyplug_host_free(ptr, cap, align)` when done.
    typedef struct Buffer {
        uint8_t* ptr;
        //  Bytes currently used.
        size_t len;
        //  Bytes allocated.
        size_t cap;
    } Buffer;

    //  Opaque handle to a loaded plugin — validated on use.
    // 
    //  INTERNAL STRUCTURE: index into registry array + generation counter.
    //  The generation counter detects use-after-unload.
    typedef struct PluginHandle {
        //  Slot in the registry array.
        uint32_t index;
        //  Incremented on unload — detects stale handles.
        uint32_t generation;
    } PluginHandle;

    //  Opaque host context passed to plugin functions via rt_ctx parameter.
    // 
    //  Contains the runtime pointer and the bundle_id of the calling bundle.
    //  The actual implementation is in the polyplug crate; this definition
    //  establishes the ABI layout.
    // 
    //  OWNERSHIP: `'static`, lives as long as the runtime.
    typedef struct HostContext {
        //  Opaque pointer to the Runtime. Never dereferenced by plugins.
        void* runtime;
        //  Bundle ID of the calling bundle for dependency enforcement.
        uint64_t bundle_id;
    } HostContext;

    //  ABI error — returned by value from all ABI calls.
    // 
    //  OWNERSHIP: `code` is a value type. `message.ptr` is allocated by the callee
    //  via `host_alloc`. Caller frees with `polyplug_host_free(message.ptr, message.len, 1)`
    //  after reading. If `code == ABI_OK`, `message.ptr` is NULL — no free needed.
    typedef struct AbiError {
        //  0 = success, non-zero = error.
        uint32_t code;
        //  Empty/NULL if success. UTF-8 message if non-zero code.
        StringView message;
    } AbiError;

    //  Native dispatch data — direct function pointer array.
    // 
    //  Used when `dispatch_type == DispatchType::Native`.
    //  The `functions` array contains `function_count` function pointers.
    typedef struct NativeDispatch {
        //  Pointer to a static array of function pointers, indexed by function_id.
        void* const* functions;
    } NativeDispatch;

    //  VM dispatch data — call through a dispatch function.
    // 
    //  Used when `dispatch_type == DispatchType::VirtualMachine`.
    //  The `call` function receives `loader_data` which contains VM-specific state.
    typedef struct VmDispatch {
        //  Dispatch function called for every VM function invocation.
        // 
        //  # Arguments
        //  - `loader_data`: VM-specific data (cast from `*mut c_void`)
        //  - `fn_id`: Function index within the contract
        //  - `args`: Pointer to packed arguments (ABI-specific layout)
        //  - `out`: Pointer to output buffer for return value
        AbiError (*call )(void*, uint32_t, const void*, void*);
        //  Loader-specific data (e.g., LuaLoaderData, JsLoaderData).
        //  Opaque to the host; interpreted by the dispatch function.
        void* loader_data;
    } VmDispatch;

]]

-- ─── ABI Unions ───────────────────────────────────────────────────────────────

ffi.cdef[[
    //  Union of dispatch mechanisms — use based on `dispatch_type`.
    // 
    //  # Safety
    //  Access the correct variant based on `PluginInterface::dispatch_type`:
    //  - `dispatch_type == Native` → access `.native`
    //  - `dispatch_type == VirtualMachine` → access `.vm`
    typedef union PluginDispatch {
        //  Native dispatch data (when dispatch_type == Native).
        NativeDispatch native;
        //  VM dispatch data (when dispatch_type == VirtualMachine).
        VmDispatch vm;
    } PluginDispatch;

]]

-- ─── ABI Structs (after unions) ──────────────────────────────────────────────

ffi.cdef[[
    //  Metadata about a plugin within a bundle.
    // 
    //  OWNERSHIP: value type passed by pointer during init. The `name` and
    //  `contract_name` StringViews are borrowed from the plugin's static memory.
    //  The receiver must not free or outlive the plugin's library.
    typedef struct PluginDescriptor {
        //  Human-readable plugin name.
        StringView name;
        //  Full contract name for collision detection.
        StringView contract_name;
        uint32_t version_major;
        uint32_t version_minor;
        uint32_t version_patch;
    } PluginDescriptor;

    //  Plugin interface — one per contract implemented by a plugin.
    // 
    //  OWNERSHIP: Must be `'static` or intentionally leaked.
    //  Never stack-allocated. Never freed while runtime lives.
    // 
    //  # Dispatch
    //  - `dispatch_type == Native`: Call via `dispatch.native.functions[fn_id]`
    //  - `dispatch_type == VirtualMachine`: Call via `dispatch.vm.call(...)`
    typedef struct PluginInterface {
        //  Pointer to the host context for this plugin.
        //  Used for host function calls and dependency enforcement.
        const HostContext* rt_ctx;
        //  FNV-1a hash of "contract_name@major_version".
        uint64_t contract_id;
        //  minor.patch encoded as `(minor << 16 | patch)`.
        uint32_t contract_version;
        //  Number of valid entries in the dispatch array.
        uint32_t function_count;
        //  Dispatch mechanism type (Native or VirtualMachine).
        DispatchType dispatch_type;
        //  Union of dispatch mechanisms — access based on dispatch_type.
        PluginDispatch dispatch;
    } PluginInterface;

    //  Host capabilities passed to every plugin at init time.
    // 
    //  OWNERSHIP: `'static`, lives as long as the runtime.
    // 
    //  All functions take `rt_ctx` as first parameter - an opaque pointer to the Runtime.
    //  This allows each Runtime to have its own isolated state (no global registry).
    typedef struct HostVTable {
        AbiError (*register_plugin )(void*, const PluginDescriptor*, const PluginInterface*);
        uint8_t* (*alloc )(void*, size_t, size_t);
        void (*free )(void*, uint8_t*, size_t, size_t);
        PluginHandle (*find_by_contract )(void*, uint64_t, uint32_t);
        PluginHandle (*find_by_bundle )(void*, uint64_t, uint64_t, uint32_t);
        size_t (*find_all_by_contract )(void*, uint64_t, uint32_t, PluginHandle*, size_t);
        const PluginInterface* (*resolve_plugin )(void*, PluginHandle);
        const void* (*get_extension )(void*, uint32_t);
    } HostVTable;

    //  Context passed to every guest `polyplug_init()` function.
    //  The `bundle_path` pointer is runtime-owned and valid for the lifetime of the `PluginRuntime`.
    //  **Plugin must not store the raw pointer** — copy the string value if persistence is needed.
    typedef struct PluginContext {
        //  Absolute canonical path to the directory containing the loaded bundle.
        StringView bundle_path;
        //  Host's supported ABI version for negotiation (Option C).
        //  Plugin can use this to determine available features.
        uint32_t host_abi_version;
        //  Bundle ID for dependency enforcement during init.
        uint64_t bundle_id;
    } PluginContext;

    //  A single extension entry in the runtime config.
    // 
    //  OWNERSHIP: the `vtable` pointer must be `'static` (valid for the runtime
    //  lifetime). `ExtensionEntry` arrays are passed by pointer to `RuntimeConfig`
    //  and never owned or freed by the runtime.
    typedef struct ExtensionEntry {
        //  FNV-1a lower 32 bits of the extension name.
        uint32_t extension_id;
        //  Pointer to the extension's vtable struct.
        const void* vtable;
    } ExtensionEntry;

    //  Configuration passed to `polyplug_runtime_create` during runtime initialisation.
    // 
    //  OWNERSHIP: borrowed for the duration of the runtime build only.
    //  The caller may free all pointed-to memory after the build
    //  returns. The runtime copies any data it needs to retain.
    typedef struct RuntimeConfig {
        //  Plugin directories to scan (array of `plugin_dir_count` StringViews).
        const StringView* plugin_dirs;
        size_t plugin_dir_count;
        //  Compatibility mode: 0 = Strict (only mode implemented in MVP).
        uint32_t compatibility;
        //  Extensions provided by the host (array of `extension_count` entries).
        const ExtensionEntry* extensions;
        size_t extension_count;
    } RuntimeConfig;

]]

-- ─── FNV-1a Hash Helpers ──────────────────────────────────────────────────────

local bit = require("bit")
local FNV_OFFSET = 0xcbf29ce484222325ULL
local FNV_PRIME = 0x00000100000001B3ULL

--- Compute FNV-1a 64-bit hash of a string.
-- @param str string  The input string.
-- @return number     The 64-bit hash value.
local function fnv1a_64(str)
    local h = FNV_OFFSET
    for i = 1, #str do
        local b = str:byte(i)
        h = bit.bxor(h, b)
        h = h * FNV_PRIME
    end
    return h
end

--- Compute the contract ID for "name@major_version" using FNV-1a 64-bit.
-- @param name string         The contract name.
-- @param major_version number The major version.
-- @return number             The contract ID.
function M.contract_id(name, major_version)
    local s = name .. '@' .. tostring(major_version)
    return fnv1a_64(s)
end

--- Compute an extension ID from its name using FNV-1a lower 32 bits.
-- @param name string  The extension name.
-- @return number      The extension ID (uint32).
function M.extension_id(name)
    local h = fnv1a_64(name)
    return ffi.cast("uint32_t", h)
end

--- Compute a bundle ID from its name using FNV-1a 64-bit hash.
-- @param name string  The bundle name.
-- @return number      The bundle ID.
function M.bundle_id(name)
    return fnv1a_64(name)
end

-- ─── String Helpers ────────────────────────────────────────────────────────────

--- Convert StringView to Lua string.
-- @param sv StringView|string  The StringView (FFI cdata) or Lua string.
-- @return string               The Lua string.
local function to_string(sv)
    if type(sv) == "string" then
        return sv
    end
    -- Assume it's a StringView FFI cdata
    return ffi.string(sv.ptr, sv.len)
end

--- Strip prefix from a string.
-- @param sv StringView|string  The input string.
-- @param prefix string         The prefix to strip.
-- @return string               String without prefix, or original if no match.
function M.strip_prefix(sv, prefix)
    local s = to_string(sv)
    if s:sub(1, #prefix) == prefix then
        return s:sub(#prefix + 1)
    end
    return s
end

--- Check if string starts with prefix.
-- @param sv StringView|string  The input string.
-- @param prefix string         The prefix to check.
-- @return boolean              True if string starts with prefix.
function M.starts_with(sv, prefix)
    local s = to_string(sv)
    return s:sub(1, #prefix) == prefix
end

--- Split string by delimiter.
-- @param sv StringView|string  The input string.
-- @param delimiter string      The delimiter (single character).
-- @return table                Array of strings.
function M.split(sv, delimiter)
    local s = to_string(sv)
    local result = {}
    local pattern = "([^" .. delimiter .. "]+)"
    for part in s:gmatch(pattern) do
        table.insert(result, part)
    end
    return result
end

return M
