-- Layout tests for polyplug ABI structs.
-- AUTO-GENERATED by polyplug_abi build script — do not edit.

local script_dir = (arg and arg[0] or ""):match("^(.*[/\\])") or "./"
package.path = script_dir .. "?.lua;" .. package.path
local ffi = require("ffi")
require("abi")

assert(ffi.sizeof("NativeDispatch") == 16, "NativeDispatch size mismatch")
assert(ffi.sizeof("VmDispatch") == 16, "VmDispatch size mismatch")
assert(ffi.sizeof("VmLoaderData") == 8, "VmLoaderData size mismatch")
assert(ffi.sizeof("GuestContractInstance") == 16, "GuestContractInstance size mismatch")
assert(ffi.sizeof("GuestContractInterface") == 56, "GuestContractInterface size mismatch")
assert(ffi.sizeof("HostApi") == 144, "HostApi size mismatch")
assert(ffi.sizeof("HostContractInstance") == 8, "HostContractInstance size mismatch")
assert(ffi.sizeof("HostContractInterface") == 80, "HostContractInterface size mismatch")
assert(ffi.sizeof("RuntimeApi") == 96, "RuntimeApi size mismatch")
assert(ffi.sizeof("GuestContractHandle") == 4, "GuestContractHandle size mismatch")
assert(ffi.sizeof("BundleInitContext") == 24, "BundleInitContext size mismatch")
assert(ffi.sizeof("PluginDescriptor") == 48, "PluginDescriptor size mismatch")
assert(ffi.sizeof("ReloadPhase") == 48, "ReloadPhase size mismatch")
assert(ffi.sizeof("RuntimeConfig") == 24, "RuntimeConfig size mismatch")
assert(ffi.sizeof("AbiError") == 24, "AbiError size mismatch")
assert(ffi.sizeof("Buffer") == 24, "Buffer size mismatch")
assert(ffi.sizeof("ArenaOverflowBlock") == 16, "ArenaOverflowBlock size mismatch")
assert(ffi.sizeof("CallArena") == 40, "CallArena size mismatch")
assert(ffi.sizeof("DependencyInfo") == 24, "DependencyInfo size mismatch")
assert(ffi.sizeof("StringView") == 16, "StringView size mismatch")
assert(ffi.sizeof("Version") == 12, "Version size mismatch")

print("All layout tests passed!")
