[bundle]
name = "cpp_worker"
version = "0.1.0"
api = "../../api.toml"
runtime = "native"

[bundle.file]
linux.x86_64 = "libworker.so"

[[plugin]]
name = "worker"
version = "1.0.0"
implements = ["example.worker@1.0"]
