// THIS FILE IS AUTO-GENERATED BY polyplug_abi build script.
// DO NOT EDIT STRUCT/FIELD DEFINITIONS.
// Helper methods are preserved by ast-grep across regenerations.
/**
 *  Native dispatch data — direct function pointer array.
 * 
 *  Used when `dispatch_type == DispatchType::Native`.
 *  The `functions` array contains `function_count` function pointers.
 */
export interface NativeDispatch {
    /**  Number of valid entries in the dispatch array. */
    function_count: number;
    /**  Pointer to a static array of function pointers, indexed by function_id. */
    functions: bigint;
}

export const NATIVE_DISPATCH_FUNCTION_COUNT_OFFSET: number = 0;
export const NATIVE_DISPATCH_FUNCTIONS_OFFSET: number = 8;
export const NATIVE_DISPATCH_SIZE: number = 16;

/**
 *  VM dispatch data — call through a dispatch function.
 * 
 *  Used when `dispatch_type == DispatchType::VirtualMachine`.
 *  The `call` function receives `loader_data` which contains VM-specific state.
 */
export interface VmDispatch {
    /**
     *  Dispatch function called for every VM function invocation.
     * 
     *  # Arguments
     *  - `loader_data`: VmLoaderData handle containing VM-specific state
     *  - `instance`: The guest contract instance (opaque handle)
     *  - `fn_id`: Function index within the contract
     *  - `args`: Pointer to packed arguments (ABI-specific layout)
     *  - `out`: Pointer to output buffer for return value
     */
    call: number;
    /**
     *  Loader-specific data handle.
     *  Opaque to the host; interpreted by the dispatch function.
     */
    loader_data: VmLoaderData;
}

export const VM_DISPATCH_CALL_OFFSET: number = 0;
export const VM_DISPATCH_LOADER_DATA_OFFSET: number = 8;
export const VM_DISPATCH_SIZE: number = 16;

/**
 *  Opaque handle to VM loader-specific data.
 * 
 *  Wraps VM-specific state managed by each loader (Python, Lua, JS).
 *  Opaque to core runtime — loaders know their own state layout.
 * 
 *  # OWNERSHIP
 *  Owned by the loader. Lives for the lifetime of the loaded plugin.
 */
export interface VmLoaderData {
    /**  Opaque pointer to VM-specific loader data. */
    data: bigint;
}

export const VM_LOADER_DATA_DATA_OFFSET: number = 0;
export const VM_LOADER_DATA_SIZE: number = 8;

/**
 *  Opaque handle to a guest contract instance.
 * 
 *  Created by `GuestContractInterface::create_instance`, destroyed by `destroy_instance`.
 * 
 *  # Who provides
 *  Guest code creates instances via create_instance factory.
 *  The guest owns the underlying data.
 * 
 *  # Who calls
 *  Host code passes instances to dispatch functions and destroy_instance.
 * 
 *  # Ownership
 *  This is an owned handle - the instance must be destroyed via
 *  `GuestContractInterface::destroy_instance` before hot-reload.
 *  Failure to destroy causes memory leaks and prevents safe hot-reload.
 * 
 *  # Lifetime
 *  Lives until `destroy_instance` is called. Must be destroyed before
 *  the bundle is unloaded or hot-reloaded.
 * 
 *  # Layout
 *  - `data`: Opaque instance pointer (owned by guest)
 *  - `contract_id`: Contract ID for zero-overhead dispatch
 * 
 *  # Dispatch
 *  The `contract_id` field enables `call_guest_method` to dispatch without
 *  looking up the contract in a map. This is zero-overhead dispatch.
 */
export interface GuestContractInstance {
    /**
     *  Opaque instance data pointer.
     *  The actual data is owned by the guest plugin.
     * 
     *  # Ownership
     *  Guest owns the memory. Host must not free or modify.
     *  Must be freed via GuestContractInterface::destroy_instance.
     */
    data: bigint;
    /**
     *  Contract ID for zero-overhead dispatch.
     *  Enables call_guest_method to dispatch without lookup.
     * 
     *  # Purpose
     *  Eliminates the need to look up which contract an instance belongs to.
     *  The contract_id is set by create_instance and used for direct dispatch.
     */
    contract_id: GuestContractId;
}

export const GUEST_CONTRACT_INSTANCE_DATA_OFFSET: number = 0;
export const GUEST_CONTRACT_INSTANCE_CONTRACT_ID_OFFSET: number = 8;
export const GUEST_CONTRACT_INSTANCE_SIZE: number = 16;

/**
 *  Guest Contract Interface — one per contract implemented by a guest (plugin).
 * 
 *  # Who provides
 *  Guest (plugin) code creates this struct and registers it via `register_contract`.
 *  Must be `'static` or intentionally leaked.
 * 
 *  # Who calls
 *  Host code calls `create_instance`, `destroy_instance`, and dispatch functions.
 * 
 *  # Ownership
 *  Must be `'static`. Never stack-allocated. Never freed while runtime lives.
 *  Typically created as `static` or via `Box::leak()`.
 * 
 *  # Lifetime
 *  Lives for the entire runtime lifetime. Must survive hot-reload.
 * 
 *  # Instance Lifecycle
 *  - `create_instance`: Factory function to create new instances
 *  - `destroy_instance`: Destructor to clean up instances before hot-reload
 * 
 *  # Dispatch
 *  - `dispatch_type == Native`: Call via `dispatch.native.functions[fn_id](instance, args, out)`
 *  - `dispatch_type == VirtualMachine`: Call via `dispatch.vm.call(loader_data, instance, fn_id, args, out)`
 */
export interface GuestContractInterface {
    /**
     *  FNV-1a hash of "guest_contract:name@major_version".
     * 
     *  Generated by polyplugc from contract name and major version.
     *  Used for contract lookup via `find_by_contract`.
     */
    contract_id: GuestContractId;
    /**
     *  Contract version (major, minor, patch).
     * 
     *  Used for version compatibility checks during lookup.
     */
    contract_version: Version;
    /**
     *  Dispatch mechanism type (Native or VirtualMachine).
     * 
     *  Determines how dispatch functions are invoked:
     *  - Native: Direct function pointer call
     *  - VirtualMachine: VM-specific dispatch via loader
     */
    dispatch_type: DispatchType;
    /**
     *  Create a new instance of this contract.
     * 
     *  Factory function called by host to create instances.
     *  Returns null handle on failure.
     * 
     *  # Arguments
     *  - `host`: HostInterface pointer (for memory allocation via host->alloc)
     *  - `args`: Optional initialization arguments (contract-specific)
     * 
     *  # Returns
     *  Opaque instance handle, or null handle on failure.
     * 
     *  # Thread Safety
     *  May be called from any thread. Implementation must handle synchronization.
     */
    create_instance: number;
    /**
     *  Destroy an instance of this contract.
     * 
     *  MUST be called before hot-reload for all instances.
     *  Failure to destroy instances causes memory leaks.
     * 
     *  # Arguments
     *  - `host`: HostInterface pointer
     *  - `instance`: Instance handle to destroy
     * 
     *  # Safety
     *  After calling destroy_instance, the instance handle is invalid.
     */
    destroy_instance: number;
    /**
     *  Union of dispatch mechanisms — access based on dispatch_type.
     * 
     *  For Native dispatch: use `dispatch.native.functions[fn_id]`.
     *  For VM dispatch: use `dispatch.vm.call(loader_data, instance, fn_id, args, out)`.
     */
    dispatch: DispatchMechanisms;
}

export const GUEST_CONTRACT_INTERFACE_CONTRACT_ID_OFFSET: number = 0;
export const GUEST_CONTRACT_INTERFACE_CONTRACT_VERSION_OFFSET: number = 8;
export const GUEST_CONTRACT_INTERFACE_DISPATCH_TYPE_OFFSET: number = 16;
export const GUEST_CONTRACT_INTERFACE_CREATE_INSTANCE_OFFSET: number = 24;
export const GUEST_CONTRACT_INTERFACE_DESTROY_INSTANCE_OFFSET: number = 32;
export const GUEST_CONTRACT_INTERFACE_DISPATCH_OFFSET: number = 40;
export const GUEST_CONTRACT_INTERFACE_SIZE: number = 56;

/**
 *  Host Interface — function table passed to guests during initialization.
 * 
 *  Contains an opaque runtime pointer and function pointers for guest calls.
 *  All functions use self-passing pattern (receive HostInterface pointer as first parameter).
 * 
 *  # Who provides
 *  The runtime creates this struct and passes it to `polyplug_init()`.
 *  The struct is allocated using `Box::leak()` for `'static` lifetime.
 * 
 *  # Who calls
 *  Guest (plugin) code calls these functions to interact with the runtime.
 *  SDK-generated wrappers handle the self-passing pattern automatically.
 * 
 *  # Ownership
 *  The struct is statically allocated by the runtime. The pointer is valid
 *  until the runtime is destroyed. Guest must NOT free this pointer.
 * 
 *  # Lifetime
 *  Lives as long as the runtime that created it.
 * 
 *  # Thread Safety
 *  All functions are safe to call from any thread. The runtime uses
 *  internal synchronization (RwLock/Mutex) for shared state.
 * 
 *  # Self-passing pattern
 *  Each function receives the interface pointer as its first parameter,
 *  allowing guests to call: `host->find_by_contract(host, id, ver)`
 *  SDKs hide this pattern: `host.find_by_contract(id, ver)`
 */
export interface HostInterface {
    /**
     *  Opaque pointer to Runtime.
     * 
     *  Set during interface creation. Provides access to runtime state
     *  for dependency enforcement and resource management.
     * 
     *  # Ownership
     *  Owned by the runtime. Guests must NOT free or modify this pointer.
     */
    runtime: bigint;
    /**
     *  Register a guest contract implementation.
     * 
     *  Called by plugins during `polyplug_init()` to register their contracts.
     *  Returns error if contract_id collision detected or ABI version mismatch.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     *  - `descriptor`: Plugin descriptor with contract metadata
     *  - `interface`: GuestContractInterface to register
     * 
     *  # Returns
     *  AbiError::OK on success, error code on failure.
     */
    register_contract: number;
    /**
     *  Allocate memory using the host allocator.
     * 
     *  Memory allocated here must be freed via `free`.
     *  Returns null on allocation failure.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     *  - `size`: Number of bytes to allocate
     *  - `align`: Alignment requirement (must be power of 2)
     * 
     *  # Returns
     *  Pointer to allocated memory, or null on failure.
     */
    alloc: number;
    /**
     *  Free memory allocated via `alloc`.
     * 
     *  Must pass the same size and align used for allocation.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     *  - `ptr`: Pointer to memory to free
     *  - `size`: Size used for allocation
     *  - `align`: Alignment used for allocation
     */
    free: number;
    /**
     *  Find a guest contract by contract_id and minimum version.
     * 
     *  Returns a GuestContractHandle that can be resolved to an interface.
     *  Returns null handle if no matching contract found.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     *  - `contract_id`: Contract identifier hash
     *  - `min_version`: Minimum version required
     * 
     *  # Returns
     *  GuestContractHandle for the first matching contract, or null handle.
     */
    find_guest_contract: number;
    /**
     *  Find all guest contracts matching contract_id and minimum version.
     * 
     *  Returns an Array of GuestContractHandle. Caller must free via `host->free`.
     *  Use when multiple implementations of the same contract may exist.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     *  - `contract_id`: Contract identifier hash
     *  - `min_version`: Minimum version required
     * 
     *  # Returns
     *  Array of GuestContractHandle. Caller owns and must free.
     */
    find_all_guest_contracts: number;
    /**
     *  Resolve a GuestContractHandle to a GuestContractInterface pointer.
     * 
     *  Returns null if the handle is invalid or contract was unloaded.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     *  - `handle`: GuestContractHandle from find_guest_contract
     * 
     *  # Returns
     *  Pointer to GuestContractInterface, or null if invalid/stale.
     */
    resolve_guest_contract: number;
    /**
     *  Call a method on a guest contract instance.
     * 
     *  This is the cross-dispatch mechanism for calling methods across
     *  different dispatch types (Native vs VM).
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     *  - `instance`: GuestContractInstance with contract_id for dispatch
     *  - `method_id`: Method index within the contract
     *  - `args`: Pointer to packed arguments (contract-specific layout)
     *  - `out`: Pointer to output buffer for return value
     * 
     *  # Returns
     *  AbiError::OK on success, error code on failure.
     */
    call_guest_method: number;
    /**
     *  Get a host contract instance by contract_id and minimum version.
     * 
     *  For singleton host contracts, returns the same instance every time.
     *  For multi-instance host contracts, returns a new instance each time.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     *  - `contract_id`: Host contract identifier hash
     *  - `min_version`: Minimum version required
     * 
     *  # Returns
     *  HostContractInstance for the contract.
     */
    get_host_contract: number;
    /**
     *  Resolve a host contract interface by contract_id and minimum version.
     * 
     *  Returns the HostContractInterface pointer for the contract.
     *  This is needed to access dispatch metadata (dispatch_type, function_count, functions).
     *  Returns null if no matching contract found.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     *  - `contract_id`: Host contract identifier hash
     *  - `min_version`: Minimum version required
     * 
     *  # Returns
     *  Pointer to HostContractInterface, or null if invalid/not found.
     */
    resolve_host_contract_interface: number;
    /**
     *  List all loaded bundles.
     * 
     *  Returns an Array of BundleId. Caller must free via `host->free`.
     *  Bundle IDs are stable for the lifetime of the runtime.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     * 
     *  # Returns
     *  Array of BundleId. Caller owns and must free.
     */
    list_bundles: number;
    /**
     *  Get dependencies for the calling bundle.
     * 
     *  Uses bundle_id from current BundleInitContext (TLS) to look up declared deps.
     *  Returns an Array of DependencyInfo. Caller must free via `host->free`.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     * 
     *  # Returns
     *  Array of DependencyInfo. Caller owns and must free.
     *  Returns empty array if called outside bundle init context.
     */
    get_dependencies: number;
    /**
     *  Load a plugin bundle from a path.
     * 
     *  Host applications call this to load a bundle at runtime.
     *  The loader matching the bundle's runtime type is used.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     *  - `path`: UTF-8 path to bundle directory (not null-terminated)
     *  - `path_len`: Length of path in bytes
     * 
     *  # Returns
     *  AbiError::OK on success, error code on failure.
     */
    load_bundle: number;
    /**
     *  Reload a plugin bundle (hot-reload).
     * 
     *  Replaces the bundle's contracts with new versions from the updated binary.
     *  All instances must be destroyed before calling this.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     *  - `path`: UTF-8 path to bundle directory (not null-terminated)
     *  - `path_len`: Length of path in bytes
     * 
     *  # Returns
     *  AbiError::OK on success, error code on failure.
     */
    reload_bundle: number;
    /**
     *  Register a host contract interface.
     * 
     *  Host applications register their contracts for plugins to consume.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     *  - `interface`: HostContractInterface to register
     * 
     *  # Returns
     *  AbiError::OK on success, error code on failure.
     */
    register_host_contract: number;
    /**
     *  Register a language loader.
     * 
     *  Host applications register loaders for each runtime language they support.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     *  - `runtime_name`: Name of the runtime (e.g., "rust", "python")
     *  - `loader_ptr`: Opaque pointer to the loader implementation
     * 
     *  # Returns
     *  AbiError::OK on success, error code on failure.
     */
    register_loader: number;
    /**
     *  Get last error message.
     * 
     *  Returns the most recent error message from this runtime.
     *  Copies up to buf_len bytes into buf.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     *  - `buf`: Buffer to write error message into
     *  - `buf_len`: Maximum bytes to write
     * 
     *  # Returns
     *  Number of bytes written (0 if no error or buffer too small).
     */
    get_last_error: number;
    /**
     *  Get last error message length.
     * 
     *  Returns the byte length of the most recent error message.
     *  Use to allocate buffer before calling get_last_error.
     * 
     *  # Arguments
     *  - `this`: HostInterface pointer (self-passing)
     * 
     *  # Returns
     *  Length of last error message (0 if no error).
     */
    get_error_len: number;
}

export const HOST_INTERFACE_RUNTIME_OFFSET: number = 0;
export const HOST_INTERFACE_REGISTER_CONTRACT_OFFSET: number = 8;
export const HOST_INTERFACE_ALLOC_OFFSET: number = 16;
export const HOST_INTERFACE_FREE_OFFSET: number = 24;
export const HOST_INTERFACE_FIND_GUEST_CONTRACT_OFFSET: number = 32;
export const HOST_INTERFACE_FIND_ALL_GUEST_CONTRACTS_OFFSET: number = 40;
export const HOST_INTERFACE_RESOLVE_GUEST_CONTRACT_OFFSET: number = 48;
export const HOST_INTERFACE_CALL_GUEST_METHOD_OFFSET: number = 56;
export const HOST_INTERFACE_GET_HOST_CONTRACT_OFFSET: number = 64;
export const HOST_INTERFACE_RESOLVE_HOST_CONTRACT_INTERFACE_OFFSET: number = 72;
export const HOST_INTERFACE_LIST_BUNDLES_OFFSET: number = 80;
export const HOST_INTERFACE_GET_DEPENDENCIES_OFFSET: number = 88;
export const HOST_INTERFACE_LOAD_BUNDLE_OFFSET: number = 96;
export const HOST_INTERFACE_RELOAD_BUNDLE_OFFSET: number = 104;
export const HOST_INTERFACE_REGISTER_HOST_CONTRACT_OFFSET: number = 112;
export const HOST_INTERFACE_REGISTER_LOADER_OFFSET: number = 120;
export const HOST_INTERFACE_GET_LAST_ERROR_OFFSET: number = 128;
export const HOST_INTERFACE_GET_ERROR_LEN_OFFSET: number = 136;
export const HOST_INTERFACE_SIZE: number = 144;

/**
 *  Runtime Interface — function table returned to host from polyplug_runtime_create().
 * 
 *  Contains an opaque runtime pointer and function pointers for host calls.
 *  All functions take `*const RuntimeInterface` as first parameter.
 * 
 *  # Who provides
 *  The runtime creates this struct and returns it from `polyplug_runtime_create()`.
 *  The struct is heap-allocated and owned by the host.
 * 
 *  # Who calls
 *  Host application code calls these functions to interact with the runtime.
 *  SDK-generated wrappers handle the self-passing pattern automatically.
 * 
 *  # Ownership
 *  The struct is allocated by `polyplug_runtime_create()`. The host owns
 *  the pointer and must call `destroy()` to free the runtime and interface.
 * 
 *  # Lifetime
 *  Lives until `destroy()` is called. After destroy, the pointer is invalid.
 * 
 *  # Thread Safety
 *  All functions are safe to call from any thread. The runtime uses
 *  internal synchronization for shared state.
 * 
 *  # Self-passing pattern
 *  Each function receives the interface pointer as its first parameter,
 *  allowing hosts to call: `rt->load_bundle(rt, path)`
 *  SDKs hide this pattern: `rt.load_bundle(path)`
 */
export interface RuntimeInterface {
    /**
     *  Opaque pointer to Runtime.
     * 
     *  Set during interface creation. Provides access to runtime state.
     * 
     *  # Ownership
     *  Owned by the runtime. Host must call `destroy()` to free.
     */
    runtime: bigint;
    /**
     *  Load a plugin bundle from the given path.
     * 
     *  Loads the bundle and initializes all its guest contracts.
     *  Dependencies are resolved in topological order.
     * 
     *  # Arguments
     *  - `this`: RuntimeInterface pointer (self-passing)
     *  - `path`: Path to the bundle directory or manifest file
     * 
     *  # Returns
     *  AbiError::OK on success, error code on failure.
     *  Use `get_last_error()` for detailed error message.
     */
    load_bundle: number;
    /**
     *  Reload a bundle (hot-reload).
     * 
     *  Triggers hot-reload of the specified bundle. The runtime will:
     *  1. Call pre-reload callbacks to notify hosts
     *  2. Wait for all instances to be destroyed
     *  3. Unload the old bundle
     *  4. Load the new bundle
     *  5. Call post-reload callbacks
     * 
     *  # Arguments
     *  - `this`: RuntimeInterface pointer (self-passing)
     *  - `bundle_id`: ID of the bundle to reload
     * 
     *  # Returns
     *  AbiError::OK on success, error code on failure.
     */
    reload_bundle: number;
    /**
     *  Unload a bundle.
     * 
     *  Removes the bundle and all its guest contracts from the registry.
     *  Host must destroy all instances before unloading.
     * 
     *  # Arguments
     *  - `this`: RuntimeInterface pointer (self-passing)
     *  - `bundle_id`: ID of the bundle to unload
     * 
     *  # Returns
     *  AbiError::OK on success, error code on failure.
     */
    unload_bundle: number;
    /**
     *  Find a guest contract by contract_id and minimum version.
     * 
     *  Returns a GuestContractHandle that can be resolved to an interface.
     *  Returns null handle if no matching contract found.
     * 
     *  # Arguments
     *  - `this`: RuntimeInterface pointer (self-passing)
     *  - `contract_id`: Contract identifier hash
     *  - `min_version`: Minimum version required
     * 
     *  # Returns
     *  GuestContractHandle for the first matching contract, or null handle.
     */
    find_by_contract: number;
    /**
     *  Find all guest contracts matching contract_id and minimum version.
     * 
     *  Returns an Array of GuestContractHandle. Caller must free via host->free.
     *  Use when multiple implementations of the same contract may exist.
     * 
     *  # Arguments
     *  - `this`: RuntimeInterface pointer (self-passing)
     *  - `contract_id`: Contract identifier hash
     *  - `min_version`: Minimum version required
     * 
     *  # Returns
     *  Array of GuestContractHandle. Caller owns and must free.
     */
    find_all_by_contract: number;
    /**
     *  Resolve a GuestContractHandle to a GuestContractInterface pointer.
     * 
     *  Returns null if the handle is invalid or contract was unloaded.
     * 
     *  # Arguments
     *  - `this`: RuntimeInterface pointer (self-passing)
     *  - `handle`: GuestContractHandle from find_by_contract
     * 
     *  # Returns
     *  Pointer to GuestContractInterface, or null if invalid/stale.
     */
    resolve_contract: number;
    /**
     *  Get a host contract instance by contract_id and minimum version.
     * 
     *  For singleton host contracts, returns the same instance every time.
     *  For multi-instance host contracts, returns a new instance each time.
     * 
     *  # Arguments
     *  - `this`: RuntimeInterface pointer (self-passing)
     *  - `contract_id`: Host contract identifier hash
     *  - `min_version`: Minimum version required
     * 
     *  # Returns
     *  HostContractInstance for the contract.
     */
    get_host_contract: number;
    /**
     *  Get the last error message.
     * 
     *  Returns detailed error message for the most recent failed operation.
     *  Message is valid until the next operation is performed.
     * 
     *  # Arguments
     *  - `this`: RuntimeInterface pointer (self-passing)
     * 
     *  # Returns
     *  StringView containing the error message, or empty string if no error.
     */
    get_last_error: number;
    /**
     *  List all loaded bundles.
     * 
     *  Returns an Array of BundleId. Caller must free via host->free.
     *  Bundle IDs are stable for the lifetime of the runtime.
     * 
     *  # Arguments
     *  - `this`: RuntimeInterface pointer (self-passing)
     * 
     *  # Returns
     *  Array of BundleId. Caller owns and must free.
     */
    list_bundles: number;
    /**
     *  Get dependencies (returns empty array for host context).
     * 
     *  Hosts have no bundle dependencies, so this returns an empty array.
     *  Guests use HostInterface::get_dependencies for their actual deps.
     * 
     *  # Arguments
     *  - `this`: RuntimeInterface pointer (self-passing)
     * 
     *  # Returns
     *  Empty Array of DependencyInfo. Caller owns and must free.
     */
    get_dependencies: number;
    /**
     *  Destroy the runtime and free this interface.
     * 
     *  # Arguments
     *  - `this`: RuntimeInterface pointer (self-passing)
     * 
     *  # Safety
     *  After calling destroy, the pointer is invalid and must not be used.
     *  All instances must be destroyed before calling this.
     */
    destroy: number;
}

export const RUNTIME_INTERFACE_RUNTIME_OFFSET: number = 0;
export const RUNTIME_INTERFACE_LOAD_BUNDLE_OFFSET: number = 8;
export const RUNTIME_INTERFACE_RELOAD_BUNDLE_OFFSET: number = 16;
export const RUNTIME_INTERFACE_UNLOAD_BUNDLE_OFFSET: number = 24;
export const RUNTIME_INTERFACE_FIND_BY_CONTRACT_OFFSET: number = 32;
export const RUNTIME_INTERFACE_FIND_ALL_BY_CONTRACT_OFFSET: number = 40;
export const RUNTIME_INTERFACE_RESOLVE_CONTRACT_OFFSET: number = 48;
export const RUNTIME_INTERFACE_GET_HOST_CONTRACT_OFFSET: number = 56;
export const RUNTIME_INTERFACE_GET_LAST_ERROR_OFFSET: number = 64;
export const RUNTIME_INTERFACE_LIST_BUNDLES_OFFSET: number = 72;
export const RUNTIME_INTERFACE_GET_DEPENDENCIES_OFFSET: number = 80;
export const RUNTIME_INTERFACE_DESTROY_OFFSET: number = 88;
export const RUNTIME_INTERFACE_SIZE: number = 96;

/**
 *  Opaque handle to a host contract instance.
 * 
 *  Created by `HostContractInterface::create_instance`, destroyed by `destroy_instance`.
 *  For singleton host contracts, the same instance is returned for all callers.
 */
export interface HostContractInstance {
    /**
     *  Opaque instance data pointer.
     *  The actual data is owned by the host.
     */
    data: bigint;
}

export const HOST_CONTRACT_INSTANCE_DATA_OFFSET: number = 0;
export const HOST_CONTRACT_INSTANCE_SIZE: number = 8;

/**
 *  Host Contract Interface — for host-provided services.
 * 
 *  Host contracts are services provided by the host application to plugins.
 * 
 *  # Who provides
 *  Host application code creates this struct and registers it with the runtime.
 *  Must be `'static` or intentionally leaked.
 * 
 *  # Who calls
 *  Guest (plugin) code calls the dispatch functions after obtaining an instance
 *  via `HostInterface::get_host_contract()`.
 * 
 *  # Ownership
 *  Must be `'static`. The runtime holds a reference for the plugin lifetime.
 *  Never freed while runtime lives.
 * 
 *  # Lifetime
 *  Lives for the entire runtime lifetime. Must survive hot-reload.
 * 
 *  # Singleton Mode
 *  - `singleton == true`: Same instance returned for all callers
 *  - `singleton == false`: New instance per caller (caller must destroy)
 * 
 *  # Self-Passing Pattern
 *  `create_instance` and `destroy_instance` take `self: *const HostContractInterface`.
 *  The runtime field provides access to runtime services.
 */
export interface HostContractInterface {
    /**
     *  FNV-1a hash of "host_contract:name@major_version".
     * 
     *  Generated by polyplugc from contract name and major version.
     *  Used for contract lookup via `get_host_contract`.
     */
    contract_id: HostContractId;
    /**
     *  Contract version (major, minor, patch).
     * 
     *  Used for version compatibility checks during lookup.
     */
    contract_version: Version;
    /**
     *  Whether this contract provides a singleton instance.
     * 
     *  If true, `get_host_contract` returns the same instance for all callers.
     *  If false, each call returns a new instance that caller must destroy.
     */
    singleton: boolean;
    /**
     *  Dispatch mechanism type (Native or VirtualMachine).
     * 
     *  Host contracts typically use Native dispatch for direct calls.
     */
    dispatch_type: DispatchType;
    /**
     *  Opaque pointer to Runtime.
     * 
     *  Host contracts can use this for runtime-specific operations.
     *  Set during interface registration.
     * 
     *  # Ownership
     *  Owned by the runtime. Host contract implementations must not free.
     */
    runtime: bigint;
    /**
     *  Create a new instance of this host contract.
     * 
     *  For singleton contracts, this is typically called once and the instance
     *  is cached. For multi-instance contracts, called for each get_host_contract.
     * 
     *  # Arguments
     *  - `this`: HostContractInterface pointer (self-passing pattern)
     *  - `args`: Optional initialization arguments (contract-specific)
     * 
     *  # Returns
     *  Opaque instance handle, or null handle on failure.
     */
    create_instance: number;
    /**
     *  Destroy an instance of this host contract.
     * 
     *  For singleton contracts, this is typically a no-op (singleton lives forever).
     *  For multi-instance contracts, caller must destroy after use.
     * 
     *  # Arguments
     *  - `this`: HostContractInterface pointer (self-passing pattern)
     *  - `instance`: Instance handle to destroy
     * 
     *  # Safety
     *  After calling destroy_instance, the instance handle is invalid.
     */
    destroy_instance: number;
    /**
     *  Union of dispatch mechanisms — access based on dispatch_type.
     * 
     *  For Native dispatch: use `dispatch.native.functions[fn_id]`.
     *  For VM dispatch: use `dispatch.vm.call(loader_data, instance, fn_id, args, out)`.
     */
    dispatch: DispatchMechanisms;
}

export const HOST_CONTRACT_INTERFACE_CONTRACT_ID_OFFSET: number = 0;
export const HOST_CONTRACT_INTERFACE_CONTRACT_VERSION_OFFSET: number = 8;
export const HOST_CONTRACT_INTERFACE_SINGLETON_OFFSET: number = 16;
export const HOST_CONTRACT_INTERFACE_DISPATCH_TYPE_OFFSET: number = 24;
export const HOST_CONTRACT_INTERFACE_RUNTIME_OFFSET: number = 32;
export const HOST_CONTRACT_INTERFACE_CREATE_INSTANCE_OFFSET: number = 40;
export const HOST_CONTRACT_INTERFACE_DESTROY_INSTANCE_OFFSET: number = 48;
export const HOST_CONTRACT_INTERFACE_DISPATCH_OFFSET: number = 56;
export const HOST_CONTRACT_INTERFACE_SIZE: number = 72;

/**
 *  Context passed to every guest `polyplug_init()` function.
 * 
 *  # OWNERSHIP
 *  The `bundle_path` pointer is runtime-owned and valid for the lifetime of the `PluginRuntime`.
 *  **Plugin must not store the raw pointer** — copy the string value if persistence is needed.
 */
export interface BundleInitContext {
    /**  Bundle ID for dependency enforcement during init. */
    bundle_id: bigint;
    /**  Absolute canonical path to the directory containing the loaded bundle. */
    bundle_path: StringView;
}

export const BUNDLE_INIT_CONTEXT_BUNDLE_ID_OFFSET: number = 0;
export const BUNDLE_INIT_CONTEXT_BUNDLE_PATH_OFFSET: number = 8;
export const BUNDLE_INIT_CONTEXT_SIZE: number = 24;

/**
 *  Metadata about a plugin within a bundle.
 * 
 *  # OWNERSHIP
 *  value type passed by pointer during init. The `name` and
 *  `contract_name` StringViews are borrowed from the plugin's static memory.
 *  The receiver must not free or outlive the plugin's library.
 */
export interface PluginDescriptor {
    /**  Human-readable plugin name. */
    name: StringView;
    /**  Full contract name for collision detection. */
    contract_name: StringView;
    /**  Plugin version */
    version: Version;
}

export const PLUGIN_DESCRIPTOR_NAME_OFFSET: number = 0;
export const PLUGIN_DESCRIPTOR_CONTRACT_NAME_OFFSET: number = 8;
export const PLUGIN_DESCRIPTOR_VERSION_OFFSET: number = 16;
export const PLUGIN_DESCRIPTOR_SIZE: number = 48;

/**
 *  Opaque handle to a registered guest contract.
 * 
 *  The handle is just an index into the registry array.
 *  Out-of-bounds indices return InvalidHandle error.
 * 
 *  # Naming
 *  Named `GuestContractHandle` for consistency with `GuestContractInterface`
 *  and `GuestContractInstance`.
 * 
 *  # Layout
 *  - `index`: Slot index in the registry (u32)
 * 
 *  # Safety
 *  Handles become stale after unload. Call `resolve_contract` to validate.
 *  Returns null pointer if the handle is invalid.
 */
export interface GuestContractHandle {
    /**  Slot in the registry array. */
    index: number;
}

export const GUEST_CONTRACT_HANDLE_INDEX_OFFSET: number = 0;
export const GUEST_CONTRACT_HANDLE_SIZE: number = 4;

/**
 *  Configuration for the polyplug runtime passed to `polyplug_runtime_create`.
 * 
 *  # OWNERSHIP
 *  Borrowed for the duration of the runtime build only.
 *  The runtime copies any data it needs to retain.
 */
export interface RuntimeConfig {
    /**  Compatibility mode for version resolution. */
    compatibility: Compatibility;
    /**  Whether hot-reload is enabled. */
    hot_reload_enabled: boolean;
    /**  Optional hot-reload callback, or null for no callback. */
    on_reload: number;
}

export const RUNTIME_CONFIG_COMPATIBILITY_OFFSET: number = 0;
export const RUNTIME_CONFIG_HOT_RELOAD_ENABLED_OFFSET: number = 8;
export const RUNTIME_CONFIG_ON_RELOAD_OFFSET: number = 16;
export const RUNTIME_CONFIG_SIZE: number = 16;

/**
 *  FFI-safe reload phase for hot-reload callbacks.
 * 
 *  Tagged union style struct — `phase_type` indicates which variant is active.
 *  Uses `StringView` for FFI compatibility (non-owning borrows).
 * 
 *  # Lifetime
 *  `StringView` fields are borrowed from the caller's strings.
 *  The callback must not store these views beyond the callback scope.
 */
export interface ReloadPhase {
    /**  Type of reload phase. */
    phase_type: ReloadPhaseType;
    /**  Bundle being reloaded. */
    bundle_id: BundleId;
    /**  Bundle name (borrowed string). */
    bundle_name: StringView;
    /**  Failure reason (only for Failed phase). */
    reason: StringView;
}

export const RELOAD_PHASE_PHASE_TYPE_OFFSET: number = 0;
export const RELOAD_PHASE_BUNDLE_ID_OFFSET: number = 8;
export const RELOAD_PHASE_BUNDLE_NAME_OFFSET: number = 16;
export const RELOAD_PHASE_REASON_OFFSET: number = 24;
export const RELOAD_PHASE_SIZE: number = 48;

/**
 *  ABI error — returned by value from all ABI calls.
 * 
 *  OWNERSHIP: `code` is a value type. `message.ptr` is allocated by the callee
 *  via `host_alloc`. Caller frees with `polyplug_host_free(message.ptr, message.len, 1)`
 *  after reading. If `code == AbiErrorCode::Ok`, `message.ptr` is NULL — no free needed.
 */
export interface AbiError {
    /**  0 = success, non-zero = error. */
    code: AbiErrorCode;
    /**  Empty/NULL if success. UTF-8 message if non-zero code. */
    message: StringView;
}

export const ABI_ERROR_CODE_OFFSET: number = 0;
export const ABI_ERROR_MESSAGE_OFFSET: number = 8;
export const ABI_ERROR_SIZE: number = 24;

/**
 *  FFI-safe array with caller-frees ownership model.
 * 
 *  # Memory Management
 *  - Allocated via `host->alloc(self, len * sizeof(T), align)`
 *  - Freed via `host->free(self, items, len * sizeof(T), align)`
 * 
 *  # Ownership
 *  Caller owns the memory and must free via host allocator.
 *  CodeGen generates RAII wrappers in each language SDK:
 *  - Rust: `Drop` impl calls `host->free`
 *  - Python: `__del__` calls free
 *  - C#: `IDisposable.Dispose` calls free
 * 
 *  # Safety
 *  The `align` field is required for proper freeing. Generic code must
 *  track alignment of `T` to free correctly.
 * 
 *  # Thread Safety
 *  Safe to read from multiple threads if underlying data is immutable.
 *  Send/Sync implemented for T: Send/Sync.
 */
export interface Array {
    /**
     *  Pointer to elements, allocated via host allocator.
     * 
     *  # Ownership
     *  Caller owns. Must be freed via `host->free` with same size/align.
     */
    items: bigint;
    /**
     *  Number of elements.
     * 
     *  Used to calculate total size for freeing: `len * sizeof(T)`.
     */
    len: number;
    /**
     *  Alignment of T, for proper freeing.
     * 
     *  # Purpose
     *  Required because generic code may not know T's alignment at runtime.
     *  Must match `align_of::<T>()` used during allocation.
     */
    align: number;
}

export const ARRAY_ITEMS_OFFSET: number = 0;
export const ARRAY_LEN_OFFSET: number = 8;
export const ARRAY_ALIGN_OFFSET: number = 16;
export const ARRAY_SIZE: number = 24;

/**
 *  Owning byte buffer.
 * 
 *  OWNERSHIP: `ptr` is always allocated via `polyplug_host_alloc`.
 *  Owner calls `polyplug_host_free(ptr, cap, align)` when done.
 */
export interface Buffer {
    ptr: bigint;
    /**  Bytes currently used. */
    len: number;
    /**  Bytes allocated. */
    cap: number;
}

export const BUFFER_PTR_OFFSET: number = 0;
export const BUFFER_LEN_OFFSET: number = 8;
export const BUFFER_CAP_OFFSET: number = 16;
export const BUFFER_SIZE: number = 24;

/**
 *  Dependency information returned by get_dependencies introspection API.
 * 
 *  Mirrors `manifest.toml` `\[dependency\]` table structure for plugins to query
 *  their own declared dependencies at runtime.
 * 
 *  # Who provides
 *  Runtime returns this from `HostInterface::get_dependencies`.
 * 
 *  # Who calls
 *  Guest (plugin) code calls `get_dependencies` during initialization
 *  to discover available dependencies.
 * 
 *  # Ownership
 *  Returned in an Array that caller owns and must free via `host->free`.
 * 
 *  # Fields
 *  - `contract_id`: The contract being depended upon
 *  - `min_version`: Minimum version required
 *  - `bundle_id`: Specific bundle if ByBundle, 0 if ByContract
 */
export interface DependencyInfo {
    /**
     *  Contract ID of the dependency.
     * 
     *  FNV-1a hash of the contract name and major version.
     *  Use this to find matching contracts via `find_by_contract`.
     */
    contract_id: GuestContractId;
    /**
     *  Minimum version required.
     * 
     *  Used for version compatibility checks during contract lookup.
     *  Contracts with version >= min_version will match.
     */
    min_version: number;
    /**
     *  Bundle ID if dependency is ByBundle, 0 if ByContract.
     * 
     *  # ByBundle vs ByContract
     *  - `bundle_id != 0`: Dependency is on a specific bundle
     *  - `bundle_id == 0`: Dependency is on any bundle providing the contract
     */
    bundle_id: BundleId;
}

export const DEPENDENCY_INFO_CONTRACT_ID_OFFSET: number = 0;
export const DEPENDENCY_INFO_MIN_VERSION_OFFSET: number = 8;
export const DEPENDENCY_INFO_BUNDLE_ID_OFFSET: number = 16;
export const DEPENDENCY_INFO_SIZE: number = 24;

/**
 *  Non-owning UTF-8 string view.
 * 
 *  OWNERSHIP: borrowed reference. `ptr` must remain valid for the duration
 *  of the call. Never freed by the receiver.
 */
export interface StringView {
    /**  UTF-8 bytes, NOT null-terminated. */
    ptr: bigint;
    /**  Byte count. */
    len: number;
}

export const STRING_VIEW_PTR_OFFSET: number = 0;
export const STRING_VIEW_LEN_OFFSET: number = 8;
export const STRING_VIEW_SIZE: number = 16;

/**  A three-component semantic version (major.minor.patch). */
export interface Version {
    /**  Major version. */
    major: number;
    /**  Minor version. */
    minor: number;
    /**  Patch version. */
    patch: number;
}

export const VERSION_MAJOR_OFFSET: number = 0;
export const VERSION_MINOR_OFFSET: number = 4;
export const VERSION_PATCH_OFFSET: number = 8;
export const VERSION_SIZE: number = 12;

export const enum ContractType {
    Host = 0,
    Plugin = 1,
}

/**  Dispatch mechanism type — determines how function calls are routed. */
export const enum DispatchType {
    /**  Native dispatch: direct function pointer calls (zero overhead). */
    Native = 0,
    /**  VM dispatch: call through a dispatch function with loader_data. */
    VirtualMachine = 1,
}

/**  How strictly version compatibility is enforced when resolving plugins. */
export const enum Compatibility {
    /**  Exact major match and minor >= required. */
    Strict = 0,
    /**  Same major, any minor. */
    Relaxed = 1,
    /**  Any version accepted. */
    Yolo = 2,
}

/**  Type of reload phase for FFI callbacks. */
export const enum ReloadPhaseType {
    /**  Bundle is being prepared for reload. */
    Preparing = 0,
    /**  Bundle has been successfully reloaded. */
    Reloaded = 1,
    /**  Bundle reload failed. */
    Failed = 2,
}

/**  Runtime type identifier — identifies the language/runtime hosting plugins. */
export const enum RuntimeLanguage {
    Rust = 0,
    Cpp = 1,
    Dotnet = 2,
    Python = 3,
    Lua = 4,
    JavaScript = 5,
}

/**
 *  ABI error codes (reserved: 0-255 runtime, 256+ plugin-defined).
 * 
 *  These codes are returned by all ABI functions to indicate success or failure.
 *  The `code` field of `AbiError` uses these values.
 */
export const enum AbiErrorCode {
    /**  Success — no error. */
    Ok = 0,
    /**  Generic error — unspecified failure. */
    Generic = 1,
    /**  Buffer too small — caller must reallocate (see Buffer protocol). */
    BufferTooSmall = 2,
    /**  Panic — plugin panicked (caught by catch_unwind). */
    Panic = 3,
    /**  Not found — plugin/contract not found. */
    NotFound = 4,
    /**  Stale handle — GuestContractHandle is invalid (contract unloaded). */
    StaleHandle = 5,
    /**  Function not available — function_id >= function_count. */
    FunctionNotAvailable = 6,
    /**  Duplicate provider — same bundle already provides this contract. */
    DuplicateProvider = 7,
    /**  Invalid pointer — null or invalid pointer passed to ABI function. */
    InvalidPointer = 8,
    /**  Host contract not found — no host contract matches contract_id. */
    HostContractNotFound = 100,
    /**  Host contract version mismatch — host contract version does not match. */
    HostContractVersionMismatch = 101,
    /**  Host contract call failed — host contract function call failed. */
    HostContractCallFailed = 102,
}

export const enum ParseVersionError {
    InvalidFormat = 0,
    InvalidInt = 1,
}

/**
 *  Union of dispatch mechanisms — use based on `dispatch_type`.
 * 
 *  # Safety
 *  Access the correct variant based on `GuestContractInterface::dispatch_type`:
 *  - `dispatch_type == Native` → access `.native`
 *  - `dispatch_type == VirtualMachine` → access `.vm`
 */
export type DispatchMechanisms =
    | { native: NativeDispatch }
    | { vm: VmDispatch }
;

export const POLYPLUG_ABI_VERSION: number = 1;


// ─── Helper Methods (preserved from helper files) ───

/**
 * StringView helper functions for the polyplug plugin runtime.
 * @module polyplug_abi/string_view_helper
 */


/**
 * Convert a StringView to a JavaScript string.
 * @param sv - The StringView to convert.
 * @returns The JavaScript string, or empty string if null/empty.
 */
export function stringViewToString(sv: StringView | null | undefined): string {
    if (!sv || sv.ptr === 0n || sv.len === 0) return '';
    // Note: Actual implementation requires FFI access to read memory.
    // This is a placeholder - the host/guest libraries provide actual implementation.
    return '';
}

/**
 * Strip a prefix from a string.
 * @param sv - The input StringView or string.
 * @param prefix - The prefix to strip.
 * @returns The string without prefix, or original if prefix not present.
 */
export function stripPrefix(sv: StringView | string, prefix: string): string {
    const s: string = typeof sv === 'string' ? sv : stringViewToString(sv);
    if (s.startsWith(prefix)) {
        return s.slice(prefix.length);
    }
    return s;
}

/**
 * Check if a string starts with a prefix.
 * @param sv - The input StringView or string.
 * @param prefix - The prefix to check.
 * @returns True if the string starts with the prefix.
 */
export function startsWith(sv: StringView | string, prefix: string): boolean {
    const s: string = typeof sv === 'string' ? sv : stringViewToString(sv);
    return s.startsWith(prefix);
}

/**
 * Check if a string ends with a suffix.
 * @param sv - The input StringView or string.
 * @param suffix - The suffix to check.
 * @returns True if the string ends with the suffix.
 */
export function endsWith(sv: StringView | string, suffix: string): boolean {
    const s: string = typeof sv === 'string' ? sv : stringViewToString(sv);
    return s.endsWith(suffix);
}

/**
 * Convert a StringView to a JavaScript string (shorthand alias).
 * @param sv - The StringView to convert.
 * @returns The JavaScript string, or empty string if null/empty.
 */
export function toStr(sv: StringView | null | undefined): string {
    return stringViewToString(sv);
}

/**
 * Split a string by a delimiter.
 * @param sv - The input StringView or string.
 * @param delimiter - The delimiter to split by.
 * @returns An array of strings.
 */
export function split(sv: StringView | string, delimiter: string): string[] {
    const s: string = typeof sv === 'string' ? sv : stringViewToString(sv);
    return s.split(delimiter);
}

