// Layout tests for polyplug ABI structs.
// AUTO-GENERATED by polyplug_abi build script — do not edit.

import {
    NATIVE_DISPATCH_SIZE,
    VM_DISPATCH_SIZE,
    VM_LOADER_DATA_SIZE,
    GUEST_CONTRACT_INSTANCE_SIZE,
    GUEST_CONTRACT_INTERFACE_SIZE,
    HOST_API_SIZE,
    HOST_CONTRACT_INSTANCE_SIZE,
    HOST_CONTRACT_INTERFACE_SIZE,
    GUEST_CONTRACT_HANDLE_SIZE,
    BUNDLE_INIT_CONTEXT_SIZE,
    PLUGIN_DESCRIPTOR_SIZE,
    RELOAD_PHASE_SIZE,
    RUNTIME_CONFIG_SIZE,
    ABI_ERROR_SIZE,
    BUFFER_SIZE,
    ARENA_OVERFLOW_BLOCK_SIZE,
    CALL_ARENA_SIZE,
    DEPENDENCY_INFO_SIZE,
    STRING_VIEW_SIZE,
    VERSION_SIZE,
} from "./abi.ts";
import { assertStrictEquals, test } from "../testing/harness.ts";

test("NativeDispatch is 16 bytes", () => {
    assertStrictEquals(NATIVE_DISPATCH_SIZE, 16);
});

test("VmDispatch is 16 bytes", () => {
    assertStrictEquals(VM_DISPATCH_SIZE, 16);
});

test("VmLoaderData is 8 bytes", () => {
    assertStrictEquals(VM_LOADER_DATA_SIZE, 8);
});

test("GuestContractInstance is 16 bytes", () => {
    assertStrictEquals(GUEST_CONTRACT_INSTANCE_SIZE, 16);
});

test("GuestContractInterface is 56 bytes", () => {
    assertStrictEquals(GUEST_CONTRACT_INTERFACE_SIZE, 56);
});

test("HostApi is 184 bytes", () => {
    assertStrictEquals(HOST_API_SIZE, 184);
});

test("HostContractInstance is 8 bytes", () => {
    assertStrictEquals(HOST_CONTRACT_INSTANCE_SIZE, 8);
});

test("HostContractInterface is 80 bytes", () => {
    assertStrictEquals(HOST_CONTRACT_INTERFACE_SIZE, 80);
});

test("GuestContractHandle is 8 bytes", () => {
    assertStrictEquals(GUEST_CONTRACT_HANDLE_SIZE, 8);
});

test("BundleInitContext is 24 bytes", () => {
    assertStrictEquals(BUNDLE_INIT_CONTEXT_SIZE, 24);
});

test("PluginDescriptor is 48 bytes", () => {
    assertStrictEquals(PLUGIN_DESCRIPTOR_SIZE, 48);
});

test("ReloadPhase is 48 bytes", () => {
    assertStrictEquals(RELOAD_PHASE_SIZE, 48);
});

test("RuntimeConfig is 48 bytes", () => {
    assertStrictEquals(RUNTIME_CONFIG_SIZE, 48);
});

test("AbiError is 24 bytes", () => {
    assertStrictEquals(ABI_ERROR_SIZE, 24);
});

test("Buffer is 24 bytes", () => {
    assertStrictEquals(BUFFER_SIZE, 24);
});

test("ArenaOverflowBlock is 24 bytes", () => {
    assertStrictEquals(ARENA_OVERFLOW_BLOCK_SIZE, 24);
});

test("CallArena is 40 bytes", () => {
    assertStrictEquals(CALL_ARENA_SIZE, 40);
});

test("DependencyInfo is 24 bytes", () => {
    assertStrictEquals(DEPENDENCY_INFO_SIZE, 24);
});

test("StringView is 16 bytes", () => {
    assertStrictEquals(STRING_VIEW_SIZE, 16);
});

test("Version is 12 bytes", () => {
    assertStrictEquals(VERSION_SIZE, 12);
});

