[bundle]
name = "cpp_validator"
version = "1.0.0"
api = "../../../api.toml"
loader = "native"

[bundle.file]
linux.x86_64 = "libvalidator.so"

[[plugin]]
name = "validator"
implements = ["pipeline.Validator@1.0"]
