[package]
name = "polyplug_host"
description = "Universal high-performance zero-overhead cross-language plugin runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
polyplug = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
