//! polyplug guest library — Rust bindings for guest-side (plugin developer) use.
//!
//! This crate provides the ABI types, allocator hookup, and registration
//! helpers that plugin authors need to implement a polyplug contract.
//!
//! # Quick Start
//!
//! A minimal Rust plugin implementing a contract looks like this:
//!
//! ```rust,ignore
//! // In Cargo.toml: crate-type = ["cdylib"]
//! use polyplug_abi::*;
//!
//! // 1. Compute the contract ID at compile time (FNV-1a of "my.contract@1")
//! const MY_CONTRACT_ID: u64 = /* polyplugc generates this */;
//!
//! // 2. Implement your function with the generic dispatch signature
//! extern "C" fn my_fn(args: *const (), out: *mut ()) -> AbiError {
//!     // ... cast args/out, compute, write result
//!     AbiError::ok()
//! }
//!
//! // 3. Declare static vtable
//! static MY_FNS: [FnPtr; 1] = [FnPtr(my_fn as *const ())];
//! static MY_VTABLE: PluginInterface = PluginInterface {
//!     contract_id: MY_CONTRACT_ID,
//!     contract_version: 1 << 16, // minor=1, patch=0
//!     function_count: 1,
//!     functions: MY_FNS.as_ptr() as *const *const (),
//! };
//! static MY_DESCRIPTOR: PluginDescriptor = PluginDescriptor {
//!     name: StringView { ptr: b"my_plugin".as_ptr(), len: 9 },
//!     contract_name: StringView { ptr: b"my.contract".as_ptr(), len: 11 },
//!     version_major: 1, version_minor: 0, version_patch: 0,
//! };
//!
//! // 4. Export ABI version sentinel
//! #[unsafe(no_mangle)]
//! pub extern "C" fn polyplug_abi_version() -> u32 { POLYPLUG_ABI_VERSION }
//!
//! // 5. Export init function — registers vtables with the host
//! #[unsafe(no_mangle)]
//! pub unsafe extern "C" fn polyplug_init(
//!     rt_ctx: *mut core::ffi::c_void,
//!     host_vtable: *const HostVTable,
//!     _ctx: *const PluginContext,
//! ) -> AbiError {
//!     if host_vtable.is_null() {
//!         return AbiError { code: ABI_ERROR_GENERIC, message: StringView::null() };
//!     }
//!     let host: &HostVTable = unsafe { &*host_vtable };
//!     unsafe {
//!         (host.register_plugin)(rt_ctx, &MY_DESCRIPTOR, &MY_VTABLE)
//!     }
//! }
//! ```
//!
//! # Status
//! Scaffold only. Full implementation is code-generated by `polyplugc`.

// ─── ABI Constants ────────────────────────────────────────────────────────────

/// ABI version sentinel — all plugins must export `polyplug_abi_version() -> u32`
/// returning this value. The loader rejects plugins with a different version.
pub use polyplug_abi::POLYPLUG_ABI_VERSION;

/// Output buffer too small — caller must reallocate and retry.
pub use polyplug_abi::ABI_BUFFER_TOO_SMALL;
pub use polyplug_abi::ABI_ERROR_DUPLICATE_PROVIDER;
/// Generic error code — use for unclassified plugin errors.
pub use polyplug_abi::ABI_ERROR_GENERIC;
pub use polyplug_abi::ABI_ERROR_INVALID_POINTER;
/// Requested plugin or contract not found.
pub use polyplug_abi::ABI_ERROR_NOT_FOUND;
/// Plugin panicked — returned by the host runtime when `catch_unwind` fires.
pub use polyplug_abi::ABI_ERROR_PANIC;
/// Plugin handle is stale (plugin was unloaded and reloaded).
pub use polyplug_abi::ABI_ERROR_STALE_HANDLE;
/// Function ID is out of range for this vtable.
pub use polyplug_abi::ABI_FUNCTION_NOT_AVAIL;
/// Success code — no error.
pub use polyplug_abi::ABI_OK;

// ─── ABI Types ────────────────────────────────────────────────────────────────

/// Non-owning UTF-8 string view. Never null-terminated.
///
/// OWNERSHIP: borrowed reference. `ptr` must remain valid for the duration
/// of the call. Never freed by the receiver.
pub use polyplug_abi::StringView;

/// Owning byte buffer allocated via the host allocator.
///
/// OWNERSHIP: `ptr` is always allocated via `polyplug_host_alloc`.
/// Owner calls `polyplug_host_free(ptr, cap, align)` when done.
pub use polyplug_abi::Buffer;

/// ABI error returned by value from all ABI calls.
///
/// OWNERSHIP: `code` is a value type. `message.ptr` (if non-null) is
/// allocated by the callee via `host_alloc`. Caller frees with
/// `polyplug_host_free(message.ptr, message.len, 1)` after reading.
pub use polyplug_abi::AbiError;

/// Opaque handle to a loaded plugin — validated on every use.
pub use polyplug_abi::PluginHandle;

/// Plugin VTable — one per contract implemented by a plugin.
///
/// OWNERSHIP: Must be `'static` or intentionally leaked.
pub use polyplug_abi::PluginInterface;

/// Host context passed to plugins.
pub use polyplug_abi::HostContext;

/// Dispatch type for plugin interfaces.
pub use polyplug_abi::DispatchType;

/// Native dispatch mechanism.
pub use polyplug_abi::NativeDispatch;

/// VM dispatch mechanism.
pub use polyplug_abi::VmDispatch;

/// Union of dispatch mechanisms.
pub use polyplug_abi::PluginDispatch;

/// Host capabilities passed to every plugin at init time.
///
/// Accessed via `PluginRegistrar::host`. Provides allocation, plugin lookup,
/// and extension vtable retrieval.
pub use polyplug_abi::HostVTable;

/// Metadata about a plugin within a bundle.
///
/// OWNERSHIP: value type passed by pointer during init. The `name` and
/// `contract_name` StringViews are borrowed from the plugin's static memory.
pub use polyplug_abi::PluginDescriptor;

/// Context passed to every guest `polyplug_init()` function.
///
/// Contains `bundle_path` — the absolute path to the bundle directory.
/// **Plugin must not store the raw pointer** — copy the string value if persistence is needed.
pub use polyplug_abi::PluginContext;

// ─── Hash Utilities ───────────────────────────────────────────────────────────

/// Compute the FNV-1a 64-bit contract ID for `"name@major_version"`.
///
/// Use this to verify at runtime that your compile-time constant matches.
/// `polyplugc` generates these constants for you at code-generation time.
///
/// # Example
/// ```rust
/// use polyplug_abi::contract_id;
/// assert_eq!(contract_id("test.add", 1), 0xCC4232FAB0410D2B);
/// ```
pub use polyplug_abi::contract_id;

/// Compute the FNV-1a 64-bit bundle ID for a bundle name.
pub use polyplug_abi::bundle_id;

/// Compute the FNV-1a 32-bit extension ID for an extension name.
pub use polyplug_abi::extension_id;

// ─── Allocator ────────────────────────────────────────────────────────────────

/// Allocate memory via the host system allocator.
///
/// All memory that crosses the plugin/host boundary must use this allocator.
/// Returns null for size=0 or invalid alignment.
pub use polyplug_abi::ffi::polyplug_host_alloc;

/// Free memory previously allocated by `polyplug_host_alloc`.
///
/// Passing null or size=0 is a safe no-op.
pub use polyplug_abi::ffi::polyplug_host_free;

// ─── Helper Types ─────────────────────────────────────────────────────────────

/// Wrapper for a function pointer stored in a static vtable array.
///
/// Raw `*const ()` does not implement `Sync`, but function pointers in a
/// `static` array are effectively `'static` and immutable.
/// Wrap each function pointer in `FnPtr` when building your vtable's
/// `functions` array.
///
/// # Example
/// ```rust,ignore
/// extern "C" fn my_fn(args: *const (), out: *mut ()) -> AbiError { AbiError::ok() }
/// static MY_FNS: [FnPtr; 1] = [FnPtr(my_fn as *const ())];
/// ```
#[repr(transparent)]
pub struct FnPtr(pub *const ());

// SAFETY: FnPtr wraps a 'static function pointer. Function pointers are safe
// to share across threads — the function itself handles its own synchronization.
unsafe impl Send for FnPtr {}
// SAFETY: Function pointers are inherently Sync — multiple threads may call
// the same function concurrently. The data is read-only 'static memory.
unsafe impl Sync for FnPtr {}

/// Error returned from guest-side plugin trait methods.
///
/// Produced by generated ABI wrappers when an ABI call returns a non-zero code.
/// Plugin developers return `Result<T, PluginError>` from their trait implementations.
#[derive(Debug)]
pub struct PluginError {
    /// ABI error code (non-zero).
    pub code: u32,
    /// Human-readable error message. May be empty.
    pub message: String,
}

impl core::fmt::Display for PluginError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(
            f,
            "PluginError(code={}, message={})",
            self.code, self.message
        )
    }
}

impl core::error::Error for PluginError {}

// ─── String Helpers ───────────────────────────────────────────────────────────

/// Convert a `StringView` to a `&str`.
///
/// # Safety
/// The `StringView` must point to valid UTF-8 data.
/// The returned slice is valid only as long as the `StringView` data remains valid.
///
/// # Example
/// ```rust
/// use polyplug_guest::{StringView, to_str};
///
/// let sv = StringView { ptr: b"hello".as_ptr(), len: 5 };
/// let s: &str = to_str(sv);
/// assert_eq!(s, "hello");
/// ```
pub fn to_str(sv: StringView) -> &'static str {
    if sv.ptr.is_null() || sv.len == 0 {
        return "";
    }
    // SAFETY: sv.ptr is non-null (checked above) and sv.len is the valid length.
    // The caller guarantees the pointer is valid for sv.len bytes and points to UTF-8 data.
    unsafe { core::str::from_utf8(core::slice::from_raw_parts(sv.ptr, sv.len)).unwrap_or("") }
}

/// Allocate a `StringView` from a `&str` using the host allocator.
///
/// The returned `StringView` points to memory allocated via `polyplug_host_alloc`.
/// The caller (host) is responsible for freeing the memory via `polyplug_host_free`.
///
/// # Errors
/// Returns `Err(PluginError)` if allocation fails.
///
/// # Example
/// ```rust
/// use polyplug_guest::{alloc_string, StringView};
///
/// let sv: StringView = alloc_string("hello").unwrap();
/// // sv.ptr points to host-allocated memory
/// // Host must call polyplug_host_free(sv.ptr, sv.len, 1) when done
/// ```
pub fn alloc_string(s: &str) -> Result<StringView, PluginError> {
    let bytes: &[u8] = s.as_bytes();
    let ptr: *mut u8 = polyplug_host_alloc(bytes.len(), 1);
    if ptr.is_null() {
        return Err(PluginError {
            code: ABI_ERROR_GENERIC,
            message: "allocation failed".to_string(),
        });
    }
    // SAFETY: ptr is non-null (checked above) and was allocated by polyplug_host_alloc
    // with size bytes.len() and align 1. The source bytes.as_ptr() is valid for
    // bytes.len() bytes. The destination is valid for bytes.len() bytes.
    unsafe { core::ptr::copy_nonoverlapping(bytes.as_ptr(), ptr, bytes.len()) };
    Ok(StringView {
        ptr,
        len: bytes.len(),
    })
}
