[bundle]
name = "csharp_reporter"
version = "1.0.0"
api = "../../../api.toml"
runtime = "csharp"
file = "reporter.dll"

[[plugin]]
name = "reporter"
version = "1.0.0"
implements = ["data.Reporter@1.0"]
