[package]
name = "polyplug_utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Utility functions for polyplug (hashing, etc.)"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
serde = { workspace = true }

[lints]
workspace = true