[package]
name = "polyplug_codegen"
description = "Code generation library for polyplug host-side contract callers"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
polyplug_utils = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
libloading = { workspace = true }
polyplug_abi = { workspace = true }

[lints]
workspace = true
