[package]
name = "polyplug_codegen"
description = "Code generation library for polyplug host-side contract callers"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
polyplug_utils = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
libloading = { workspace = true }

[lints]
workspace = true
