// THIS FILE IS AUTO-GENERATED BY polyplug_abi
// DO NOT EDIT BY HAND

using System.Runtime.InteropServices;

namespace Polyplug.Abi;

/// <summary>ABI error code constants. Must match Rust ABI constants exactly.</summary>
public static class AbiConstants
{
    public const uint POLYPLUG_ABI_VERSION = 1u;
    public const uint ABI_OK = 0u;
    public const uint ABI_ERROR_GENERIC = 1u;
    public const uint ABI_BUFFER_TOO_SMALL = 2u;
    public const uint ABI_ERROR_PANIC = 3u;
    public const uint ABI_ERROR_NOT_FOUND = 4u;
    public const uint ABI_ERROR_STALE_HANDLE = 5u;
    public const uint ABI_FUNCTION_NOT_AVAIL = 6u;
    public const uint ABI_ERROR_DUPLICATE_PROVIDER = 7u;
    public const uint ABI_ERROR_INVALID_POINTER = 8u;
}

// ─── ABI Structs ─────────────────────────────────────────────────────────────

///  Non-owning UTF-8 string view.
///
///  OWNERSHIP: borrowed reference. `ptr` must remain valid for the duration
///  of the call. Never freed by the receiver.
[StructLayout(LayoutKind.Sequential)]
public struct StringView
{
///  UTF-8 bytes, NOT null-terminated.
    public IntPtr Ptr;
///  Byte count.
    public nuint Len;
}

///  Owning byte buffer.
///
///  OWNERSHIP: `ptr` is always allocated via `polyplug_host_alloc`.
///  Owner calls `polyplug_host_free(ptr, cap, align)` when done.
[StructLayout(LayoutKind.Sequential)]
public struct Buffer
{
    public IntPtr Ptr;
///  Bytes currently used.
    public nuint Len;
///  Bytes allocated.
    public nuint Cap;
}

///  ABI error — returned by value from all ABI calls.
///
///  OWNERSHIP: `code` is a value type. `message.ptr` is allocated by the callee
///  via `host_alloc`. Caller frees with `polyplug_host_free(message.ptr, message.len, 1)`
///  after reading. If `code == ABI_OK`, `message.ptr` is NULL — no free needed.
[StructLayout(LayoutKind.Sequential)]
public struct AbiError
{
///  0 = success, non-zero = error.
    public uint Code;
///  Empty/NULL if success. UTF-8 message if non-zero code.
    public StringView Message;
}

///  Opaque handle to a loaded plugin — validated on use.
///
///  INTERNAL STRUCTURE: index into registry array + generation counter.
///  The generation counter detects use-after-unload.
[StructLayout(LayoutKind.Sequential)]
public struct PluginHandle
{
///  Slot in the registry array.
    public uint Index;
///  Incremented on unload — detects stale handles.
    public uint Generation;
}

///  Opaque host context passed to plugin functions via rt_ctx parameter.
///
///  Contains the runtime pointer and the bundle_id of the calling bundle.
///  The actual implementation is in the polyplug crate; this definition
///  establishes the ABI layout.
///
///  OWNERSHIP: `'static`, lives as long as the runtime.
[StructLayout(LayoutKind.Sequential)]
public struct HostContext
{
///  Opaque pointer to the Runtime. Never dereferenced by plugins.
    public IntPtr Runtime;
///  Bundle ID of the calling bundle for dependency enforcement.
    public ulong BundleId;
}

///  Native dispatch data — direct function pointer array.
///
///  Used when `dispatch_type == DispatchType::Native`.
///  The `functions` array contains `function_count` function pointers.
[StructLayout(LayoutKind.Sequential)]
public struct NativeDispatch
{
///  Pointer to a static array of function pointers, indexed by function_id.
    public IntPtr Functions;
}

///  VM dispatch data — call through a dispatch function.
///
///  Used when `dispatch_type == DispatchType::VirtualMachine`.
///  The `call` function receives `loader_data` which contains VM-specific state.
[StructLayout(LayoutKind.Sequential)]
public struct VmDispatch
{
///  Dispatch function called for every VM function invocation.
///
///  # Arguments
///  - `loader_data`: VM-specific data (cast from `*mut c_void`)
///  - `fn_id`: Function index within the contract
///  - `args`: Pointer to packed arguments (ABI-specific layout)
///  - `out`: Pointer to output buffer for return value
    public IntPtr Call;
///  Loader-specific data (e.g., LuaLoaderData, JsLoaderData).
///  Opaque to the host; interpreted by the dispatch function.
    public IntPtr LoaderData;
}

///  Plugin interface — one per contract implemented by a plugin.
///
///  OWNERSHIP: Must be `'static` or intentionally leaked.
///  Never stack-allocated. Never freed while runtime lives.
///
///  # Dispatch
///  - `dispatch_type == Native`: Call via `dispatch.native.functions[fn_id]`
///  - `dispatch_type == VirtualMachine`: Call via `dispatch.vm.call(...)`
[StructLayout(LayoutKind.Sequential)]
public struct PluginInterface
{
///  Pointer to the host context for this plugin.
///  Used for host function calls and dependency enforcement.
    public IntPtr RtCtx;
///  FNV-1a hash of "contract_name@major_version".
    public ulong ContractId;
///  minor.patch encoded as `(minor << 16 | patch)`.
    public uint ContractVersion;
///  Number of valid entries in the dispatch array.
    public uint FunctionCount;
///  Dispatch mechanism type (Native or VirtualMachine).
    public DispatchType DispatchType;
///  Union of dispatch mechanisms — access based on dispatch_type.
    public PluginDispatch Dispatch;
}

///  Host capabilities passed to every plugin at init time.
///
///  OWNERSHIP: `'static`, lives as long as the runtime.
///
///  All functions take `rt_ctx` as first parameter - an opaque pointer to the Runtime.
///  This allows each Runtime to have its own isolated state (no global registry).
[StructLayout(LayoutKind.Sequential)]
public struct HostVTable
{
    public IntPtr RegisterPlugin;
    public IntPtr Alloc;
    public IntPtr Free;
    public IntPtr FindByContract;
    public IntPtr FindByBundle;
    public IntPtr FindAllByContract;
    public IntPtr ResolvePlugin;
///  Get host contract vtable by contract_id and minimum version.
///  Returns null if no host contract matches the criteria.
    public IntPtr GetHostContract;
}

///  Metadata about a plugin within a bundle.
///
///  OWNERSHIP: value type passed by pointer during init. The `name` and
///  `contract_name` StringViews are borrowed from the plugin's static memory.
///  The receiver must not free or outlive the plugin's library.
[StructLayout(LayoutKind.Sequential)]
public struct PluginDescriptor
{
///  Human-readable plugin name.
    public StringView Name;
///  Full contract name for collision detection.
    public StringView ContractName;
    public uint VersionMajor;
    public uint VersionMinor;
    public uint VersionPatch;
}

///  Context passed to every guest `polyplug_init()` function.
///  The `bundle_path` pointer is runtime-owned and valid for the lifetime of the `PluginRuntime`.
///  **Plugin must not store the raw pointer** — copy the string value if persistence is needed.
[StructLayout(LayoutKind.Sequential)]
public struct PluginContext
{
///  Absolute canonical path to the directory containing the loaded bundle.
    public StringView BundlePath;
///  Host's supported ABI version for negotiation (Option C).
///  Plugin can use this to determine available features.
    public uint HostAbiVersion;
///  Bundle ID for dependency enforcement during init.
    public ulong BundleId;
}

///  Configuration passed to `polyplug_runtime_create` during runtime initialisation.
///
///  OWNERSHIP: borrowed for the duration of the runtime build only.
///  The caller may free all pointed-to memory after the build
///  returns. The runtime copies any data it needs to retain.
[StructLayout(LayoutKind.Sequential)]
public struct RuntimeConfig
{
///  Plugin directories to scan (array of `plugin_dir_count` StringViews).
    public IntPtr PluginDirs;
    public nuint PluginDirCount;
///  Compatibility mode: 0 = Strict (only mode implemented in MVP).
    public uint Compatibility;
}

// ─── ABI Enums ────────────────────────────────────────────────────────────────

///  Dispatch mechanism type — determines how function calls are routed.
public enum DispatchType : uint
{
///  Native dispatch: direct function pointer calls (zero overhead).
    Native = 0,
///  VM dispatch: call through a dispatch function with loader_data.
    VirtualMachine = 1,
}

// ─── ABI Unions ───────────────────────────────────────────────────────────────

///  Union of dispatch mechanisms — use based on `dispatch_type`.
///
///  # Safety
///  Access the correct variant based on `PluginInterface::dispatch_type`:
///  - `dispatch_type == Native` → access `.native`
///  - `dispatch_type == VirtualMachine` → access `.vm`
[StructLayout(LayoutKind.Explicit)]
public struct PluginDispatch
{
///  Native dispatch data (when dispatch_type == Native).
    [FieldOffset(0)]
    public NativeDispatch Native;
///  VM dispatch data (when dispatch_type == VirtualMachine).
    [FieldOffset(0)]
    public VmDispatch Vm;
}

// ─── FNV-1a Hash Helpers ──────────────────────────────────────────────────────

/// <summary>FNV-1a hash helpers for computing contract, extension, and bundle IDs.</summary>
public static class ContractId
{
    private const ulong FNV_OFFSET = 0xcbf29ce484222325ul;
    private const ulong FNV_PRIME = 0x00000100000001B3ul;

    /// <summary>Compute FNV-1a 64-bit hash of a byte span.</summary>
    public static ulong Fnv1a64(ReadOnlySpan<byte> data)
    {
        ulong hash = FNV_OFFSET;
        foreach (byte b in data)
        {
            hash ^= b;
            hash *= FNV_PRIME;
        }
        return hash;
    }

    /// <summary>Compute the contract ID for "name@major_version" using FNV-1a 64-bit.</summary>
    public static ulong Compute(string name, uint majorVersion)
    {
        string canonical = $"{name}@{majorVersion}";
        int maxLen = System.Text.Encoding.UTF8.GetMaxByteCount(canonical.Length);
        Span<byte> buffer = stackalloc byte[maxLen];
        int len = System.Text.Encoding.UTF8.GetBytes(canonical, buffer);
        return Fnv1a64(buffer.Slice(0, len));
    }

    /// <summary>Compute an extension ID from its name using FNV-1a lower 32 bits.</summary>
    public static uint ExtensionId(string name)
    {
        int maxLen = System.Text.Encoding.UTF8.GetMaxByteCount(name.Length);
        Span<byte> buffer = stackalloc byte[maxLen];
        int len = System.Text.Encoding.UTF8.GetBytes(name, buffer);
        return (uint)Fnv1a64(buffer.Slice(0, len));
    }

    /// <summary>Compute a bundle ID from its name using FNV-1a 64-bit hash.</summary>
    public static ulong BundleId(string name)
    {
        int maxLen = System.Text.Encoding.UTF8.GetMaxByteCount(name.Length);
        Span<byte> buffer = stackalloc byte[maxLen];
        int len = System.Text.Encoding.UTF8.GetBytes(name, buffer);
        return Fnv1a64(buffer.Slice(0, len));
    }
}
