using System.Runtime.InteropServices;

namespace Polyplug.Abi {

///  Native dispatch data — direct function pointer array.
///
///  Used when `dispatch_type == DispatchType::Native`.
///  The `functions` array contains `function_count` function pointers.
[StructLayout(LayoutKind.Sequential)]
public struct NativeDispatch
{
    ///  Number of valid entries in the dispatch array.
    public uint FunctionCount;
    ///  Pointer to a static array of function pointers, indexed by function_id.
    public IntPtr Functions;
}

///  VM dispatch data — call through a dispatch function.
///
///  Used when `dispatch_type == DispatchType::VirtualMachine`.
///  The `call` function receives `loader_data` which contains VM-specific state.
[StructLayout(LayoutKind.Sequential)]
public struct VmDispatch
{
    ///  Dispatch function called for every VM function invocation.
    ///
    ///  # Arguments
    ///  - `loader_data`: VmLoaderData handle containing VM-specific state
    ///  - `instance`: The guest contract instance (opaque handle)
    ///  - `fn_id`: Function index within the contract
    ///  - `args`: Pointer to packed arguments (ABI-specific layout)
    ///  - `out`: Pointer to output buffer for return value
    public unsafeextern"C"fn(loader_data:VmLoaderData,instance:GuestContractInstance,fn_id:u32,args:*const(),out:*mut(),)->AbiError Call;
    ///  Loader-specific data handle.
    ///  Opaque to the host; interpreted by the dispatch function.
    public VmLoaderData LoaderData;
}

///  Opaque handle to VM loader-specific data.
///
///  Wraps VM-specific state managed by each loader (Python, Lua, JS).
///  Opaque to core runtime — loaders know their own state layout.
///
///  # OWNERSHIP
///  Owned by the loader. Lives for the lifetime of the loaded plugin.
[StructLayout(LayoutKind.Sequential)]
public struct VmLoaderData
{
    ///  Opaque pointer to VM-specific loader data.
    public IntPtr Data;
}

///  Opaque handle to a guest contract instance.
///
///  Created by `GuestContractInterface::create_instance`, destroyed by `destroy_instance`.
///
///  # Who provides
///  Guest code creates instances via create_instance factory.
///  The guest owns the underlying data.
///
///  # Who calls
///  Host code passes instances to dispatch functions and destroy_instance.
///
///  # Ownership
///  This is an owned handle - the instance must be destroyed via
///  `GuestContractInterface::destroy_instance` before hot-reload.
///  Failure to destroy causes memory leaks and prevents safe hot-reload.
///
///  # Lifetime
///  Lives until `destroy_instance` is called. Must be destroyed before
///  the bundle is unloaded or hot-reloaded.
///
///  # Layout
///  - `data`: Opaque instance pointer (owned by guest)
///  - `contract_id`: Contract ID for zero-overhead dispatch
///
///  # Dispatch
///  The `contract_id` field enables `call_guest_method` to dispatch without
///  looking up the contract in a map. This is zero-overhead dispatch.
[StructLayout(LayoutKind.Sequential)]
public struct GuestContractInstance
{
    ///  Opaque instance data pointer.
    ///  The actual data is owned by the guest plugin.
    ///
    ///  # Ownership
    ///  Guest owns the memory. Host must not free or modify.
    ///  Must be freed via GuestContractInterface::destroy_instance.
    public IntPtr Data;
    ///  Contract ID for zero-overhead dispatch.
    ///  Enables call_guest_method to dispatch without lookup.
    ///
    ///  # Purpose
    ///  Eliminates the need to look up which contract an instance belongs to.
    ///  The contract_id is set by create_instance and used for direct dispatch.
    public GuestContractId ContractId;
}

///  Guest Contract Interface — one per contract implemented by a guest (plugin).
///
///  # Who provides
///  Guest (plugin) code creates this struct and registers it via `register_contract`.
///  Must be `'static` or intentionally leaked.
///
///  # Who calls
///  Host code calls `create_instance`, `destroy_instance`, and dispatch functions.
///
///  # Ownership
///  Must be `'static`. Never stack-allocated. Never freed while runtime lives.
///  Typically created as `static` or via `Box::leak()`.
///
///  # Lifetime
///  Lives for the entire runtime lifetime. Must survive hot-reload.
///
///  # Instance Lifecycle
///  - `create_instance`: Factory function to create new instances
///  - `destroy_instance`: Destructor to clean up instances before hot-reload
///
///  # Dispatch
///  - `dispatch_type == Native`: Call via `dispatch.native.functions[fn_id](instance, args, out)`
///  - `dispatch_type == VirtualMachine`: Call via `dispatch.vm.call(loader_data, instance, fn_id, args, out)`
[StructLayout(LayoutKind.Sequential)]
public struct GuestContractInterface
{
    ///  FNV-1a hash of "guest_contract:name@major_version".
    ///
    ///  Generated by polyplugc from contract name and major version.
    ///  Used for contract lookup via `find_by_contract`.
    public GuestContractId ContractId;
    ///  Contract version (major, minor, patch).
    ///
    ///  Used for version compatibility checks during lookup.
    public Version ContractVersion;
    ///  Dispatch mechanism type (Native or VirtualMachine).
    ///
    ///  Determines how dispatch functions are invoked:
    ///  - Native: Direct function pointer call
    ///  - VirtualMachine: VM-specific dispatch via loader
    public DispatchType DispatchType;
    ///  Create a new instance of this contract.
    ///
    ///  Factory function called by host to create instances.
    ///  Returns null handle on failure.
    ///
    ///  # Arguments
    ///  - `host`: HostInterface pointer (for memory allocation via host->alloc)
    ///  - `args`: Optional initialization arguments (contract-specific)
    ///
    ///  # Returns
    ///  Opaque instance handle, or null handle on failure.
    ///
    ///  # Thread Safety
    ///  May be called from any thread. Implementation must handle synchronization.
    public unsafeextern"C"fn(host:*constHostInterface,args:*const(),)->GuestContractInstance CreateInstance;
    ///  Destroy an instance of this contract.
    ///
    ///  MUST be called before hot-reload for all instances.
    ///  Failure to destroy instances causes memory leaks.
    ///
    ///  # Arguments
    ///  - `host`: HostInterface pointer
    ///  - `instance`: Instance handle to destroy
    ///
    ///  # Safety
    ///  After calling destroy_instance, the instance handle is invalid.
    public unsafeextern"C"fn(host:*constHostInterface,instance:GuestContractInstance,) DestroyInstance;
    ///  Union of dispatch mechanisms — access based on dispatch_type.
    ///
    ///  For Native dispatch: use `dispatch.native.functions[fn_id]`.
    ///  For VM dispatch: use `dispatch.vm.call(loader_data, instance, fn_id, args, out)`.
    public DispatchMechanisms Dispatch;
}

///  Host Interface — function table passed to guests during initialization.
///
///  Contains an opaque runtime pointer and function pointers for guest calls.
///  All functions use self-passing pattern (receive HostInterface pointer as first parameter).
///
///  # Who provides
///  The runtime creates this struct and passes it to `polyplug_init()`.
///  The struct is allocated using `Box::leak()` for `'static` lifetime.
///
///  # Who calls
///  Guest (plugin) code calls these functions to interact with the runtime.
///  SDK-generated wrappers handle the self-passing pattern automatically.
///
///  # Ownership
///  The struct is statically allocated by the runtime. The pointer is valid
///  until the runtime is destroyed. Guest must NOT free this pointer.
///
///  # Lifetime
///  Lives as long as the runtime that created it.
///
///  # Thread Safety
///  All functions are safe to call from any thread. The runtime uses
///  internal synchronization (RwLock/Mutex) for shared state.
///
///  # Self-passing pattern
///  Each function receives the interface pointer as its first parameter,
///  allowing guests to call: `host->find_by_contract(host, id, ver)`
///  SDKs hide this pattern: `host.find_by_contract(id, ver)`
[StructLayout(LayoutKind.Sequential)]
public struct HostInterface
{
    ///  Opaque pointer to Runtime.
    ///
    ///  Set during interface creation. Provides access to runtime state
    ///  for dependency enforcement and resource management.
    ///
    ///  # Ownership
    ///  Owned by the runtime. Guests must NOT free or modify this pointer.
    public IntPtr Runtime;
    ///  Register a guest contract implementation.
    ///
    ///  Called by plugins during `polyplug_init()` to register their contracts.
    ///  Returns error if contract_id collision detected or ABI version mismatch.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///  - `descriptor`: Plugin descriptor with contract metadata
    ///  - `interface`: GuestContractInterface to register
    ///
    ///  # Returns
    ///  AbiError::OK on success, error code on failure.
    public unsafeextern"C"fn(this:*constHostInterface,descriptor:*constPluginDescriptor,interface:*constGuestContractInterface,)->AbiError RegisterContract;
    ///  Allocate memory using the host allocator.
    ///
    ///  Memory allocated here must be freed via `free`.
    ///  Returns null on allocation failure.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///  - `size`: Number of bytes to allocate
    ///  - `align`: Alignment requirement (must be power of 2)
    ///
    ///  # Returns
    ///  Pointer to allocated memory, or null on failure.
    public unsafeextern"C"fn(this:*constHostInterface,size:usize,align:usize)->*mutu8 Alloc;
    ///  Free memory allocated via `alloc`.
    ///
    ///  Must pass the same size and align used for allocation.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///  - `ptr`: Pointer to memory to free
    ///  - `size`: Size used for allocation
    ///  - `align`: Alignment used for allocation
    public unsafeextern"C"fn(this:*constHostInterface,ptr:*mutu8,size:usize,align:usize) Free;
    ///  Find a guest contract by contract_id and minimum version.
    ///
    ///  Returns a GuestContractHandle that can be resolved to an interface.
    ///  Returns null handle if no matching contract found.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///  - `contract_id`: Contract identifier hash
    ///  - `min_version`: Minimum version required
    ///
    ///  # Returns
    ///  GuestContractHandle for the first matching contract, or null handle.
    public unsafeextern"C"fn(this:*constHostInterface,contract_id:u64,min_version:u32,)->GuestContractHandle FindGuestContract;
    ///  Find all guest contracts matching contract_id and minimum version.
    ///
    ///  Returns an Array of GuestContractHandle. Caller must free via `host->free`.
    ///  Use when multiple implementations of the same contract may exist.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///  - `contract_id`: Contract identifier hash
    ///  - `min_version`: Minimum version required
    ///
    ///  # Returns
    ///  Array of GuestContractHandle. Caller owns and must free.
    public unsafeextern"C"fn(this:*constHostInterface,contract_id:u64,min_version:u32,)->Array<GuestContractHandle> FindAllGuestContracts;
    ///  Resolve a GuestContractHandle to a GuestContractInterface pointer.
    ///
    ///  Returns null if the handle is invalid or contract was unloaded.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///  - `handle`: GuestContractHandle from find_guest_contract
    ///
    ///  # Returns
    ///  Pointer to GuestContractInterface, or null if invalid/stale.
    public unsafeextern"C"fn(this:*constHostInterface,handle:GuestContractHandle,)->*constGuestContractInterface ResolveGuestContract;
    ///  Call a method on a guest contract instance.
    ///
    ///  This is the cross-dispatch mechanism for calling methods across
    ///  different dispatch types (Native vs VM).
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///  - `instance`: GuestContractInstance with contract_id for dispatch
    ///  - `method_id`: Method index within the contract
    ///  - `args`: Pointer to packed arguments (contract-specific layout)
    ///  - `out`: Pointer to output buffer for return value
    ///
    ///  # Returns
    ///  AbiError::OK on success, error code on failure.
    public unsafeextern"C"fn(this:*constHostInterface,instance:GuestContractInstance,method_id:u32,args:*const(),out:*mut(),)->AbiError CallGuestMethod;
    ///  Get a host contract instance by contract_id and minimum version.
    ///
    ///  For singleton host contracts, returns the same instance every time.
    ///  For multi-instance host contracts, returns a new instance each time.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///  - `contract_id`: Host contract identifier hash
    ///  - `min_version`: Minimum version required
    ///
    ///  # Returns
    ///  HostContractInstance for the contract.
    public unsafeextern"C"fn(this:*constHostInterface,contract_id:u64,min_version:u32,)->crate::host::HostContractInstance GetHostContract;
    ///  Resolve a host contract interface by contract_id and minimum version.
    ///
    ///  Returns the HostContractInterface pointer for the contract.
    ///  This is needed to access dispatch metadata (dispatch_type, function_count, functions).
    ///  Returns null if no matching contract found.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///  - `contract_id`: Host contract identifier hash
    ///  - `min_version`: Minimum version required
    ///
    ///  # Returns
    ///  Pointer to HostContractInterface, or null if invalid/not found.
    public unsafeextern"C"fn(this:*constHostInterface,contract_id:u64,min_version:u32,)->*constcrate::host::HostContractInterface ResolveHostContractInterface;
    ///  List all loaded bundles.
    ///
    ///  Returns an Array of BundleId. Caller must free via `host->free`.
    ///  Bundle IDs are stable for the lifetime of the runtime.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///
    ///  # Returns
    ///  Array of BundleId. Caller owns and must free.
    public unsafeextern"C"fn(this:*constHostInterface,)->Array<BundleId> ListBundles;
    ///  Get dependencies for the calling bundle.
    ///
    ///  Uses bundle_id from current BundleInitContext (TLS) to look up declared deps.
    ///  Returns an Array of DependencyInfo. Caller must free via `host->free`.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///
    ///  # Returns
    ///  Array of DependencyInfo. Caller owns and must free.
    ///  Returns empty array if called outside bundle init context.
    public unsafeextern"C"fn(this:*constHostInterface,)->Array<DependencyInfo> GetDependencies;
    ///  Load a plugin bundle from a path.
    ///
    ///  Host applications call this to load a bundle at runtime.
    ///  The loader matching the bundle's runtime type is used.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///  - `path`: UTF-8 path to bundle directory (not null-terminated)
    ///  - `path_len`: Length of path in bytes
    ///
    ///  # Returns
    ///  AbiError::OK on success, error code on failure.
    public unsafeextern"C"fn(this:*constHostInterface,path:*constu8,path_len:usize,)->AbiError LoadBundle;
    ///  Reload a plugin bundle (hot-reload).
    ///
    ///  Replaces the bundle's contracts with new versions from the updated binary.
    ///  All instances must be destroyed before calling this.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///  - `path`: UTF-8 path to bundle directory (not null-terminated)
    ///  - `path_len`: Length of path in bytes
    ///
    ///  # Returns
    ///  AbiError::OK on success, error code on failure.
    public unsafeextern"C"fn(this:*constHostInterface,path:*constu8,path_len:usize,)->AbiError ReloadBundle;
    ///  Register a host contract interface.
    ///
    ///  Host applications register their contracts for plugins to consume.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///  - `interface`: HostContractInterface to register
    ///
    ///  # Returns
    ///  AbiError::OK on success, error code on failure.
    public unsafeextern"C"fn(this:*constHostInterface,interface:*constcrate::host::HostContractInterface,)->AbiError RegisterHostContract;
    ///  Register a language loader.
    ///
    ///  Host applications register loaders for each runtime language they support.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///  - `runtime_name`: Name of the runtime (e.g., "rust", "python")
    ///  - `loader_ptr`: Opaque pointer to the loader implementation
    ///
    ///  # Returns
    ///  AbiError::OK on success, error code on failure.
    public IntPtr RegisterLoader;
    ///  Get last error message.
    ///
    ///  Returns the most recent error message from this runtime.
    ///  Copies up to buf_len bytes into buf.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///  - `buf`: Buffer to write error message into
    ///  - `buf_len`: Maximum bytes to write
    ///
    ///  # Returns
    ///  Number of bytes written (0 if no error or buffer too small).
    public unsafeextern"C"fn(this:*constHostInterface,buf:*mutu8,buf_len:usize,)->usize GetLastError;
    ///  Get last error message length.
    ///
    ///  Returns the byte length of the most recent error message.
    ///  Use to allocate buffer before calling get_last_error.
    ///
    ///  # Arguments
    ///  - `this`: HostInterface pointer (self-passing)
    ///
    ///  # Returns
    ///  Length of last error message (0 if no error).
    public unsafeextern"C"fn(this:*constHostInterface,)->usize GetErrorLen;
}

///  Runtime Interface — function table returned to host from polyplug_runtime_create().
///
///  Contains an opaque runtime pointer and function pointers for host calls.
///  All functions take `*const RuntimeInterface` as first parameter.
///
///  # Who provides
///  The runtime creates this struct and returns it from `polyplug_runtime_create()`.
///  The struct is heap-allocated and owned by the host.
///
///  # Who calls
///  Host application code calls these functions to interact with the runtime.
///  SDK-generated wrappers handle the self-passing pattern automatically.
///
///  # Ownership
///  The struct is allocated by `polyplug_runtime_create()`. The host owns
///  the pointer and must call `destroy()` to free the runtime and interface.
///
///  # Lifetime
///  Lives until `destroy()` is called. After destroy, the pointer is invalid.
///
///  # Thread Safety
///  All functions are safe to call from any thread. The runtime uses
///  internal synchronization for shared state.
///
///  # Self-passing pattern
///  Each function receives the interface pointer as its first parameter,
///  allowing hosts to call: `rt->load_bundle(rt, path)`
///  SDKs hide this pattern: `rt.load_bundle(path)`
[StructLayout(LayoutKind.Sequential)]
public struct RuntimeInterface
{
    ///  Opaque pointer to Runtime.
    ///
    ///  Set during interface creation. Provides access to runtime state.
    ///
    ///  # Ownership
    ///  Owned by the runtime. Host must call `destroy()` to free.
    public IntPtr Runtime;
    ///  Load a plugin bundle from the given path.
    ///
    ///  Loads the bundle and initializes all its guest contracts.
    ///  Dependencies are resolved in topological order.
    ///
    ///  # Arguments
    ///  - `this`: RuntimeInterface pointer (self-passing)
    ///  - `path`: Path to the bundle directory or manifest file
    ///
    ///  # Returns
    ///  AbiError::OK on success, error code on failure.
    ///  Use `get_last_error()` for detailed error message.
    public unsafeextern"C"fn(this:*constRuntimeInterface,path:*constc_char)->AbiError LoadBundle;
    ///  Reload a bundle (hot-reload).
    ///
    ///  Triggers hot-reload of the specified bundle. The runtime will:
    ///  1. Call pre-reload callbacks to notify hosts
    ///  2. Wait for all instances to be destroyed
    ///  3. Unload the old bundle
    ///  4. Load the new bundle
    ///  5. Call post-reload callbacks
    ///
    ///  # Arguments
    ///  - `this`: RuntimeInterface pointer (self-passing)
    ///  - `bundle_id`: ID of the bundle to reload
    ///
    ///  # Returns
    ///  AbiError::OK on success, error code on failure.
    public unsafeextern"C"fn(this:*constRuntimeInterface,bundle_id:BundleId)->AbiError ReloadBundle;
    ///  Unload a bundle.
    ///
    ///  Removes the bundle and all its guest contracts from the registry.
    ///  Host must destroy all instances before unloading.
    ///
    ///  # Arguments
    ///  - `this`: RuntimeInterface pointer (self-passing)
    ///  - `bundle_id`: ID of the bundle to unload
    ///
    ///  # Returns
    ///  AbiError::OK on success, error code on failure.
    public unsafeextern"C"fn(this:*constRuntimeInterface,bundle_id:BundleId)->AbiError UnloadBundle;
    ///  Find a guest contract by contract_id and minimum version.
    ///
    ///  Returns a GuestContractHandle that can be resolved to an interface.
    ///  Returns null handle if no matching contract found.
    ///
    ///  # Arguments
    ///  - `this`: RuntimeInterface pointer (self-passing)
    ///  - `contract_id`: Contract identifier hash
    ///  - `min_version`: Minimum version required
    ///
    ///  # Returns
    ///  GuestContractHandle for the first matching contract, or null handle.
    public unsafeextern"C"fn(this:*constRuntimeInterface,contract_id:u64,min_version:u32,)->GuestContractHandle FindByContract;
    ///  Find all guest contracts matching contract_id and minimum version.
    ///
    ///  Returns an Array of GuestContractHandle. Caller must free via host->free.
    ///  Use when multiple implementations of the same contract may exist.
    ///
    ///  # Arguments
    ///  - `this`: RuntimeInterface pointer (self-passing)
    ///  - `contract_id`: Contract identifier hash
    ///  - `min_version`: Minimum version required
    ///
    ///  # Returns
    ///  Array of GuestContractHandle. Caller owns and must free.
    public unsafeextern"C"fn(this:*constRuntimeInterface,contract_id:u64,min_version:u32,)->Array<GuestContractHandle> FindAllByContract;
    ///  Resolve a GuestContractHandle to a GuestContractInterface pointer.
    ///
    ///  Returns null if the handle is invalid or contract was unloaded.
    ///
    ///  # Arguments
    ///  - `this`: RuntimeInterface pointer (self-passing)
    ///  - `handle`: GuestContractHandle from find_by_contract
    ///
    ///  # Returns
    ///  Pointer to GuestContractInterface, or null if invalid/stale.
    public unsafeextern"C"fn(this:*constRuntimeInterface,handle:GuestContractHandle,)->*constGuestContractInterface ResolveContract;
    ///  Get a host contract instance by contract_id and minimum version.
    ///
    ///  For singleton host contracts, returns the same instance every time.
    ///  For multi-instance host contracts, returns a new instance each time.
    ///
    ///  # Arguments
    ///  - `this`: RuntimeInterface pointer (self-passing)
    ///  - `contract_id`: Host contract identifier hash
    ///  - `min_version`: Minimum version required
    ///
    ///  # Returns
    ///  HostContractInstance for the contract.
    public unsafeextern"C"fn(this:*constRuntimeInterface,contract_id:u64,min_version:u32,)->HostContractInstance GetHostContract;
    ///  Get the last error message.
    ///
    ///  Returns detailed error message for the most recent failed operation.
    ///  Message is valid until the next operation is performed.
    ///
    ///  # Arguments
    ///  - `this`: RuntimeInterface pointer (self-passing)
    ///
    ///  # Returns
    ///  StringView containing the error message, or empty string if no error.
    public unsafeextern"C"fn(this:*constRuntimeInterface)->StringView GetLastError;
    ///  List all loaded bundles.
    ///
    ///  Returns an Array of BundleId. Caller must free via host->free.
    ///  Bundle IDs are stable for the lifetime of the runtime.
    ///
    ///  # Arguments
    ///  - `this`: RuntimeInterface pointer (self-passing)
    ///
    ///  # Returns
    ///  Array of BundleId. Caller owns and must free.
    public unsafeextern"C"fn(this:*constRuntimeInterface,)->Array<BundleId> ListBundles;
    ///  Get dependencies (returns empty array for host context).
    ///
    ///  Hosts have no bundle dependencies, so this returns an empty array.
    ///  Guests use HostInterface::get_dependencies for their actual deps.
    ///
    ///  # Arguments
    ///  - `this`: RuntimeInterface pointer (self-passing)
    ///
    ///  # Returns
    ///  Empty Array of DependencyInfo. Caller owns and must free.
    public unsafeextern"C"fn(this:*constRuntimeInterface,)->Array<DependencyInfo> GetDependencies;
    ///  Destroy the runtime and free this interface.
    ///
    ///  # Arguments
    ///  - `this`: RuntimeInterface pointer (self-passing)
    ///
    ///  # Safety
    ///  After calling destroy, the pointer is invalid and must not be used.
    ///  All instances must be destroyed before calling this.
    public unsafeextern"C"fn(this:*constRuntimeInterface) Destroy;
}

///  Opaque handle to a host contract instance.
///
///  Created by `HostContractInterface::create_instance`, destroyed by `destroy_instance`.
///  For singleton host contracts, the same instance is returned for all callers.
[StructLayout(LayoutKind.Sequential)]
public struct HostContractInstance
{
    ///  Opaque instance data pointer.
    ///  The actual data is owned by the host.
    public IntPtr Data;
}

///  Host Contract Interface — for host-provided services.
///
///  Host contracts are services provided by the host application to plugins.
///
///  # Who provides
///  Host application code creates this struct and registers it with the runtime.
///  Must be `'static` or intentionally leaked.
///
///  # Who calls
///  Guest (plugin) code calls the dispatch functions after obtaining an instance
///  via `HostInterface::get_host_contract()`.
///
///  # Ownership
///  Must be `'static`. The runtime holds a reference for the plugin lifetime.
///  Never freed while runtime lives.
///
///  # Lifetime
///  Lives for the entire runtime lifetime. Must survive hot-reload.
///
///  # Singleton Mode
///  - `singleton == true`: Same instance returned for all callers
///  - `singleton == false`: New instance per caller (caller must destroy)
///
///  # Self-Passing Pattern
///  `create_instance` and `destroy_instance` take `self: *const HostContractInterface`.
///  The runtime field provides access to runtime services.
[StructLayout(LayoutKind.Sequential)]
public struct HostContractInterface
{
    ///  FNV-1a hash of "host_contract:name@major_version".
    ///
    ///  Generated by polyplugc from contract name and major version.
    ///  Used for contract lookup via `get_host_contract`.
    public HostContractId ContractId;
    ///  Contract version (major, minor, patch).
    ///
    ///  Used for version compatibility checks during lookup.
    public Version ContractVersion;
    ///  Whether this contract provides a singleton instance.
    ///
    ///  If true, `get_host_contract` returns the same instance for all callers.
    ///  If false, each call returns a new instance that caller must destroy.
    public bool Singleton;
    ///  Dispatch mechanism type (Native or VirtualMachine).
    ///
    ///  Host contracts typically use Native dispatch for direct calls.
    public DispatchType DispatchType;
    ///  Opaque pointer to Runtime.
    ///
    ///  Host contracts can use this for runtime-specific operations.
    ///  Set during interface registration.
    ///
    ///  # Ownership
    ///  Owned by the runtime. Host contract implementations must not free.
    public IntPtr Runtime;
    ///  Create a new instance of this host contract.
    ///
    ///  For singleton contracts, this is typically called once and the instance
    ///  is cached. For multi-instance contracts, called for each get_host_contract.
    ///
    ///  # Arguments
    ///  - `this`: HostContractInterface pointer (self-passing pattern)
    ///  - `args`: Optional initialization arguments (contract-specific)
    ///
    ///  # Returns
    ///  Opaque instance handle, or null handle on failure.
    public unsafeextern"C"fn(this:*constHostContractInterface,args:*const(),)->HostContractInstance CreateInstance;
    ///  Destroy an instance of this host contract.
    ///
    ///  For singleton contracts, this is typically a no-op (singleton lives forever).
    ///  For multi-instance contracts, caller must destroy after use.
    ///
    ///  # Arguments
    ///  - `this`: HostContractInterface pointer (self-passing pattern)
    ///  - `instance`: Instance handle to destroy
    ///
    ///  # Safety
    ///  After calling destroy_instance, the instance handle is invalid.
    public unsafeextern"C"fn(this:*constHostContractInterface,instance:HostContractInstance,) DestroyInstance;
    ///  Union of dispatch mechanisms — access based on dispatch_type.
    ///
    ///  For Native dispatch: use `dispatch.native.functions[fn_id]`.
    ///  For VM dispatch: use `dispatch.vm.call(loader_data, instance, fn_id, args, out)`.
    public DispatchMechanisms Dispatch;
}

///  Context passed to every guest `polyplug_init()` function.
///
///  # OWNERSHIP
///  The `bundle_path` pointer is runtime-owned and valid for the lifetime of the `PluginRuntime`.
///  **Plugin must not store the raw pointer** — copy the string value if persistence is needed.
[StructLayout(LayoutKind.Sequential)]
public struct BundleInitContext
{
    ///  Bundle ID for dependency enforcement during init.
    public ulong BundleId;
    ///  Absolute canonical path to the directory containing the loaded bundle.
    public StringView BundlePath;
}

///  Metadata about a plugin within a bundle.
///
///  # OWNERSHIP
///  value type passed by pointer during init. The `name` and
///  `contract_name` StringViews are borrowed from the plugin's static memory.
///  The receiver must not free or outlive the plugin's library.
[StructLayout(LayoutKind.Sequential)]
public struct PluginDescriptor
{
    ///  Human-readable plugin name.
    public StringView Name;
    ///  Full contract name for collision detection.
    public StringView ContractName;
    ///  Plugin version
    public Version Version;
}

///  Opaque handle to a registered guest contract.
///
///  The handle is just an index into the registry array.
///  Out-of-bounds indices return InvalidHandle error.
///
///  # Naming
///  Named `GuestContractHandle` for consistency with `GuestContractInterface`
///  and `GuestContractInstance`.
///
///  # Layout
///  - `index`: Slot index in the registry (u32)
///
///  # Safety
///  Handles become stale after unload. Call `resolve_contract` to validate.
///  Returns null pointer if the handle is invalid.
[StructLayout(LayoutKind.Sequential)]
public struct GuestContractHandle
{
    ///  Slot in the registry array.
    public uint Index;
}

///  Configuration for the polyplug runtime passed to `polyplug_runtime_create`.
///
///  # OWNERSHIP
///  Borrowed for the duration of the runtime build only.
///  The runtime copies any data it needs to retain.
[StructLayout(LayoutKind.Sequential)]
public struct RuntimeConfig
{
    ///  Compatibility mode for version resolution.
    public Compatibility Compatibility;
    ///  Whether hot-reload is enabled.
    public bool HotReloadEnabled;
    ///  Optional hot-reload callback, or null for no callback.
    public Option<unsafeextern"C"fn(ReloadPhase)> OnReload;
}

///  FFI-safe reload phase for hot-reload callbacks.
///
///  Tagged union style struct — `phase_type` indicates which variant is active.
///  Uses `StringView` for FFI compatibility (non-owning borrows).
///
///  # Lifetime
///  `StringView` fields are borrowed from the caller's strings.
///  The callback must not store these views beyond the callback scope.
[StructLayout(LayoutKind.Sequential)]
public struct ReloadPhase
{
    ///  Type of reload phase.
    public ReloadPhaseType PhaseType;
    ///  Bundle being reloaded.
    public BundleId BundleId;
    ///  Bundle name (borrowed string).
    public StringView BundleName;
    ///  Failure reason (only for Failed phase).
    public StringView Reason;
}

///  ABI error — returned by value from all ABI calls.
///
///  OWNERSHIP: `code` is a value type. `message.ptr` is allocated by the callee
///  via `host_alloc`. Caller frees with `polyplug_host_free(message.ptr, message.len, 1)`
///  after reading. If `code == AbiErrorCode::Ok`, `message.ptr` is NULL — no free needed.
[StructLayout(LayoutKind.Sequential)]
public struct AbiError
{
    ///  0 = success, non-zero = error.
    public AbiErrorCode Code;
    ///  Empty/NULL if success. UTF-8 message if non-zero code.
    public StringView Message;
}

///  FFI-safe array with caller-frees ownership model.
///
///  # Memory Management
///  - Allocated via `host->alloc(self, len * sizeof(T), align)`
///  - Freed via `host->free(self, items, len * sizeof(T), align)`
///
///  # Ownership
///  Caller owns the memory and must free via host allocator.
///  CodeGen generates RAII wrappers in each language SDK:
///  - Rust: `Drop` impl calls `host->free`
///  - Python: `__del__` calls free
///  - C#: `IDisposable.Dispose` calls free
///
///  # Safety
///  The `align` field is required for proper freeing. Generic code must
///  track alignment of `T` to free correctly.
///
///  # Thread Safety
///  Safe to read from multiple threads if underlying data is immutable.
///  Send/Sync implemented for T: Send/Sync.
[StructLayout(LayoutKind.Sequential)]
public struct Array
{
    ///  Pointer to elements, allocated via host allocator.
    ///
    ///  # Ownership
    ///  Caller owns. Must be freed via `host->free` with same size/align.
    public IntPtr Items;
    ///  Number of elements.
    ///
    ///  Used to calculate total size for freeing: `len * sizeof(T)`.
    public nuint Len;
    ///  Alignment of T, for proper freeing.
    ///
    ///  # Purpose
    ///  Required because generic code may not know T's alignment at runtime.
    ///  Must match `align_of::<T>()` used during allocation.
    public nuint Align;
}

///  Owning byte buffer.
///
///  OWNERSHIP: `ptr` is always allocated via `polyplug_host_alloc`.
///  Owner calls `polyplug_host_free(ptr, cap, align)` when done.
[StructLayout(LayoutKind.Sequential)]
public struct Buffer
{
    public IntPtr Ptr;
    ///  Bytes currently used.
    public nuint Len;
    ///  Bytes allocated.
    public nuint Cap;
}

///  Dependency information returned by get_dependencies introspection API.
///
///  Mirrors `manifest.toml` `\[dependency\]` table structure for plugins to query
///  their own declared dependencies at runtime.
///
///  # Who provides
///  Runtime returns this from `HostInterface::get_dependencies`.
///
///  # Who calls
///  Guest (plugin) code calls `get_dependencies` during initialization
///  to discover available dependencies.
///
///  # Ownership
///  Returned in an Array that caller owns and must free via `host->free`.
///
///  # Fields
///  - `contract_id`: The contract being depended upon
///  - `min_version`: Minimum version required
///  - `bundle_id`: Specific bundle if ByBundle, 0 if ByContract
[StructLayout(LayoutKind.Sequential)]
public struct DependencyInfo
{
    ///  Contract ID of the dependency.
    ///
    ///  FNV-1a hash of the contract name and major version.
    ///  Use this to find matching contracts via `find_by_contract`.
    public GuestContractId ContractId;
    ///  Minimum version required.
    ///
    ///  Used for version compatibility checks during contract lookup.
    ///  Contracts with version >= min_version will match.
    public uint MinVersion;
    ///  Bundle ID if dependency is ByBundle, 0 if ByContract.
    ///
    ///  # ByBundle vs ByContract
    ///  - `bundle_id != 0`: Dependency is on a specific bundle
    ///  - `bundle_id == 0`: Dependency is on any bundle providing the contract
    public BundleId BundleId;
}

///  Non-owning UTF-8 string view.
///
///  OWNERSHIP: borrowed reference. `ptr` must remain valid for the duration
///  of the call. Never freed by the receiver.
[StructLayout(LayoutKind.Sequential)]
public struct StringView
{
    ///  UTF-8 bytes, NOT null-terminated.
    public IntPtr Ptr;
    ///  Byte count.
    public nuint Len;
}

///  A three-component semantic version (major.minor.patch).
[StructLayout(LayoutKind.Sequential)]
public struct Version
{
    ///  Major version.
    public uint Major;
    ///  Minor version.
    public uint Minor;
    ///  Patch version.
    public uint Patch;
}

public enum ContractType : uint
{
    Host = 0,
    Plugin = 1,
}

///  Dispatch mechanism type — determines how function calls are routed.
public enum DispatchType : uint
{
    ///  Native dispatch: direct function pointer calls (zero overhead).
    Native = 0,
    ///  VM dispatch: call through a dispatch function with loader_data.
    VirtualMachine = 1,
}

///  How strictly version compatibility is enforced when resolving plugins.
public enum Compatibility : uint
{
    ///  Exact major match and minor >= required.
    Strict = 0,
    ///  Same major, any minor.
    Relaxed = 1,
    ///  Any version accepted.
    Yolo = 2,
}

///  Type of reload phase for FFI callbacks.
public enum ReloadPhaseType : uint
{
    ///  Bundle is being prepared for reload.
    Preparing = 0,
    ///  Bundle has been successfully reloaded.
    Reloaded = 1,
    ///  Bundle reload failed.
    Failed = 2,
}

///  Runtime type identifier — identifies the language/runtime hosting plugins.
public enum RuntimeLanguage : uint
{
    Rust = 0,
    Cpp = 1,
    Dotnet = 2,
    Python = 3,
    Lua = 4,
    JavaScript = 5,
}

///  ABI error codes (reserved: 0-255 runtime, 256+ plugin-defined).
///
///  These codes are returned by all ABI functions to indicate success or failure.
///  The `code` field of `AbiError` uses these values.
public enum AbiErrorCode : uint
{
    ///  Success — no error.
    Ok = 0,
    ///  Generic error — unspecified failure.
    Generic = 1,
    ///  Buffer too small — caller must reallocate (see Buffer protocol).
    BufferTooSmall = 2,
    ///  Panic — plugin panicked (caught by catch_unwind).
    Panic = 3,
    ///  Not found — plugin/contract not found.
    NotFound = 4,
    ///  Stale handle — GuestContractHandle is invalid (contract unloaded).
    StaleHandle = 5,
    ///  Function not available — function_id >= function_count.
    FunctionNotAvailable = 6,
    ///  Duplicate provider — same bundle already provides this contract.
    DuplicateProvider = 7,
    ///  Invalid pointer — null or invalid pointer passed to ABI function.
    InvalidPointer = 8,
    ///  Host contract not found — no host contract matches contract_id.
    HostContractNotFound = 100,
    ///  Host contract version mismatch — host contract version does not match.
    HostContractVersionMismatch = 101,
    ///  Host contract call failed — host contract function call failed.
    HostContractCallFailed = 102,
}

public enum ParseVersionError : uint
{
    InvalidFormat = 0,
    InvalidInt = 1,
}

///  Union of dispatch mechanisms — use based on `dispatch_type`.
///
///  # Safety
///  Access the correct variant based on `GuestContractInterface::dispatch_type`:
///  - `dispatch_type == Native` → access `.native`
///  - `dispatch_type == VirtualMachine` → access `.vm`
[StructLayout(LayoutKind.Explicit)]
public struct DispatchMechanisms
{
    [FieldOffset(0)]
    public NativeDispatch Native;
    [FieldOffset(0)]
    public VmDispatch Vm;
}


/// ABI error codes — returned by all ABI functions.
public enum AbiErrorCode : uint
{
    Ok = 0,
    Generic = 1,
    BufferTooSmall = 2,
    Panic = 3,
    NotFound = 4,
    StaleHandle = 5,
    FunctionNotAvailable = 6,
    DuplicateProvider = 7,
    InvalidPointer = 8,
    HostContractNotFound = 100,
    HostContractVersionMismatch = 101,
    HostContractCallFailed = 102,
}

/// ABI constants for polyplug.
public static class AbiConstants
{
    public const uint POLYPLUG_ABI_VERSION = 1u;
}
}
