[bundle]
name = "python_transformer"
version = "1.0.0"
api = "../../../api.toml"
loader = "python"
file = "transformer.py"

[[plugin]]
name = "transformer"
version = "1.0.0"
implements = ["data.Transformer@1.0"]

[[dependency]]
kind = "contract"
contract = "pipeline.Validator"
min_version = "1.0"
