// THIS FILE IS AUTO-GENERATED BY polyplugc
// DO NOT EDIT BY HAND
// Re-generate with: polyplugc generate --api api.toml --lang ts-node --out <dir>

/**
 * A read-only view into a UTF-8 string in the host's address space.
 * `ptr` is a pointer (as bigint) to the first byte; `len` is the byte count.
 */
export interface StringView {
    readonly ptr: bigint;
    readonly len: number;
}

/**
 * A growable byte buffer owned by the host allocator.
 * `ptr` is a pointer (as bigint) to the first byte; `len` is current length; `cap` is capacity.
 */
export interface Buffer {
    readonly ptr: bigint;
    readonly len: number;
    readonly cap: number;
}

/**
 * Error code returned from ABI functions. `code === 0` means success (ABI_OK).
 * `message` is a StringView pointing to an optional error description.
 */
export interface AbiError {
    readonly code: number;
    readonly message: StringView;
}

/** ABI_OK sentinel value — an AbiError with code 0 means success. */
export const ABI_OK: number = 0;

/**
 * An opaque handle to a loaded plugin instance.
 * `index` identifies the plugin slot; `generation` guards against stale handles.
 */
export interface PluginHandle {
    readonly index: number;
    readonly generation: number;
}

/**
 * The vtable registered by a plugin via `polyplug_init`.
 * `functions` is a pointer (as bigint) to an array of function pointers.
 */
export interface PluginVTable {
    readonly contract_id: bigint;
    readonly contract_version: number;
    readonly function_count: number;
    readonly functions: bigint;
}

/**
 * Descriptor passed by a plugin during registration.
 */
export interface PluginDescriptor {
    readonly name: StringView;
    readonly contract_name: StringView;
    readonly version_major: number;
    readonly version_minor: number;
    readonly version_patch: number;
}

/**
 * The registrar passed to `polyplug_init`. Plugins call `register_plugin`
 * to register their vtable.
 */
export interface PluginRegistrar {
    readonly register_plugin: bigint;
    readonly host: bigint;
}

/**
 * Entry point that every compiled `.node` plugin must export.
 * Signature: `extern "C" fn(*mut PluginRegistrar) -> AbiError`.
 *
 * When polyplug-js loads a `.node` bundle, it resolves this symbol and calls it
 * with a pointer to a `PluginRegistrar`. The plugin must call `register_plugin`
 * for each contract it implements.
 *
 * The `.node` file is a compiled native addon — this entry point is a plain C symbol,
 * not a JavaScript function.
 */
export type PolyplugInitFn = (registrar_ptr: bigint) => AbiError;

/**
 * TypeScript → ABI type mapping reference (for code generators):
 *
 * Primitive types:
 *   u8 / u16 / u32 / i8 / i16 / i32 / f32 / f64 → number
 *   u64 / i64                                   → bigint
 *   bool                                        → boolean
 *
 * ABI types:
 *   StringView → StringView (interface above)
 *   Buffer     → Buffer (interface above)
 *   ptr        → bigint
 *   void       → void
 *
 * User-defined structs → corresponding TypeScript interface
 */
export {}; // ensure this is treated as a module
