//! Integration test: verify the generated catch_unwind ABI wrapper catches a panic
//! and returns ABI_ERROR_PANIC (= 3) WITHOUT aborting the process.
//!
//! This test crate is the crate root for the `integration_panic` test binary.
//! (AGENTS.md Rule 1: module roots use dirname/mod.rs)

#![allow(clippy::expect_used)]

use std::path::Path;
use std::path::PathBuf;
use std::process::Command;
use std::process::ExitStatus;

use polyplug::abi::ABI_ERROR_PANIC;
use polyplug::abi::AbiError;
use polyplug::abi::PluginDescriptor;
use polyplug::abi::PluginRegistrar;
use polyplug::abi::PluginVTable;
use polyplug::abi::StringView;

// ─── Registrar callback that stores the vtable pointer ───────────────────────

/// Global storage for the vtable pointer captured during `polyplug_init`.
///
/// # Safety
/// Only written by `capture_register_callback` which is called once during
/// `polyplug_init`, before the vtable pointer is read in the test.
static mut CAPTURED_VTABLE_PTR: *const PluginVTable = core::ptr::null();

/// A minimal registrar callback that captures the vtable pointer.
///
/// # Safety
/// `_reg`, `_desc`, and `vtable` must be valid for the duration of the call.
unsafe extern "C" fn capture_register_callback(
    _reg: *mut PluginRegistrar,
    _desc: *const PluginDescriptor,
    vtable: *const PluginVTable,
) -> AbiError {
    // SAFETY: CAPTURED_VTABLE_PTR is only written here, during polyplug_init,
    // before the test reads it. Single-threaded test execution ensures no data race.
    unsafe {
        CAPTURED_VTABLE_PTR = vtable;
    }
    AbiError {
        code: 0,
        message: StringView {
            ptr: core::ptr::null(),
            len: 0,
        },
    }
}

// ─── Test ─────────────────────────────────────────────────────────────────────

#[test]
fn test_panic_returns_abi_error_panic() {
    // ── Step 1: Locate workspace root and polyplugc binary ────────────────────
    let manifest_dir: &Path = Path::new(env!("CARGO_MANIFEST_DIR"));
    // CARGO_MANIFEST_DIR = crates/polyplug; workspace root is two up.
    let workspace_root: &Path = manifest_dir
        .parent()
        .expect("crates parent")
        .parent()
        .expect("workspace root");

    let api_toml: PathBuf = workspace_root
        .join("tests")
        .join("fixtures")
        .join("test_panic_api.toml");

    // ── Step 2: Create a temp directory for the panic plugin crate ────────────
    let tmp_dir: PathBuf = std::env::temp_dir().join("polyplug_panic_plugin_test");
    std::fs::create_dir_all(&tmp_dir).expect("create tmp dir");
    std::fs::create_dir_all(tmp_dir.join("src")).expect("create tmp src dir");

    // ── Step 3: Run polyplugc generate into tmp_dir/src ───────────────────────
    let polyplugc_bin: &str = env!("CARGO_BIN_EXE_polyplugc");
    let gen_status: ExitStatus = Command::new(polyplugc_bin)
        .arg("generate")
        .arg("--api")
        .arg(&api_toml)
        .arg("--lang")
        .arg("rust")
        .arg("--out")
        .arg(tmp_dir.join("src"))
        .status()
        .expect("polyplugc generate failed to run");

    assert!(
        gen_status.success(),
        "polyplugc generate exited with non-zero status"
    );

    // ── Step 4: Write Cargo.toml for the cdylib crate ─────────────────────────
    // Only depend on polyplug-guest; polyplug is an indirect dep.
    // We do NOT add polyplug as a direct dep to avoid duplicate
    // `polyplug_abi_version` symbol (it is defined in polyplug/src/lib.rs).
    let guest_lib_path: PathBuf = workspace_root.join("guest-libs").join("rust");
    let cargo_toml_content: String = format!(
        "[package]\n\
         name = \"panic_plugin\"\n\
         version = \"0.1.0\"\n\
         edition = \"2024\"\n\
         \n\
         [lib]\n\
         name = \"panic_plugin\"\n\
         crate-type = [\"cdylib\"]\n\
         \n\
         [dependencies]\n\
         polyplug-guest = {{ path = \"{}\" }}\n",
        guest_lib_path.display()
    );
    std::fs::write(tmp_dir.join("Cargo.toml"), &cargo_toml_content).expect("write Cargo.toml");

    // ── Step 5: Write src/lib.rs implementing TestPanicPlugin ─────────────────
    // The generated src/vtables.rs, src/contracts.rs, src/types.rs already exist.
    // We provide the crate root lib.rs that declares those mods and implements the trait.
    // We do NOT include mod init; — we write our own polyplug_init here.
    // We do NOT define polyplug_abi_version — it comes from polyplug rlib.
    let lib_rs_content: &str = concat!(
        "// THIS FILE IS WRITTEN BY THE integration_panic TEST — NOT generated by polyplugc.\n",
        "// It implements the TestPanicPlugin trait with a function that always panics.\n",
        "\n",
        "mod types;\n",
        "mod contracts;\n",
        "mod vtables;\n",
        "\n",
        "use polyplug_guest::AbiError;\n",
        "use polyplug_guest::PluginDescriptor;\n",
        "use polyplug_guest::PluginError;\n",
        "use polyplug_guest::PluginRegistrar;\n",
        "use polyplug_guest::PluginVTable;\n",
        "use polyplug_guest::StringView;\n",
        "use polyplug_guest::ABI_ERROR_GENERIC;\n",
        "use vtables::TEST_PANIC_IMPL;\n",
        "use vtables::TEST_PANIC_VTABLE;\n",
        "use contracts::TestPanicPlugin;\n",
        "\n",
        "struct PanicPlugin;\n",
        "\n",
        "impl TestPanicPlugin for PanicPlugin {\n",
        "    fn do_panic(&self) -> Result<(), PluginError> {\n",
        "        panic!(\"intentional test panic\");\n",
        "    }\n",
        "}\n",
        "\n",
        "/// Register the panic plugin vtable with the host.\n",
        "///\n",
        "/// # Safety\n",
        "/// `registrar` must be a valid non-null pointer to a PluginRegistrar.\n",
        "#[unsafe(no_mangle)]\n",
        "pub unsafe extern \"C\" fn polyplug_init(registrar: *mut PluginRegistrar) -> AbiError {\n",
        "    TEST_PANIC_IMPL.get_or_init(|| Box::new(PanicPlugin));\n",
        "    if registrar.is_null() {\n",
        "        return AbiError {\n",
        "            code: ABI_ERROR_GENERIC,\n",
        "            message: StringView::null(),\n",
        "        };\n",
        "    }\n",
        "    // SAFETY: registrar is non-null and valid per ABI contract.\n",
        "    let reg: &mut PluginRegistrar = unsafe { &mut *registrar };\n",
        "    let desc: PluginDescriptor = PluginDescriptor {\n",
        "        name: StringView {\n",
        "            ptr: b\"panic_plugin\".as_ptr(),\n",
        "            len: 12_usize,\n",
        "        },\n",
        "        contract_name: StringView {\n",
        "            ptr: b\"test.panic\".as_ptr(),\n",
        "            len: 10_usize,\n",
        "        },\n",
        "        version_major: 1_u32,\n",
        "        version_minor: 0_u32,\n",
        "        version_patch: 0_u32,\n",
        "    };\n",
        "    // SAFETY: desc and vtable are valid for the duration of the call.\n",
        "    unsafe {\n",
        "        (reg.register_plugin)(\n",
        "            registrar,\n",
        "            &desc as *const PluginDescriptor,\n",
        "            &TEST_PANIC_VTABLE as *const PluginVTable,\n",
        "        )\n",
        "    }\n",
        "}\n",
    );
    std::fs::write(tmp_dir.join("src").join("lib.rs"), lib_rs_content).expect("write src/lib.rs");

    // ── Step 6: Build the cdylib ───────────────────────────────────────────────
    let build_status: ExitStatus = Command::new(env!("CARGO"))
        .arg("build")
        .arg("--manifest-path")
        .arg(tmp_dir.join("Cargo.toml"))
        .arg("--release")
        .status()
        .expect("cargo build failed to run");

    assert!(
        build_status.success(),
        "cargo build for panic_plugin cdylib failed"
    );

    // ── Step 7: Locate the compiled .so ───────────────────────────────────────
    let lib_filename: &str = if cfg!(target_os = "macos") {
        "libpanic_plugin.dylib"
    } else if cfg!(target_os = "windows") {
        "panic_plugin.dll"
    } else {
        "libpanic_plugin.so"
    };

    let so_path: PathBuf = tmp_dir.join("target").join("release").join(lib_filename);

    // ── Step 8: Load with libloading ──────────────────────────────────────────
    // SAFETY: so_path is a compiled cdylib.
    let library: libloading::Library = unsafe {
        libloading::Library::new(&so_path).expect("failed to load panic_plugin shared library")
    };

    // ── Step 9: Resolve and call polyplug_init ────────────────────────────────
    // SAFETY: polyplug_init matches the expected ABI signature.
    let init_fn: libloading::Symbol<'_, unsafe extern "C" fn(*mut PluginRegistrar) -> AbiError> = unsafe {
        library
            .get(b"polyplug_init\0")
            .expect("polyplug_init symbol not found")
    };

    let mut registrar: PluginRegistrar = PluginRegistrar {
        register_plugin: capture_register_callback,
        host: core::ptr::null(),
    };

    // SAFETY: init_fn is valid; registrar lives for the call duration.
    let init_result: AbiError = unsafe { init_fn(&mut registrar as *mut PluginRegistrar) };
    assert_eq!(init_result.code, 0, "polyplug_init must succeed (code 0)");

    // SAFETY: CAPTURED_VTABLE_PTR was written by capture_register_callback above.
    // Single-threaded; no race condition.
    let vtable_ptr: *const PluginVTable = unsafe { CAPTURED_VTABLE_PTR };
    assert!(!vtable_ptr.is_null(), "vtable pointer must be non-null");

    // SAFETY: vtable_ptr is valid (plugin library is loaded, not yet dropped).
    let vtable: &PluginVTable = unsafe { &*vtable_ptr };

    assert_eq!(
        vtable.function_count, 1_u32,
        "test.panic vtable must have 1 function"
    );

    // ── Step 10: Call function_id 0 (do_panic) through the vtable ────────────
    // The generated ABI wrapper uses catch_unwind internally, so the panic is
    // caught inside the extern "C" boundary. The host sees AbiError { code: 3 }.

    // SAFETY: fn_ptr is function 0 in the vtable (do_panic).
    let fn_ptr: *const () = unsafe { *vtable.functions.add(0) };
    let dispatch_fn: unsafe extern "C" fn(*const (), *mut ()) -> AbiError =
        // SAFETY: fn_ptr is the do_panic ABI wrapper — extern "C" with no
        // meaningful args/out (void, no params). The catch_unwind wrapper
        // inside the plugin catches the panic before it crosses the FFI boundary.
        unsafe { core::mem::transmute(fn_ptr) };

    // SAFETY: do_panic ignores args and out entirely (void function, no params).
    let call_result: AbiError = unsafe { dispatch_fn(core::ptr::null(), core::ptr::null_mut()) };

    // ── Step 11: Assert panic was caught and returned ABI_ERROR_PANIC ─────────
    assert_eq!(
        call_result.code, ABI_ERROR_PANIC,
        "do_panic ABI wrapper must return ABI_ERROR_PANIC (={ABI_ERROR_PANIC}), got {}",
        call_result.code
    );

    // Process continues here — no abort occurred. Test completing IS the proof.

    // Leak the library to avoid dlclose issues on some platforms.
    std::mem::forget(library);
}
