[bundle]
name = "python_reporter"
version = "1.0.0"
api = "../../../api.toml"
runtime = "python"
file = "reporter.py"

[[plugin]]
name = "reporter"
version = "1.0.0"
contracts = ["data.Reporter@1.0"]
