[bundle]
name = "python_reporter"
version = "1.0.0"
api = "../../../api.toml"
loader = "python"
file = "reporter.py"

[[plugin]]
name = "reporter"
version = "1.0.0"
implements = ["data.Reporter@1.0"]
