//! C++ code generator for polyplugc.
//!
//! Generates:
//! - Host-side: header-only C++ callers (RAII wrapper + vtable dispatch)
//! - Guest-side: extern "C" ABI wrappers + abstract base classes + vtable statics

use crate::error::CodegenError;
use crate::generators::CodeGenerator;
use crate::generators::GeneratedFile;
use crate::generators::GeneratedFiles;
use crate::ir::AbiBuiltin;
use crate::ir::PrimitiveType;
use crate::ir::ResolvedContract;
use crate::ir::ResolvedFunction;
use crate::ir::ResolvedType;
use crate::ir::ResolvedTypeRef;
use crate::ir::ValidatedIr;

/// The C++ code generator.
pub(crate) struct CppGenerator;

impl CodeGenerator for CppGenerator {
    fn language_name(&self) -> &'static str {
        "cpp"
    }

    fn generate_host(
        &self,
        ir: &ValidatedIr,
        files: &mut GeneratedFiles,
    ) -> Result<(), CodegenError> {
        // ── File 1: types.hpp ────────────────────────────────────────────────
        let types_hpp: String = generate_types_hpp(ir);
        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("types.hpp"),
            content: types_hpp,
        });

        // ── File 2: host_callers.hpp ─────────────────────────────────────────
        let host_callers_hpp: String = generate_host_callers_hpp(ir)?;
        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("host_callers.hpp"),
            content: host_callers_hpp,
        });

        // ── File 3: manifest.toml ────────────────────────────────────────────
        let manifest_toml: String = generate_manifest_toml();
        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("manifest.toml"),
            content: manifest_toml,
        });

        Ok(())
    }

    fn generate_guest(
        &self,
        ir: &ValidatedIr,
        files: &mut GeneratedFiles,
    ) -> Result<(), CodegenError> {
        // ── File 1: types.hpp ────────────────────────────────────────────────
        let types_hpp: String = generate_types_hpp(ir);
        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("types.hpp"),
            content: types_hpp,
        });

        // ── File 2: contracts.hpp ────────────────────────────────────────────
        let contracts_hpp: String = generate_contracts_hpp(ir);
        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("contracts.hpp"),
            content: contracts_hpp,
        });

        // ── File 3: vtables.hpp ──────────────────────────────────────────────
        let vtables_hpp: String = generate_vtables_hpp(ir)?;
        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("vtables.hpp"),
            content: vtables_hpp,
        });

        // ── File 4: init.hpp ─────────────────────────────────────────────────
        let init_hpp: String = generate_init_hpp(ir)?;
        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("init.hpp"),
            content: init_hpp,
        });

        // ── File 5: manifest.toml ────────────────────────────────────────────
        let manifest_toml: String = generate_manifest_toml();
        files.files.push(GeneratedFile {
            path: std::path::PathBuf::from("manifest.toml"),
            content: manifest_toml,
        });

        Ok(())
    }
}

// ─── types.hpp generator ─────────────────────────────────────────────────────

fn generate_types_hpp(ir: &ValidatedIr) -> String {
    let mut out: String = String::new();
    out.push_str("// THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n");
    out.push_str("// Re-generate with: polyplugc generate --api api.toml --lang cpp --out <dir>\n");
    out.push_str("#pragma once\n");
    out.push_str("#include <cstdint>\n");
    out.push_str("#include \"polyplug/abi.hpp\"\n\n");

    for ty in &ir.types {
        generate_cpp_type(&mut out, ty);
    }

    out
}

// ─── contracts.hpp generator ─────────────────────────────────────────────────

fn generate_contracts_hpp(ir: &ValidatedIr) -> String {
    let mut out: String = String::new();
    out.push_str("// THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n");
    out.push_str("// Re-generate with: polyplugc generate --api api.toml --lang cpp --out <dir>\n");
    out.push_str("#pragma once\n");
    out.push_str("#include \"types.hpp\"\n");
    out.push_str("#include <cstdint>\n\n");
    out.push_str("namespace polyplug_plugin {\n\n");
    out.push_str("struct PolyplugError { uint32_t code; };\n\n");

    for contract in &ir.contracts {
        generate_cpp_guest_contract_class(&mut out, contract);
    }

    out.push_str("}  // namespace polyplug_plugin\n");
    out
}

fn generate_cpp_guest_contract_class(out: &mut String, contract: &ResolvedContract) {
    let class_name: String = contract_name_to_plugin_class(&contract.name);
    out.push_str(&format!(
        "/// Abstract plugin base for contract `{}` (id=0x{:016X})\n",
        contract.name, contract.contract_id
    ));
    out.push_str(&format!("class {} {{\npublic:\n", class_name));
    out.push_str(&format!("    virtual ~{}() = default;\n", class_name));

    for func in &contract.functions {
        generate_cpp_guest_abstract_method(out, func);
    }

    out.push_str("};\n\n");
}

fn generate_cpp_guest_abstract_method(out: &mut String, func: &ResolvedFunction) {
    let return_type: String = func
        .returns
        .as_ref()
        .map(cpp_type_name)
        .unwrap_or_else(|| "void".to_owned());

    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| {
            let cpp_ty: String = cpp_type_name(&p.ty);
            match &p.ty {
                ResolvedTypeRef::UserDefined(_) => format!("const {}& {}", cpp_ty, p.name),
                ResolvedTypeRef::Primitive(_) | ResolvedTypeRef::AbiType(_) => {
                    format!("{} {}", cpp_ty, p.name)
                }
            }
        })
        .collect();
    let params_str: String = params.join(", ");

    out.push_str(&format!(
        "    virtual {} {}({}) = 0;\n",
        return_type, func.name, params_str
    ));
}

// ─── vtables.hpp generator ───────────────────────────────────────────────────

fn generate_vtables_hpp(ir: &ValidatedIr) -> Result<String, CodegenError> {
    let mut out: String = String::new();
    out.push_str("// THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n");
    out.push_str("// Re-generate with: polyplugc generate --api api.toml --lang cpp --out <dir>\n");
    out.push_str("#pragma once\n");
    out.push_str("#include \"contracts.hpp\"\n");
    out.push_str("#include \"polyplug/abi.hpp\"\n");
    out.push_str("#include <cstdint>\n");
    out.push_str("#include <exception>\n\n");
    out.push_str("namespace polyplug_plugin {\n\n");

    for contract in &ir.contracts {
        generate_cpp_guest_contract_vtable(&mut out, contract)?;
    }

    out.push_str("}  // namespace polyplug_plugin\n");
    Ok(out)
}

fn generate_cpp_guest_contract_vtable(
    out: &mut String,
    contract: &ResolvedContract,
) -> Result<(), CodegenError> {
    let lower: String = contract_name_to_lower_snake(&contract.name);
    let upper: String = contract_name_to_upper_snake(&contract.name);
    let class_name: String = contract_name_to_plugin_class(&contract.name);
    let fn_count: usize = contract.functions.len();
    let contract_version: u32 = (contract.version.minor << 16) | contract.version.patch;

    // Forward declaration of impl pointer
    out.push_str("// Forward declaration -- set by polyplug_init\n");
    out.push_str(&format!("extern {}* g_{}_impl;\n\n", class_name, lower));

    // Contract ID constant
    out.push_str(&format!(
        "constexpr uint64_t {}_CONTRACT_ID = 0x{:016X}ULL;\n\n",
        upper, contract.contract_id
    ));

    // ABI wrapper functions — one per function
    for func in &contract.functions {
        generate_cpp_guest_abi_wrapper(out, &lower, func)?;
    }

    // Function pointer array
    out.push_str(&format!("static void* const {}_FNS[] = {{\n", upper));
    for func in &contract.functions {
        out.push_str(&format!(
            "    reinterpret_cast<void*>({0}_{1}_abi),\n",
            lower, func.name
        ));
    }
    out.push_str("};\n\n");

    // VTable static
    out.push_str(&format!("static PluginVTable {}_VTABLE = {{\n", upper));
    out.push_str(&format!("    {}_CONTRACT_ID,\n", upper));
    out.push_str(&format!(
        "    {}U,  // contract_version: (minor << 16) | patch\n",
        contract_version
    ));
    out.push_str(&format!("    {}U,  // function_count\n", fn_count));
    out.push_str(&format!("    {}_FNS\n", upper));
    out.push_str("};\n\n");

    Ok(())
}

fn generate_cpp_guest_abi_wrapper(
    out: &mut String,
    contract_lower: &str,
    func: &ResolvedFunction,
) -> Result<(), CodegenError> {
    let fn_id: u32 = func.function_id;
    let is_void_return: bool = matches!(
        func.returns.as_ref(),
        None | Some(ResolvedTypeRef::AbiType(AbiBuiltin::Void))
    );

    out.push_str(&format!(
        "// ABI wrapper for {} (function_id = {})\n",
        func.name, fn_id
    ));
    out.push_str(&format!(
        "inline AbiError {0}_{1}_abi(const void* args, void* out) noexcept {{\n",
        contract_lower, func.name
    ));
    out.push_str("    try {\n");

    // Build the call expression
    let call_expr: String = build_guest_call_expr(contract_lower, func);
    out.push_str(&call_expr);

    if is_void_return {
        // For void, emit success return (call_expr already emits the call + newline)
        out.push_str("        (void)out;\n");
        out.push_str("        return AbiError{ABI_OK, StringView{nullptr, 0}};\n");
    } else {
        let ret_type: String = func
            .returns
            .as_ref()
            .map(cpp_type_name)
            .unwrap_or_else(|| "void".to_owned());
        out.push_str(&format!(
            "        *static_cast<{}*>(out) = result;\n",
            ret_type
        ));
        out.push_str("        return AbiError{ABI_OK, StringView{nullptr, 0}};\n");
    }

    out.push_str("    } catch (const std::exception&) {\n");
    out.push_str("        return AbiError{1U, StringView{nullptr, 0}};  // ABI_ERROR_GENERIC\n");
    out.push_str("    } catch (...) {\n");
    out.push_str("        return AbiError{3U, StringView{nullptr, 0}};  // ABI_ERROR_PANIC\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    Ok(())
}

/// Build the call-to-impl lines inside the try block.
/// For non-void, assigns `auto result = ...`. For void, just calls.
fn build_guest_call_expr(contract_lower: &str, func: &ResolvedFunction) -> String {
    let is_void_return: bool = matches!(
        func.returns.as_ref(),
        None | Some(ResolvedTypeRef::AbiType(AbiBuiltin::Void))
    );

    let result_prefix: &str = if is_void_return { "" } else { "auto result = " };

    if func.params.is_empty() {
        // No params — ignore args entirely
        return format!(
            "        (void)args;\n        {}g_{}_impl->{}();\n",
            result_prefix, contract_lower, func.name
        );
    }

    if func.params.len() == 1 {
        let param: &crate::ir::ResolvedParam = &func.params[0];
        match &param.ty {
            ResolvedTypeRef::UserDefined(type_name) => {
                // Single user-defined struct param — dereference args directly
                return format!(
                    "        {}g_{}_impl->{}(*static_cast<const {}*>(args));\n",
                    result_prefix, contract_lower, func.name, type_name
                );
            }
            ResolvedTypeRef::Primitive(_) | ResolvedTypeRef::AbiType(_) => {
                // Single primitive param — dereference args as the primitive type
                let cpp_ty: String = cpp_type_name(&param.ty);
                return format!(
                    "        {}g_{}_impl->{}(*static_cast<const {}*>(args));\n",
                    result_prefix, contract_lower, func.name, cpp_ty
                );
            }
        }
    }

    // Multiple params — use a packed struct
    let func_name_cap: String = capitalise_first(&func.name);
    let struct_name: String = format!("{}Args", func_name_cap);

    let mut code: String = String::new();
    // Inline struct definition
    code.push_str(&format!("        struct {} {{", struct_name));
    for param in &func.params {
        let cpp_ty: String = cpp_type_name(&param.ty);
        code.push_str(&format!(" {} {};", cpp_ty, param.name));
    }
    code.push_str(" };\n");

    // Cast args to packed struct pointer
    code.push_str(&format!(
        "        const {name}* packed = static_cast<const {name}*>(args);\n",
        name = struct_name
    ));

    // Build call argument list
    let call_args: Vec<String> = func
        .params
        .iter()
        .map(|p| format!("packed->{}", p.name))
        .collect();
    let call_args_str: String = call_args.join(", ");

    code.push_str(&format!(
        "        {}g_{}_impl->{}({});\n",
        result_prefix, contract_lower, func.name, call_args_str
    ));

    code
}

// ─── init.hpp generator ──────────────────────────────────────────────────────

fn generate_init_hpp(ir: &ValidatedIr) -> Result<String, CodegenError> {
    let mut out: String = String::new();
    out.push_str("// THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n");
    out.push_str("// Re-generate with: polyplugc generate --api api.toml --lang cpp --out <dir>\n");
    out.push_str("#pragma once\n");
    out.push_str("#include \"vtables.hpp\"\n");
    out.push_str("#include \"polyplug/abi.hpp\"\n\n");

    // Definition of impl pointer globals
    out.push_str("namespace polyplug_plugin {\n\n");
    for contract in &ir.contracts {
        let lower: String = contract_name_to_lower_snake(&contract.name);
        let class_name: String = contract_name_to_plugin_class(&contract.name);
        out.push_str(&format!("{}* g_{}_impl = nullptr;\n", class_name, lower));
        out.push_str(&format!(
            "// Developer must define: {}* create_{}_impl();\n",
            class_name, lower
        ));
    }
    out.push_str("\n}  // namespace polyplug_plugin\n\n");

    // Factory forward declarations
    out.push_str("namespace polyplug_plugin {\n");
    for contract in &ir.contracts {
        let lower: String = contract_name_to_lower_snake(&contract.name);
        let class_name: String = contract_name_to_plugin_class(&contract.name);
        out.push_str(&format!("{}* create_{}_impl();\n", class_name, lower));
    }
    out.push_str("}  // namespace polyplug_plugin (forward decls)\n\n");

    // polyplug_abi_version
    out.push_str("extern \"C\" uint32_t polyplug_abi_version() { return 1U; }\n\n");

    // polyplug_init
    out.push_str("extern \"C\" AbiError polyplug_init(PluginRegistrar* registrar) {\n");
    out.push_str("    if (!registrar) return AbiError{1U, StringView{nullptr, 0}};\n\n");

    for contract in &ir.contracts {
        generate_init_hpp_register_contract(&mut out, contract)?;
    }

    out.push_str("    return AbiError{0U, StringView{nullptr, 0}};\n");
    out.push_str("}\n");

    Ok(out)
}

fn generate_init_hpp_register_contract(
    out: &mut String,
    contract: &ResolvedContract,
) -> Result<(), CodegenError> {
    let lower: String = contract_name_to_lower_snake(&contract.name);
    let upper: String = contract_name_to_upper_snake(&contract.name);
    let name_bytes: usize = contract.name.len();

    out.push_str(&format!("    // Register contract: {}\n", contract.name));
    out.push_str(&format!(
        "    polyplug_plugin::g_{0}_impl = polyplug_plugin::create_{0}_impl();\n",
        lower
    ));

    out.push_str("    PluginDescriptor desc_");
    out.push_str(&upper);
    out.push_str(" = {\n");
    out.push_str(&format!(
        "        {{ (const uint8_t*)\"{name}\", {len}U }},  // name\n",
        name = contract.name,
        len = name_bytes
    ));
    out.push_str(&format!(
        "        {{ (const uint8_t*)\"{name}\", {len}U }},  // contract_name\n",
        name = contract.name,
        len = name_bytes
    ));
    out.push_str(&format!(
        "        {}U, {}U, {}U\n",
        contract.version.major, contract.version.minor, contract.version.patch
    ));
    out.push_str("    };\n");

    out.push_str(&format!(
        "    AbiError err_{upper} = registrar->register_plugin(registrar, &desc_{upper}, &polyplug_plugin::{upper}_VTABLE);\n",
        upper = upper
    ));
    out.push_str(&format!(
        "    if (err_{}.code != 0U) return err_{};\n\n",
        upper, upper
    ));

    Ok(())
}

// ─── host_callers.hpp generator ──────────────────────────────────────────────

fn generate_host_callers_hpp(ir: &ValidatedIr) -> Result<String, CodegenError> {
    let mut out: String = String::new();
    out.push_str("// THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n");
    out.push_str("// Re-generate with: polyplugc generate --api api.toml --lang cpp --out <dir>\n");
    out.push_str("#pragma once\n");
    out.push_str("#include \"types.hpp\"\n");
    out.push_str("#include \"polyplug/error.hpp\"\n");
    out.push_str("#include \"polyplug/abi.hpp\"\n\n");
    out.push_str("namespace polyplug_generated {\n\n");

    for contract in &ir.contracts {
        generate_cpp_host_contract(&mut out, contract)?;
    }

    out.push_str("}  // namespace polyplug_generated\n");
    Ok(out)
}

// ─── manifest.toml generator ─────────────────────────────────────────────────

fn generate_manifest_toml() -> String {
    let mut out: String = String::new();
    out.push_str("# THIS FILE IS AUTO-GENERATED BY polyplugc. DO NOT EDIT.\n");
    out.push_str("[manifest]\n");
    out.push_str("schema_version = 1\n");
    out.push_str("lang = \"cpp\"\n");
    out.push_str("generated_by = \"polyplugc\"\n");
    out
}

// ─── Per-type struct emitter ──────────────────────────────────────────────────

fn generate_cpp_type(out: &mut String, ty: &ResolvedType) {
    out.push_str(&format!("/// User-defined type `{}`\n", ty.name));
    out.push_str("struct ");
    out.push_str(&ty.name);
    out.push_str(" {\n");
    for field in &ty.fields {
        out.push_str(&format!(
            "    {} {};\n",
            cpp_type_name(&field.ty),
            field.name
        ));
    }
    out.push_str("};\n\n");
}

// ─── Per-contract class emitter ───────────────────────────────────────────────

fn generate_cpp_host_contract(
    out: &mut String,
    contract: &ResolvedContract,
) -> Result<(), CodegenError> {
    let class_name: String = contract_name_to_class(&contract.name);
    out.push_str(&format!(
        "/// Host caller for contract `{}` (id=0x{:016X})\n",
        contract.name, contract.contract_id
    ));
    out.push_str(&format!("class {} {{\npublic:\n", class_name));
    out.push_str(&format!(
        "    explicit {}(PluginHandle handle, const HostVTable* host) noexcept\n",
        class_name
    ));
    out.push_str("        : handle_(handle), host_(host) {}\n\n");

    for func in &contract.functions {
        generate_cpp_host_function(out, &class_name, func)?;
    }

    out.push_str("private:\n");
    out.push_str("    PluginHandle handle_;\n");
    out.push_str("    const HostVTable* host_;\n");
    out.push_str("};\n\n");
    Ok(())
}

// ─── Per-function method emitter ──────────────────────────────────────────────

fn generate_cpp_host_function(
    out: &mut String,
    class_name: &str,
    func: &ResolvedFunction,
) -> Result<(), CodegenError> {
    let return_type: String = func
        .returns
        .as_ref()
        .map(cpp_type_name)
        .unwrap_or_else(|| "void".to_owned());

    // Build parameter list string.
    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| format!("{} {}", cpp_type_name(&p.ty), p.name))
        .collect();
    let params_str: String = params.join(", ");

    out.push_str(&format!(
        "    {} {}({}) {{\n",
        return_type, func.name, params_str
    ));

    // Determine args_ptr expression.
    let args_ptr_code: String = build_args_ptr_code(class_name, func);
    out.push_str(&args_ptr_code);

    let fn_id: u32 = func.function_id;

    let is_void_return: bool = matches!(
        func.returns.as_ref(),
        None | Some(ResolvedTypeRef::AbiType(AbiBuiltin::Void))
    );

    if is_void_return {
        out.push_str(&format!(
            "        AbiError err = (host_->call_plugin)(handle_, {}U, args_ptr, nullptr);\n",
            fn_id
        ));
        out.push_str("        polyplug::check_abi_error(err);\n");
    } else {
        out.push_str(&format!("        {} out{{}};\n", return_type));
        out.push_str("        void* out_ptr = &out;\n");
        out.push_str(&format!(
            "        AbiError err = (host_->call_plugin)(handle_, {}U, args_ptr, out_ptr);\n",
            fn_id
        ));
        out.push_str("        polyplug::check_abi_error(err);\n");
        out.push_str("        return out;\n");
    }

    out.push_str("    }\n\n");
    Ok(())
}

/// Build the `args_ptr` preamble lines for a function body.
///
/// Returns the lines (indented 8 spaces) that set up `args_ptr`.
fn build_args_ptr_code(class_name: &str, func: &ResolvedFunction) -> String {
    if func.params.is_empty() {
        // No args — pass nullptr.
        return "        const void* args_ptr = nullptr;\n".to_owned();
    }

    if func.params.len() == 1 {
        let param = &func.params[0];
        match &param.ty {
            ResolvedTypeRef::UserDefined(_) => {
                // User-defined struct: pass pointer directly.
                return format!("        const void* args_ptr = &{};\n", param.name);
            }
            ResolvedTypeRef::Primitive(_) | ResolvedTypeRef::AbiType(_) => {
                // Single primitive: store in local and pass pointer.
                let cpp_ty: String = cpp_type_name(&param.ty);
                return format!(
                    "        const {cpp_ty} local_{name} = {name};\n        const void* args_ptr = &local_{name};\n",
                    cpp_ty = cpp_ty,
                    name = param.name
                );
            }
        }
    }

    // Multiple params: pack into a generated args struct.
    // Capitalise the function name for the struct name.
    let func_name_cap: String = capitalise_first(&func.name);
    let struct_name: String = format!("{}{}{}", class_name, func_name_cap, "Args");

    let mut code: String = String::new();
    // Inline struct definition.
    code.push_str(&format!("        struct {} {{", struct_name));
    for param in &func.params {
        let cpp_ty: String = cpp_type_name(&param.ty);
        code.push_str(&format!(" {} {};", cpp_ty, param.name));
    }
    code.push_str(" };\n");

    // Initialise the struct.
    let field_inits: Vec<String> = func.params.iter().map(|p| p.name.clone()).collect();
    code.push_str(&format!(
        "        {} args_val{{ {} }};\n",
        struct_name,
        field_inits.join(", ")
    ));
    code.push_str("        const void* args_ptr = &args_val;\n");
    code
}

// ─── Utility helpers ──────────────────────────────────────────────────────────

fn cpp_type_name(ty: &ResolvedTypeRef) -> String {
    match ty {
        ResolvedTypeRef::Primitive(p) => p.cpp_name().to_owned(),
        ResolvedTypeRef::AbiType(AbiBuiltin::StringView) => "StringView".to_owned(),
        ResolvedTypeRef::AbiType(AbiBuiltin::Buffer) => "Buffer".to_owned(),
        ResolvedTypeRef::AbiType(AbiBuiltin::Ptr) => "void*".to_owned(),
        ResolvedTypeRef::AbiType(AbiBuiltin::Void) => "void".to_owned(),
        ResolvedTypeRef::UserDefined(name) => name.clone(),
    }
}

fn contract_name_to_class(name: &str) -> String {
    // Convert "image.decode" -> "ImageDecodeContract"
    name.split('.')
        .map(|p| {
            let mut chars: core::str::Chars<'_> = p.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join("")
        + "Contract"
}

/// Convert "test.add" → "TestAddPlugin"
fn contract_name_to_plugin_class(name: &str) -> String {
    name.split('.')
        .map(|p| {
            let mut chars: core::str::Chars<'_> = p.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join("")
        + "Plugin"
}

/// Convert "test.add" → "test_add"
fn contract_name_to_lower_snake(name: &str) -> String {
    name.replace('.', "_")
}

/// Convert "test.add" → "TEST_ADD"
fn contract_name_to_upper_snake(name: &str) -> String {
    name.replace('.', "_").to_uppercase()
}

fn capitalise_first(s: &str) -> String {
    let mut chars: core::str::Chars<'_> = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

// Suppress unused import warning
const _: fn() = || {
    let _ = cpp_type_name(&ResolvedTypeRef::Primitive(PrimitiveType::U8));
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn class_name_conversion() {
        assert_eq!(
            contract_name_to_class("image.decode"),
            "ImageDecodeContract"
        );
    }

    #[test]
    fn plugin_class_name_conversion() {
        assert_eq!(contract_name_to_plugin_class("test.add"), "TestAddPlugin");
    }

    #[test]
    fn lower_snake_conversion() {
        assert_eq!(contract_name_to_lower_snake("test.add"), "test_add");
    }

    #[test]
    fn upper_snake_conversion() {
        assert_eq!(contract_name_to_upper_snake("test.add"), "TEST_ADD");
    }

    #[test]
    fn generate_host_empty_ir() {
        let generator: CppGenerator = CppGenerator;
        let ir: ValidatedIr = ValidatedIr {
            types: vec![],
            contracts: vec![],
            bundle: None,
        };
        let mut files: GeneratedFiles = GeneratedFiles::default();
        generator
            .generate_host(&ir, &mut files)
            .expect("generate_host");
        // Now produces 3 files: types.hpp, host_callers.hpp, manifest.toml
        assert!(files.files.len() >= 1);
        // At least one file contains the AUTO-GENERATED header
        assert!(
            files
                .files
                .iter()
                .any(|f| f.content.contains("AUTO-GENERATED"))
        );
    }

    #[test]
    fn generate_guest_empty_ir() {
        let generator: CppGenerator = CppGenerator;
        let ir: ValidatedIr = ValidatedIr {
            types: vec![],
            contracts: vec![],
            bundle: None,
        };
        let mut files: GeneratedFiles = GeneratedFiles::default();
        generator
            .generate_guest(&ir, &mut files)
            .expect("generate_guest");
        // Produces 5 files: types.hpp, contracts.hpp, vtables.hpp, init.hpp, manifest.toml
        assert_eq!(files.files.len(), 5);
        let names: Vec<String> = files
            .files
            .iter()
            .map(|f| f.path.to_string_lossy().to_string())
            .collect();
        assert!(names.contains(&"types.hpp".to_owned()));
        assert!(names.contains(&"contracts.hpp".to_owned()));
        assert!(names.contains(&"vtables.hpp".to_owned()));
        assert!(names.contains(&"init.hpp".to_owned()));
        assert!(names.contains(&"manifest.toml".to_owned()));
    }
}
