// THIS FILE IS AUTO-GENERATED BY polyplug_abi
// DO NOT EDIT BY HAND
// Re-generate with: polyplug_abi generate --lang cpp

#pragma once

#include <cstddef>
#include <cstdint>

// ─── ABI Constants ────────────────────────────────────────────────────────────

#define POLYPLUG_ABI_VERSION 1U
#define ABI_OK 0U
#define ABI_ERROR_GENERIC 1U
#define ABI_BUFFER_TOO_SMALL 2U
#define ABI_ERROR_PANIC 3U
#define ABI_ERROR_NOT_FOUND 4U
#define ABI_ERROR_STALE_HANDLE 5U
#define ABI_FUNCTION_NOT_AVAIL 6U

// ─── ABI Enums ────────────────────────────────────────────────────────────────

///  Dispatch mechanism type — determines how function calls are routed.
enum class DispatchType : uint32_t {
    ///  Native dispatch: direct function pointer calls (zero overhead).
    Native = 0,
    ///  VM dispatch: call through a dispatch function with loader_data.
    VirtualMachine = 1,
};

// ─── ABI Structs ──────────────────────────────────────────────────────────────

extern "C" {

///  Non-owning UTF-8 string view.
///
///  OWNERSHIP: borrowed reference. `ptr` must remain valid for the duration
///  of the call. Never freed by the receiver.
struct StringView {
    ///  UTF-8 bytes, NOT null-terminated.
    const uint8_t* ptr;
    ///  Byte count.
    size_t len;
};

///  Owning byte buffer.
///
///  OWNERSHIP: `ptr` is always allocated via `polyplug_host_alloc`.
///  Owner calls `polyplug_host_free(ptr, cap, align)` when done.
struct Buffer {
    uint8_t* ptr;
    ///  Bytes currently used.
    size_t len;
    ///  Bytes allocated.
    size_t cap;
};

///  Opaque handle to a loaded plugin — validated on use.
///
///  INTERNAL STRUCTURE: index into registry array + generation counter.
///  The generation counter detects use-after-unload.
struct PluginHandle {
    ///  Slot in the registry array.
    uint32_t index;
    ///  Incremented on unload — detects stale handles.
    uint32_t generation;
};

///  Opaque host context passed to plugin functions via rt_ctx parameter.
///
///  Contains the runtime pointer and the bundle_id of the calling bundle.
///  The actual implementation is in the polyplug crate; this definition
///  establishes the ABI layout.
///
///  OWNERSHIP: `'static`, lives as long as the runtime.
struct HostContext {
    ///  Opaque pointer to the Runtime. Never dereferenced by plugins.
    void* runtime;
    ///  Bundle ID of the calling bundle for dependency enforcement.
    uint64_t bundle_id;
};

///  ABI error — returned by value from all ABI calls.
///
///  OWNERSHIP: `code` is a value type. `message.ptr` is allocated by the callee
///  via `host_alloc`. Caller frees with `polyplug_host_free(message.ptr, message.len, 1)`
///  after reading. If `code == ABI_OK`, `message.ptr` is NULL — no free needed.
struct AbiError {
    ///  0 = success, non-zero = error.
    uint32_t code;
    ///  Empty/NULL if success. UTF-8 message if non-zero code.
    StringView message;
};

///  Native dispatch data — direct function pointer array.
///
///  Used when `dispatch_type == DispatchType::Native`.
///  The `functions` array contains `function_count` function pointers.
struct NativeDispatch {
    ///  Pointer to a static array of function pointers, indexed by function_id.
    void* const* functions;
};

///  VM dispatch data — call through a dispatch function.
///
///  Used when `dispatch_type == DispatchType::VirtualMachine`.
///  The `call` function receives `loader_data` which contains VM-specific state.
struct VmDispatch {
    ///  Dispatch function called for every VM function invocation.
    ///
    ///  # Arguments
    ///  - `loader_data`: VM-specific data (cast from `*mut c_void`)
    ///  - `fn_id`: Function index within the contract
    ///  - `args`: Pointer to packed arguments (ABI-specific layout)
    ///  - `out`: Pointer to output buffer for return value
    AbiError (*call )(void*, uint32_t, const void*, void*);
    ///  Loader-specific data (e.g., LuaLoaderData, JsLoaderData).
    ///  Opaque to the host; interpreted by the dispatch function.
    void* loader_data;
};

} // extern "C"

// ─── ABI Unions ───────────────────────────────────────────────────────────────

extern "C" {

///  Union of dispatch mechanisms — use based on `dispatch_type`.
///
///  # Safety
///  Access the correct variant based on `PluginInterface::dispatch_type`:
///  - `dispatch_type == Native` → access `.native`
///  - `dispatch_type == VirtualMachine` → access `.vm`
union PluginDispatch {
    ///  Native dispatch data (when dispatch_type == Native).
    NativeDispatch native;
    ///  VM dispatch data (when dispatch_type == VirtualMachine).
    VmDispatch vm;
};

} // extern "C"

extern "C" {

///  Metadata about a plugin within a bundle.
///
///  OWNERSHIP: value type passed by pointer during init. The `name` and
///  `contract_name` StringViews are borrowed from the plugin's static memory.
///  The receiver must not free or outlive the plugin's library.
struct PluginDescriptor {
    ///  Human-readable plugin name.
    StringView name;
    ///  Full contract name for collision detection.
    StringView contract_name;
    uint32_t version_major;
    uint32_t version_minor;
    uint32_t version_patch;
};

///  Plugin interface — one per contract implemented by a plugin.
///
///  OWNERSHIP: Must be `'static` or intentionally leaked.
///  Never stack-allocated. Never freed while runtime lives.
///
///  # Dispatch
///  - `dispatch_type == Native`: Call via `dispatch.native.functions[fn_id]`
///  - `dispatch_type == VirtualMachine`: Call via `dispatch.vm.call(...)`
struct PluginInterface {
    ///  Pointer to the host context for this plugin.
    ///  Used for host function calls and dependency enforcement.
    const HostContext* rt_ctx;
    ///  FNV-1a hash of "contract_name@major_version".
    uint64_t contract_id;
    ///  minor.patch encoded as `(minor << 16 | patch)`.
    uint32_t contract_version;
    ///  Number of valid entries in the dispatch array.
    uint32_t function_count;
    ///  Dispatch mechanism type (Native or VirtualMachine).
    DispatchType dispatch_type;
    ///  Union of dispatch mechanisms — access based on dispatch_type.
    PluginDispatch dispatch;
};

///  Host capabilities passed to every plugin at init time.
///
///  OWNERSHIP: `'static`, lives as long as the runtime.
///
///  All functions take `rt_ctx` as first parameter - an opaque pointer to the Runtime.
///  This allows each Runtime to have its own isolated state (no global registry).
struct HostVTable {
    AbiError (*register_plugin )(void*, const PluginDescriptor*, const PluginInterface*);
    uint8_t* (*alloc )(void*, size_t, size_t);
    void (*free )(void*, uint8_t*, size_t, size_t);
    PluginHandle (*find_by_contract )(void*, uint64_t, uint32_t);
    PluginHandle (*find_by_bundle )(void*, uint64_t, uint64_t, uint32_t);
    size_t (*find_all_by_contract )(void*, uint64_t, uint32_t, PluginHandle*, size_t);
    const PluginInterface* (*resolve_plugin )(void*, PluginHandle);
    const void* (*get_extension )(void*, uint32_t);
};

///  Context passed to every guest `polyplug_init()` function.
///  The `bundle_path` pointer is runtime-owned and valid for the lifetime of the `PluginRuntime`.
///  **Plugin must not store the raw pointer** — copy the string value if persistence is needed.
struct PluginContext {
    ///  Absolute canonical path to the directory containing the loaded bundle.
    StringView bundle_path;
    ///  Host's supported ABI version for negotiation (Option C).
    ///  Plugin can use this to determine available features.
    uint32_t host_abi_version;
    ///  Bundle ID for dependency enforcement during init.
    uint64_t bundle_id;
};

///  A single extension entry in the runtime config.
///
///  OWNERSHIP: the `vtable` pointer must be `'static` (valid for the runtime
///  lifetime). `ExtensionEntry` arrays are passed by pointer to `RuntimeConfig`
///  and never owned or freed by the runtime.
struct ExtensionEntry {
    ///  FNV-1a lower 32 bits of the extension name.
    uint32_t extension_id;
    ///  Pointer to the extension's vtable struct.
    const void* vtable;
};

///  Configuration passed to `polyplug_runtime_create` during runtime initialisation.
///
///  OWNERSHIP: borrowed for the duration of the runtime build only.
///  The caller may free all pointed-to memory after the build
///  returns. The runtime copies any data it needs to retain.
struct RuntimeConfig {
    ///  Plugin directories to scan (array of `plugin_dir_count` StringViews).
    const StringView* plugin_dirs;
    size_t plugin_dir_count;
    ///  Compatibility mode: 0 = Strict (only mode implemented in MVP).
    uint32_t compatibility;
    ///  Extensions provided by the host (array of `extension_count` entries).
    const ExtensionEntry* extensions;
    size_t extension_count;
};

} // extern "C"

// ─── FNV-1a Hash Helpers ──────────────────────────────────────────────────────

namespace polyplug {

namespace detail {

/// FNV-1a 64-bit hash of a byte sequence.
constexpr uint64_t fnv1a_64(const uint8_t* data, size_t len) noexcept {
    constexpr uint64_t FNV_OFFSET = 0xcbf29ce484222325ULL;
    constexpr uint64_t FNV_PRIME = 0x00000100000001B3ULL;
    uint64_t hash = FNV_OFFSET;
    for (size_t i = 0; i < len; ++i) {
        hash ^= static_cast<uint64_t>(data[i]);
        hash *= FNV_PRIME;
    }
    return hash;
}

} // namespace detail

/// Compute the contract ID for "name@major_version" using FNV-1a 64-bit.
constexpr uint64_t contract_id(const char* name, uint32_t major_version) noexcept {
    // Hash name
    constexpr uint64_t FNV_OFFSET = 0xcbf29ce484222325ULL;
    constexpr uint64_t FNV_PRIME = 0x00000100000001B3ULL;
    uint64_t hash = FNV_OFFSET;
    while (*name) {
        hash ^= static_cast<uint64_t>(static_cast<uint8_t>(*name));
        hash *= FNV_PRIME;
        ++name;
    }
    // Hash '@'
    hash ^= static_cast<uint64_t>('@');
    hash *= FNV_PRIME;
    // Hash major_version as decimal
    if (major_version == 0) {
        hash ^= static_cast<uint64_t>('0');
        hash *= FNV_PRIME;
    } else {
        uint32_t v = major_version;
        char buf[12] = {};
        int i = 11;
        while (v > 0) {
            buf[--i] = '0' + (v % 10);
            v /= 10;
        }
        const char* p = buf + i;
        while (*p) {
            hash ^= static_cast<uint64_t>(static_cast<uint8_t>(*p));
            hash *= FNV_PRIME;
            ++p;
        }
    }
    return hash;
}

/// Compute an extension ID from its name using FNV-1a lower 32 bits.
constexpr uint32_t extension_id(const char* name) noexcept {
    constexpr uint64_t FNV_OFFSET = 0xcbf29ce484222325ULL;
    constexpr uint64_t FNV_PRIME = 0x00000100000001B3ULL;
    uint64_t hash = FNV_OFFSET;
    while (*name) {
        hash ^= static_cast<uint64_t>(static_cast<uint8_t>(*name));
        hash *= FNV_PRIME;
        ++name;
    }
    return static_cast<uint32_t>(hash);
}

/// Compute a bundle ID from its name using FNV-1a 64-bit hash.
constexpr uint64_t bundle_id(const char* name) noexcept {
    constexpr uint64_t FNV_OFFSET = 0xcbf29ce484222325ULL;
    constexpr uint64_t FNV_PRIME = 0x00000100000001B3ULL;
    uint64_t hash = FNV_OFFSET;
    while (*name) {
        hash ^= static_cast<uint64_t>(static_cast<uint8_t>(*name));
        hash *= FNV_PRIME;
        ++name;
    }
    return hash;
}

} // namespace polyplug
