//! polyplug guest library — Rust bindings for guest-side (plugin developer) use.
//!
//! This crate provides the ABI types, allocator hookup, and registration
//! helpers that plugin authors need to implement a polyplug contract.
//!
//! # Quick Start
//!
//! A minimal Rust plugin implementing a contract looks like this:
//!
//! ```rust,ignore
//! // In Cargo.toml: crate-type = ["cdylib"]
//! use polyplug_abi::*;
//!
//! // 1. Compute the contract ID at compile time (FNV-1a of "my.contract@1")
//! const MY_CONTRACT_ID: u64 = /* polyplugc generates this */;
//!
//! // 2. Implement your function with the generic dispatch signature
//! extern "C" fn my_fn(args: *const (), out: *mut ()) -> AbiError {
//!     // ... cast args/out, compute, write result
//!     AbiError::ok()
//! }
//!
//! // 3. Declare static interface
//! static MY_FNS: [FnPtr; 1] = [FnPtr(my_fn as *const ())];
//! static MY_VTABLE: GuestContractInterface = GuestContractInterface {
//!     contract_id: MY_CONTRACT_ID,
//!     contract_version: Version { major: 1, minor: 0, patch: 0 },
//!     dispatch_type: DispatchType::Native,
//!     create_instance: create_instance_stub,
//!     destroy_instance: destroy_instance_stub,
//!     dispatch: DispatchMechanisms {
//!         native: NativeDispatch {
//!             function_count: 1,
//!             functions: MY_FNS.as_ptr() as *const *const (),
//!         },
//!     },
//! };
//! static MY_DESCRIPTOR: PluginDescriptor = PluginDescriptor {
//!     name: StringView { ptr: b"my_plugin".as_ptr(), len: 9 },
//!     contract_name: StringView { ptr: b"my.contract".as_ptr(), len: 11 },
//!     version: Version { major: 1, minor: 0, patch: 0 },
//! };
//!
//! // 4. Export ABI version sentinel
//! #[unsafe(no_mangle)]
//! pub extern "C" fn polyplug_abi_version() -> u32 { POLYPLUG_ABI_VERSION }
//!
//! // 5. Export init function — registers vtables with the host
//! #[unsafe(no_mangle)]
//! pub unsafe extern "C" fn polyplug_init(
//!     host_abi: *const HostApi,
//!     _ctx: *const BundleInitContext,
//! ) -> AbiError {
//!     if host_abi.is_null() {
//!         return AbiError { code: AbiErrorCode::Generic, message: StringView::null() };
//!     }
//!     let host: &HostApi = unsafe { &*host_abi };
//!     unsafe {
//!         (host.register_guest_contract)(host_abi, &MY_DESCRIPTOR, &MY_VTABLE)
//!     }
//! }
//! ```
//!
//! # Status
//! Scaffold only. Full implementation is code-generated by `polyplugc`.
//!
//! # Known Limitation — single host vtable per process
//! The host [`HostApi`] pointer is stored in a process-wide [`OnceLock`]
//! ([`HOST_VTABLE`]): the FIRST runtime to initialize a plugin built against this
//! crate wins, and the slot is never overwritten. If one plugin dylib is loaded
//! by two `Runtime` instances in the same process, every host call the plugin
//! makes (cross-contract dispatch, alloc/free, error reporting) is routed to the
//! FIRST runtime's `HostApi`, not the one that owns the in-flight call. This
//! mirrors the once-per-process constraints of the CPython and CLR loaders: for
//! full isolation with a shared Rust guest dylib, use separate processes.

use std::sync::OnceLock;

use polyplug_abi::{AbiErrorCode, HostApi, StringView};

/// Wrapper for host interface pointer that implements Send + Sync.
/// The host interface is 'static and immutable, safe to share across threads.
#[repr(transparent)]
pub struct HostVtablePtr(pub *const polyplug_abi::HostApi);

// SAFETY: HostVtablePtr wraps a 'static host interface pointer provided by the host runtime.
// The interface is immutable and valid for the plugin's lifetime. Multiple threads may read
// from the same interface concurrently — the host ensures thread-safe access to interface data.
unsafe impl Send for HostVtablePtr {}

// SAFETY: The host interface is read-only 'static memory. Multiple threads may access the
// same interface concurrently without synchronization. The host runtime guarantees the interface
// remains valid and unchanged for the plugin's lifetime.
unsafe impl Sync for HostVtablePtr {}

/// Static storage for the host interface passed during polyplug_init.
/// Set once during initialization, then read-only for guest access.
///
/// # Known Limitation — first runtime wins
/// This is a process-wide `OnceLock`: the first `Runtime` to initialize a plugin
/// built against this crate populates it, and later `set` calls are ignored. A
/// plugin dylib shared by two `Runtime` instances in the same process therefore
/// sends ALL of its host calls to the first runtime's `HostApi`, regardless of
/// which runtime is driving the current call. For full isolation with a shared
/// Rust guest dylib, use separate processes (same constraint as the CPython and
/// CLR loaders).
static HOST_VTABLE: OnceLock<HostVtablePtr> = OnceLock::new();

// ─── Helper Functions ─────────────────────────────────────────────────────────

/// Create an AbiError panic response.
pub fn abi_error_panic_caught() -> polyplug_abi::AbiError {
    polyplug_abi::AbiError::panic_caught()
}

// ─── Helper Types ─────────────────────────────────────────────────────────────

/// Wrapper for a function pointer stored in a static vtable array.
///
/// Raw `*const ()` does not implement `Sync`, but function pointers in a
/// `static` array are effectively `'static` and immutable.
/// Wrap each function pointer in `FnPtr` when building your vtable's
/// `functions` array.
///
/// # Example
/// ```rust,ignore
/// extern "C" fn my_fn(args: *const (), out: *mut ()) -> AbiError { AbiError::ok() }
/// static MY_FNS: [FnPtr; 1] = [FnPtr(my_fn as *const ())];
/// ```
#[repr(transparent)]
pub struct FnPtr(pub *const ());

// SAFETY: FnPtr wraps a 'static function pointer. Function pointers are safe
// to share across threads — the function itself handles its own synchronization.
unsafe impl Send for FnPtr {}
// SAFETY: Function pointers are inherently Sync — multiple threads may call
// the same function concurrently. The data is read-only 'static memory.
unsafe impl Sync for FnPtr {}

/// Error returned from guest-side plugin trait methods.
///
/// Produced by generated ABI wrappers when an ABI call returns a non-zero code.
/// Plugin developers return `Result<T, GuestError>` from their trait implementations.
#[derive(Debug)]
pub struct GuestError {
    /// ABI error code (non-zero).
    pub code: AbiErrorCode,
    /// Human-readable error message. May be empty.
    pub message: String,
}

impl core::fmt::Display for GuestError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(
            f,
            "GuestError(code={}, message={})",
            self.code, self.message
        )
    }
}

impl core::error::Error for GuestError {}

// ─── String Helpers ───────────────────────────────────────────────────────────

/// Convert a `StringView` to a `&str` borrowing for the view's lifetime.
///
/// # Safety
/// - `sv.ptr` must either be null or point to `sv.len` initialized bytes that
///   stay valid and immutable for the entire lifetime `'a` of the borrow.
/// - The pointed-to bytes are expected to be UTF-8; invalid UTF-8 yields `""`.
///
/// The returned `&'a str` is tied to the borrow of `sv`, so it cannot outlive
/// the `StringView` it was derived from. This is `unsafe` because the validity
/// and lifetime of `sv.ptr` cannot be checked here.
///
/// # Example
/// ```rust
/// use polyplug_abi::StringView;
/// use polyplug_guest::to_str;
///
/// let sv = StringView { ptr: b"hello".as_ptr(), len: 5 };
/// // SAFETY: `sv` borrows a live byte slice for the duration of this call.
/// let s: &str = unsafe { to_str(&sv) };
/// assert_eq!(s, "hello");
/// ```
pub unsafe fn to_str(sv: &StringView) -> &str {
    if sv.ptr.is_null() || sv.len == 0 {
        return "";
    }
    // SAFETY: sv.ptr is non-null (checked above) and sv.len is the valid length.
    // The caller guarantees, via this function's `# Safety` contract, that the
    // pointer is valid for sv.len bytes for the lifetime 'a and points to UTF-8.
    unsafe { core::str::from_utf8(core::slice::from_raw_parts(sv.ptr, sv.len)).unwrap_or("") }
}

/// Allocate a `StringView` from a `&str` using the host allocator.
///
/// Allocates through the stored `HostApi` (`host.alloc`, align 1), so the
/// bytes are owned by the host and never link a separate allocator copy into the
/// plugin dylib. The caller (host) is responsible for freeing the memory via
/// `host.free(host, ptr, len, 1)`.
///
/// # Errors
/// Returns `Err(GuestError)` if the host interface is unavailable (called before
/// `polyplug_init` stored it) or if allocation fails.
///
/// # Example
/// ```rust,ignore
/// use polyplug_abi::StringView;
/// use polyplug_guest::alloc_string;
///
/// let sv: StringView = alloc_string("hello").unwrap();
/// // sv.ptr points to host-allocated memory
/// // Host must call host.free(host, sv.ptr, sv.len, 1) when done
/// ```
pub fn alloc_string(s: &str) -> Result<StringView, GuestError> {
    let host_ptr: *const HostApi = get_host_vtable();
    if host_ptr.is_null() {
        return Err(GuestError {
            code: AbiErrorCode::Generic,
            message: "host interface unavailable".to_string(),
        });
    }
    let bytes: &[u8] = s.as_bytes();
    // SAFETY: host_ptr is non-null (checked above) and was validated during
    // store_host_vtable. `alloc` is a valid function pointer set by the host.
    let ptr: *mut u8 = unsafe { ((*host_ptr).alloc)(host_ptr, bytes.len(), 1) };
    if ptr.is_null() {
        return Err(GuestError {
            code: AbiErrorCode::Generic,
            message: "allocation failed".to_string(),
        });
    }
    // SAFETY: ptr is non-null (checked above) and was allocated by host.alloc
    // with size bytes.len() and align 1. The source bytes.as_ptr() is valid for
    // bytes.len() bytes. The destination is valid for bytes.len() bytes.
    unsafe { core::ptr::copy_nonoverlapping(bytes.as_ptr(), ptr, bytes.len()) };
    Ok(StringView {
        ptr,
        len: bytes.len(),
    })
}

/// Check if a `StringView` starts with the given prefix.
///
/// # Safety
/// Same contract as [`to_str`]: `sv` must point to valid, live UTF-8 bytes for
/// the duration of the call.
///
/// # Example
/// ```rust
/// use polyplug_abi::StringView;
/// use polyplug_guest::starts_with;
///
/// let sv = StringView { ptr: b"hello world".as_ptr(), len: 11 };
/// // SAFETY: `sv` borrows a live byte slice for the duration of this call.
/// assert!(unsafe { starts_with(&sv, "hello") });
/// assert!(!unsafe { starts_with(&sv, "world") });
/// ```
pub unsafe fn starts_with(sv: &StringView, prefix: &str) -> bool {
    // SAFETY: forwarded to the caller via this function's `# Safety` contract.
    let s: &str = unsafe { to_str(sv) };
    s.starts_with(prefix)
}

/// Check if a `StringView` ends with the given suffix.
///
/// # Safety
/// Same contract as [`to_str`]: `sv` must point to valid, live UTF-8 bytes for
/// the duration of the call.
///
/// # Example
/// ```rust
/// use polyplug_abi::StringView;
/// use polyplug_guest::ends_with;
///
/// let sv = StringView { ptr: b"hello world".as_ptr(), len: 11 };
/// // SAFETY: `sv` borrows a live byte slice for the duration of this call.
/// assert!(unsafe { ends_with(&sv, "world") });
/// assert!(!unsafe { ends_with(&sv, "hello") });
/// ```
pub unsafe fn ends_with(sv: &StringView, suffix: &str) -> bool {
    // SAFETY: forwarded to the caller via this function's `# Safety` contract.
    let s: &str = unsafe { to_str(sv) };
    s.ends_with(suffix)
}

/// Strip a prefix from a `StringView` if present.
///
/// Returns the remaining string slice if the prefix was present,
/// otherwise returns the original string. The returned slice borrows for the
/// lifetime of `sv`.
///
/// # Safety
/// Same contract as [`to_str`]: `sv` must point to valid, live UTF-8 bytes for
/// the lifetime `'a` of the borrow.
///
/// # Example
/// ```rust
/// use polyplug_abi::StringView;
/// use polyplug_guest::strip_prefix;
///
/// let sv = StringView { ptr: b"hello world".as_ptr(), len: 11 };
/// // SAFETY: `sv` borrows a live byte slice for the duration of this call.
/// assert_eq!(unsafe { strip_prefix(&sv, "hello ") }, "world");
/// assert_eq!(unsafe { strip_prefix(&sv, "goodbye") }, "hello world");
/// ```
pub unsafe fn strip_prefix<'a>(sv: &'a StringView, prefix: &str) -> &'a str {
    // SAFETY: forwarded to the caller via this function's `# Safety` contract.
    let s: &'a str = unsafe { to_str(sv) };
    match s.strip_prefix(prefix) {
        Some(remaining) => remaining,
        None => s,
    }
}

/// Split a `StringView` by a literal delimiter, keeping empty segments.
///
/// Returns a vector of string slices borrowing for the lifetime of `sv`. A
/// null or empty view returns an empty vector; an empty delimiter returns the
/// whole string as a single element. Leading, trailing, and consecutive
/// delimiters produce empty strings in the output.
///
/// # Safety
/// Same contract as [`to_str`]: `sv` must point to valid, live UTF-8 bytes for
/// the lifetime `'a` of the borrow.
///
/// # Example
/// ```rust
/// use polyplug_abi::StringView;
/// use polyplug_guest::split;
///
/// let sv = StringView { ptr: b"a,b,c".as_ptr(), len: 5 };
/// // SAFETY: `sv` borrows a live byte slice for the duration of this call.
/// let parts: Vec<&str> = unsafe { split(&sv, ",") };
/// assert_eq!(parts, vec!["a", "b", "c"]);
/// ```
pub unsafe fn split<'a>(sv: &'a StringView, delimiter: &str) -> Vec<&'a str> {
    // SAFETY: forwarded to the caller via this function's `# Safety` contract.
    let s: &'a str = unsafe { to_str(sv) };
    if s.is_empty() {
        return Vec::new();
    }
    if delimiter.is_empty() {
        return vec![s];
    }
    s.split(delimiter).collect()
}

// ─── Host Vtable Access ────────────────────────────────────────────────────────

/// Store the host interface during initialization.
///
/// # Safety
/// Must be called exactly once during polyplug_init, before any host contract access.
/// The interface pointer must remain valid for the lifetime of the plugin.
pub unsafe fn store_host_vtable(vtable: *const polyplug_abi::HostApi) {
    let _: Result<(), HostVtablePtr> = HOST_VTABLE.set(HostVtablePtr(vtable));
}

/// Get the host interface that was passed during polyplug_init.
///
/// Returns a pointer to the host interface stored during initialization.
/// The pointer is valid for the lifetime of the plugin.
/// Returns null if called before polyplug_init completes.
pub fn get_host_vtable() -> *const polyplug_abi::HostApi {
    HOST_VTABLE.get().map(|p| p.0).unwrap_or(core::ptr::null())
}

/// Log a diagnostic into the host's logging funnel (`HostApi.log`).
///
/// Routes to the same sink as the host's `RuntimeConfig::log` callback (or its
/// stderr default). `scope` should be a short stable tag, e.g.
/// `"guest.<plugin-name>"`.
///
/// No-op when called before `polyplug_init` has stored the host vtable — there
/// is no host to deliver to yet.
pub fn log(level: polyplug_abi::types::LogLevel, scope: &str, message: &str) {
    let host: *const polyplug_abi::HostApi = get_host_vtable();
    if host.is_null() {
        return;
    }
    let scope_view = StringView {
        ptr: scope.as_ptr(),
        len: scope.len(),
    };
    let message_view = StringView {
        ptr: message.as_ptr(),
        len: message.len(),
    };
    // SAFETY: `host` was stored from a valid HostApi during polyplug_init and
    // stays valid for the plugin's lifetime; `log` is always provided by the
    // runtime. Both views borrow live UTF-8 Rust string data that outlives the
    // synchronous call, matching the field's documented ownership contract.
    unsafe { ((*host).log)(host, level as u32, scope_view, message_view) }
}

// ─── FFI Module ────────────────────────────────────────────────────────────────

/// FFI utilities for guest plugins.
///
/// Provides host interface access for generated code. Cross-boundary allocation
/// goes through `crate::alloc_string` / the stored `HostApi`, never a
/// separately linked allocator symbol.
pub mod ffi {
    /// Get the host interface that was passed during polyplug_init.
    ///
    /// Returns a pointer to the host interface stored during initialization.
    /// The pointer is valid for the lifetime of the plugin.
    /// Returns null if called before polyplug_init completes.
    pub fn get_host_vtable() -> *const polyplug_abi::HostApi {
        crate::get_host_vtable()
    }
}

#[cfg(test)]
mod tests {
    use polyplug_abi::StringView;

    fn view(bytes: &[u8]) -> StringView {
        StringView {
            ptr: bytes.as_ptr(),
            len: bytes.len(),
        }
    }

    #[test]
    fn to_str_null_view_is_empty() {
        let sv = StringView {
            ptr: core::ptr::null(),
            len: 5,
        };
        // SAFETY: a null view is explicitly legal input for to_str.
        assert_eq!(unsafe { crate::to_str(&sv) }, "");
    }

    #[test]
    fn to_str_zero_len_view_is_empty() {
        let sv: StringView = view(b"x");
        let sv = StringView { len: 0, ..sv };
        // SAFETY: the view borrows a live byte slice for the duration of the call.
        assert_eq!(unsafe { crate::to_str(&sv) }, "");
    }

    #[test]
    fn split_keeps_consecutive_empty_segments() {
        let sv: StringView = view(b"a||b");
        // SAFETY: the view borrows a live byte slice for the duration of the call.
        let parts: Vec<&str> = unsafe { crate::split(&sv, "|") };
        assert_eq!(parts, vec!["a", "", "b"]);
    }

    #[test]
    fn split_keeps_leading_and_trailing_empty_segments() {
        let sv: StringView = view(b"|a|");
        // SAFETY: the view borrows a live byte slice for the duration of the call.
        let parts: Vec<&str> = unsafe { crate::split(&sv, "|") };
        assert_eq!(parts, vec!["", "a", ""]);
    }

    #[test]
    fn split_empty_view_is_empty_list() {
        let sv = StringView {
            ptr: core::ptr::null(),
            len: 0,
        };
        // SAFETY: a null view is explicitly legal input for split.
        let parts: Vec<&str> = unsafe { crate::split(&sv, "|") };
        assert!(parts.is_empty());
    }

    #[test]
    fn split_empty_delimiter_returns_whole_string() {
        let sv: StringView = view(b"ab");
        // SAFETY: the view borrows a live byte slice for the duration of the call.
        let parts: Vec<&str> = unsafe { crate::split(&sv, "") };
        assert_eq!(parts, vec!["ab"]);
    }

    #[test]
    fn split_multibyte_literal_delimiter() {
        let sv: StringView = view(b"a::b::c");
        // SAFETY: the view borrows a live byte slice for the duration of the call.
        let parts: Vec<&str> = unsafe { crate::split(&sv, "::") };
        assert_eq!(parts, vec!["a", "b", "c"]);
    }
}
