[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "polyplug-loaders-js-deno"
version = "0.1.0"
description = "JS Deno (V8) loader for polyplug"
requires-python = ">=3.8"
dependencies = [
    "polyplug",
]

[tool.setuptools.packages.find]
include = ["polyplug_loaders_js_deno*"]
