[package]
name = "polyplug_abi"
description = "ABI type definitions for the polyplug plugin runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "build/main.rs"

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
polyplug_utils = { workspace = true }

[build-dependencies]
syn = { workspace = true }
quote = { workspace = true }
polyplug_codegen = { workspace = true }